### ISSUE TITLE
Updated Polish translation

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#102]
I've translated some plugins:
Align
AutoWrap
Brackets
After translating I have created 'Pull request', but any compliations trom 7-9 days has not included this files in builds (pulls: 99, 100, 101).
Can someone check what I have done wrong?

**Comment by alabuzhev** [comment]
Nothing wrong, but those translations won't add themselves to the installer, someone has to do that.

**Comment by alabuzhev** [comment]
7954993
