### ISSUE TITLE
Installer - some points to check

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#109]
Version: Far.x64.3.0.5399.922

1) Adding QuickLaunch icon does not work under Win10 x64
2) I've choosed only Polish lang (and of cource English), but in plugins folders are some other files.
I.e.: AlignSky.lng. arclite_spa.lng, etc.

Addes log from installer.
[far_log.txt](https://github.com/FarGroup/FarManager/files/3207095/far_log.txt)

**Comment by BestiaPL** [comment]
Version: Far.x64.3.0.5402.931.555b5a8cb4040fb989a86f33f21e418838caac1b.msi

features.wxs - line 281 shoud be:
            <Feature Id="Brackets.Slovak" Level="1" Display="hidden" AllowAdvertise="no">

Now there is SLovak, and installer does not work...

MSI (s) (48!DC) [13:43:13:704]: Note: 1: 2711 2: SLovak 
Error at customact.cpp:267: Niezarejestrowany identyfikator cechy. (0x80070646)
CustomAction UpdateFeatureState returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 13:43:13: UpdateFeatureState. Return value 3.

**Comment by alabuzhev** [comment]
Thanks, fixed.

**Comment by alabuzhev** [comment]
> Adding QuickLaunch icon does not work under Win10 x64

Well, it probably doesn't work since Windows 7, because there's no Quick Launch by default?

If you add the Quick Launch tollbar manually (Right click - Toolbars - New toolbar - "C:\Users\<your name>\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch") - the shortcut will be there.

**Comment by BestiaPL** [comment]
I don't know how MSI Installer is compiled, but when I'm using InnoSetup - I can choose 'Pin to Taskbar' location.

TaskBar folder location:
C:\Users\Andrzej\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar
or:
%APPDATA%\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar

Info: https://gallery.technet.microsoft.com/ScriptCenter/b66434f1-4b3f-4a94-8dc3-e406eb30b750/

**Comment by jroessel** [comment]
@BestiaPL [pinning items to the taskbar is an action the user should do, not an application](https://devblogs.microsoft.com/oldnewthing/20141230-00/?p=43273). There's deliberately no API for that and any method may stop working eventually. The linked script on Technet is a really awful hack, by the way, mimicking what a user would to to pin an application to the taskbar.

**Comment by BestiaPL** [comment]
Re: [FarGroup/FarManager] Installer - some points to check (#109)



OK, I understand.





@BestiaPL pinning items to the taskbar is an action the user should do, not an application. There's deliberately no API for that and any method may stop working eventually. The linked script on Technet is a really awful hack, by the way, mimicking what a user would to to pin an application to the taskbar.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



--
Regards,
 Andrzej Rudnik
