### ISSUE TITLE
b5107 Git-7889706a5 broken associations

### ISSUE THREAD

**Issue by VictorVG** [FarGroup/FarManager#11]
**b5107 Git-7889706a5** fresh glitches - run by the association lua: @ "! = \!.!" test Lua script hello.lua:
```
local ret = far.Message ("Press any button", "Hello, Lua!", "& 1; & 2; & 3; & 4; & 5")
far.Message (ret <1 and "You cancelled the dialog"
                    or "You pressed the button" ..ret)
```
, we get the error message:
```
LuaMacro
cannot open \\? \F:\Developmer\Far30\ script\ "F:\Developmer\Far30\script\hello.lua: Invalid argument
```
and in b5107 Git-7889706a5 the script was run and worked out normally. It seems that the associations are broken. While spreading b5108 rather early ....

**Comment by VictorVG** [comment]
**b5109 Git-f26dd3724** - bug exists, all test used new copy w/o any plug-ins and macros - only Git plugins + association lua:@"!=\!.!" . If try command lua:@test.lua test work success. Broken only associations.

**Comment by VictorVG** [comment]
**b5109 Git-f26dd3724** - bug exists, all test used new copy w/o any plug-ins and macros - only Git plugins + association lua:@"!=!.!", locale profile in to %FARHOME% and default settings by code. If try run command like _lua:@test.lua_ all scripts work success. Broken only associations.

**Comment by shmuz** [comment]
@VictorVG, лучше пишите на русском. Автоматический перевод очень плох.

**Comment by VictorVG** [comment]
Не вопрос. Я случайно обнаружил это явление после того как нашёл способ обхода проблемы с драйвером в Process Hacker - (SERVICE_STOP_PENDING [**#197**](https://github.com/processhacker2/processhacker/issues/197) если хоть раз перезапускался с момента запуска ОС). Стал проверять  работу LuaMacro на наборе скриптов ( [script.zip](https://github.com/FarGroup/FarManager/files/1571740/script.zip) упаковал для отправки, так они лежат в каталоге) 

![1](https://user-images.githubusercontent.com/906886/34158923-639e63b2-e4d8-11e7-94a0-a7e1f9db8a2a.png)

и получил сообщение об ошибке:

![2](https://user-images.githubusercontent.com/906886/34158924-63bf2d90-e4d8-11e7-9378-274c0a80e9f8.png)

[**написал**](http://forum.ru-board.com/topic.cgi?forum=5&topic=49572&start=60#20) на forum.ru-board чтобы ещё кто не нарвался и сюда. А сейчас присмотрелся - а почему у нас локальный путь формируется из двух  фрагметов UNC пути к каталогу и полного локального пути к файлу? Вроде раньше я такого не замечал. ??? Что то непривычное...

**Comment by cmdorexe** [comment]
У меня на FAR 3.0.5000 не воспроизводится. Укажите как вы запускаете скрипты.

**Comment by VictorVG** [comment]
Спасибо! Посмотрел - ассоциации снова работают....
