### ISSUE TITLE
разнобой терминологии?

### ISSUE THREAD

**Issue by AVBL** [FarGroup/FarManager#115]
Параметры / Системные параметры - "Сканировать символические ссылки".
Поиск файлов (Alt-F7) - "искать в символических ссылках".

Однако, вдруг откуда-то выплыл другой термин:
Атрибуты (Ctrl-A) - "Точка повторного анализа"
Раскраска файлов - "Точка повторного анализа"

PS: На днях, после долго перерыва, настраивал "раскраску" для каталогов, включая симлинки (см. соседний тикет), и эта новоявленная "точка" основательно запутывала.

**Comment by alabuzhev** [comment]
Different concepts require different terminology.

"Reparse point" is a file attribute.
"Symbolic link" is one of possible reparse point types.

"Scan symbolic links" & "Search in symbolic links" refer to symbolic links (and directory junctions) only.
"Reparse point" in "Attributes" refers to all possible reparse points.
