### ISSUE TITLE
объёмы диска в информационной панели

### ISSUE THREAD

**Issue by AVBL** [FarGroup/FarManager#116]
Раньше фар в информационной панели (Ctrl-L) показывал все объёмы в байтах. Сейчас вдруг обнаружил, что с какой-то из последних версий размер стал округляться (например, 40,8 ГБ). Соответственно, пожелание - вернуть старые объёмы в байтах (вместо округлённых размеров или вместе с ними).

PS: Проводник, диалог Свойства для дисков - показывает все объёмы и так, и так. Например:
![explorer-sizes](https://user-images.githubusercontent.com/49921898/58375251-25870a00-7f57-11e9-9a8a-180cc1a4be21.jpg)

**Comment by alabuzhev** [comment]
<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd>

And <kbd>F1</kbd> in general.
