### ISSUE TITLE
Очепятка в языковом файле

### ISSUE THREAD

**Issue by lidacity** [FarGroup/FarManager#118]
\far\farlang.templ.m4

MConfigInfoPanelUNServicePrincipal
"Сбъект-служба"

наверное надо "Объект-служба", но "Service Principal" как-то по-другому переводится?

**Comment by alabuzhev** [comment]
Actually it [should be](https://www.microsoft.com/en-us/language/Search?&searchTerm=Service%20Principal&langID=635&Source=true&productid=0) `Субъект`.
Thanks, will fix.

**Comment by alabuzhev** [comment]
Fixed in 05c9be810d3905abaefbb59124452d286f2c05ec.
