### ISSUE TITLE
Новая копия с чистым профилем b5111 - поздняя перерисовка панелей при D&D.

### ISSUE THREAD

**Issue by VictorVG** [FarGroup/FarManager#12]
Копирую перетаскиванием в b5111 файлы с одной панели на другую и вижу:

![1](https://user-images.githubusercontent.com/906886/34201102-8190659e-e584-11e7-9fb3-16301aaeb236.png)

понятно что это косметика - остаётся след прорисовки, но вид забавный, хотя ошибок копирования вроде и нет. В конце появляется нормальный диалог копирования и операция завершается успешно.

**Comment by VictorVG** [comment]
В ночнушке видим то же самое:

![x64](https://user-images.githubusercontent.com/906886/34206495-d3923490-e597-11e7-8004-c81a8d03d6c1.png)

![x86](https://user-images.githubusercontent.com/906886/34206497-d3ba8e90-e597-11e7-80d6-37e25d474410.png)

перерисовка консоли присходит несколько позднее, для воспроизведения явления достаточно взять любой файл, перетащить мышкой на пассивную панель и вернуть обратно где отменить операцию отпустив кнопку - на экране увидим "следы" которых ранее мы не видили. Это и есть замеченная косметика.

**Comment by VictorVG** [comment]
Спасибо! Правда в моей копии новая забава вылезла - выбрали файл, не помечаем, перетаскиваем на пассивную панель и в середине операции как только курсор окажется на ней он тут же прыгает в корень панели:

![1](https://user-images.githubusercontent.com/906886/34209034-9c1885e6-e5a1-11e7-93de-70788d156e76.png)
![2](https://user-images.githubusercontent.com/906886/34209036-9c4ba11a-e5a1-11e7-9f07-996f1955aa04.png)
![3](https://user-images.githubusercontent.com/906886/34209037-9c6cf48c-e5a1-11e7-8b9c-7b8b39683bd1.png)

перепроверил в чистой копии - не воспроизводится, значит либо плагин, либо кто из скриптов шуткует. Пошёл искать хулигана. А то как увидел эти прыжки кота на заборе -  дар речи от удивления потерял. :)

**Comment by VictorVG** [comment]
Забавно - позакрывал все копии фар-а, открыл b5112 заново и явление пропало. Так и не удалось его толком исследовать. А какой был повод отдохнуть после сытного обеда.:) Пришлось снова за перфоратор браться и сверлить бетон.:)

**Comment by shmuz** [comment]
@VictorVG, **у меня просьба**: без надобности сюда не постить.
Делиться впечатлениями - для этого есть форум.
Не забывайте, что каждый пост сюда приводит к отправке десятков e-mail, и десятки людей прерываются, чтобы прочитать, что "явление пропало", и что вы сверлите бетон.
Ещё раз - сюда пишут только по делу - и желательно без воды.
