### ISSUE TITLE
Requires gcc 7.1.0?

### ISSUE THREAD

**Issue by techtonik** [FarGroup/FarManager#15]
I can't compile Far on AppVeyor https://ci.appveyor.com/project/techtonik/farmanager/build/1.0.5#L46

From build log I don't understand what feature of `gcc 7.1.0` is used there?

**Comment by alabuzhev** [comment]
As far as I remember - only variable templates for type traits.
It's a library feature and it can be emulated for 6.x, I just can't see the point.

**Comment by techtonik** [comment]
The point is to setup automated builds on AppVeyor, which doesn't ship with GCC 7.1.0 yet. 

https://help.appveyor.com/discussions/problems/10783-add-gccmingw-720503-plz

**Comment by alabuzhev** [comment]
You can deploy any mingw version [manually](https://ci.appveyor.com/project/alabuzhev/farmanager-qn7kq) from your build script.

**Comment by techtonik** [comment]
Build fail with 7.2.0 for some reason - https://ci.appveyor.com/project/techtonik/farmanager/build/1.1.10#L151

**Comment by alabuzhev** [comment]
You need to set DIRBIT to 64.
Starting from 701ce90 it will be detected automatically.

**Comment by techtonik** [comment]
Nice. It works now. https://ci.appveyor.com/project/techtonik/farmanager#L151
