### ISSUE TITLE
табуляции в DESCRIPT.ION

### ISSUE THREAD

**Issue by AVBL** [FarGroup/FarManager#161]
У меня есть файл DESCRIPT.ION с датой от 2013 года. Тогда он работал, а сейчас не работает (не показывает описания в панелях фара). Проблема в том, что имена файлов/каталогов в нём от описаний отделены табуляциями.

Сколько-то версий назад логику работы с DESCRIPT.ION в фаре переделали. Тогда сломали поддержку строк-продолжений (строки, которые следуют за строкой-описанием и начинаются с пробелов) и, вероятно, именно тогда перестали распознаваться табуляции в строке-описании. Сейчас я проверил, строки-продолжения опять работают, а табуляции - всё ещё нет.

**Comment by alabuzhev** [comment]
[Technical Note -- Using DESCRIPT.ION](https://web.archive.org/web/20160318122322/https://jpsoft.com/ascii/descfile.txt)

> Each line is in the following format:
> 
>      filename.ext Description[*<ID>Other program info]...<CR><LF>
> 
> There is normally one space between the description and filename but
> additional spaces may be used in future versions.

I can't see any mention of Tab characters there.
Does it work in any other program?

**Comment by AVBL** [comment]
> Does it work in any other program?
Я давно не использую DOS (по очевидным причинам) и не могу сейчас проверить 4dos/ndos, но, если память меня не обманывает, табуляции там поддерживались. Ещё, насколько я помню, DESCRIPT.ION создавался в ReGet, но эту программу я тоже лет 15 не использую.

> I can't see any mention of Tab characters there.
Если говорить формально, то под space часто подразумевают не один код 32, а все или часть из whitespace characters.

Да и потом, раньше фар tab поддерживал и никаких проблем не было (да и не должно было быть).

**Comment by alabuzhev** [comment]
Ok.
5427 / cee0c4ff4ff34e878d9d471b83d6e4db8dafd024
