### ISSUE TITLE
Visual C++ warning C4838

### ISSUE THREAD

**Issue by MKadaner** [FarGroup/FarManager#166]
As you surely noticed, VC++ raises "warning C4838: conversion from 'unsigned __int64' to 'int' requires a narrowing conversion" while compiling these lines:

https://github.com/FarGroup/FarManager/blob/a55f5e5101cafdaa48b983e22b3e0df878823915/far/copy.cpp#L135-L146

I posted [DevCom issue](https://developercommunity.visualstudio.com/content/problem/702172/too-aggressive-warning-c4244.html) in the hope that they would fix it soon.

If not, what do you think of creating two different operators, `_bit32` and `_bit64`? Ugly, but at least clean compile. Or, is there a better solution?

**Comment by alabuzhev** [comment]
VS 2019 doesn't show this warning so I suppose it has been fixed already.
Given that it only happens in this particular place - no, I don't think there's a need for different operators, static_cast should do.
7c743c28d55b61507b520dea0f20de06e16587d2

**Comment by MKadaner** [comment]
Thank you. I am surprised I still have VS 2017. Will upgrade.

**Comment by MKadaner** [comment]
Installed VS 2019. The warning is still there:
```
D:\TEMP\Projects\C++ Scratchpad>type "C++ Scratchpad.cpp"
constexpr auto operator "" _bit(unsigned long long pos)
{
    return 1ull << pos;
}
struct S
{
    unsigned u;
};
static const S s{ 0_bit };

D:\TEMP\Projects\C++ Scratchpad>cl /c /permissive- /W4 /WX "C++ Scratchpad.cpp"
Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

C++ Scratchpad.cpp
C++ Scratchpad.cpp(9): error C2220: warning treated as error - no 'object' file generated
C++ Scratchpad.cpp(9): warning C4244: 'initializing': conversion from 'unsigned __int64' to 'unsigned int', possible loss of data
```
Will continue monitoring DevCom issue.
