### ISSUE TITLE
crash in arclite.dll

### ISSUE THREAD

**Issue by HommeCurieux** [FarGroup/FarManager#171]
in "\plugins\arclite\ui.cpp"  line 164
```diff
  if (Far::get_msg(msg_ids[0]) != msg_texts[0]) {
    for (int i = 0; i < 1 + 5 + 5; ++i)
- suffixes[i] = (msg_texts[i] = msg_ids[i]      ? Far::get_msg(msg_ids[i]) : wstring()).c_str();
+ suffixes[i] = (msg_texts[i] = msg_ids[i] != 0 ? Far::get_msg(msg_ids[i]) : wstring()).c_str();
```diff

**Comment by alabuzhev** [comment]
Could you please elaborate:
- How to reproduce the crash?
- What does your change fix?

**Comment by HommeCurieux** [comment]
In Far Manager v3.0 build 5476 x64 (2019-09-19) is no longer confirmed.
![1](https://user-images.githubusercontent.com/16163947/65223141-2f65e780-dac9-11e9-89ae-b12011d9bd46.PNG)
