### ISSUE TITLE
Show partially panel on CTRL+O or command execution

### ISSUE THREAD

**Issue by kingoleg** [FarGroup/FarManager#172]
Far 5454x64 shows partially panel on top right corner when command line should be shown

**Comment by kingoleg** [comment]
Opps, fixed after typing 

$ cls

o0

**Comment by alabuzhev** [comment]
Sometimes (usually due to plugin bugs or 3rd-party apps) the screen under panels may contain rubbish. That's unfortunate, but we can't do much about it. As you've discovered, `cls` helps indeed.
