### ISSUE TITLE
Saving edited file by creating a temp copy

### ISSUE THREAD

**Issue by ascvorcov** [FarGroup/FarManager#175]
Latest versions of far manager save edited files by creating a temporary copy,
renaming original file, renaming copy to original file name copying attributes, 
and finally deleting old file.

This breaks some of the behavior some applications rely on - for example, if application is
configured to monitor 'last write time' attribute through win32 API - this event is triggered only for "FAR####.tmp" file - which is not a monitoring target, and immediately deleted.

Older FAR versions did overwrite original file, and last write attribute modification 
was fired for original file name.

Would it be possible to revert to old behavior, or at least introduce a setting
to preserve original file saving functionality?

**Comment by shmuz** [comment]
Try `far:config`, see options `Editor.SaveSafely`, `Editor.CreateBackups`.
There's still no help about them so try them and see their impact.

**Comment by ascvorcov** [comment]
Thank you, setting Editor.SaveSafely to false solves my problem
