### ISSUE TITLE
Translate remaining help pages into English

### ISSUE THREAD

**Issue by MKadaner** [FarGroup/FarManager#19]
Some help pages in file FarEng.hlf.m4 are copy-pasted from the Russian help file. I am going to translate them as time permits.

**Comment by VictorVG** [comment]
Опечатка в far/FarEng.hlf.m4::5248  - Version in**v**formation :)

**Comment by VictorVG** [comment]
> LuaFAR Search
> 
> Файлов найдено:          58
> Файлов обработано:       58
> Файлов с вхождениями:    2
> Файлов модифицировано:   2
> 
> Вхождений найдено:       6
> Замен выполнено:         6

греп по исходникам Far для текущего Git 58db52044 мгновенно  отыскивает где надо исправить - far\FarEng.hlf.m4

строка 852:

  **~Version invformation~@FarAbout@**

строка  5247:

**$ #Version invformation#**

P.S.

Мне уже третий редактор из  издательств говорит что после добавления Вашего перевода обратил внимание на ошибки в тексте ...

**Comment by MKadaner** [comment]
@VictorVG: I am sorry for missing the typo. Things happen, you know.
@alabuzhev: Thank you for fixing it.  For whatever reasons I did not receive the notification about Victor's comment here. I'll be monitoring the thread more closely. You can assign the Issue to me. I cannot do it myself.

**Comment by MKadaner** [comment]
Translation of the remaining help pages to English completed in PR #252. Closing this issue.

Please report new help-related issues separately. Consider mentioning me to make sure I do not miss them.
