### ISSUE TITLE
Add support for symbolic links creation without elevation

### ISSUE THREAD

**Issue by Vertigo093i** [FarGroup/FarManager#22]
According to [this blog post](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/) Windows 10 version 1703 and later have possibility to allow symbolic links creation without elevation while in "Developer Mode". This is achieved through the `CreateSymbolicLink` API's new flag: `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE`.

mklink utility and Git for Windows both support this. It would be very nice if the Far itself also has this feature.

**Comment by alabuzhev** [comment]
> This is achieved through the `CreateSymbolicLink` API's new flag

Fabulously retarded design decision...
Ok, we will use this flag.

**Comment by alabuzhev** [comment]
build 5136 / 4f717daa

**Comment by Vertigo093i** [comment]
Thank you!
Also related 5139 / a86c1702e2449c05a92f7b5c5778e6035367bc1b.
