### ISSUE TITLE
Help for MkTemp is out of date or something is broken

### ISSUE THREAD

**Issue by nightroman** [FarGroup/FarManager#221]
Here is what the API help tells about `MkTemp`

    Prefix
    Указывает на оканчивающуюся нулём строку-префикс. Максимум первые четыре
    символа из этой строки будут использованы в качестве префикса имени файла.
    Far Manager дополнит символами '0' префикс, если размер Prefix меньше 4.
    Если Prefix = NULL или пустой строке, то будет применён стандартный префикс
    "FTMP"

In FarNet.PowerShellFar, from command line invoke repeatedly commands like:

    ps: $Far.TempName()
    ps: $Far.TempName('my')

Sample output:

    ps: $Far.TempName()
    ...\AppData\Local\Temp\FARFAC.tmp
    ps: $Far.TempName()
    ...\AppData\Local\Temp\FARFAD.tmp

    ps: $Far.TempName('my')
    ...\AppData\Local\Temp\my63E4.tmp
    ps: $Far.TempName('my')
    ...\AppData\Local\Temp\my63E5.tmp

We can see that:

- Standard prefix seems to be "FAR"
- Custom prefix is not appended by "0"

**Comment by alabuzhev** [comment]
2109026 / 5565.
