### ISSUE TITLE
Web site https://www.farmanager.com/ is broken

### ISSUE THREAD

**Issue by anatolyborodin** [FarGroup/FarManager#224]
https://www.farmanager.com/ shows the index page as a source code:

```php
<?php
	$current_page = 0;

	include ("common.php");

	do_begin_html ();
	do_header() ;

	if ( !strcmp ($lang, "ru") )
		include ("inc/index.ru.php");
	else
		include ("inc/index.en.php");

	do_footer();
	do_end_html ();
?>
```

**Comment by anatolyborodin** [comment]
Here is the snapshot taken on 15.01.2020: http://web.archive.org/web/20200115001020/https://farmanager.com/

**Comment by anatolyborodin** [comment]
@alabuzhev the fact that the website works **today** (thanks btw) doesn't mean that the original issue is invalid ;)

**Comment by alabuzhev** [comment]
The website wasn't working due to planned upgrade, so there's no issue at all.
