### ISSUE TITLE
Тег stable

### ISSUE THREAD

**Issue by xtemp09** [FarGroup/FarManager#225]
Если посмотрите теги в релизах, вы увидите много всяких ci/vXXXXXXXXXXX.

Может, пришла пора добавить тег stable, чтобы выкачивать стабильный релиз или исходный код стабильного релиза?

Только представьте, заходишь на странице в Releases, жмёшь тег Stable и тебе показываются стабильные релизы! Крутто!

**Comment by alabuzhev** [comment]
Would be cool indeed, but GitHub doesn't work like that.
