### ISSUE TITLE
[Bug] virtualenvwrapper-win doesn't work

### ISSUE THREAD

**Issue by Kristinita** [FarGroup/FarManager#23]
### 1. Summary

**If** I use Far:

    I can't begin to use [**virtualenvwrapper-win**](https://pypi.python.org/pypi/virtualenvwrapper-win) in Far.

**elif** I use default cmd.exe terminal:

    I can successful use virtualenvwrapper-win.

### 2. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Python 3.6.4,
+ Far Manager 3.0 (build 5100) x64,
+ virtualenv 15.1.0,
+ virtualenvwrapper-win 1.2.5.

### 3. Steps to reproduce

I run commands from [**virtualenvwrapper-win**](https://pypi.python.org/pypi/virtualenvwrapper-win) documentation.

### 4. Expected behavior

Behavior in default cmd.exe:

```shell
D:\SashaPyromaDebugging>mkvirtualenv sashaenv
Using base prefix 'c:\\python36'
New python executable in C:\Users\SashaChernykh\Envs\sashaenv\Scripts\python.exe
Installing setuptools, pip, wheel…done.

(sashaenv) D:\SashaPyromaDebugging>workon sashaenv
(sashaenv) D:\SashaPyromaDebugging>toggleglobalsitepackages

    Enabled global site-packages

(sashaenv) D:\SashaPyromaDebugging>toggleglobalsitepackages

    Disabled global site-packages
```

### 5. Actual behavior

Behavior in Far Manager:

```shell
D:\SashaPyromaDebugging>mkvirtualenv sashaenv
Using base prefix 'c:\\python36'
New python executable in C:\Users\SashaChernykh\Envs\sashaenv\Scripts\python.exe
Installing setuptools, pip, wheel…done.

D:\SashaPyromaDebugging>workon sashaenv

D:\SashaPyromaDebugging>toggleglobalsitepackages

 You must have an active virtualenv to use this command.
```

I can't activate my virtualenv `sashaenv`.

Thanks.

**Comment by alabuzhev** [comment]
> I can't begin to use [**virtualenvwrapper-win**](https://pypi.python.org/pypi/virtualenvwrapper-win) in Far.

Have you read that link yourself?

> These scripts should work on any version of Windows (Windows XP, Windows Vista, Windows 7/8/10).
> 
> However, they only work in the **regular command prompt**.

Far is not a "regular command prompt" and it is not possible to modify its environment with bat files.

You can do that with plugins or lua scripts, but that is a different story.

**Comment by MKadaner** [comment]
However, you can create a shortcut (desktop or taskbar) and set its "Target" (command to execute) to something like this:
`cmd /k "mkvirtualenv sashaenv"&far`
**Disclaimer:** I did not try this command, just typed it here. It may not work in your case.

**Comment by DamianFekete** [comment]
Dear Far fans,

This is an old topic which bugged me for some time, so as I have found a solution (by "John Doe") I will link it here: https://forum.farmanager.com/viewtopic.php?p=176009#p176009

---

Assuming you save the following code under `%FARPROFILE%\venv.lua` you can call it as `luas:@%FARPROFILE%\venv.lua "venv"` to create a Python virtual environment under the folder `venv`.

You could also add the command as a Menu entry or create an alias (doskey) for it (see below).

```lua
if print == mf.print then
    print = mf.printconsole
end

local path = win.GetEnv "PATH"
local venv = win.GetEnv "VENV"

local function activate(venv)
    local dir = venv .. "\\Scripts"
    local exist = win.GetFileAttr(dir)
    if not exist then
        print(venv .. " not found")
    else
        win.SetEnv("VENV", venv)
        win.SetEnv("PATH", dir .. ";" .. path)
        print("Virtual environment activated: " .. venv)
    end
end

local function deactivate()
    if not venv then
        return
    end
    local scripts = venv .. "\\Scripts;"
    local i, j = path:find(scripts, 1, true)
    if i then
        path = path:sub(1, i - 1) .. path:sub(j + 1, -1)
        if path:find(scripts, 1, true) then
            print "Error: %PATH% includes %VENV% more than once"
            return
        end
        win.SetEnv("PATH", path)
        win.SetEnv("VENV")
        print("Virtual environment deactivated: " .. venv)
    else
        --print(path)
        --print(venv)
        print "Error: %PATH% does not contain %VENV%"
    end
end

if ... == nil then
    if venv then
        deactivate()
    end
    return
end

local name = ...
local venv_path = far.ConvertPath(name)
local venv_path_exists = win.GetFileAttr(venv_path)

if venv then
    deactivate()
end

if not venv_path_exists then
    panel.GetUserScreen()
    print("Creating virtual envinronment: " .. venv_path)
    win.system(('python -m venv "%s"'):format(venv_path))
    panel.SetUserScreen()
end
activate(venv_path)
```

---

**Alias/Doskey:**
* Use something like this (or ConEmu) to automatically load aliases: https://forum.farmanager.com/viewtopic.php?f=15&t=8546 (make sure to translate the spoilers as well to understand the entire context if you're unfamiliar to aliases).
* Just to test an alias execute `doskey venv=luas:@"%FARPROFILE%\venv.lua" "xyz"`, and after that you can execute `venv` directly in Far in the command line.

**Comment by yegor-mialyk** [comment]
The more advanced and generic solution is here: https://forum.farmanager.com/viewtopic.php?t=13400. It should cover a lot more scenarios.

Here is an execution sample for Python virtual env using new script:

`env:<mkvirtualenv sashaenv`
