### ISSUE TITLE
Поддержка Windows Terminal

### ISSUE THREAD

**Issue by drweb86** [FarGroup/FarManager#230]
Добрый день,

Windows Terminal вроде выходит из беты. Там поддерживаются много вкладок и ресайзинг. Вот как выглядит там фар - 
![изображение](https://user-images.githubusercontent.com/4712173/76701859-1b94ea00-66d6-11ea-9c2c-dfa69b9c4da2.png) (там что-то с слитностью диалоговых границ и страшненькие цвета)

Если что, я пользуюсь ConEmu  - выглядит все четко и менять не хочется. Но эта штука микрософтовская и по идее будет многолетнее ConEmu

**Comment by alabuzhev** [comment]
So what support are you asking for?
Far is a console application, meaning that all its inputs and outputs are defined by a terminal, be it the standard windows host, conemu or this new thing.
We can't help with imperfect fonts, weird colors, missing hotkeys etc.
Please report any issues to https://github.com/microsoft/terminal directly.

**Comment by drweb86** [comment]
Спасибо.

Написал им по поводу шрифтов и выделения. Они в курсе и подправят это к моменту 1 версии.
