### ISSUE TITLE
Panel.SetPosIdx makes hidden Panel visible

### ISSUE THREAD

**Issue by taviso** [FarGroup/FarManager#233]
Hello, if a panel is not visible, changing it's item position makes it visible again, I think this is a bug. 

Reproduce:

```lua
    -- Prentend a user has hidden the Panels
    if APanel.Visible or PPanel.Visible then
        Keys("CtrlO")
    end  

    -- Change the Position
    Panel.SetPosIdx(0, 1)
    -- BUG: The panel is now visible
```

If you set the position to the active item, then it doesn't become visible. For example, `Panel.SetPosIdx(0, 0)` does not make the panel visible.

**Comment by alabuzhev** [comment]
Hi, as far as I can see, it's [intentional](https://github.com/FarGroup/FarManager/blob/45360e8551787442a52211f66cc32cce1e4d789f/far/macro.cpp#L4299). Last time it was changed in 0c423fe7a9eb79d747288b30d1e534c88fc1aa53. @shmuz , could you confirm please?

**Comment by shmuz** [comment]
It must take some time for investigation (hopefully not more than a week).

**Comment by taviso** [comment]
Thank you! I assumed it was a bug, because usually you can't have **only** the passive panel active.

If you hide the Active panel (e.g. Ctrl+F1), then the Passive panel will become active.

Reproduce:

1. Hide both panels: `Ctrl+O`
2. Change the Passive item by typing `lua:Panel.SetPosIdx(1, 1)`

Now only a passive panel is visible. I guess you can workaround it like this, in case anybody else searches for this: 😄 

```lua
local NotHidden = APanel.Visible
Panel.SetPosIdx(0, num)
if not NotHidden == APanel.Visible then
    -- https://github.com/FarGroup/FarManager/issues/233
    Keys(APanel.Left and "CtrlF1" or "CtrlF2")
end
```

**Comment by shmuz** [comment]
Fixed in build 5591 (available from [Releases](https://github.com/FarGroup/FarManager/releases) page). Please test.
