### ISSUE TITLE
set command is too strict with whitespace

### ISSUE THREAD

**Issue by taviso** [FarGroup/FarManager#237]
I was trying to set a variable like this:

`set bookmark=<CtrlF>`

so that later on I can do `cd %bookmark%`, that doesn't work though because `CtrlF` adds a space after the path.

In cmd, if you do `set foo="bar"<space>`, it works as expected, but far does not, the space is added to the variable.

I think `set` should ignore spaces at the end of commands.

Reproduce:

1. type `set bookmark=`
2. Press `CtrlF` `Enter`
3. type `cd %bookmark%`
4. `The system cannot find the path specified.`

Verify it's the spaces:
1. type `set bookmark=`
2. Press `CtrlF` `Backspace` `Enter`
3. type `cd %bookmark%`
4. Success

**Comment by alabuzhev** [comment]
Fair enough, fixed.
