### ISSUE TITLE
Far2 CtrlAltShift behavior?

### ISSUE THREAD

**Issue by AnrDaemon** [FarGroup/FarManager#242]
Far3 only react to `CtrlAltShift` if all 3 keys are pressed on the same side of the keyboard, while Far2 react to CAS in any combination.

Don't know about you, but I'm using both hands when working with computer. And pressing Ctrl+Shift on the right and Alt on the left (or the opposite) is easier for me, than to twist fingers to press all keys on the same side at once.

**Comment by alabuzhev** [comment]
Fair enough, 5604.
