### ISSUE TITLE
Suggestion: make all history lists searchable

### ISSUE THREAD

**Issue by kthulhu** [FarGroup/FarManager#245]
How hard it would be to make all the history panels searchable?
Something "unix-style", let's say on "/" keypress - capture a pattern and filter the entries.

Right now it's pretty hard to find anything in those Ctrl-Num lists of filesystem locations or folders / commands history.

Any opinions?

**Comment by yegor-mialyk** [comment]
It is hard to tell what you mean by "history (?) panel", but all menus including command history (AltF8) are searchable. Press CtrlAltF or RAlt to activate the search (you will see [ ] in title) and start typing.

As for file panels there is no quick filter, but there is a quick search (Alt+<name>) and filters (Ctrl+I).

**Comment by kthulhu** [comment]
Exactly, i meant command, directory, edit history panels and those one Ctrl-Shift-Num, Ctrl-Num, quick filesystem shortcuts, not sure what's the proper name.
I see, it's already there. Good to know.

PS: By the way, are there a full maintainable list of Far hotkeys exists anywhere?
In documentation maybe or elsewhere?

**Comment by yegor-mialyk** [comment]
F1
Keyboard reference

**Comment by kthulhu** [comment]
Oh, so it's always was here, nice, thank you.
I was checking just documentation folder, it's a bit confusing.
Closing.
