### ISSUE TITLE
Problem opening hiew from plugin

### ISSUE THREAD

**Issue by polakovicp** [FarGroup/FarManager#246]
Hi, this is ask for help rather than issue report.
I am trying to open hiew from plugin using following code
```
BOOL OpenExternalViewer(
    const wchar_t * pwszExternalViewer,
    const fs::path& file)
{
    fs::path parent{ file.parent_path() };
    std::wstring wsCmd{ L"\"\"" };
    wsCmd.insert(1, file);

    SHELLEXECUTEINFO sei = { sizeof(sei) };
    sei.fMask = SEE_MASK_NOASYNC | SEE_MASK_NO_CONSOLE;
    sei.hwnd = NULL;
    //sei.lpVerb = L"open";
    sei.lpFile = pwszExternalViewer;
    sei.lpParameters = wsCmd.c_str();
    sei.lpDirectory = parent.c_str();
    sei.nShow = SW_SHOWNORMAL;

    return ShellExecuteEx(&sei);
}
```

Yes, file gets opened but the screen is messed up
![obrázok](https://user-images.githubusercontent.com/522894/84682100-70ded280-af35-11ea-86e3-6b403b555693.png)

Any advice how to correctly open external viewer with inherited console?
Thanks!

**Comment by alabuzhev** [comment]
Probably hiew can't work properly if the screen buffer is too large.
You can check that by running Far with `/w-` parameter.
If so, you can use various console APIs to reduce the size before invoking ShellExecuteEx and to restore it afterwards.

**Comment by polakovicp** [comment]
Reducing sizes works
```
void StretchConsoleWindowToScreenBuffer()
{
    CONSOLE_SCREEN_BUFFER_INFO csbi{ 0 };

    auto hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
    GetConsoleScreenBufferInfo(hConsole, &csbi);

    COORD coord{ csbi.dwSize.X, csbi.dwSize.Y - csbi.srWindow.Top };

    SMALL_RECT sr{
        csbi.srWindow.Left,
        0x0,
        csbi.srWindow.Right,
        csbi.srWindow.Bottom - csbi.srWindow.Top
    };

    SetConsoleWindowInfo(hConsole, TRUE, &sr);
    SetConsoleScreenBufferSize(hConsole, coord);
    SetCursorPos(
        csbi.dwCursorPosition.X,
        csbi.dwCursorPosition.Y - csbi.srWindow.Top);
};
```
I am running _StretchConsoleWindowToScreenBuffer_ inside _OpenPlugin_, because restoring console after _ShellExecuteEx_ somehow doesn't work...
This code leaves editor screen black (my plugin controls editor):
```
BOOL OpenExternalViewer(
    const wchar_t * pwszExternalViewer,
    const fs::path& file)
{
... same as before ...

... save screen info ...
    StretchConsoleWindowToScreenBuffer()

    auto bRes = ShellExecuteEx(&sei);

    HANDLE hWaitHandle = NULL;
    pRcs->hObject = sei.hProcess;

    RegisterWaitForSingleObject(
        &pRcs->hWait,
        sei.hProcess,
        WaitOrTimerCallback,
        ptr.release(),
        INFINITE,
        WT_EXECUTEINWAITTHREAD | WT_EXECUTEONLYONCE);

    return bRes;
}
```
This callback should restore screen, but it leaves editor screen blank
```
VOID CALLBACK WaitOrTimerCallback(
    _In_ LPVOID   lpParameter,
    _In_ BOOLEAN TimerOrWaitFired
)
{
    std::unique_ptr<REVERT_CONSOLE_SCREEN> rcsPtr((PREVERT_CONSOLE_SCREEN)lpParameter);

    UnregisterWait(rcsPtr->hWait);
    CloseHandle(rcsPtr->hObject);

    SetConsoleScreenBufferSize(hConsole, original dwSize);
    SetConsoleWindowInfo(hConsole, TRUE, original srWindow);
    
    SetCursorPos(original cursor X, originl cursor Y);
}
```

**Comment by alabuzhev** [comment]
Why do you need RegisterWaitForSingleObject there? It's for thread pools.
You're launching the process in the same console and therefore can't do anything useful until it finishes, so can just wait for it synchronously with WaitForSingleObject.

Don't forget to pass SEE_MASK_NOCLOSEPROCESS to ShellExecuteEx to obtain the handle in the first place.

**Comment by polakovicp** [comment]
As mentioned before, upon hiew exit, editor screen remains black (PgUp & PgDown redraws some portion of screen, but keybar labels are still black...)
```
   // StretchConsoleWindowToScreenBuffer now returns previous CONSOLE_SCREEN_BUFFER_INFO
    auto csbi = StretchConsoleWindowToScreenBuffer();

    auto bRes = ShellExecuteEx(&sei);

    while (WaitForSingleObject(sei.hProcess, INFINITE) != WAIT_OBJECT_0);

    CloseHandle(sei.hProcess);

    RestoreConsoleWindow(csbi);
```
Restoring screen after 
```
void RestoreConsoleWindow(CONSOLE_SCREEN_BUFFER_INFO csbi)
{
    auto hConsole = GetStdHandle(STD_OUTPUT_HANDLE);

    SetConsoleScreenBufferSize(hConsole, csbi.dwSize);
    SetConsoleWindowInfo(hConsole, TRUE, &csbi.srWindow);
    SetCursorPos(
        csbi.dwCursorPosition.X,
        csbi.dwCursorPosition.Y);
};
```

**Comment by alabuzhev** [comment]
> editor screen remains black (PgUp & PgDown redraws some portion of screen

Far redraws only "changed" screen areas due to performance reasons.
In this case it obviously doesn't know that you've drawn something on the screen yourself and keeps updating only what's needed.
You need to either manually save the screen content before creating the process and restore it afterwards (using console or Far API) or force redraw of everything using ACTL_REDRAWALL.

**Comment by polakovicp** [comment]
I removed setting size of the console buffer (_SetConsoleScreenBufferSize_) and left only moving console window to the first row of the buffer (SetConsoleWindowInfo) and everything seems to work well (without Save&Restore screen).
@alabuzhev thank you very much for the help
```
    CONSOLE_SCREEN_BUFFER_INFO csbi{ 0 };

    auto hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
    GetConsoleScreenBufferInfo(hConsole, &csbi);

    SMALL_RECT sr{
        csbi.srWindow.Left, 0x0,
        csbi.srWindow.Right, csbi.srWindow.Bottom - csbi.srWindow.Top};

    SetConsoleWindowInfo(hConsole, TRUE, &sr);
    SetCursorPos(csbi.dwCursorPosition.X, csbi.dwCursorPosition.Y - csbi.srWindow.Top);
    
    auto bRes = ShellExecuteEx(&sei);

    while (WaitForSingleObject(sei.hProcess, INFINITE) != WAIT_OBJECT_0);

    CloseHandle(sei.hProcess);

    SetConsoleWindowInfo(hConsole, TRUE, &csbi.srWindow);
    SetCursorPos(csbi.dwCursorPosition.X, csbi.dwCursorPosition.Y);
```

**Comment by alabuzhev** [comment]
@polakovicp, it appears that this scenario works fine without any additional actions in "legacy console" mode - hiew resizes the buffer itself and restores upon exit.
In other words - it's another Windows 10 console regression, you might want to report it [here](https://github.com/microsoft/terminal/issues).

**Comment by alabuzhev** [comment]
It's also reproducible if you start hiew manually from cmd.exe when the part of the screen buffer is above the window (i.e. press and hold <kbd>Enter</kbd> for a while first).
