### ISSUE TITLE
Идея - возможность пинить папки в диалоге смены диска

### ISSUE THREAD

**Issue by drweb86** [FarGroup/FarManager#248]
Добрый день,

В голову пришла идея, хотелось бы поделиться.

![изображение](https://user-images.githubusercontent.com/4712173/85695847-17b73180-b6e1-11ea-93fc-cc1794765e14.png)
При нажатии на Alt+F1 я вижу список дисков. Идея - добавить возможность добавлять туда папки. Т.е. добавить шорткаты Ins,F4 и по нажатии на них открывать диалог добавления папки в список с полями Название, Путь, и показывать впоследствии название в этом списке.

Это позволит запинить наиболее часто используемые папки с проектными папками, и легко переходить между ними.

**Comment by shmuz** [comment]
Это делают некоторые плагигы и макросы. Ищите в форуме и на плагринге.
