### ISSUE TITLE
How to redefine shortcuts

### ISSUE THREAD

**Issue by amirhosseindavoody** [FarGroup/FarManager#249]
Stupid question, but how can I redefine shortcut key for copying fullpath to a file or directory?

**Comment by alabuzhev** [comment]
Short answer:
- Press <kbd>Ctrl</kbd>+<kbd>.</kbd>, press the original key, press <kbd>Ctrl</kbd>+<kbd>.</kbd> again, press a new key, press Enter.

Long answer:
- Read about keyboard macros - <kbd>F1</kbd>, <kbd>End</kbd>, <kbd>Enter</kbd>.
