### ISSUE TITLE
Use ArcLite for .apk and .aar by default

### ISSUE THREAD

**Issue by rusefi** [FarGroup/FarManager#250]
Default Far Manager installation knows to use ArcLite to enter .zip and .jar files

There are two Android file formats which are also zip archieves - .apk and .aar. Those should be handled by ArcLite in the same exact manner as .jar and .zip

PS: thank you for the amazing tool!

**Comment by alabuzhev** [comment]
707f469 / Far 5633 / ArcLite 313
