### ISSUE TITLE
Mistake in help file

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#261]
Based on English help file....
In section: @InfoPanelSettings
there is described "User name format" - first of all is "Default" line 1230 in FarEng.hlf.m4.
But in configuration screen there is no "Default" option.

> #User name format#
> 
>  Can be one of:
> 
>  - #Default#
>    User login, (for example, JeffSmith)

![FAR_InfoPanel_Settings](https://user-images.githubusercontent.com/26287042/88845980-3c715e00-d1e5-11ea-8415-2b75eb6aa874.PNG)

**Comment by alabuzhev** [comment]
Actually both the help and the configuration were incorrect. Thanks.
