### ISSUE TITLE
Feature Request: Reuse User Input tokens in F2 User Menu

### ISSUE THREAD

**Issue by fitdev** [FarGroup/FarManager#269]
F2 User Menu allows one to define inline user input tokens in the form: `!?$<history>$<title>?<init>!`.

Sometimes it is useful to insert the provided values in _more than one place_ in the command. At present this does not seem possible, and so the user would need to manually type in the same value. This is inefficient and error-prone.

So, perhaps this syntax can be augmented with say `!?$<history>$?!` token where `<history>` acts as an identifier of the tag that takes the already provided value. Or a new syntax could be devised perhaps?

So for example:

`mycmd.exe -param1 !?$mycmd.param1$First Parameter?default value! -output file.!?$mycmd.param1$?!.ext` would be transformed into: `mycmd.exe -param1 foo -output file.foo.ext` with the user-provided value for `mycmd.param1` being `foo` (which was asked of user _once_).

**Comment by alabuzhev** [comment]
This is already possible with an extra step.

mycmd.cmd:
```cmd
mycmd.exe -param1 %1 -output file.%1.ext
```
User menu:
```cmd
mycmd.cmd !?First Parameter?default value!
```

**Comment by fitdev** [comment]
Thank you for the workaround tip. But unfortunately this leads to a huge duplication of effort, especially when many commands are involved and each has many parameters, since it requires you to define a cmd file for each user command.

**Comment by alabuzhev** [comment]
One more workaround:
```cmd
@for /f "usebackq tokens=2,3,4" %a in (`echo - !?P1?! !?P2?! !?P3?!`) do mycmd.exe %a file.%a.ext %b %c
```

P.S. Reusing input tokens is a neat idea per se, but these metasymbols are already overcomplicated, so I'd like to make sure there's no other (reasonable enough) way before making any changes there.

**Comment by bitraid** [comment]
If you are willing to sacrifice a character (in this example it's `|`), you can use something like this:
```
@for /f "tokens=1-26 delims=|" %A in ("!?$mycmd.paramA$First Parameter?default value!|!?$mycmd.paramB$Second Parameter?default value 2!") do mycmd.exe -param1 %A -param2 %B -input "file.%A.ext" -output "file.%B.ext"
```
Up to 26 (passed with `%A` - `%Z`) recurring parameter-values can be used (the other ones can be defined as usual, to prevent the forbidden character limitation).

**Comment by bitraid** [comment]
We posted almost the same time @alabuzhev!
I think your example has problems with values containing spaces, though.

**Comment by alabuzhev** [comment]
@bitraid similar ideas and almost simultaneously :)
Handling spaces is left as an exercise for the reader - your example looks better indeed.
Technically any rare/invalid Unicode character can be used instead of `|`, e.g. `￿` (0xFFFF).

**Comment by fitdev** [comment]
> P.S. Reusing input tokens is a neat idea per se, but these metasymbols are already overcomplicated, so I'd like to make sure there's no other (reasonable enough) way before making any changes there.

I partially agree with you. However in my opinion slightly adjusting the existing syntax to allow for token reuse would be _an easier to use solution for end users_, despite somewhat complicated syntax. Why? Because the alternative is likely to be even more complicated for end users. I doubt that many of them know the cmd syntax by heart and would have no idea how to use the workarounds you suggested (especially the 2nd one). So to them (and for me personally), having a built-in mechanism would be preferred.

Also, some of my commands for instance, already do use the `@for ...` syntax, and having those nested is not supported by cmd as far as  I know, and in any case would make it a virtually undecipherable mess - more difficult to understand, IMHO, than having a slightly modified syntax for token reuse in FAR.

**Comment by alabuzhev** [comment]
Ok, let's try.
d3db2da / 5675

**Comment by fitdev** [comment]
Wow! That was so fast! Thank you so much! Will be sure to try it ASAP (likely in a few days, as I have 20+ FAR instances running and cannot close all of them to test the update).

**Comment by fitdev** [comment]
Sorry for the late reply. Have only gotten around to this now and tested it today. Works really well! Thank you. The only drawback is that it seems to work across a single line only, i.e. it is not applied to subsequent lines, which is often useful. So perhaps you can make it so it would apply to other lines (commands) as well, in case of multi-line commands?

**Comment by alabuzhev** [comment]
In general, these are not multi-line commands, but completely separate commands, grouped for convenience.
However, sharing the variables between them would probably be more logical than not sharing.

6c721cf / 5680

**Comment by fitdev** [comment]
Just gotten around to trying the latest build 5699. Now there seems to be an issue with the generated temp files that are generated by commands containing: `!@FQ!`, so that syntax like this `for /F "usebackq tokens=*" %a in ("!@FQ!") do ` no longer works. I cannot seem to examine the generated temp files, since FAR deletes them immediately.

**Comment by alabuzhev** [comment]
@fitdev maybe, I'll have a look. However, it's a separate thing. Does the feature discussed in this issue (reusing input tokens) work as expected?

**Comment by fitdev** [comment]
@alabuzhev
Thank you for a quick response. The problem is I cannot test the feature of this issue, since I rely on `!@FQ!` in virtually all commands, and none of them work. I have done some extensive testing with `!@FQ!` and `!@UFQ!` and other varieties (on different commands, including simple like even `copy "!@UFQ!" "files.txt"` and _none_ of them work. They do not produce any errors or output. And the `FAR607A.tmp` files seem to be deleted almost immediately by FAR... I was not able to get a hold of a single file, since they are gone in an instant.

**Comment by fitdev** [comment]
The last build I tried was 5678 and everything was working fine there.

**Comment by alabuzhev** [comment]
Ok, the issue with !@FQ! should be fixed in 5700.
I believe it was introduced in 5698, so any version in the range 5680 - 5697 should work fine as well.

**Comment by fitdev** [comment]
@alabuzhev Thanks so much for looking into this and confirming this bug. Would 5700 be available in a few days, or should I downgrade (if it is safe) to an earlier build, in case it takes longer for 5700 to appear?

**Comment by alabuzhev** [comment]
It should appear within the next hour on the [releases](https://github.com/FarGroup/FarManager/releases) page here and after 10 hours or so on farmanager.com.
Downgrading is safe as well.

**Comment by fitdev** [comment]
@alabuzhev That's awesome! Thanks so much for such a quick fix! I will let you know regarding the main issue tomorrow.

**Comment by fitdev** [comment]
I have installed 5700 and everything is working now! Also tested the main issue reported here. Now the user tokens can be properly reused even across multiple command lines. Great work! Thank you.
