### ISSUE TITLE
How to import templates in Far Manager3.x? Which plugins support this functionality?

### ISSUE THREAD

**Issue by piyush26c** [FarGroup/FarManager#270]
Hello developers,
I just wanted to know how to import a template in FAR manager3.x? I am looking for this for a long time but I can't find a way to do it. Here is what I want:

When I want to add two entities whether it would be string, double values, or integer values whatever it might it be......I will write a template call add function so every time I won't be writing this add so-called "template-function", I will add this template in add.cpp file or any other extension file (this is what I don't know) and when I type to add in my regular source code file - add template should get imported.

Plugins: Text

**Comment by alabuzhev** [comment]
1. This might work - https://github.com/chronoxor/TrueTemplate
2. Please use [forum](https://enforum.farmanager.com/) for general questions.
