### ISSUE TITLE
Mouse wheel doesn't work correctly when the window is not focused

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [FarGroup/FarManager#271]
### Steps to reproduce

1. Launch Far.
2. Switch focus to another window that does not cover the Far window.
3. Move mouse over the Far window.
4. Mouse wheel up.

### Expected result

Mouse wheel should work the same independently of whether the window has focus or not.

### Actual result

![image](https://user-images.githubusercontent.com/302938/95982315-a7b3ef00-0e28-11eb-9b40-5ea5e76471f9.png)

--------

Far version 3.0.5678.0 x64.

**Comment by yegor-mialyk** [comment]
A console window does not receive any mouse events when not in focus. It is not a Far Manager issue.

**Comment by alabuzhev** [comment]
To be precise, the inactive console window does receive mouse events, but it doesn't forward them to the console application, so we can't help.

Consider reporting it to https://github.com/microsoft/terminal.
