### ISSUE TITLE
Editor: Selection isn't cleared on Ctrl+Home/End

### ISSUE THREAD

**Issue by tnodir** [FarGroup/FarManager#274]
Editor Settings: turn off "Persistent blocks".

1. Edit some text file and select some line
2. Press Ctrl+Home or Ctrl+End
Bug: Selection is not cleared.

**Comment by tnodir** [comment]
Other related bug:
1. Select some characters in the line
2. Press Ctrl+Right to next word
Bug: Selection is not cleared.
3. Start selecting with Shift+Right
Bug: Selection continues in the old position.

**Comment by johnd0e** [comment]
Confirming (5683)

**Comment by alabuzhev** [comment]
Fixed in 5684 (012d498), thank you.
