### ISSUE TITLE
Small bug (?) in window title

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#279]
In Menu/Options is position "Group of file masks", after enter to this dialog - dialog title uses this same name - with shortcut key.
Look at the pictures:

![FAR_group_01](https://user-images.githubusercontent.com/26287042/97158147-56d1be00-1779-11eb-992e-7f51ec47fcdd.JPG)
![FAR_group_02](https://user-images.githubusercontent.com/26287042/97158156-59ccae80-1779-11eb-839f-dda6a033f092.JPG)

This same in all languages available in Far.

**Comment by alabuzhev** [comment]
5694 (93de0d4)
