### ISSUE TITLE
New executor gives priority to folders over programs with the same name in PATH

### ISSUE THREAD

**Issue by bitraid** [FarGroup/FarManager#290]
Started with 7a3f2554fee8d90d4aa6e7e2063cb593c95f3777, when a directory is in `PATH` and contains a program with the same name, entering the program name in Far prompt, opens the directory in explorer instead of running the program:
```cmd
C:\>md c:\test
C:\>(echo:echo:Executing: %~df0) > c:\test\test.cmd
C:\>set PATH=%PATH%;c:\test
C:\>test
```

**Comment by alabuzhev** [comment]
![image](https://user-images.githubusercontent.com/11453922/99295635-943bdf80-283d-11eb-9cf3-a55cb1e9850b.png)
1794335 / 5705

**Comment by bitraid** [comment]
It now works as expected for executables, but for scripts, if a folder with the same name exists in current dir, it opens it in explorer instead of running the script in `PATH`.

**Comment by bitraid** [comment]
I've also noticed that `%PATHEXT%` might not be respected: The `.com` extension doesn't have priority over `.exe`. (Some programs like Visual Studio use a special console launcher with `com` extension and the same name as the main `exe` GUI, so it can act as a console program when started from the terminal by its name).

**Comment by alabuzhev** [comment]
I see. Ok, 5706 (hopefully).

**Comment by bitraid** [comment]
Seems to be working fine now 👍

**Comment by alabuzhev** [comment]
Thanks for vigilance 👍
