### ISSUE TITLE
Подсветка завершающих строку пробельных символов

### ISSUE THREAD

**Issue by Valeriy-Zainullin** [FarGroup/FarManager#309]
В случае, когда пробельные символы (табы или пробелы) завершают строку, они незаметны и можно их случайно оставить в файле с исходным кодом. Не хорошо тем, что читающие будут предполагать, что их там нет, потому что обычно это так.
Можно ли добавить подсветку фона завершающих строку пробельных символов? Наверно, это нужно делать не всегда, а при каком-то расширении файла и по желанию пользователя.

**Comment by Valeriy-Zainullin** [comment]
Я пытался разработать [плагин](https://github.com/Valeriy-Zainullin/far-extensions), который бы добавлял этот функционал, но Far вызывал `GetGlobalInfoW`, а потом, видимо, выгружал dll и больше не загружал. Вроде, я инициализировал все поля структуры `GlobalInfo`. Может быть, код будет полезен.

**Comment by alabuzhev** [comment]
Colorer - Scheme settings - spaces-as-errors

**Comment by Valeriy-Zainullin** [comment]
Не знал. Спасибо!
