### ISSUE TITLE
Bug in 3.0.5711 and 3.0.5712

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#313]
I'm using MsiUpdate Plugin (https://sourceforge.net/projects/farplugs/files/MsiUpdate/), version 1.4.5.
After update from 3.0.5710.1864 to 3.0.5711 (and also 3.0.5712) there is a bug on startup.
![msi_update_bug](https://user-images.githubusercontent.com/26287042/101656077-96f7b200-3a42-11eb-8e74-902f74ff8a28.PNG)

If I choose 'Disable plugin' - Far is working correctly, 'Igrore' - automatically closes Far.
I've returned to 3.0.5710 - everything is ok.
Please, check also file version of FAR - I see only 3.0.5712.**0**, not 3.0.5712.**1866**.
MsiUpdate version is 1.4.5, but FAR is detecting version as 1.4.0.5.

> FILEVERSION    1,4,5,0
PRODUCTVERSION 1,4,5,0
FILEFLAGSMASK  0x0
FILEFLAGS      0x0
FILEOS         VOS_NT_WINDOWS32
FILETYPE       VFT_DLL
FILESUBTYPE    0x0
{
  BLOCK "StringFileInfo"
  {
    BLOCK "04090000"
    {
      VALUE "FileVersion",       "1.4.5.0"
      VALUE "ProductVersion",    "1.4.5.0"
      VALUE "FileDescription",   "MsiUpdate for Far Manager 3 x64"
      VALUE "OriginalFilename",  "msiupdate.dll"
      VALUE "LegalCopyright",    "https://sourceforge.net/p/farplugs/code/HEAD/tree/chupakabra_farplug/"
      VALUE "CompanyName",       "Oleg Makovski, Vladimir Surguchev"
    }
  }
  BLOCK "VarFileInfo"
  {
    VALUE "Translation", 0x409, 0
  }
}

**Comment by alabuzhev** [comment]
@BestiaPL when you want to report a crash, please use the Copy button in that dialog ('Kopiuj' on your screenshot, it's selected).
It will copy all available information to clipboard and you can paste it here. It will be easier for you and more useful for us than screenshots.

Re versions:
- 3.0.5712.0 is the correct one, 1866 is simply an automated CI build number.
- Far doesn't read plugin versions from resources, plugins report them via API. Apparently there's a discrepancy between msiupdate resources and the internal version. Please let the author know.

**Comment by alabuzhev** [comment]
Re the crash:
There's a bug in the plugin - it [tries](https://sourceforge.net/p/farplugs/code/HEAD/tree/chupakabra_farplug/msiupdate/update.cpp#l105) to "read" the settings without "opening" them first (at least twice in that file, probably more elsewhere).
Previously this operation was failing silently, and probably the plugin worked incorrectly in some cases.
Now the failure is more pronounced, which is ultimately a good thing.

As far as I understand, the plugin is currently supported by @w17, please let him know.

**Comment by w17** [comment]
@alabuzhev @BestiaPL I'll fix **msiupdate** and probably **NTFSinfo**.

**Comment by w17** [comment]
[url=https://sourceforge.net/projects/farplugs/files/MsiUpdate/]1.4.6[/url]

**Comment by BestiaPL** [comment]
MSIUpdate is working correctly :)
