### ISSUE TITLE
Suggestion: Git-history-aware File Viewer on F3

### ISSUE THREAD

**Issue by mirzah** [FarGroup/FarManager#314]
File Viewer on F3 should be aware of file history, when text file is tracked by Git. For such files there could be on top second status line, with datetime stamp of viewed version and possibility to move in time by Alt+Left and Alt+Right. This way user could easily see gradual evolution of file in time. Few additional things would be neat in that context:
1) some shortcut should be available to switch between selected and current version of file, at same vertical text position. This way we could check how file is changed compared to now.
2) Lines modified in any given revision should be marked, perhaps at the right-end side, by red color.

**Comment by alabuzhev** [comment]
We do not plan to integrate anything with git (nor with any other source control system) for a single reason: [Far supports plugins](https://farmanager.com/plugins.php).
If there's no such plugin, you're very welcome to create one.
