### ISSUE TITLE
[Feature request] far:config Filtering/searching for options

### ISSUE THREAD

**Issue by birdie-github** [FarGroup/FarManager#316]
Currently it's impossible to jump to an option you're interested in.

It would be great to either or both
* Be able to start typing an option name and have Far jump to the first found entry (this is not really great since there could be many with the same name or part of the name and jumping between them would mean extra shortcuts and complications)
* Have a search dialog, which could be permanent on the screen at the top or be a normal pop up window like e.g. in F3/F4 -> F7

**Comment by alabuzhev** [comment]
Ctrl+Alt+F or RightAlt.

It's even mentioned in help (F1).

**Comment by birdie-github** [comment]
Indeed!
