### ISSUE TITLE
Please add the file 'my-mirror.hrd' for set navy blue background (like Norton Commander)

### ISSUE THREAD

**Issue by skarsgal** [FarGroup/FarManager#320]
Hi,
Please add to FarManager installer(.msi) and archive (.7z) the file 'my-mirror.hrd' for **set navy blue background** (like Norton Commander).
You can find that file on GitHub at Mattia72/Far https://github.com/mattia72/Far.
(You can also change file name).
I don't know if the file can be taken as is, or if it needs some modification.
Thanks.

**Comment by alabuzhev** [comment]
@ctapmex, is it something you can look at?

**Comment by ctapmex** [comment]
yes, it`s for me. I created issue https://github.com/colorer/Colorer-schemes/issues/106
