### ISSUE TITLE
Delay when opening large files using their default program in Windows

### ISSUE THREAD

**Issue by fitdev** [FarGroup/FarManager#351]
I am currently using FAR 3.0.5740 x64 on Windows 10 1803.

I am pretty sure this issue started recently - maybe after FAR 3.0.57xx. My guess is that it could be related to the executor updates made recently.

Here's the issue as it happens in time: 
1. I double-click via ConEmu or just hit Enter on the large mp4 file in FAR (say a few Gigabytes in size)
2. There is a 5-10 second delay and the ConEmu's mouse cursor is semi-busy at this point 
3. Then, ~10 seconds later I see FAR panels disappear and black command line appear for a split-second, indicating that the command is actually being executed
4. FAR is back to Panels and is in a usable state (command has been "passed" onto Windows to handle)
5. Default Windows app for the file type (in my example Media Player) is launched and the file is opened there

The issue is step 2. Prior to a few months or so ago it was not there. At first I did not even pay attention to this, so did not notice it right away after upgrading FAR - in part since it is only noticeable with large files.

I double-checked and there is _no such delay_ in either Windows Explorer or FAR 2.0. I also tried running FAR w/o ConEmu with the same result, so it's not a ConEmu issue either.

**Comment by bitraid** [comment]
It's probably a 3rd party plugin you are using. If not, try without any plugins at all (`far -p`).

**Comment by fitdev** [comment]
@bitraid You are right! Without any plugins loaded it works correctly. Any suggestion on how to test it without disabling plugins one-by-one?

**Comment by bitraid** [comment]
Use [PlugMenu](https://plugring.farmanager.com/plugin.php?pid=882&l=en) plugin, which allows unloading plugins on the fly, and start with the ones that you recently added (skip the ones that come with Far). Sort your plugins folder by date if it helps.

**Comment by fitdev** [comment]
Found the culprit - turns out it's built-in ArcLite plugin. So, I guess the issue still belongs to this repo. Any ideas what can be causing such a strange behavior?

**Comment by bitraid** [comment]
Is ` Open files matching masks` in ArcLite settings not active?

**Comment by fitdev** [comment]
Sorry I was wrong in my findings above. Turns out it's not related to _any particular plugin_! It _works_ if I start AFR with `-p` switch. However, if I start FAR _without_ that switch (i.e. start it normally), then there IS a delay _even without any plugins_ loaded (empty Plugins folder).

**Comment by fitdev** [comment]
> Is Open files matching masks in ArcLite settings not active?
That's right, this setting is _not_ active. However, as I discovered I get FAR opening files quickly only when I pass the `-p` switch. So it's not ArcLite after all. And I _did test FAR standalone_ (without ConEmu).

**Comment by bitraid** [comment]
It should *be* active if you wish to avoid some delays on  certain files. You can also use <kbd>Shift+Enter</kbd> to directly open the file using the Windows association.  Are you sure about `-p` and empty plugins folder?

**Comment by alabuzhev** [comment]
> I also tried running FAR w/o ConEmu with the same result, so it's not a ConEmu issue either

Good. However, *"the ConEmu's mouse cursor is semi-busy at this point"* still sounds like an elephant in the room.
Please try running without conemu and *without its plugins*.

By default plugins are loaded from:
- %farhome%\plugins
- %farprofile%\plugins

Please check both locations.

> there is *no such delay* in [...] FAR 2.0

Good to know. However, checking a version that is literally 10 years old is pretty pointless.
If you suspect it's a recent regression, please check [the recent versions](https://farmanager.com/nightly.php).

**Comment by fitdev** [comment]
Thank you for looking into this.

> Please try running without conemu and without its plugins.

My normal setup is to run FAR via ConEmu, which is why I mentioned the mouse cursor. My later testing I carried out _without_ ConEmu in FAR solo.

I will do some additional testing and report back. It seems rather weird at this point - the only consistent thing is that if I open (hit Enter on them) large files via FAR 3 - there is a delay _sometimes_, whereas if I open the same / similar large files in other ways - using Windows Explorer or FAR 2, then there is never a delay. I will test FAR 3's earlier versions as you suggested.

**Comment by fitdev** [comment]
I did some more tests and discovered very strange behavior.

First of all, turns out the actual culprit for the delay is Comodo Firewall (cmdagent.exe). This is rather strange in itself, because I have it set only in Firewall mode (all file / AntiVirus scanning functionality is disabled, and Windows Defender is turned on for that instead).

It appears that after I try to open a file in FAR (and before I momentarily see FAR's command line, indicating that the file is actually being opened) cmdagent.exe is using a lot of CPU and looking at its active thread's stack it appears that it is hashing the file, hence a long delays since the file is large.

However the interesting bit is that it started happening with FAR's build `3.0.5702.1804 - 7a3f255`. I did extensive testing on various build to discover when this behavior starts to occur. And found that the last working properly build is `3.0.5701.1803 - d8288fb` (for which no cmdagent.exe appears to be invoked at all).

I realize that it may not be directly FAR's issue per se. But it is rather very strange why the prior builds do not cause this strange behavior (nor does Windows Explorer when opening files from there), but later FAR builds cause this behavior.

**Comment by alabuzhev** [comment]
> looking at its active thread's stack it appears that it is hashing the file, hence a long delays since the file is large

This is actually hilarious. See, prior to 7a3f255 Far was *actually reading the file every time you run it* and trying to figure out whether or not it's an console executable, and if not it was trying to find an associated application and ask it the same question.
After the change Far *doesn't read any files anymore*. Instead it looks at the spawned process and figures out its type directly. There's nothing illegal or suspicious in that method per se. In fact, this is what cmd.exe does (by the way, is it affected as well?). 
And the fact that these actions now somehow motivate a firewall (!) to read the file which we don't even touch... Well, it tells a lot.

> it is rather very strange why the prior builds do not cause this strange behavior

Not at all.
I'm not going to post my personal opinions about Comodo products in particular or "antivirus" software in general, but this is not the first and most certainly not the last time when things go south because of them.

**Comment by fitdev** [comment]
Thank you very much for looking into this! Yes, that is very bizarre indeed. I guess I will get a replacement for their Firewall since obviously it does something in addition to being strictly speaking a firewall even though all the other "protections" are turned off.

I did in fact confirm the same behavior with plain `cmd.exe`, so it's definitely not a FAR issue then.

The only question that remains is perhaps you can suggest I change some settings in FAR to enable _old_ behavior, so that at least, in the meantime, I can open files from FAR without delay? Does the new way always use `cmd.exe` then to open files / interpret commands? Can there be an option to do it the way Windows Explorer opens files perhaps?

**Comment by alabuzhev** [comment]
> I will get a replacement for their Firewall

If the issue is reproducible with cmd.exe, it might be worth reporting it to them - the chances to get something fixed are significantly higher if a system component is affected and not only some third-party OFM.

> suggest I change some settings in FAR to enable *old* behavior

There's no such setting. However, you could try using <kbd>Shift</kbd>+<kbd>Enter</kbd> to open such files - this is pretty much "do the Explorer way". Alternatively, try creating an association for *.mp4 with a command like  `lua:win.system("!.!")` to bypass the internal launcher completely. Or maybe try other commands like `start "!\!.!"` or `"path_to\player.exe" "!\!.!"`, one of them could make the firewall happy.

**Comment by fitdev** [comment]
Thank you for you suggestions and help! Unfortunately Shift+Enter does not make any difference, so I will try the lua approach then.

I will report it to them though I doubt they will fix it any time soon.

**Comment by alabuzhev** [comment]
> Shift+Enter does not make any difference

Then it's probably not about inspecting the process, but about creating the process.
Currently Far tries to pass the file name to [CreateProcessW](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) API first, if that doesn't work it tries [ShellExecuteExW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecuteexw), if that doesn't work as well it asks cmd.exe to run it (and cmd does something similar).
Presumably your firewall intercepts CreateProcessW and inspects the content of the the passed file, for whatever reasons.
If so, an association like `wmplayer "!\!.!"` (or others mentioned above) should help - by the time the control reaches CreateProcessW, the file name there will already be replaced with the file name of the player. The firewall will still read its full content and do other murky things, but player executables are usually within several MB, not GB, so it should take a little less time.

**Comment by fitdev** [comment]
Thanks so much for the tip and the explanation! I ended up using file associations and `lua:win.system("!.!")` as you suggested. This works great! Incidentally, do you know what API does it actually call - CreateProcessW or ShellExecuteExW?

And a bit off topic: when creating file associations I noticed that you need to specify file masks. I think it would be great if in addition to plain file masks one could use one of the defined file groups (as I already have defined several file groups like videos, audio files, etc. for file highlighting reasons).

**Comment by alabuzhev** [comment]
> Currently Far tries to pass the file name to CreateProcessW API first, if that doesn't work it tries ShellExecuteExW, if that doesn't work as well it asks cmd.exe to run it (and cmd does something similar).
> Presumably your firewall intercepts CreateProcessW and inspects the content of the the passed file, for whatever reasons.

@fitdev FYI the fix for #449 somewhat alters this behavior and mp4 files should no longer go through that path. Hopefully it resolves this issue as well.
