### ISSUE TITLE
Help files - redundant entry

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#361]
I found entry #Edit sort groups# (line 1464 in FarEng.hlf.m4), but I didn't found entry in menu Commands.
Place is marked in attached screenshot.

![obraz](https://user-images.githubusercontent.com/26287042/108814811-b9b25500-75b3-11eb-8fd1-ae1d30525efa.png)

**Comment by alabuzhev** [comment]
Sort groups and files highlighting used to be separate entities, now it's a single one, so yes, the help is outdated.
However, they might become separate entities again in the observable future, so I suggest keeping that entry for now.
Feel free to translate it or ignore it.

**Comment by BestiaPL** [comment]
I will translate it, of course :)
