### ISSUE TITLE
Reproducible exception related to regular expressions

### ISSUE THREAD

**Issue by Valeriy-Zainullin** [FarGroup/FarManager#367]
Tested on 3.0.5754.2038.

Steps to reproduce:
1. Open a new file in the editor.
1. Write a character.
1. Request to replace the character with `\$"`.

![1](https://user-images.githubusercontent.com/16137770/110163872-b152e900-7e01-11eb-91dc-fbb747285262.png)
![2](https://user-images.githubusercontent.com/16137770/110163876-b1eb7f80-7e01-11eb-8447-333ed32768c0.png)
![3](https://user-images.githubusercontent.com/16137770/110163880-b2841600-7e01-11eb-85f1-5b9290b26de9.png)

**Comment by shmuz** [comment]
```
╔═ Bisect Far builds ══╗
║ Far 3.0.5567 is good ║
║ Far 3.0.5580 is bad  ║
╟──────────────────────╢
║   { OK } [ Copy ]    ║
╚══════════════════════╝
```
Sorry, doesn't have any builds in-between.

**Comment by alabuzhev** [comment]
5755 / 1b28bd5

**Comment by Valeriy-Zainullin** [comment]
Doesn't happen anymore.
