### ISSUE TITLE
Latest stable (Build 5757) fails to obtain administrator privileges

### ISSUE THREAD

**Issue by rupor-github** [FarGroup/FarManager#371]
When trying to step into directory Far requests administrative privileges and process gets aborted....

![Clipboard01](https://user-images.githubusercontent.com/5368784/111069612-3a25f080-84a4-11eb-9a62-7745a9b588d8.jpg)

This did not happen with build 5700

**Comment by alabuzhev** [comment]
@rupor-github, I can't reproduce it.
Could you please try several [versions between 5700 and 5757](https://farmanager.com/nightly.php) to pinpoint the issue?
Also, what OS do you use and have you tried without conemu (just in case)?

**Comment by rupor-github** [comment]
Sorry - Windows 10 19042.867
Far runs under Windows Terminal 1.7.572.0
Installed via scoop - I'll see if I could pinpoint an exact build.

**Comment by rupor-github** [comment]
Change happened between 5751 (works) and 5753 (does not work).

As far as I could tell it could only be reproduced when Far is started using command line which has at least one directory junction in it. For example `C:\\Users\\mike0\\scoop\\apps\\far\\current\\Far.exe` where "current" is

![Clipboard01](https://user-images.githubusercontent.com/5368784/111073048-8cbad900-84b3-11eb-9990-0b28bc8619ea.jpg)

If current points to anything before build 5753 - it works...

**Comment by alabuzhev** [comment]
Thank you - fixed in 5758 / 57de47a.

**Comment by rupor-github** [comment]
Confirming fix, thank you!
