### ISSUE TITLE
Feature Request: Support Symlink creation/modification on SMB shares

### ISSUE THREAD

**Issue by fitdev** [FarGroup/FarManager#378]
Currently FAR has great support for working with Junctions and Symlinks on local file systems. It would be great if this support can be extended to public shares accessed via SMB protocol (network folders and drives).

**Comment by alabuzhev** [comment]
What do you mean? It's [already supported](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw).

**Comment by fitdev** [comment]
Hmm. Strangely it does not work (at least on my Win10 x64 1803).
For example, with the following panel setup in FAR:

Passive: `\\192.168.10.11\MySMBSharedFolder1\SubfolderA`
Active: `\\192.168.10.11\MySMBSharedFolder1\SubfolderB` (Cursor on `SubSubFolderC`)

I press `Alt+F6` and a _Link_ dialog appears.

When _Junction_ is selected, I get the error:
```
 0x00001126 - The file or directory is not a reparse point.
```
That makes sense since junctions are not supported to network-mapped folders.

However when I select either _Symbolic Link_ or _Symbolic Link (Folder)_ under _link type_, I get first a UAC prompt, which I confirm, and then:
```
0x00001126 - The file or directory is not a reparse point.
```
Exactky the same error message as for junctions.

**Comment by alabuzhev** [comment]
Obviously, it will only work if the underlying filesystem & the server OS support symlinks (or reparse points in general).
You can try the `mklink` tool to confirm.

**Comment by fitdev** [comment]
Thank you for the tip. I cannot create it with mklink either, even though I have the symlink creation explicitly enabled on my NAS under SMB3 settings. But strangely I _can_ create hardlinks!

Well, I guess this is not a FAR issue then, since I cannot make it work with mklink either. Thank you for looking into this though.
