### ISSUE TITLE
Symbolic links copy/move issues

### ISSUE THREAD

**Issue by bitraid** [FarGroup/FarManager#380]
After 8a1a7c3: copying a symlink does nothing; moving a symlink just removes it.
For previous versions, copying a symlink requires administrator privileges, while moving does not (works ok).

**Comment by alabuzhev** [comment]
cf4c8ac / 5778

**Comment by bitraid** [comment]
> [cf4c8ac](https://github.com/FarGroup/FarManager/commit/cf4c8acac6c742fcb5a6d468adb5da350fcb0e38) / 5778

Moving works ok - Copying requires Admin.

**Comment by alabuzhev** [comment]
> Copying requires Admin.

As it should:
> For previous versions, copying a symlink requires administrator privileges

**Comment by bitraid** [comment]
But why should it?

**Comment by bitraid** [comment]
My bad, it should.

**Comment by alabuzhev** [comment]
> But why should it?

Because Microsoft decided so 🤷‍♂️

**Comment by w17** [comment]
Maybe turning on Developer mode can help.

**Comment by bitraid** [comment]
> Maybe turning on Developer mode can help.

Interesting - it does! Thanks!

**Comment by alabuzhev** [comment]
Or allow it in group policy editor:

![image](https://user-images.githubusercontent.com/11453922/113948678-57c94a00-9805-11eb-85a3-040764dd183a.png)

**Comment by bitraid** [comment]
Nice, I wasn't aware of that setting. I also found out that you can use `fsutil` to enable remote to local and remote to remote symlinks.
