### ISSUE TITLE
display  issue

### ISSUE THREAD

**Issue by Shing0724** [FarGroup/FarManager#381]
In  Chinese,the Far Manager display abnormal. Need to add space in each Chinese character.
![1-1](https://user-images.githubusercontent.com/32982150/113956018-69374400-984f-11eb-9244-d129ec122001.PNG)
![1-2](https://user-images.githubusercontent.com/32982150/113956100-8c61f380-984f-11eb-9e00-0d6adbeaec06.PNG)
![2-1](https://user-images.githubusercontent.com/32982150/113956104-8cfa8a00-984f-11eb-8945-699872c27e96.PNG)
![2-2](https://user-images.githubusercontent.com/32982150/113956109-8d932080-984f-11eb-914c-669e4fe712f5.PNG)

**Comment by alabuzhev** [comment]
It's a known issue, unfortunately the chances of fixing it are close to 0.
Far is a console app and historically the whole console subsystem assumes that the display is a grid of uniform rectangular cells and each character occupies exactly one cell.
You can try [ConEmu](https://github.com/Maximus5/ConEmu) though - as far as I know, there's an option to make all the cells double width / square, which should help with CJK characters.

**Comment by alabuzhev** [comment]
The situation might be slightly better after 5809.
