### ISSUE TITLE
Offtopic: is main site down?

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#398]
I cannot connect to Far Manager website (http://www.farmanager.com or https://www.farmanager.com).

**Comment by alabuzhev** [comment]
Neither can I. Apparently the hoster does some hoster things.
Keep calm and carry on, it will be back eventually.

P.S. [Discussions](https://github.com/FarGroup/FarManager/discussions) is probably a more appropriate section for such questions.
