### ISSUE TITLE
b5082 Git-5075f3008 избирательно поломались ассоциации для вьера/радактора 

### ISSUE THREAD

**Issue by VictorVG** [FarGroup/FarManager#4]
Нарвался случайно, ноги растут из _b5082 Git-5075f3008_ (проверено по коллекции билдов с b3000 по b5089) - в _b5081 Git-5ae0d6df7_ ошибки нет в _b5082 Git-5075f3008_ избирательно поломались ассоциации на F3/F4 и что интересно, для конкретных шаблонов имён файлов . 

Внешне выглядит так - есть ассоциация _Readme and descriptions_ на маски _Readme.[t,w]xt,Descript.ion,File_Id.diz,[r]notes.[t,w]xt,readme.md_
```
[x] Команда, выполняемая по Enter: view:"!=\!+!"
[x] Команда просмотра, выполняемая по F3: View:"!=\!+!"
[x] Команда просмотра, выполняемая по Alt+F3: "!=\!+!"
[x] Команда редактирования, выполняемая по F4: edit:"!=\!+!"
[x] Команда редактирования, выполняемая по Alt+F4: "!=\!+!"[/q]
```
и после b5082 Git-5075f3008 в архиве нельзя посмотреть или отредактировать всё, что попадает под сию маску. F3 "не работает" - на экране панели, по F4 просто дёргается экран, в %TMP% временные каталоги с распакованными файлами, но обращения к ним нет. По крайней мере я в Process Hacker v3.0.5596.1069 хендлов указывающих на них не обнаружил, в более ранних билдах - нет вопросов, начиная с данного коммита в списке их нет.

Воспроизведение элементарно - или руками выставить ассоциацию на этот набор имён, или импортировать из приложенного [**test.zip**](https://github.com/FarGroup/FarManager/files/1442865/test.zip) файл  test.farconfig, а после попробовать посмотреть/отредактировать readme.txt/File_id.diz в этом же архиве.

**P.S.**

_Интересно, а почему бяка вылезла именно на "readme."? Каким мёдом ей это слово намазано?_

**Comment by zg0** [comment]
5090.

**Comment by VictorVG** [comment]
Спасибо!
