### ISSUE TITLE
Latest Far stable (5800) - FarColorer does not work when user settings are used.

### ISSUE THREAD

**Issue by rupor-github** [FarGroup/FarManager#401]
Windows 10 21H1, Far runs in Windows Terminal 1.8

Using "user file of color styles" works perfectly up to v5775:
![settings](https://user-images.githubusercontent.com/5368784/118813884-967b0700-b87d-11eb-9d33-7b6c4905d6d4.jpg)
In v5800 no changes in the environment this causes dump in FarColorer plugin: C++ exception (class std::out_of_range -> struct std::_With_nested<class far_wrapper_exception,class far_wrapper_exception>)

**Comment by rupor-github** [comment]
[bug_report.txt](https://github.com/FarGroup/FarManager/files/6508754/bug_report.txt)

**Comment by rupor-github** [comment]
Dump seems to be too big for this WiKi to handle even when zip-ed

**Comment by alabuzhev** [comment]
@ctapmex have a look please

**Comment by rupor-github** [comment]
Both daily builds v5801 and v5802 still exhibit the same behavior. Do you know in what version fix will be available?
[Far.2021.05.22_12.19.21.669_10092.zip](https://github.com/FarGroup/FarManager/files/6526391/Far.2021.05.22_12.19.21.669_10092.zip)

**Comment by ctapmex** [comment]
Hmm, I thought I fixed the bug. A similar problem was described on the forum, and there it no longer occurs.
@rupor-github please show/attach  file console.xml

**Comment by rupor-github** [comment]
Sure 😄 

[Farcolorer.zip](https://github.com/FarGroup/FarManager/files/6526401/Farcolorer.zip)

**Comment by ctapmex** [comment]
I get farmanager from https://farmanager.com/download.php?l=en  and trying to reproduce - it`s OK.
last actual version of FarColorer - https://github.com/colorer/FarColorer/releases/tag/v1.4.2 . It same that in farmanager. Please recheck. And if problem wasn`t solved , download pdb file from https://github.com/colorer/FarColorer/releases/tag/v1.4.2, unpack to Far root folder and retest - report of problem will be more full

**Comment by rupor-github** [comment]
You are right - I re-downloaded and reinstalled everything and it seems OK now. I will run with colorer.pdb for a while, just in case. Thank You!
