### ISSUE TITLE
Far x86 (5803) crashed when entering in shared folder (SMB) on Windows XP SP3

### ISSUE THREAD

**Issue by de77** [FarGroup/FarManager#409]
When entering a shared folder on a remote computer via SMB (Microsoft Network) Far crashed, said "something went wrong" and saved the information about failure in the Far profile folder (<user_name>\Local Settings\Application Data\Far Manager\Profile\CrashLogs\Far.2021.06.01_05.55.12.015_208\). For now it happened only once. For crash dumps and more information see https://rapidshare.io/U2g/Far.2021.06.01_05.55.12.015_208.zip

**Comment by Pxx64** [comment]
I wonder where did you get that 5803 build, as on site there are 5802 builds followed by 5804 build. Without pdb file the dumps are pretty much useless..

**Comment by alabuzhev** [comment]
@de77 Should be fixed in 5810.

@Pxx64 https://github.com/FarGroup/FarManager/releases

**Comment by Pxx64** [comment]
Ok, I didn't know that there are also builds on GitHub now, thanks :)
