### ISSUE TITLE
update "command line prompt format" from command line

### ISSUE THREAD

**Issue by ecc256** [FarGroup/FarManager#419]
Is it possible to update "command line prompt format" from command line?
I can edit it manually via "Command line settings" menu or far:config

Anyway to set is from command line, smth. like this:
`far:config "Cmdline.PromptFormat" %PROMPT%`

**Comment by alabuzhev** [comment]
Not directly, but you could probably set it to some environment variable in the dialog (e.g. %PROMPT%) and then change that variable from the command line as you like using `set`.

**Comment by ecc256** [comment]
Alex,
Yep, you are right!
That’s probably easiest (and the only) way as of now.
To clarify I do use Anaconda and Python virtual envs.
I do switch them from Far menu.
Will be nice see current venv in the Far prompt.
They do set different env. vars, thus need a way to tell Far where to get it from.
And I do want add current git branch sometimes too :)

**Comment by alabuzhev** [comment]
> And I do want add current git branch sometimes too :)

https://github.com/smithx/far

**Comment by ecc256** [comment]
Yeah, that's what use too! :)
