### ISSUE TITLE
Wrong editor work in 3.0.5834.2274

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#422]
Version: 3.0.5834.2274

Open any text file in internal editor. Save this file (key F2). I see that left half is in editor, right half of FAR is file manager.

https://user-images.githubusercontent.com/26287042/123432264-7bad5800-d5ca-11eb-9afb-b04fd75ec54e.mp4

After saving I'm pressing UP/DOWN keys (it's invisible), them screen is refreshed correctly.

**Comment by alabuzhev** [comment]
Should be fixed in 5835.

**Comment by BestiaPL** [comment]
Work fine, now.
