### ISSUE TITLE
Incorrect file sizes shown/calculated for files compressed with LZX

### ISSUE THREAD

**Issue by birdie-github** [FarGroup/FarManager#425]
Steps to reproduce:

`compact /C /F /EXE:LZX file`

Ctrl + Q for this directory will show something totally incorrect (as if the compressed file(s) occupies practically nothing).

**Comment by alabuzhev** [comment]
Ugh. Why everything that comes with windows 10 is so spectacularly broken 🤦‍♂️ 

5852.
