### ISSUE TITLE
[Feature Request] WSL support

### ISSUE THREAD

**Issue by sanyarnd** [FarGroup/FarManager#427]
WSL added a special syntax for accessing an underlying linux filesystem: `\\wsl$`. It'd be nice FAR to support it.

**Comment by bitraid** [comment]
Doesn't `net:wsl$` work?

**Comment by sanyarnd** [comment]
Just checked, it works on one PC, but it doesn't on the other one. `net:wsl$` returns an empty list.

Both systems are running Windows 10 21H1, WSL2 and Ubuntu 20.04.
Far version is the latest stable.

**Comment by yegor-mialyk** [comment]
@sanyarnd, please try a more precise path, like `\\wsl$\Ubuntu`. Sometimes (e.g. after the PC restart) you have to run/open WSL at least once in order to start "Linux" machine.

**Comment by sanyarnd** [comment]
That solved as issue, thanks. Though it's strange that Explorer displays everything under `\\wsl$` despite the fact machine is not running.
