### ISSUE TITLE
files "ordered" randomly

### ISSUE THREAD

**Issue by cdcseacave** [FarGroup/FarManager#43]
I am using the latest stable FAR and in the default sorting by name in increasing order some files are not correctly ordered. For example the following file are ordered like this:
```
Names-171215144412006F65.log
Names-180501143336003EB5.log
Names-1711031741120076A5.log
```
I am probably missing something obvious here, but as far as I know (and how I expect this to work) is to order the files in ascending order, reading the name from left to right. In this case the first difference is `8` and so that file should be the last one. Same for the other two files: `2` is bigger than `1` but it appears above it.

Thank you for such a great app!

**Comment by shmuz** [comment]
I confirm that. Build 5133 is OK, current builds are not.

**Comment by zg0** [comment]
i think option «[x] Treat digits as numbers» is on. so everything is obvious:
171215144412006<180501143336003<1711031741120076

**Comment by shmuz** [comment]
Many option are good as long as reasonable defaults are given.
I think most users when press Ctrl-F3 expect to see the same order as in `dir /on`

**Comment by alabuzhev** [comment]
@shmuz , by default we sort numerically to be consistent with windows shell (including open/save dialogs in every single app).

**Comment by cdcseacave** [comment]
I confirm that option solves this issue. Sorry for bothering you, didn't know about this option.
