### ISSUE TITLE
7z.sfx and 7zS2.sfx in the ArcLite Plugin in Far30b5858.x64.20210727 marked as viruses?

### ISSUE THREAD

**Issue by darthdeus** [FarGroup/FarManager#432]
Here's reports from VirusTotal, both are in Plugins/ArcLite

- [7z.sfx](https://www.virustotal.com/gui/file/09147ad8fd25ffcb853097c244c49c0d2130c6ef7b12e1b43c8ee78de2e47b33/detection)
- [7zS2.sfx](https://www.virustotal.com/gui/file/7dc4bb1546218a157059a32dc35ef2a76b62ef49f30c0ecea36b5c6ae33ca3b5/detection)

**Comment by alabuzhev** [comment]
Please report false positives to the corresponding vendors.
