### ISSUE TITLE
Wrong description in settings and help 

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#433]
In Setting: F9, Options, Files highlighting..., (edit any mask) there is an edit box named "Mask".
In help file this option is described as: "A file mask or several file masks" - marked with green color.
Please, look at screens.
![podswietlanie_ustawienia](https://user-images.githubusercontent.com/26287042/128984366-665753a2-37fb-478a-8c84-5a1abff2a8ec.PNG)

![podswietlanie_pomoc](https://user-images.githubusercontent.com/26287042/128984364-2babf148-d440-4ebf-af78-5b33cb8e4280.PNG)

Also - on editing screen there is an error - double "n" shortcut: "**N**ame"/"tra**n**sparent" (marked with blue color on first screenshot).

**Comment by alabuzhev** [comment]
The help seems to be quite outdated - that option was renamed in 1.70 b3, 20 years ago.
I've removed that paragraph because it's already quite obvious and the next one explains the same thing again anyway.

**Comment by BestiaPL** [comment]
Cool. I will analyze the help file when translating into Polish, I will try to catch such inconsistencies.
