### ISSUE TITLE
Difference between help file and dialog window.

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#436]
File FarEng.hlf.m4, topic: @FileAttrDlg, lines: 3933-3934.

> If you do not want to process files in subfolders, clear the "Process subfolders" option.

But I have checked, that this checkbox is disabled as default (latest build: v3.0.5879.2356).

**Comment by alabuzhev** [comment]
It was on by default in the last millennium, in 1.65...
Good catch, I'll remove it.

**Comment by alabuzhev** [comment]
5880
