### ISSUE TITLE
File list copy: Wrong number of total bytes on retry

### ISSUE THREAD

**Issue by bitraid** [FarGroup/FarManager#437]
When retrying a copy of a list of files, the total number of bytes is wrong.

To demonstrate, I copy the contents of Windows 10 ISO to a samba share:
![copy-1](https://user-images.githubusercontent.com/4866740/130588851-3b0a43e2-923f-4b5f-acc1-3d4f2ba36eeb.PNG)

While copying `install.wim`, I restart the samba service to make the copy fail:
![copy-2](https://user-images.githubusercontent.com/4866740/130589056-b338fdb4-50a7-4f51-99c2-b53d3d7b31f6.PNG)

On retry, the total number of bytes and progress is wrong:
![copy-3](https://user-images.githubusercontent.com/4866740/130589433-d578ef5a-58a3-4f2d-98bc-1670ec03ea89.PNG)

**Comment by alabuzhev** [comment]
Should be fixed in 5886.

**Comment by bitraid** [comment]
Confirmed.
