### ISSUE TITLE
ExcDump .dll not handling stack-faults

### ISSUE THREAD

**Issue by gvanem** [FarGroup/FarManager#44]
I just discovered the cool `ExcDump.dll` which I tried to test using `<root>/misc/fexcept/execdump/test.cpp`. I changed the `makefile_vc` and added this:
```
test: test_release_MT.exe test_debug_MT.exe

test_clean:
	rm -f test_release_MT.* test_debug_MT.* $(OBJDIR)/test_release_MT.obj $(OBJDIR)/test_debug_MT.obj FStd_trap.log

COMPILE_TEST = $(CC) -Oy- -Ob0 -nologo -GS- -Zi -Fo$(OBJDIR)\\ -arch:IA32 -I. test/test.cpp
LINK_ARGS    = -link $(XXLIB) -debug -incremental:no

test_release_MT.exe: test/test.cpp $(XXLIB) Makefile_vc
	$(COMPILE_TEST) -MT -Fe./$@ $(LINK_ARGS)
	copy $(WORKDIR)\$(NAME).dll .

test_debug_MT.exe: test/test.cpp $(XXLIB) Makefile_vc
	$(COMPILE_TEST) -MTd -Fe./$@ $(LINK_ARGS)
	copy $(WORKDIR)\$(NAME).dll .
```
But discovered that these choices did not generate an exception:
```
 3. Generate stack overrun
 4. Generate float math overflow (value / 0)
```
AFAICS from the dis-assembly of case `'3'` this should overflow the stack.
What's going on here?

**Comment by alabuzhev** [comment]
- `char str[ 10 ]; memset( str, 's', 30 );` is a UB; stack overrun might happen or might not; Something like [this](https://github.com/FarGroup/FarManager/blob/58f30710ce95fd41ee3c946fb46c59c9dd6536f9/far/farexcpt.cpp#L642) should work.
- Floating point exceptions are disabled by default; you need to do `_clearfp(); _controlfp(0, _MCW_EM);` first ([example](https://github.com/FarGroup/FarManager/blob/58f30710ce95fd41ee3c946fb46c59c9dd6536f9/far/farexcpt.cpp#L544)).
