### ISSUE TITLE
Files Highlighting Regression

### ISSUE THREAD

**Issue by fitdev** [FarGroup/FarManager#440]
Sometime between 5740 and 5858 something changed in the way files highlighting works, which now prevents the *bold* style to be preserved when _Continue processing_ is _checked_ in _Files highlighting_ dialog.

I had it set up so that any file / dir with _Reparse Point_ attribute is *bold*: the group was looking only for whether the attribute is set, and modified only the bold font style - _not_ the colors) (I use ConEmu to support advanced fonts and colors).

Then additional highlighting groups were defined below with different _colors_ for different file masks. For example, `*.mp4`s would be Red, `*.exe`s would be Green.

This setup worked fine in 5740: if an `*.exe` file was a symlink (had a reparse point attribute set), it would be _both_ *bold* and Green: with the 2 effects coming from 2 highlighting groups that effect the file.

However as of 5858, this is no longer how it works: the _last_ group seems to _override all styles_! So, in my example, `*.exe` symlink is just Green, not *bold* Green. If I swap the order of highlighting groups around, then I will lose all colors, i.e. in my example `*.exe`s and `*.mp4`s would all have the same default color, but the *bold*-ness would now work (if they have reparse point attribute set).

So, I had to create a workaround by basically duplicating all the "colored" groups: having one version for reparse points (bold + color), and the other version for when the reparse point attribute is not set (color only). This is not optimal, as it forces one to duplicate things:

### Current, 5858, Workaround Setup:

```
 ╔═══════════════════ Files highlighting ═══════════════════╗ 
 ║      │                       │ +D          .... │ ..     ║ 
 ║      │                       │ +D          ...↓ │        ║ 
 ║      │                       │ +H          ...↓ │        ║ 
 ║      │                       │ +L -D       ...↓ │        ║ 
 ║  '!' │                       │ +DL         ...↓ │        ║ 
 ║      │                       │ +L          .... │ <exec> ║ 
 ║      │                       │             .... │ <exec> ║ 
 ║      │                       │ +L          .... │ <arc>  ║ 
 ║      │                       │             .... │ <arc>  ║ 
 ║      │                       │ +L          .... │ <pic>  ║ 
 ║      │                       │             .... │ <pic>  ║ 
 ║      │                       │ +L          .... │ <vid>  ║ 
 ║      │                       │             .... │ <vid>  ║ 
 ║      │                       │ +L          .... │ <temp> ║ 
 ║      │                       │             .... │ <temp> ║ 
 ║      │                       │ +L          .... │ <img>  ║ 
 ║      │                       │             .... │ <img>  ║ 
 ║      │                       │ +L          .... │ <aud>  ║ 
 ║      │                       │             .... │ <aud>  ║ 
 ║                                                          ║ 
 ╟──────────────────── Upper sort group ────────────────────╢ 
 ║                                                          ║ 
 ╟──────────────────── Lower sort group ────────────────────╢ 
 ║                                                          ║ 
 ╟─────────── Lowest priority highlighting group ───────────╢ 
 ║                                                          ║ 
 ╚═════════ Ins Del F4 F5 Ctrl+Up Ctrl+Down Ctrl+R ═════════╝ 
```

### Old, 5740, Setup:

![2021-08-30 10_51_24-20210825-101628 ConEmu64 jpg   1936 x 1066 x 24b   100%   19634_22633   -   Pict](https://user-images.githubusercontent.com/8166847/131305434-881d7644-e967-4e81-ac4b-ac55007ea3f4.jpg)

Is it possible to restore the old behavior?

**Comment by bitraid** [comment]
You have to select the `Inherit` style option:
```
 ╔═════════════════════════ Color ═══╤══════════════════════╗
 ║ [x] Foreground:          AA     # │ Style:               ║
 ║  •                       FF     0 │ [x] Inherit          ║
 ║                          [ RGB… ] │ ──────────────────── ║
 ╟───────────────────────────────────┤ [ ] Bold             ║
 ║ [ ] Background:          AA     # │ [ ] Italic           ║
 ║  •                       00     0 │ [ ] Underline        ║
 ║                          [ RGB… ] │ [ ] Double           ║
 ╟───────────────────────────────────┤ [ ] Overline         ║
 ║ Text Text Text Text Text Text Tex │ [ ] Strikeout        ║
 ║ Text Text Text Text Text Text Tex │ [ ] Faint            ║
 ║ Text Text Text Text Text Text Tex │ [ ] Blink            ║
 ╟───────────────────────────────────┴──────────────────────╢
 ║                    { Set } [ Cancel ]                    ║
 ╚══════════════════════════════════════════════════════════╝
```

**Comment by alabuzhev** [comment]
That's right, set "Inherit" if you want the group to pick the previous style.
Related discussion: https://forum.farmanager.com/viewtopic.php?t=12578

**Comment by fitdev** [comment]
Thank you for you help. But I do not see this new dialog. How do I access it?

**Comment by BURKAY9191** [comment]
Ne ile yarıyr

Android için Outlook<https://aka.ms/AAb9ysg>’u edinin
________________________________

**Comment by alabuzhev** [comment]
> How do I access it?

Get the latest version.

**Comment by fitdev** [comment]
Thank you! Latest build seems to have fixed it.
