### ISSUE TITLE
Updated Polish translation

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#441]
Hi.
I see that in latest build (3.0.5885.2370) in file FarPol.lng is one line not translated:

> // need translation:
> //[MConfigFullWidthAwareRendering]
> "Fullwidth-aware rendering"

But this string was already translated on 5 July this year.
Link to my commit: https://github.com/FarGroup/FarManager/commit/cc272287d366ac1ea74fde8d4048bd9f190e9725

Alex, could you check what is wrong with this translation, please?

**Comment by alabuzhev** [comment]
@BestiaPL, you translated the 7th line instead of the 6th so... look in your FarSpa.lng :)

Fixed in 81616a34a61321a48606f1c6924e162756ca8623.

**Comment by BestiaPL** [comment]
My mistake. Thanks for correcting :)

**Comment by Burkay5441** [comment]
Şimdi ne oluyor bu
