### ISSUE TITLE
Incomplete description of options in the help file 

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#446]
Topic: @FileDiz
In Russian help file:
_#Использовать кодовую страницу ANSI по умолчанию#

 #Сохранять в UTF8#_

In English/Polish help file:
 _Use ANSI code page by default

 Save in UTF8_

Maybe somebody can explain both options - i doesn't matter in which language (Russian/English) and could update help files.

**Comment by alabuzhev** [comment]
By default Far uses the OEM codepage (e.g.  "850 Multilingual Latin I") for file descriptions, both for reading and writing.
"Use ANSI code page by default" changes it to ANSI (e.g. to "1252 Latin I").

If "Save in UTF8" is set, the diz file will be saved in UTF-8 when when you add / remove / update descriptions.

All this doesn't apply if the file has the UTF-8 signature. In this case it is always read and written in UTF-8.

**Comment by BestiaPL** [comment]
Can you add this explanation to all help files?

**Comment by alabuzhev** [comment]
Ok, added.

**Comment by BestiaPL** [comment]
Thank you.
But I have tried to set this option (default is zero):
```
//[MCfgDizStartPos]
"&Position of new descriptions in the string"
```

but nothing was happened inside Descript.ion file (new folder, new diz file).

**Comment by alabuzhev** [comment]
It's to align the description column:
```
file.txt              some description
some_other_file.txt   some other description
anoother file.txt     another description
```

1. Set it to a relatively large value (e.g. 50)
2. Describe a file with a significantly shorter name, e.g. `1.txt`
3. Check the diz to see the difference.

**Comment by BestiaPL** [comment]
Thanks for info.
