### ISSUE TITLE
New bug report - bug

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#447]
I have tried to add new bug (about help file), but after all the text (all fields) had been entered, the "Submit new issue" button was inactive. 

![new_bug](https://user-images.githubusercontent.com/26287042/132754489-f6429cb3-9465-4423-90af-620760dccadb.PNG)

**Comment by alabuzhev** [comment]
> Fields marked with an asterisk (*) are required.

You need to fill `OS version`. If it's not relevant, put "any", "N/A" or something like that there.

**Comment by BestiaPL** [comment]
Sorry for mistake...
