### ISSUE TITLE
Far does not properly display UTF8 file names in zip archives

### ISSUE THREAD

**Issue by fitdev** [FarGroup/FarManager#448]
### Far Manager version

3.0.5885

### OS version

10.0.17134.1345

### Steps to reproduce

1. Use `7z.exe` to create a `zip` archive with for example Cyrillic letters: `7z a "archive.zip" ".\FilesToBeArchived\абв*"`
2. Open `archive.zip` in FAR by selecting it and pressing `Enter`

### Expected behavior

FAR lists properly named files and folder in the archive, including properly display non-ASCII characters like `абв`.

### Actual behavior

Non-ASCII characters are displayed as something like: `╨У╨╛╤А╨╛`.

**Comment by shmuz** [comment]
Far 3.0.5886 x86, 7z.exe 19.00, Windows 10

![Clipboard01](https://user-images.githubusercontent.com/344558/133573125-c86ef4f7-05ce-47b0-88fa-b1f4b59b38eb.png)

**Comment by fitdev** [comment]
@shmuz Hmmm. Very strange. Though I use x64 version of FAR, however don't think it makes a difference.

**Comment by fitdev** [comment]
Here's my test:
[files.zip](https://github.com/FarGroup/FarManager/files/7176043/files.zip)

![2021-09-16 11_10_26-{ArcLite_zip_files zip} - Far 3 0 5885 0 x64](https://user-images.githubusercontent.com/8166847/133575675-00e08bcd-f6bb-4f6b-97f2-0aba0edf1f3f.jpg)

**Comment by shmuz** [comment]
@fitdev , your archive displays incorrectly on my Far too.

**Comment by fitdev** [comment]
@shmuz Interestingly, in my case it displays _correctly_ in Windows Explorer:
![2021-09-16 11_23_45-files zip](https://user-images.githubusercontent.com/8166847/133577773-29125245-3668-4a6d-bf5d-901ed0884686.jpg)

**Comment by fitdev** [comment]
Ideally FAR should be smart enough to figure out proper encoding, or at the least have the option to select one on a per-archive basis. In this particular case though, I think the encoding is UTF8, so I have no idea why FAR is having trouble with it.

**Comment by w17** [comment]
7z считает что имя файла в вашем архиве в OEM кодировке, на самом деле UTF-8.
7zfm в вашем архиве покажет те же закорючки, поэтому вопрос к нему, или к тому как вы создавали архив.
в arclite вы можете исправить ситуацию, задав в настройках для кодовой страницы OEM 65001 (UTF-8).

**Comment by fitdev** [comment]
@w17 Thanks for your comments.

> 7zfm в вашем архиве покажет те же закорючки

It works fine in my case:
![2021-09-16 11_28_48-X___saves_files zip_](https://user-images.githubusercontent.com/8166847/133578432-fbd64619-4363-470f-8849-96ea8550f1b0.jpg)

> поэтому вопрос к нему, или к тому как вы создавали архив

`7z a "files.zip" ".\*" -mx5`

> в arclite вы можете исправить ситуацию, задав в настройках для кодовой страницы OEM 65001 (UTF-8).

This worked! Thanks for the tip! Though now I suppose it will not correctly work with other (older archives), since I changed the CP...

**Comment by w17** [comment]
Actually 7z, Winrar and Windows explorer doesn't handle your archive properly.
So it is probably something was incorrect in archive creation process.

**Comment by w17** [comment]
What is 7z version, your system OEM/ANSI codepages and maybe chcp in your console?

**Comment by fitdev** [comment]
@w17 I guess it's a 7z issue then. Sadly there is no command line switch there to specify filename encoding explicitly. Though I still don't get how come my Windows and 7zFM display the archive correctly, while your Windows and 7z display it incorrectly.

> What is 7z version, your system OEM/ANSI codepages and maybe chcp in your console?

7z: 18.06 x64
chcp: 65001
Locale: RUS (I frequently need to work with old files/programs in Cyrillic so that's why I set it to RUS). I also have a checkmark that says _Beta: Use Unicode UTF-8 for worldwide language support_:
![2021-09-16 11_55_14-Region Settings](https://user-images.githubusercontent.com/8166847/133582620-ad485ae7-7aaa-488b-a458-a8e09838a26b.jpg)

**Comment by alabuzhev** [comment]
> I also have a checkmark that says Beta: Use Unicode UTF-8 for worldwide language support

That must be it. Apparently in this case 7z puts UTF-8 encoded names where OEM-encoded names would normally be expected.
Since your whole system is UTF-8, it eventually works in your 7z and Explorer, but not elsewhere.

However, it doesn't explain why it doesn't work in your Arclite. It should use UTF-8 instead of OEM, same as everything else.

**Comment by w17** [comment]
I think 7z is not ready to UTF-8 as current codepage.
It should check if CP==6500 and add UTF-8 flag to archive header.
You can create ticket here: https://sourceforge.net/p/sevenzip/bugs/
First check if somebody didn't that already...

**Comment by w17** [comment]
Actually did -- https://sourceforge.net/p/sevenzip/bugs/2287/

**Comment by alabuzhev** [comment]
> However, it doesn't explain why it doesn't work in your Arclite. It should use UTF-8 instead of OEM, same as everything else.

@fitdev I've enabled UTF-8 in Region settings and your archive looks properly in arclite:
![image](https://user-images.githubusercontent.com/11453922/133586229-18be31b8-d22a-4b1a-9fd4-af5b338f8aaf.png)
Are you sure you didn't have codepages in arclite overridden before opening this issue?
Does it work when the codepages are not specified in the settings?

**Comment by w17** [comment]
> Are you sure you didn't have codepages in arclite overridden before opening this issue?
>
Or disabled UTF-8 in regional settings...

**Comment by fitdev** [comment]
@alabuzhev Thank you for looking into this. Yes, turns out I had Arclite's CP set to 866 (from when I needed to work with old archives). So when I now changed it to 65001, everything is working properly.
