### ISSUE TITLE
Security concern: execute exe file without extension

### ISSUE THREAD

**Issue by bgospodaru** [FarGroup/FarManager#449]
### Far Manager version

3.0.5885.0

### OS version

10.0.19043.1237

### Steps to reproduce

Simply rename any .exe file to "aaa" or any other name without an extension, hit enter and it will execute.

### Expected behavior

On older far versions (for example: v3.0.0.5577), you get the "How do you want to open this file?" dialog:
![image](https://user-images.githubusercontent.com/12615581/133891023-ee5f4623-716b-4382-82fc-2fa2f001e2fd.png)

### Actual behavior

The file will be executed.

**Comment by bgospodaru** [comment]
This will also work if for example the file name is "aaa.aa".

**Comment by alabuzhev** [comment]
> hit enter and it will execute

And why exactly is that a security concern?
Far doesn't execute some unrelated file, it does exactly what the user has asked for.

**Comment by bgospodaru** [comment]
You're saying it's completely normal to execute exe files that do not end in .exe?
Why was the behavior changed anyway?

Let's say you have a list of unknown files and you hit enter by mistake (which can happen from time to time), instead of receiving an error or at least the "How do you want to open this file?" dialog it executes. How is that safe?

The whole reason for renaming a file in the first place and getting rid of the extension is to stop it from executing if you so happen to double click/enter it by mistake.

**Comment by bgospodaru** [comment]
And if you consider that normal behavior, then it should be generalized to the other extensions as well.
For example, after renaming a ".zip" file and removing its extension, hitting enter on the file will not actually enter the zip file. It will pop the "How do you want to open this file?" dialog.

**Comment by alabuzhev** [comment]
> You're saying it's completely normal to execute exe files that do not end in .exe?

I'm not *saying* anything. I'm asking why do you consider it a security concern and expecting to see clear and reasonable arguments.

> Why was the behavior changed anyway?

Windows doesn't offer a single and clear way to launch arbitrary commands.
We have to resort to CreateProcess, ShellExecute and delegating to %comspec% in different order and combinations, depending on the situation. These combinations change from time to time, as we discover more and more weird corner cases. Every such change can introduce new corner cases like this one.

Generally, CreateProcess is preferable for executables, ShellExecute - for various documents and %comspec% - naturally, for comspec-specific commands. However, there's no reliable way to tell whether an arbitrary command is an executable file, a document or something else, so we try all these methods until one of them succeeds. And this is how [CreateProcess](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) works - it doesn't care whether the file has an extension or not.

> Let's say you have a list of unknown files and you hit enter by mistake. ... How is that safe?

Hitting random keys by mistake is never safe.

**Comment by bgospodaru** [comment]
I'm pretty sure you used CreateProcess in older builds of far as well, and you cannot execute randomly named files without extension on those builds (like I mentioned in the original post).
So the behavior clearly changed somewhere along the line.

I still stand by this: the whole reason for renaming a file in the first place and getting rid of the extension is to stop it from executing if you so happen to double click/enter it by mistake.

> Hitting random keys by mistake is never safe.
Mistakes can and will happen always.

I'm curious, what's your reasoning for not introducing a check for valid file extensions to execute with CreateProcess?
I fail to see why would executing a MZPE without extension be useful to anyone.

**Comment by alabuzhev** [comment]
> what's your reasoning for not introducing a check for valid file extensions to execute with CreateProcess?

Naturally, the same as for not doing anything else: no one has ever asked for it (until now).

**Comment by bgospodaru** [comment]
I thought I saw a similar post about this on the forums, I may be wrong though.

Would this be ok to be added to your tasks/roadmap?

**Comment by alabuzhev** [comment]
Let's try. 5888.

**Comment by bgospodaru** [comment]
Seems to be working!

Thank you for your time and cooperation!
