### ISSUE TITLE
Editor: Очень странный баг позиции курсора

### ISSUE THREAD

**Issue by vmech** [FarGroup/FarManager#45]
FAR 3.0.5200 x64 / Windows 10 v1607 x64
Опции `Editor settings`/`Cursor beyond end of line` и `Persistent blocks` **выключены**
Создаём файл со следующим содержимым (cp1251):
```
Строка проверки
Не ноль
Очень длинная строка для копирования
Не ноль
Строка проверки
```
Ставим курсор в конец строки **3**, нажимаем `Ctrl-C`.
Перемещаем курсор стрелками вниз или вверх на последнюю или первую строку. Курсор устанавливается в позицию **8**, которая затирает последнюю позицию из строки **3**.

**Comment by shmuz** [comment]
1. При перемещении курсора вниз с 6-й строки, он попадает на строку 7, которая пустая.
2. В соответствии с выключенной опцией "Cursor beyond end of line", горизонтальная позиция курсора на пустой строке может быть только начальной (первая колонка).
3. В чём же состоит баг?

**Comment by vmech** [comment]
В том, что в любом другом файле (я не зря упомянул о предшествовавшем редактировании множества файлов другого типа), при перемещении по строкам позиция курсора не сбрасывается: курсор устанавливается либо в конец строки, если её длина меньше запомненной позиции, либо в запомненную позицию, если длина строки больше.
Баг же вылезает **только после** копирования по `Ctrl-C`, и только в приведённом файле.

**Comment by shmuz** [comment]
> курсор устанавливается либо в конец строки, если её длина меньше запомненной позиции

При перемещении курсора с 6-й строки на пустую 7-ю начальная позиция и есть конец строки.

**Comment by vmech** [comment]
> При перемещении курсора с 6-й строки на пустую 7-ю начальная позиция и есть конец строки
И на 8ой, и на 9ой, и на 11ой, и на 12ой строках, которые не пустые, курсор останется в позиции 0 по горизонтали.

**Comment by shmuz** [comment]
> И на 8ой, и на 9ой, и на 11ой, и на 12ой строках, которые не пустые, курсор останется в позиции 0 по горизонтали.

1. Так, с правильным перемещением на начальную позицию строки 7 вы, похоже, согласились.
2. Проверил Far 3.0.5200 без плагинов и макросов. Утверждение по поводу 8,9,11,12 строк не подтверждаю. У меня в этих строках курсор не остаётся на начальной позиции.

**Comment by vmech** [comment]
> Проверил Far 3.0.5200 без плагинов и макросов. Утверждение по поводу 8,9,11,12 строк не подтверждаю. У меня в этих строках курсор не остаётся на начальной позиции.

Рад за Вас. У меня баг проявляется и при запуске через `far.exe -ro -s %TEMP%\farprofile\%RANDOM%`.

**Comment by shmuz** [comment]
1. Баг подтверждаю.
2. Для воспроизведения бага, помимо опции "Cursor beyond end of line" ещё должна быть сброшена опция "Persistent blocks".
3. Баг появился в билде 5024.

**Comment by MKadaner** [comment]
Могу подтвердить. Этот баг "был всегда". У меня на работе установлен build 3367 (всё не доходят руки обновить), дома -- 5199, в обоих это поведение воспроизводится. Более точное описание сценария:

1. Файл содержит пустую строку (или несколько) вокруг которых есть непустые строки.
2. "Курсор за пределами строки" выключен.
3. "Persistent blocks" выключен.
4. Курсор в строке, перед или после пустой.
5. Выделить одну (или несколько) букв движением курсора со стрелками. Курсор должен остаться не в первой позиции.
6. Сдвинуться на пустую строку и перейти на непустую (продолжить двигаться или вернуться).
7. Горизонтальная позиция курсора теряется, и курсор двигается по первым позициям строк.

**Comment by vmech** [comment]
@shmuz да, `Постоянные блоки` не установлены.

**Comment by shmuz** [comment]
@MKadaner, в билде 5023 ваша последовательность работает правильно, баг не наблюдается.

**Comment by MKadaner** [comment]
@shmuz, Вы правы, в старой версии _эта_ проблема не воспроизводится. Там есть другая, похожая. Если двигать курсор  с контролом (т.е., скроллить текст под курсором), то горизонтальная позиция курсора "сползает" по мере того, как курсору встречаются всё более короткие строки. В частности, после пересечения пустой строки, курсор навсегда остаётся в первой позиции.

Эту проблему я наблюдаю давно. Не был уверен, что это не "by design". Раздражает, но не сильно.

**Comment by shmuz** [comment]
@vmech
> ЗЫ. Исправил стартовый пост на более корректно описывающий ситуацию.

И тем самым сделали бессмысленной бОльшую часть обсуждения.

**Comment by zg0** [comment]
находясь в конце самой длинной строки жмём down f7 esc up. где должен быть курсор?

**Comment by shmuz** [comment]
> находясь в конце самой длинной строки жмём down f7 esc up. где должен быть курсор?

На мой взгляд, вызов модального диалога поиска и его отмена не должны влиять на состояние курсора. Так, например,  ведут себя редакторы SciTE и Notepad++ (это то, что я попробовал сейчас).

**Comment by vmech** [comment]
> На мой взгляд, вызов модального диалога поиска и его отмена не должны влиять на состояние курсора.

Нажатие Ctrl-C, без предварительного выделения чего либо, тоже не должно влиять на состояние (положение) курсора.

**Comment by zg0** [comment]
ctrl-c без выделения выделяет текущую строку.
я лично не пользуюсь [ ] Cursor beyond end of line и не представляю, как оно там должно быть. по факту «реальное» положение обновляется с текущего положения курсора кроме случаев, когда происходит вертикальная навигация. т.е. вот такой макрос всё ломает:
`Macro {
  area="Editor"; key="Down";
  action=function()
    Keys"Down"
    far.AdvControl"ACTL_REDRAWALL"
  end;
}`
почему так сделано — к Рошалу, в 1.65 всё точно также.
в случае с ctrl-c до 5024 при снятии выделения редактор честно не перерисовывался, поэтому «реальное» положение не сбрасывалось. т.е. именно ctrl-c закостылить несложно, но раз этим кто-то реально пользуется — может нужно сделать нормально? правильно ли я понимаю, что «реальное» положение должно менятся только при изменении горизонтальной позиции курсора?

**Comment by shmuz** [comment]
> правильно ли я понимаю, что «реальное» положение должно менятся только при изменении горизонтальной позиции курсора?

1. Да
2. Также при каждом вызове ECTL_SETPOSITION, безотносительно к прежнему состоянию курсора
3. Функция Keys() должна влиять так, как будто клавишу нажали руками

Так мне представляется, не претендую на истину в последней инстанции.

**Comment by MKadaner** [comment]
> правильно ли я понимаю, что «реальное» положение должно меняться только при изменении горизонтальной позиции курсора?

Да, это то, как я ожидаю поведение курсора при вертикальной навигации. Я пользуюсь `[_] Cursor beyond end of line` всё время. Это я когда-то убедил Рошаля сделать эту опцию.

**Comment by excitoon** [comment]
Да, действительно, сбивается положение курсора, если начать перемещаться с Shift (выделяя). Но автор не про это писал. Вообще же плохо, что курсор не прилипает в этом режиме к концу строки как в vim.

**Comment by alabuzhev** [comment]
Fixed in 5575 (44a55b9)

**Comment by MKadaner** [comment]
Thank you!
