### ISSUE TITLE
Issue with navigation if dir structure was deleted outside of far

### ISSUE THREAD

**Issue by joye-ramone** [FarGroup/FarManager#481]
### Far Manager version

3.0.5921.0 x86

### OS version

10.0.19044.1348

### Steps to reproduce

1. Create dir structure like C:\1\2\
2. Open dir 2 at far panal
3. Open explorer or any other file manager and delete dir 1 (including it's content)
4. Back to far and try to either navigate to parent dir from current "2"  or Ctrl+R

### Expected behavior

After first message 
 The system cannot find the path specified.
far go to nearest valid path on this drive or to root of drive 

### Actual behavior

Far get stuck in endless loop between dialogs with message:
0x00000003 - The system cannot find the path specified.

Only possible options to resolve it - either change active panel and change it back
Or change current disk to different one and then change back.

**Comment by alabuzhev** [comment]
ok, 5922.

**Comment by joye-ramone** [comment]
Works like a charm! Thx
