### ISSUE TITLE
Omitted text highlighting

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#489]
I think that  ‘.’ marker in line 4797 should be displayed in white, because this is similar to line 4798 (topic: "**regexp"**). This same in all help files (translations).

https://github.com/FarGroup/FarManager/blob/28934c6481bbb4e398dbcf233dbb7b21fedf3cc0/far/FarEng.hlf.m4#L4797-L4799

**Comment by alabuzhev** [comment]
Thanks, updated.
