### ISSUE TITLE
Removal of Parenthesis from a User Variable Initial Value in F2 User Command

### ISSUE THREAD

**Issue by fitdev** [FarGroup/FarManager#502]
### Far Manager version

3.0.5885.0

### OS version

10.0.17134.1345

### Steps to reproduce

Create a new user menu command:

```
download.exe -o "!\\%(playlist_title)s (WEB-%(playlist_id)s)\!?$webdl_list_filename$File Name?%(playlist_index)03d - %(title)s (%(upload_date)s WEB.%(channel_id)s-%(id)s).%(ext)s!" "!?$webdl_list$Url?https://!" --merge-output-format mkv
```

Note the `(` and `)` after first `%` in the initial value section of `$webdl_list_filename$` user variable.

### Expected behavior

```
                                                                            
   ╔═══════════════════════════════ Test ═══════════════════════════════╗   
   ║ File Name                                                          ║   
   ║ %(playlist_index)03d - %(title)s (%(upload_date)s WEB.%(channel_id↓║   
   ║ Url                                                                ║   
   ║ https://                                                          ↓║   
   ╟────────────────────────────────────────────────────────────────────╢   
   ║                         { OK } [ Cancel ]                          ║   
   ╚════════════════════════════════════════════════════════════════════╝   
                                                                                                                                                 
```

Note the `(` and `)` around `playlist_index` in the _File Name_ field.

### Actual behavior

```
                                                                            
   ╔═══════════════════════════════ Test ═══════════════════════════════╗   
   ║ File Name                                                          ║   
   ║ %playlist_index03d - %(title)s (%(upload_date)s WEB.%(channel_id)s↓║   
   ║ Url                                                                ║   
   ║ https://                                                          ↓║   
   ╟────────────────────────────────────────────────────────────────────╢   
   ║                         { OK } [ Cancel ]                          ║   
   ╚════════════════════════════════════════════════════════════════════╝   
                                                                            
```

**Comment by bitraid** [comment]
Parentheses have special meaning in parameter definition. Use double parentheses to have the desired effect.

**Comment by fitdev** [comment]
@bitraid Thanks for the tip. But strangely all other parenthesis pairs in my actual, more complex command work just fine.

**Comment by bitraid** [comment]
Since the use of parentheses in `title` and `init` is to enclose the special symbols, I think the actual bug is that they are used for that purpose only for the first pair.

**Comment by bitraid** [comment]
But this is not restrictive, since one pair is enough to enclose multiple symbols and normal parentheses.
Your string, for example, should be (where you could also insert `!.!` etc):
`!?$webdl_list_filename$File Name?%((playlist_index)03d - %(title)s (%(upload_date)s WEB.%(channel_id)s-%(id)s).%(ext)s)!`

**Comment by fitdev** [comment]
Thank you for your example.

So, then is the general recommendation to use a _single pair_ of `(`...`)` to enclose everything within the `init` user variable value as long as there are any parenthesis inside?

**Comment by alabuzhev** [comment]
@fitdev, by enclosing a part of the string in parentheses you're effectively asking the code to look at it and expand the special symbols, if any. Enclosing everything as long as there are any parenthesis inside might be not the best idea, because, obviously, the code can actually find something there even if it wasn't your intention.

Thinking about it, we could probably be a bit smarter in this particular case and leave the parentheses alone if there are no special symbols between them.

**Comment by alabuzhev** [comment]
> leave the parentheses alone if there are no special symbols between them

 5945.

**Comment by bitraid** [comment]
Parentheses pair with special symbols doesn't work properly if it's not the first pair (pre-existing bug). For example: `!??(text)(!.!)!`

**Comment by alabuzhev** [comment]
I know, only the first pair is considered special. No idea why, it was 18 years ago. Maybe the author thought it would be enough, since you can enclose the whole expression, or maybe he was fed up with the complexity, or maybe didn't think of it at all. It can be extended of course, but I'm not sure we should.

**Comment by bitraid** [comment]
The weird thing is that the string is treated as a command (including the starting `!??`), the special symbols are processed (including the parentheses), and the final `!` is also processed (name only).

**Comment by alabuzhev** [comment]
Ugh.
As I said, the code considers only the first pair, so it *should* stop on the first `!` after the brackets and parse `!??(text)(!.!)!` as `(text)(` + `.` + `long file name without extension` + `)` + `long file name without extension`.

And this is exactly what it tries to do, but for some insane reason it keeps checking whether the subsequent parentheses are balanced, even though they don't have any special meaning, and fails the whole thing. 🤦

**Comment by bitraid** [comment]
I know this is getting frustrating, but another thing broke - the escaping of `!`: `!??(!!)!`

**Comment by alabuzhev** [comment]
```
!!       The ‘!’ character
```

**Comment by bitraid** [comment]
Oops, my bad - I thought that this didn't work after e4bbd272d91b6a0e2ea51ae9e69b70662105c28b, but I actually messed up the test string.

**Comment by alabuzhev** [comment]
Anything else here or can we close it?

**Comment by fitdev** [comment]
So, is the double parenthesis escaping `((`...`))` necessary now in the latest build?

**Comment by alabuzhev** [comment]
Only if you have special symbols within them.

**Comment by fitdev** [comment]
I see. Thank you. Ideally this should be documented in help.
