### ISSUE TITLE
Help file - suggestion (ommited key highlight)

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#504]
FarEng.hlf, line #5131 - i think that word "Shift" should be enclosed in hash signs, as Ctrl is enclosed. And it should be enabled in all languages.
In Polish version I've already chenged to #Shift#.
https://github.com/FarGroup/FarManager/blob/9474ca47655e66b59d6f8dbe14b0063a2c465ca2/far/FarEng.hlf.m4#L5128-L5131

**Comment by alabuzhev** [comment]
Thanks, b399c54
