### ISSUE TITLE
Bug in help file - @System.QuotedName

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#510]
### Far Manager version

3.0.5961.0

### OS version

10.0.19044.1526

### Steps to reproduce

Help file, topic: @System.QuotedName

>  Bit numbers:
 0 - ^<wrap>Quote names when inserting into the command line or editor;
 1 - Quote names when copying to the clipboard.
> 
> Default value: 1 (quote when inserting into the command line or editor).

I see that default value is set to 1 (one), but there is wrong description.

### Actual behavior

Wrong description.

**Comment by alabuzhev** [comment]
The description is correct.
Those are **bit** numbers:
bit 0 = 2<sup>0</sup> = 1
bit 1 = 2<sup>1</sup> = 2
bit 2 = 2<sup>2</sup> = 4 and so on.

You can press Alt+F4 to view & change bits.

**Comment by BestiaPL** [comment]
You are right. I'll try to explain in Polish translation.
