### ISSUE TITLE
Picture View Plugin doesn't work in Windows Terminal

### ISSUE THREAD

**Issue by azinsharaf** [FarGroup/FarManager#511]
### Far Manager version

3.0.5959.0 x64

### OS version

10

### Other software

Windows Terminal

### Steps to reproduce

- install Picture View plugin: https://plugring.farmanager.com/plugin.php?pid=693&l=en
- install windows Terminal
- Launch Far.exe inside of Win Terminal
- Select a picture file and press 11 (Plugin) and Picture View

Nothing shows up.
It works if I do out outside of Windows Terminal

### Actual behavior

Picture view doesn't show the picture.

**Comment by alabuzhev** [comment]
@azinsharaf it's sad that the plugin doesn't work, but it has nothing to do with Far.

Please report this either to [microsoft/terminal](https://github.com/microsoft/terminal) (probably pointless - Windows Terminal is *intentionally broken* in many ways), or to [the plugin's author](https://forum.farmanager.com/viewtopic.php?p=169718#p169718) (hopefully workarounds are possible).
