### ISSUE TITLE
Drives are "initialized" when Alt-F1 or Alt-F2 is pressed for the first time

### ISSUE THREAD

**Issue by pboettcher** [FarGroup/FarManager#524]
### Far Manager version

3.0 (build 4444) x64

### OS version

6.1.7601

### Steps to reproduce

- Start Far on Toshiba Satellite R830-13D laptop.
- Press Alt-F1 or Alt-F2 to bring up drive change panel.
- For the first time DVD-Drive (with no disk in it) makes a mechanical initialization whack noise and there is a delay.
- For subsequential Alt-F1 or Alt-F2 key presses no initialization recalibration happens.
- Close Far Manager and start it again.
- Press Alt-F1 or Alt-F2 to bring up drive change panel.
- No recalibration happens.
- Let the drive be idle for several minutes.
- Press Alt-F1 or Alt-F2
- Mechanical recalibration happens.

### Expected behavior

No drives initialization happens.

### Actual behavior

Allegedly a disks initialization command is issued. It is definitely **not** the GetLogicalDrives(). I have a software that calls this function each second and there is no such effect.

**Comment by alabuzhev** [comment]
"Change drive" menu can show various extended information. Some of it, e.g. disk label or filesystem, requires disk access for obvious reasons. You can choose what exactly should be displayed by pressing F9 in the menu. Unchecking individual options one by one, or, alternatively, the "Show CD drive parameters" altogether could help.

**Comment by pboettcher** [comment]
> "Change drive" menu can show various extended information. Some of it, e.g. disk label or filesystem, requires disk access for obvious reasons. You can choose what exactly should be displayed by pressing F9 in the menu. Unchecking individual options one by one, or, alternatively, the "Show CD drive parameters" altogether could help.

Ok, I will test it out, one by one.
