### ISSUE TITLE
Incorrect handling of string substitution

### ISSUE THREAD

**Issue by tvasenin** [FarGroup/FarManager#529]
### Far Manager version

3.0.5959

### OS version

Microsoft Windows [Version 10.0.19043.1645]

### Other software

FFMPEG (any version should work, mine is 5.0.1 installed via Chocolatey)

### Steps to reproduce

1, Create the user menu entry with the comands:
```
set SS=!?ss?00:00.000!
set SS_subst=%SS::=_%
set FILEOUT=!.TRIM_%SS_subst%.!`
echo %FILEOUT%
ffmpeg  -hide_banner -ss %SS% -i "!.!" -c copy -movflags faststart "%FILEOUT%"
````
2. Take any file, rename it to `test.mp4` and run the above command against it.

### Expected behavior

Both `echo %FILEOUT%` and `ffmpeg ... "%FILEOUT%"` treat the FILEOUT variable as `test.TRIM_00_00.000.mp4`.

### Actual behavior

ECHO correctly displays `test.TRIM_00_00.000.mp4`.

FFMPEG call results in error: `test.TRIM_%SS::=_%.mp4: Invalid argument`.

**Comment by alabuzhev** [comment]
Far doesn't support advanced substitution.
If you want it, pass the whole command to cmd, e.g. `cmd /s /c "ffmpeg ... "%FILEOUT%""`.
