### ISSUE TITLE
Temporary panel: Saved content to a list file contains null termination character

### ISSUE THREAD

**Issue by pmisik** [FarGroup/FarManager#537]
### Far Manager version

3.0.6000 x64

### OS version

Microsoft Windows [Version 10.0.19044.1826]

### Other software

TmpPanel, version 3.0.112.0

### Steps to reproduce

1. Press Alt-F7 (Command >Find File)
2. Keep default settings
3. Press Find button
4. Press Panel button
5. Press Alt-Shift-F2 (Save file list as file)

### Expected behavior

Serialized file list  is new line delimited file list without \0 character.
e.g.:
C:\Program Files\Far Manager\changelog\r\n
C:\Program Files\Far Manager\Far.exe\r\n
C:\Program Files\Far Manager\Far.exe.example.ini\r\n

### Actual behavior

Serialized file list  is new line delimited file list with \0 character.
e.g.:
C:\Program Files\Far Manager\changelog\0\r\n
C:\Program Files\Far Manager\Far.exe\0\r\n
C:\Program Files\Far Manager\Far.exe.example.ini\0\r\n

![image](https://user-images.githubusercontent.com/14224662/182453007-cfccce3a-ea7c-41b8-8592-045eda0a7533.png)

**Comment by alabuzhev** [comment]
Thanks, fixed.
