### ISSUE TITLE
Far crashes when trying to free up memory used to store Descript.ion file records

### ISSUE THREAD

**Issue by dpelevin** [FarGroup/FarManager#54]
Far crashes trying to free up memory used to store Descript.ion file records, if descriptions were displayed at the panel provided by a plugin (which can handle Descript.ion files), regular file panels are not affected.

Bug is present at least for a year and can be reproduced with a last stable build:
Far Manager, version 3.0 (build 5225) x64

Crash happens at the following line:
https://github.com/FarGroup/FarManager/blob/973a3da59809845de319dbe24a3606a5c7a9de66/far/filelist.cpp#L435

It is not possible to reproduce the bug with any of default Far package plugins like ArcLite or NetBox, as both ignore Descript.ion files, but it is not complex to reproduce it with [MultiArc plugin](https://plugring.farmanager.com/plugin.php?pid=915&l=ru) and 7-Zip archiver.

Steps to reproduce:
1) Remove ArcLite plugin (as it'll conflict with MultiArc)
2) Download [7-Zip Extra: standalone console version](https://www.7-zip.org/download.html) (or use an existing installation of 7-Zip) (7-zip site could be unavailable if you are trying to download the file from the territory of Russian Federation).
3) Extract 7za.exe, and copy it as 7z.exe to Far's directory (near far.exe) or just add it to the PATH.
4) Change MultiArc's default 7z file extraction command from:
'7z e {-p%%P} -r0 -y -scsDOS -- %%A @%%LQMN'
to:
'7z e {-p%%P} -r0 -y -scsDOS %%A @%%LQMN'
(it can be done via Options -> Plugins configurations -> Archive support -> Command lines -> 7z, 'Extract without paths' command).
5) Prepare 7z archieve with an empty file ('1.txt', for example) and 'Descript.ion' (just add description to '1.txt' by Ctrl+Z hotkey).
6) Open created 7z archieve with Enter key.
7) Validate MultiArc plugin configuration by extracting '1.txt' file with F5 key.
8) Change panel mode to 'Descriptions' (can be done with main menu Left -> Description or LCtrl+6 hotkey).
8) Now you should be able to see description for the file '1.txt', displayed at the second column near the file name. Press Ctrl+R, or just leave the archive - Far will crash with a following message (in the case you are using debug version of the executable):
Assertion failed: Info->AllocationType == type, file d:\vsprojects\far\far\memcheck.cpp, line 249

**Comment by alabuzhev** [comment]
Thanks, fixed.
