### ISSUE TITLE
При просмотре текстового файла, после поиска по содержанию, вылетает с ошибкой ПичарВью и крашит FAR

### ISSUE THREAD

**Issue by VladimirMQW** [FarGroup/FarManager#544]
### Far Manager version

3.0.6000

### OS version

Win 7 x64

### Steps to reproduce

Alt-F7 *.* или *.php ищем текст в содержимом. Потом просмотреть по F3 и вылетает 
Ищем и смотрим не в картинке, а в текстовом файле, вот в  php например.
[bug_report.txt](https://github.com/FarGroup/FarManager/files/9459938/bug_report.txt)
[far.zip](https://github.com/FarGroup/FarManager/files/9459949/far.zip)
![изображение](https://user-images.githubusercontent.com/97737801/187634502-d2d66cf6-e1c8-4ad1-a264-a78a2ac0ea0b.png)

### Actual behavior

Jq

**Comment by yegor-mialyk** [comment]
PictureView plugin is not a part of Far Manager. You have to contact PictureView plugin authors separately, e.g. https://forum.farmanager.com/viewtopic.php?t=7869.

**Comment by VladimirMQW** [comment]
Вылетел FAR! Именно из панели поиска (найденных файлов). Именно при просмотре файлов *.php и *.txt. (почему текстовый файл вдруг стал смотреться PictureView) Должен был вызваться встроенный просмотровщик. Причем эти же файлы если зайти в каталог просто из панели и нажать F3/F4 показывает нормально.
На предыдущей версии 3.0.58хх - 3.0.59хх  такого не было.
Поставил PictureView V3 2021.04.19 - теперь не вылетает
