### ISSUE TITLE
"[x] Has more than one hardlink" does not work in "Files highlighting"

### ISSUE THREAD

**Issue by faerot** [FarGroup/FarManager#547]
### Far Manager version

3.0.6019

### OS version

6.1.7601

### Steps to reproduce

When checking the "Has more than one hardlink" in the Options -> Files Highlighting and sort groups, it has no effect.
I have been using build 5400 before and it worked back then. It stopped working when switching to 6000 and it is also does not work in nightly 6019.

See this image:
![изображение](https://user-images.githubusercontent.com/5680342/189078298-1de76e15-9753-4ca3-84ed-b1a2d0a07d9a.png)

### Expected behavior

File should be underlined.

### Actual behavior

File is not underlined.

**Comment by bitraid** [comment]
Since you have selected the `Continue processing` option for the hard links style, you should set the (new) `Inherit` option for the rest of the styles.

**Comment by faerot** [comment]
> Since you have selected the `Continue processing` option for the hard links style, you should set the (new) `Inherit` option for the rest of the styles.

Can you point me to the description on this option and how to use it?

**Comment by bitraid** [comment]
I don't think there is a documentation for it yet, but its usage is pretty straight forward: If you want a highlight group to include previous (higher) styles, set the `Inherit` style option:
```
 ╔═════════════════════════ Color ═══╤══════════════════════╗ 
 ║ [ ] Foreground:          AA    ## │ Style:               ║ 
 ║  •                       00    00 │ [x] Inherit          ║ 
 ║                          [ 256… ] │ ──────────────────── ║ 
 ║                          [ RGB… ] │ [ ] Bold             ║ 
 ╟───────────────────────────────────┤ [ ] Italic           ║ 
 ║ [ ] Background:          AA    ## │ [ ] Underline        ║ 
 ║  •                       00    00 │ [ ] Double           ║ 
 ║                          [ 256… ] │ [ ] Overline         ║ 
 ║                          [ RGB… ] │ [ ] Strikeout        ║ 
 ╟───────────────────────────────────┤ [ ] Faint            ║ 
 ║ Text Text Text Text Text Text Tex │ [ ] Blink            ║ 
 ║ Text Text Text Text Text Text Tex │ [ ] Inverse          ║ 
 ║ Text Text Text Text Text Text Tex │ [ ] Invisible        ║ 
 ╟───────────────────────────────────┴──────────────────────╢ 
 ║                    { Set } [ Cancel ]                    ║ 
 ╚══════════════════════════════════════════════════════════╝ 
```

**Comment by faerot** [comment]
Oh, you mean "inherit" INSIDE of the style, I thought you are referring to the one near the mark that previously was "transparent"

**Comment by bitraid** [comment]
>Oh, you mean "inherit" INSIDE of the style, I thought you are referring to the one near the mark that previously was "transparent"

That one is for the optional marking character.

**Comment by faerot** [comment]
That helped, thanks
