### ISSUE TITLE
Screen scrambled when pressing Alt-F9 under Windows 11 22H2

### ISSUE THREAD

**Issue by TheChatty** [FarGroup/FarManager#551]
### Far Manager version

3.0.6037.2930 x64

### OS version

11.0.22622.730

### Other software

When you maximize with Win+Arrow Up - it works.
When you maximize with Alt-F9 screen looks scrambled.

![image](https://user-images.githubusercontent.com/4789510/194641916-455dd2d9-eb0d-4b3c-8f14-323c1346a74c.png)

### Steps to reproduce

- Install Windows 11 22H2
- Install Far 3.0.x up to 6037.290
- Press Alt-F9

### Expected behavior

Window maximized, screen not scrambled

### Actual behavior

Window size remains, screen is scrambled

**Comment by alabuzhev** [comment]
Far calls [GetLargestConsoleWindowSize](https://learn.microsoft.com/en-us/windows/console/getlargestconsolewindowsize) when you press Alt+F9 and that API is [broken in Windows Terminal](https://github.com/microsoft/terminal/issues/10337).

Maybe we will come up with a workaround one day, but so far it is what it is.

**Comment by TheChatty** [comment]
Is there a way to use the former (Windows 11 21H2) terminal window? Because what also bugs me is when I press Ctrl-V I'm asked if I'm sure I want to insert (by Windows) and then the pasting happens real slow...

**Comment by alabuzhev** [comment]
> Since Win+Arrow Up is working... could this be a workaround? Simply maximize the window?

Unfortunately, no. Windows Terminal prevents console apps from accessing its window (because its developers believe it is the right thing to do), so we cannot do anything with it.

I think I can come with a workaround to at least not scramble the screen though. 6038.

**Comment by alabuzhev** [comment]
> Is there a way to use the former (Windows 11 21H2) terminal window?

It is somewhere in [settings](https://devblogs.microsoft.com/commandline/windows-terminal-as-your-default-command-line-experience/#default-terminal-setting).

**Comment by TheChatty** [comment]
Since window size doesn't change with Alt-F9 it would be best to simply ignore this.

**Comment by TheChatty** [comment]
I found that setting. But what works even better: Change your launching short to
`C:\Windows\System32\conhost.exe "C:\Program Files\Far Manager\Far.exe"`

**Comment by alabuzhev** [comment]
> when I press Ctrl-V I'm asked if I'm sure I want to insert (by Windows) and then the pasting happens real slow...

It can be disabled somewhere in terminal settings too as far as I remember, as well intercepting of other keys.

**Comment by TheChatty** [comment]
My suggestion is to ask the user during installation on 22H2 systems whether he wants a console or terminal app. I‘d make the former the default. If you don‘t want to ask make it default right away.

**Comment by alabuzhev** [comment]
That's an interesting idea.
We might have to do that if the number of various terminal-related bug reports becomes unbearable.

**Comment by alabuzhev** [comment]
Alt+F9 should work from 6039 onward. Sort of.

**Comment by TheChatty** [comment]
With [v3.0.6039.2932](https://github.com/FarGroup/FarManager/releases/tag/ci%2Fv3.0.6039.2932) pressing Alt-F9 looks the same as pressing Win+ArrowUp - and it works. No more scrambled terminal.

Nevertheless I'll stick with conhost - at least for Far Manager.
