### ISSUE TITLE
msi package version no longer supported on Vista 

### ISSUE THREAD

**Issue by theultramage** [FarGroup/FarManager#557]
### Far Manager version

3.0.6000.0

### OS version

6.0.6003

### Steps to reproduce

Download msi installer package from farmanager website and try to install it on Windows Vista.

### Actual behavior

Windows Installer reports that the msi package cannot be installed and that a newer version of the installer is required.
The contents of the latest version run fine when unpacked, but the msi installer seems to be produced by a version of the toolset that is not supported by vista's msiexec anymore. If Vista is still considered a supported OS then maybe take a moment to look into this small incompatibility.

Here is some info based on previous versions from wayback machine:
Far30b5888.x86.20210919.msi release - works with msiexec 4.5.6002.19424 (Vista).
Far30b5915.x86.20211113.msi nightly - does not work.

**Comment by alabuzhev** [comment]
Probably after [this change](https://github.com/FarGroup/FarManager/commit/f1ea5d83f0#diff-cfeb6cddda0fa55241cab08e6a74c851d64087bbbc4afa50758d6b3df8f78577) - we [had to](https://learn.microsoft.com/en-us/windows/win32/msi/using-64-bit-windows-installer-packages) bump the installer version to 500 to support ARM64 packages.
I'll check whether it's possible to parametrize it somehow.

**Comment by alabuzhev** [comment]
95039d95d2e8d63ff56535cae1de38cf92f4201e 

Should work all the way down:

![image](https://user-images.githubusercontent.com/11453922/198097791-5cc8d950-fa47-42ca-97a0-e63504123b31.png)
