### ISSUE TITLE
Weird vertical lines on fresh Windows 10 22H2 install

### ISSUE THREAD

**Issue by inliquid** [FarGroup/FarManager#563]
### Far Manager version

3.0.6000

### OS version

10.0.19045.2006

### Steps to reproduce

I see very strange behavior with vertical lines, which I haven't seen before:
![изображение](https://user-images.githubusercontent.com/6797881/203613519-d360a9ae-cdc5-4eec-8663-afe68009548d.png)

I have same Far version on another Windows 10 machine but older version (21H2 vs 22H2) with normal lines. Colors also look a little bit washed out.

Tried to reinstall and "play" with shortcut options.

### Expected behavior

Normal lines and colors.

### Actual behavior

See description above.

**Comment by inliquid** [comment]
I just thought that there might been some changes in OS that might make sense to reflect on Far side? Like setting some specific options for a shortcut. I didn't manage to fix it so far.

**Comment by alabuzhev** [comment]
Scaling factor might also affect the rendering.

I can reproduce your picture with consolas 20 scaled up to 125%:

![20](https://user-images.githubusercontent.com/11453922/204095851-35d48d02-a603-4b66-b794-ce011b5f7e23.png)

Scaling it back to 100% should help.
If that is not desirable, slightly different sizes should work too, e.g.

Consolas 19:

![19](https://user-images.githubusercontent.com/11453922/204095915-f2954e70-9648-43cb-9ae2-c8038836275e.png)
Consolas 21:

![21](https://user-images.githubusercontent.com/11453922/204095923-f03d44e6-a068-44e2-b13b-0274186e10b9.png)

These sizes are not available in the list, but you can type in any number directly:

![sz](https://user-images.githubusercontent.com/11453922/204096017-0bdb4242-a5f3-4d40-ab0a-4eda0b9224c5.png)

**Comment by inliquid** [comment]
Yep, sounds pretty much like a scaling problem. Closing for now. Thanks for support!
