### ISSUE TITLE
Poor warm-up time

### ISSUE THREAD

**Issue by rizopus** [FarGroup/FarManager#567]
### Far Manager version

3.0.6058.0

### OS version

10.0.19045.2251

### Steps to reproduce

Prerequisites: several thousand or more enties in a command history
1. Start Far Manager
2. Start typing in the command line
3. See a lag (several seconds, depends on HW)

### Expected behavior

When you start Far Manager that has a lot of command history lines there should be no lag once you type the first command.

### Actual behavior

In the current codebase there is a lag when you type the first command.

This is because `HistoryConfigCustom::Initialise` calls `reindex(Db)` that issues `REINDEX` sqlite statement. I suppose this statement is only needed to migrate from some old versions. Removing this call leads to eradication of the lag.

**Comment by alabuzhev** [comment]
The link above mentions that `PRAGMA INTEGRITY_CHECK;` can be used to validate the index.
Perhaps it can be faster than reindexing unconditionally.

Would you be able to apply the following patch and check that assumption?
<details>


```DIFF
diff --git a/far/configdb.cpp b/far/configdb.cpp
index dfece37cd..74cc07ba6 100644
--- a/far/configdb.cpp
+++ b/far/configdb.cpp
@@ -1975,7 +1975,13 @@ private:
 
 			try
 			{
-				reindex();
+				if (const auto stmtIntegrityCheck = Db.create_stmt(format(FSTR("PRAGMA INTEGRITY_CHECK({})"sv), Name)); stmtIntegrityCheck.Step())
+				{
+					if (const auto Result = stmtIntegrityCheck.GetColText(0); Result != L"ok"sv)
+					{
+						reindex();
+					}
+				}
 			}
 			catch (far_sqlite_exception const& e)
 			{
diff --git a/far/sqlitedb.hpp b/far/sqlitedb.hpp
index 0830639c0..01da83965 100644
--- a/far/sqlitedb.hpp
+++ b/far/sqlitedb.hpp
@@ -214,6 +214,7 @@ protected:
 		FORWARD_FUNCTION(add_nocase_collation)
 		FORWARD_FUNCTION(add_numeric_collation)
 		FORWARD_FUNCTION(ScopedTransaction)
+		FORWARD_FUNCTION(create_stmt)
 
 #undef FORWARD_FUNCTION
 
``` 
</details>

**Comment by rizopus** [comment]
> It is surprising that reindexing takes several seconds in your case.

I have 10k records in the `history` table + 15k in total in the other two tables, and quite an old computer, so maybe this counts.

> Would you be able to apply the following patch and check that assumption?

Thanks for the patch, I'll be able to test it tomorrow

**Comment by rizopus** [comment]
@alabuzhev I tested your patch, it works great - no more lags.

**Comment by alabuzhev** [comment]
Great, 6059 then.
