### ISSUE TITLE
Появляеться окно "Ой" "Что-то пошло не так" в модуле "TmpPanel 3.0.112.0"

### ISSUE THREAD

**Issue by Romario0812** [FarGroup/FarManager#569]
### Far Manager version

3.0.6000.0 x64 (e1c04d5)

### OS version

10.0.19045.2.0.0.256.1 (version 22H2, OS build 19045.2311)

### Steps to reproduce

Alt+F7 (поиск файла по имени)
в настройке поиска указал:
искать файл: 2021-06-29*
поставил галочку: искать в том числе внутри архивов
начало поиска с корня диска C:\ включая все поддирректории

### Actual behavior

Появляется окно "Ой" "Что-то пошло не так" в модуле "TmpPanel 3.0.112.0"
<img width="960" alt="2022-12-10_19-53-48" src="https://user-images.githubusercontent.com/31605897/206866289-3de24c2b-b838-4315-a8de-edf7c398b03f.png">
<img width="1142" alt="2022-12-10_19-55-04" src="https://user-images.githubusercontent.com/31605897/206866292-35ea6992-c8de-4d8e-923a-78f413fccff8.png">
[bug_report.txt](https://github.com/FarGroup/FarManager/files/10200526/bug_report.txt)
[far.mdmp.txt](https://github.com/FarGroup/FarManager/files/10200527/far.mdmp.txt)

**Comment by alabuzhev** [comment]
This was fixed a while ago, get the latest version.

**Comment by Romario0812** [comment]
Thanx!
