### ISSUE TITLE
Brackets matching plugin searches for quotes in the wrong direction

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#574]
### Far Manager version

3.0.6069.0 x64

### OS version

10.0.22623.1028

### Steps to reproduce

1. Extract `Editor.TestBrackets.lua` from the attached archive [Editor.TestBrackets.zip](https://github.com/FarGroup/FarManager/files/10239514/Editor.TestBrackets.zip)
2. Copy `Editor.TestBrackets.lua` to the `Macro\scripts` directory in the Far profile directory
3. Reload macros using `macro:load` or restart Far
4. Open `Editor.TestBrackets.lua` in the Far Editor
5. Position the cursor on the opening quote of "CtrlBackslash"
6. Press `Ctrl + \` hotkey to run the macro

### Macro Code
```lua
Macro {
    area = "Editor";
    key = "CtrlBackslash";
    description = "Test for Bracket matching";
    action = function()
        Plugin.Call("B66C436D-E657-419C-86D3-6834B9ACF3D2", "SEARCHFWD")
    end;
}
```

### Expected behavior

The cursor is positioned on the closing quote of `"CtrlBackslash"`

### Actual behavior

The cursor is positioned on the closing quote of `"Editor"`. That is, the search is performed backwards instead of forwards. If I use `SEARCHBACK`, then the search is performed forwards. Using `0` instead of `SEARCHFWD` has the same results.

Note that searching using `F11 > Brackets matching > Search > Forward` works correctly. The issue is only when called from a macro.

**Comment by w17** [comment]
should be fixed fixed now....

**Comment by rohitab** [comment]
It's fixed. I just tested version 3.0.6071.0 x64. Thank you.

**Comment by johnd0e** [comment]
https://bugs.farmanager.com/view.php?id=3021
