### ISSUE TITLE
Plugin help doesn't work when launched from some plugin panels

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#575]
### Far Manager version

3.0.6069.0 x64

### OS version

10.0.22623.1028

### Steps to reproduce

1. Open any archive in ArcLite
2. Make sure the Active panel is the one with the open archive
3. Press `F1` to open help
4. Press `Shift + F2` to open Plugins help
5. Select any topic and press `Enter`

### Expected behavior

The selected topic should open

### Actual behavior

Far displays an error message: "Cannot open the file"

**Comment by alabuzhev** [comment]
Should be fixed in 6070.

**Comment by rohitab** [comment]
It's fixed. Just tested version 3.0.6071.0 x64. Thank you..
