### ISSUE TITLE
Autocomplete does not work in a dialog launched from a macro

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#576]
### Far Manager version

3.0.6071.0 x64

### OS version

10.0.22623.1037

### Steps to reproduce

1. Extract `Panel.AutocompleteTest.lua` from the attached archive [Panel.AutocompleteTest.zip](https://github.com/FarGroup/FarManager/files/10258959/Panel.AutocompleteTest.zip)
2. Copy `Panel.AutocompleteTest.lua` to `%FARPROFILE%\Macros\scripts` directory
3. Reload macros using `macro:load` or restart Far
4. Press `Ctrl + /` hotkey from a panel
5. Start typing a path in the edit control

### Macro Code
```lua
-- Autocomplete Test
-- Rohitab Batra <rohitab@rohitab.com>

-- Dialog Ids
local DIALOG_GUID = win.Uuid("8B662783-DCA0-44C7-9F80-E06D5AF29143")

-- Initialization
local F = far.Flags

local Items = {
-- Idx    1                2  3    4  5     6     7        8     9                                                         10          11           12
-- Idx    Type             X1 Y1   X2 Y2    Sel   Hist     Mask  Flags                                                     Data        MaxLength    UserData
--[[1]] { F.DI_DOUBLEBOX,   3,1,   76,6,    0,    nil,     nil,  0,                                                        "Autocomplete Test"                   },
--[[2]] { F.DI_TEXT,        5,2,   25,2,    0,    nil,     nil,  0,                                                        "&Path:"                              },
--[[3]] { F.DI_EDIT,        5,3,   74,3,    0,    "Copy",  nil,  bor(F.DIF_HISTORY, F.DIF_USELASTHISTORY, F.DIF_EDITPATH), nil                                   },
--[[4]] { F.DI_TEXT,       -1,4,    0,0,    0,    nil,     nil,  F.DIF_SEPARATOR,                                          nil                                   },
--[[5]] { F.DI_BUTTON,      0,5,    0,0,    0,    nil,     nil,  F.DIF_DEFAULTBUTTON + F.DIF_CENTERGROUP,                  "Ok"                                  },
--[[6]] { F.DI_BUTTON,      0,5,    0,0,    0,    nil,     nil,  F.DIF_CENTERGROUP,                                        "Cancel"                              },
}

-- Property Indexes
local IDX_DATA = 10

-- Item Indexes
local IDX_EDIT_PATH = 3
local IDX_BUTTON_OK = 5

function TestAutoComplete()
    Items[IDX_EDIT_PATH][IDX_DATA] = nil
    if far.Dialog(DIALOG_GUID, -1, -1, 80, 8, nil, Items) == IDX_BUTTON_OK then
        far.Show(Items[IDX_EDIT_PATH][IDX_DATA])
    end
end

if _filename ~= nil then
    return TestAutoComplete()
end

Macro {
    area = "Shell";
    key = "Ctrl/";
    description = "Autocomplete Test";
    action = function()
        TestAutoComplete()
    end;
}
```

### Expected behavior

Path and environment variables should autocomplete.

### Actual behavior

Autocomplete does not work for paths or environment variables

If you run `lua:@%FARPROFILE%\Macros\scripts\Panel.AutocompleteTest.lua` the behavior is the same.
However, if you run `luas:@%FARPROFILE%\Macros\scripts\Panel.AutocompleteTest.lua` autocomplete works as expected for both paths and environment variables.
Note the `lua` vs. `luas` in the two commands above.

**Comment by alabuzhev** [comment]
> Autocomplete does not work in a dialog launched from a macro

It was a deliberate design decision:

https://github.com/FarGroup/FarManager/blob/80c21d4579499871f3303917b690cf2b250fb8b9/far/editcontrol.cpp#L399

Motivation: in general, you want macros to be deterministic. For example, if a macro puts some text into an edit control (e.g. the current date), you probably want a predictable result every time. Autocompleting such text with context-dependent options like filesystem objects, environment strings etc. would've been anything but predictable, both during recording and playing the macro. On top of that, macros were much simpler back in the day and situations like "user is working with the UI while a macro is playing" were way less common.

Thinking of it, if playing a macro reached a state when we interactively process the actual user input, it is probably safe to allow autocompletion. @shmuz, perchance you know a way to recognize it?

**Comment by shmuz** [comment]
I don't have much experience in autocompletion since it's always OFF in my Far configuration.
But I suppose if a plugin runs a modal dialog (as in the above example) then the autocompletion may be safely enabled no matter if this is a macro or not. And Far knows if the dialog was started by the plugin (the 1-st parameter of `DialogInit` is `PluginId`).

**Comment by alabuzhev** [comment]
Would it be safe to assume that any dialog with PluginId == LuamacroId is interactive?

**Comment by shmuz** [comment]
1. I think yes.
2. There is also the `InputBox` function that behaves the same with regards to autocompletion. And as far as I can see Far Manager happily accepts any GUID passed as its 1-st parameter,

**Comment by alabuzhev** [comment]
6074

**Comment by rohitab** [comment]
Nice! I just tested with version `3.0.6074.0 x64` and it's working. Thank you.
