### ISSUE TITLE
Potential Bugs in Viewer Search

### ISSUE THREAD

**Issue by MKadaner** [FarGroup/FarManager#581]
For whatever reasons, I am looking closely at [`Viewer::search_text_forward`](https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2768), particularly at the use of `wchar_t *t_buff` which seems to point to the copy of the characters read into the main buffer `buff`. Both copies are initially populated by [`int nw = vread(buff, nb, t_buff);`](https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2794). Then, if `swrap == SearchWrap_CYCLE` (and some other conditions), we append to both buffers a few more characters
```
int nw1 = vread(buff+nw, 3*(slen+ww), t_buff ? t_buff+nw : nullptr);
```
and adjust the end file offset `to1` accordingly:
```
to1 = to + (t_buff ? GetStrBytesNum(t_buff, static_cast<size_t>(nw1)) : sd->ch_size * nw1);
```
I presume that `nw1` above is the (adjusted) append size. If so, it looks like we get the byte count of the short string at beginning of the buffer, not of the appended string, which starts at `t_buff+nw` (before `nw` was adjusted by the appended size). Is it expected?

Next question is about [`nw1 = std::max(nw1, slen+ww-1);`](https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2799). Should it be `std::min`?

One more concern is about preparing [the next search position](https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2840) at the end of the function:
```
sd->CurPos = to1 - GetStrBytesNum(t_buff + iLast + 1, static_cast<size_t>(nw - iLast - 1));
```
Here `t_buff` is used unconditionally, even though it can be `nullptr`, which seems to happen if a fixed-width encoding is used.

From the very cursory glance, `Viewer::search_text_backward` may have similar issues, just like other `Viewer::search...` functions.

**Comment by alabuzhev** [comment]
The code is somewhat... convoluted there, as well as in the rest of Viewer.
I cannot say much without diving deep into it.


> `t_buff` is used unconditionally, even though it can be `nullptr`

I stumbled upon this one some time ago. It looks suspicious indeed, but apparently doesn't crash because here:
https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2771
it is initialized when ch_size < 0, and here:
https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2397-L2399
GetStrBytesNum returns early if ch_size > 0, before dereferencing the pointer.

You are very welcome to untangle this yarn if you like.
I'd start from renaming nb, nw, nb1, nw1, cpos, bsize, slen, ww, buff, t_buff to something human-readable.

**Comment by MKadaner** [comment]
> GetStrBytesNum returns early if ch_size > 0, before dereferencing the pointer.

Yeah! I've seen this. True, assuming `getCharSize()` is equivalent to `sd->ch_size`. I bet it is, but it's far from being obvious. Moreover, somebody clearly did not think it safe to call `GetStrBytesNum` with `nullptr` [here](https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2801):
```C++
to1 = to + (t_buff ? GetStrBytesNum(t_buff, static_cast<size_t>(nw1)) : sd->ch_size * nw1);
```
(BTW, how do you create these nice code panels? I could not find them in GFM examples or spec.)

> You are very welcome to untangle this yarn if you like.

Maybe later. For now, I am concentrating on unifying Viewer search with Editor/Help/Find files.

> I'd start from renaming nb, nw, nb1, nw1, cpos, bsize, slen, ww, buff, t_buff to something human-readable.

After several hours of staring at [`Viewer::search_text_forward`](https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2768), I think these identifiers are perfectly mnemonic. 🤣

P.S. I'd appreciate if you could validate my first two suspicions (about adjusting the end file offset and the use of `std::max`). If I did not miss something, these are subtle bugs though very unlikely to affect the behavior in a visible way.

**Comment by MKadaner** [comment]
Possible bugs aside, could you please help me understand why we need `t_buff` at all. It looks like its sole use is here

https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2840

The purpose is to calculate the (file) position to continue search at relative to the end of the current search region (`to1`). Why do we need the copy here? Why cannot we calculate the byte length of the buffer overlap using the original buffer? Is it because we modify the buffer if the search is case insensitive:

https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2805-L2806

Is there an encoding in which byte length of a lowercase string is different from byte length of the corresponding uppercase strings?

**Comment by w17** [comment]
Я поучаствую, поскольку обсуждаемый код большей частью мой (где-то 2011-2012 года).
Про баг-небаг посмотрю позже, надо всиотреть код (пока не думаю что баг, но и не исключаю).

Про t_buff Алекс почти угадал. Нужен он действительно для корректного обратного перехода от буфера отображения (экрана) к позиции в файле. И причина в возможном 'искажении' данных в буфере отображения.  Но данные в t_buff не обязаны быть оригинальными, достаточно чтобы их длина при обратном преобразовании соответствовала оригиналу. Case преобразовагие для UTF-8 не рассматривалось как источник проблемы. И мне неизвестны случаи когда оно меняет длину utf-8 послеловательности (хотя зуб не дам и так ли всё хорошо с появившейся позже utf-7 не изучал). Изначально он потребовался поскольку в первой версии преобразовагия UTF-8 => UCS-2 я заменял некорректные UTF-8 коды на код заменитель (видимо \xFFFD, сейчас это encoding::replace_char), длина которого точно больше оригинала. Но потом, насколько я помню, это переделали на некорректные коды из суррогатной области (D8..DF xx) и воможно длина при обратном преобразовании уже сохраняется. Так что нужность этого буфера - открытый вопрос.

**Comment by w17** [comment]
Похоже оба подозрения правильные, оэто баг. Должно быть примерно так:
		nw1 = std::**min**(nw1, slen+ww-1);
		nw += nw1;
		to1 = to + (t_buff ? GetStrBytesNum(t_buff**+nw**, static_cast<size_t>(nw1)) : sd->ch_size * nw1);

**Comment by MKadaner** [comment]
Спасибо за помощь и объяснения, @w17. Я сделал PR с багфиксом. Мне надо будет разобраться подробнее с тем, что на самом деле делает `vread`, но это позже. Похоже, что я могу "просто" вставить вызов `SearchString` вместо рукописного поиска, что будет полезно как с точки зрения унификации кода, так и с точки зрения добавления нестрогого поиска во Viewer.

**Comment by MKadaner** [comment]
@w17, посмотри, пожалуйста ещё одну вещь:

<https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2804>

Здесь `slen` (`= sd->search_len`) имеет размерность байт (в файле), а `nw` имеет размерность символов (в строке). Одно вычитается из другого для вычисления `iLast`, который, судя по использованию, имеет размерность символов. Не должнó ли использовать здесь `sd->search_text.size()` вместо `slen`? А также здесь:

<https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L2823>

**Comment by w17** [comment]
Есть популярное заблуждение, будто поbск viewer-a ищет байты в файле.
На самом деле это так только при hex-поиске, в остальных случаях поиск идет (как в редакторе) в текстовом представлении файла согласно текущей кодовой странице.
Объяснение моно посмотреть в недавнем gh-573.

**Comment by w17** [comment]
vread() как раз получает данные в виде юникодного текста, насколько помнню, с _текущей позиции_  (байтовой).
продвигает позицию, конвертирует, + какая-то буферизация....

**Comment by w17** [comment]
Всё это к вопросу о размерности, ну присвоение перед поиском: <https://github.com/FarGroup/FarManager/blob/08b581622da20bc0b139c048a77f2c1a264c84de/far/viewer.cpp#L3230-L3238>

**Comment by w17** [comment]
А 'здесь' 'и здесь' это длина в байтах того что найдено (результат поиска).
Не лучшие практики, не буду спорить, но как есть....

**Comment by MKadaner** [comment]
@w17: Спасибо за помощь, Владимир. Я сейчас копаюсь в этом месте с целью унифицировать поиск с редактором, и мне важно быть уверенным, что я понимаю код правильно, даже если он не идеален. Если удастся, я что-то подправлю по ходу дела. И да, я прекрасно вижу, что поиск происходит в декодированном тексте, а не в байтах в файле.

Спасибо за ревью. Идиотский баг. Я исправил. подпишите, пожалуйста.
