### ISSUE TITLE
Submenus with keyboard accelerators display ampersand character in title

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#583]
### Far Manager version

3.0.6075.0 x64

### OS version

10.0.22623.1037

### Steps to reproduce

1. Press `F2` to show _User menu_
2. Press `Ins` and select _Insert menu_ when prompted
3. For the _Label_, type in `Example &Title`
4. Press `OK` to complete insertion
5. The newly added submenu should now be visible, along with the keyboard accelerator `T`
6. Press `Enter` to go into the submenu

### Expected behavior

Title should display `Main menu (User) » Example Title`

### Actual behavior

Title displays `Main menu (User) » Example &Title`. Note the ampersand `&` character before `Title`

Similarly, if you add a submenu with label `Example Title && Text`, the menu displays `Example Title & Text`, which is correct. However, if you enter the submenu, the title displays `Main menu (User) » Example Title && Text`.

**Comment by alabuzhev** [comment]
6087

**Comment by rohitab** [comment]
Tested version `3.0.6087.0 x64`. It's fixed. Thank you.
