### ISSUE TITLE
How to set focus on an Edit control when Radio button's hotkey is pressed?

### ISSUE THREAD

**Issue by MKadaner** [FarGroup/FarManager#585]
I am adding Text/Hex Radio to [Find File dialog](https://github.com/MKadaner/FarManager/blob/408c9f8ae158b21691a9f741fc70fc308791c5d8/far/findfile.cpp#L715). I want to set focus on the Text/Hex Edit box when a Text/Hex Radio _hotkey_ is pressed, but _not_ when the Radio button itself is pressed.

I can see how it's [done now](https://github.com/FarGroup/FarManager/blob/d8097d0d404501c8491a92be89dbc49c00300e0a/far/findfile.cpp#L981-L987). It does not work in my case because `FAD_TEXT_TEXTHEX` is not an active control. If I do the same with [`FAD_RADIO_TEXT` / `FAD_RADIO_HEX`](https://github.com/MKadaner/FarManager/blob/408c9f8ae158b21691a9f741fc70fc308791c5d8/far/findfile.cpp#L988-L994), either the button is not "clicked" if I return `TRUE`, or the focus stays on the Radio if I return `FALSE`. I kinda understand why it happens. I believe If I were using `PostMessage` instead of `SendMessage`, it would work, but there is no `PostMessage`.

I also can see how it's done in Viewer Search dialog, using the "need focus" flag. It feels rather awkward.

So, what is the right technique to intercept a button's hotkey, and have the system to set focus on a certain _unrelated_ control _after_ the button's main handler completed?

Thank you in advance.
Happy New Year!

**Comment by alabuzhev** [comment]
> I can see how it's [done now](https://github.com/FarGroup/FarManager/blob/d8097d0d404501c8491a92be89dbc49c00300e0a/far/findfile.cpp#L981-L987)

That's a different scenario - that block tries to set focus to one of the overlapped edit controls when the corresponding label hotkey is pressed, and labels can't be in focus. And that is why it is completely redundant - the dialog engine does all that internally - if you try to focus an non-focusable item, the focus will go to the next focusable item automatically. We should remove the whole thing.


> I want to set focus on the Text/Hex Edit box when a Text/Hex Radio _hotkey_ is pressed, but _not_ when the Radio button itself is pressed.

Maybe just... don't? At least initially / by default?
Moving the focus from the activated controls elsewhere is a rather unorthodox feature, albeit, probably, a convenient too. We do have something like this in Viewer indeed, but it is off by default and probably not too many people know about it.

For a strategic solution we might introduce a new dialog item flag, DN_HOTKEYNOFOCUS, applicable to check boxes, buttons and radio buttons: "when set, pressing a hotkey moves the focus to the item, activates it, and then moves the focus back where it was".

**Comment by MKadaner** [comment]
Thank you for fixing tab order in the Viewer Search dialog, which I screwed up.

Yup! On master, the focus in Find File works without handling `DN_HOTKEY`, even though there are two textboxes (one is always hidden), which makes sense. OK here.

The actual problem I tried to solve was hotkey assignment. Consider
```
Containing  (•) &Text  ( ) &Hex
```
Here, it is very desirable to keep `T` and `H` hotkeys assigned to the radio buttons. Now, all letters in `Containing` are already taken by other controls on the dialog. And this is only one language. I thought that it would be neat if radio buttons' hotkeys will double as the hotkey for the editors. An alternative I considered was to say `Containing&:` with hotkey `:`. That would also work for all languages but is unusual.

What do you think?

**Comment by alabuzhev** [comment]
Ah, I see what you mean, an unfortunate situation indeed.

> So, what is the right technique to intercept a button's hotkey, and have the system to set focus on a certain _unrelated_ control _after_ the button's main handler completed?

The best I can think of is:
- In a DN_HOTKEY handler, set a flag when a hotkey has been sent to the control of interest and clear otherwise; allow it to proceed as usual.
- In a DN_BTNCLICK handler, query the flag: if it is set, then this particular DN_BTNCLICK has been caused by DN_HOTKEY and happened right after it, so we can move the focus. If it is not set, it has been caused by some other means, so leave the focus as is.

<details>
<summary>An example for the viewer dialog</summary>

```DIFF
--- a/far/viewer.cpp
+++ b/far/viewer.cpp
@@ -2478,6 +2478,8 @@ struct ViewerDialogData
 	bool recursive;
 };
 
+static bool RadioTextHexHotkeyPressed = false;
+
 intptr_t Viewer::ViewerSearchDlgProc(Dialog* Dlg,intptr_t Msg,intptr_t Param1,void* Param2)
 {
 	switch (Msg)
@@ -2554,6 +2556,9 @@ intptr_t Viewer::ViewerSearchDlgProc(Dialog* Dlg,intptr_t Msg,intptr_t Param1,vo
 						Dlg->SendMessage(DM_EDITUNCHANGEDFLAG, sd_dst, ToPtr(changed));
 					}
 
+					if (RadioTextHexHotkeyPressed && Param2)
+						Dlg->SendMessage(DM_SETFOCUS, new_hex? SD_EDIT_HEX : SD_EDIT_TEXT, nullptr);
+
 					Data.hex_mode = new_hex;
 					if (!Data.edit_autofocus)
 						return TRUE;
@@ -2584,6 +2589,11 @@ intptr_t Viewer::ViewerSearchDlgProc(Dialog* Dlg,intptr_t Msg,intptr_t Param1,vo
 			else
 				break;
 		}
+
+		case DN_HOTKEY:
+			RadioTextHexHotkeyPressed = Param1 == SD_RADIO_TEXT || Param1 == SD_RADIO_HEX;
+			return TRUE;
+
 		case DN_DRAWDIALOGDONE:
 		{
 			if (const auto FirstChar = view_as<const Manager::Key*>(Dlg->SendMessage(DM_SETDLGDATA, 0, nullptr)))
```
</details>

**Comment by MKadaner** [comment]
Thanks. I did exactly that, except for I used `FAD_TEXT_CONTAINING`'s user data to hold the flag. Using a static flag feels wrong because the dialog is an instance, though of course there will never be more than one instantiated at a time.

I'll publish PR in a few minutes.

**Comment by alabuzhev** [comment]
> Using a static flag feels wrong

Of course - it is just for demonstration purposes, don't try this at home :)

**Comment by MKadaner** [comment]
Power outage here; it'll take more time.

**Comment by MKadaner** [comment]
I am about to unify Viewer Search dialog with the `GetSearchReplaceString` in stddlg.

> We do have something like this in Viewer indeed, but it is off by default and probably not too many people know about it.

Should I implement this interesting feature in stddlg while adding optional Hex controls? If so, do you want me to implement `DIF_HOTKEYNOFOCUS` you proposed?

Re: `DIF_HOTKEYNOFOCUS`. I think the description should be slightly different:

> When set, pressing a hotkey moves the focus to the item, activates it, and then moves the focus _to the specified control._

(Not that I know how to specify the associated control when setting `DIF_HOTKEYNOFOCUS`; maybe assign control ID to user's data?)

P.S. May I ask you what time zone you operate in?

**Comment by alabuzhev** [comment]
> Should I implement this interesting feature in stddlg while adding optional Hex controls?

Up to you. I don't use it so I don't really care.
However, having a peculiar behavior in one specific dialog only is not a good thing. It should be everywhere or nowhere.
Personally I would not reimplement it in stddlg and drop the whole thing *for now*. We can discuss and implement a generic solution later.
In the meantime, people who can't live without it can easily customize the viewer dialog behavior with a lua script.

> do you want me to implement `DIF_HOTKEYNOFOCUS` you proposed?

Up to you, but see the previous answer. To keep things simple I would prefer unifying the dialogs first and implementing extra features (with or without new APIs) separately.
Come to think of it, we can even make it the default behavior for checkboxes and radio buttons, because why not.

> Not that I know how to specify the associated control

And that is why I formulated it as is :) It is easier to implement and should cover most of the use cases.
Consider, for example, the Replace dialog:
```
╔═════════════════════════════ Replace ══════════════════════════════╗
║ Search for                                  [ Word ] [ Selection ] ║
║ __________________________________________________________________↓║
║ Replace with                                                       ║
║ __________________________________________________________________↓║
╟────────────────────────────────────────────────────────────────────╢
║ [ ] Case sensitive                 [ ] Regular expressions         ║
║ [ ] Whole words                    [ ] Fuzzy search                ║
║ [ ] Reverse search                 [ ] Preserve style              ║
╟────────────────────────────────────────────────────────────────────╢
║                       { Replace } [ Cancel ]                       ║
╚════════════════════════════════════════════════════════════════════╝
```
What shall *the specified control* be - search or replace?
If I enter the search string, move down and start entering the replace string, realize that I want it to be case sensitive and press Alt+C immediately before I forget about it, I probably won't be happy with the focus jumping back to the search field, and vice versa.
While with the "There and Back Again" approach I can be anywhere and will never end up in an unexpected location after pressing a hotkey.

> May I ask what time zone you operate in?

+0, you can find it in the changelog.

**Comment by MKadaner** [comment]
I'll happily leave auto-move focus feature out. I do not use it either and do not feel it useful in general. An unusual focus behavior just breaks muscle memory in keyboard users without adding much to good hotkey assignments. Besides, this

> What shall _the specified control_ be - search or replace?

is a very good point.

> +0, you can find it in the changelog.

Thanks. I've seen it. Kinda thought that "+0" might be a rephrase of "anywhere in the world" statement. :)

**Comment by MKadaner** [comment]
For the Hex controls on the unified Search dialog, I think hotkeys should be the same as on Find File dialog for consistency, even though it should be possible to assign individual hotkeys to all three `Search for`, `Text`, and `Hex` labels. Any objections?

**Comment by alabuzhev** [comment]
Sounds reasonable.
