### ISSUE TITLE
Environment variables not expanded when editing links

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#587]
### Far Manager version

3.0.6079.0 x64

### OS version

10.0.22623.1037

### Steps to reproduce

1. Go to a directory, say `%TEMP%`
2. Press `F7` to create a new directory named `SourceDirectory`
3. Press `Alt+F6` on the `SourceDirectory` to open the _Link_ dialog
4. Type in `TestJunction`
5. Make sure _Link type_ is set to _directory junction_
6. Press `Enter` to create the link
7. Select `TestJunction` from the panel and press `F4` to edit
8. Change the value of _Junction_ to `%APPDATA%`
9. Press `Enter` to close the dialog
10. Press `F4` again to edit

### Expected behavior

The _Junction_ should be set to `C:\Users\rohitab\AppData\Roaming`

### Actual behavior

The _Junction_ is set to `C:\Users\rohitab\AppData\Local\Temp\%APPDATA%`. The `%APPDATA%` environment variable is not expanded but instead added to the current directory path. Pressing `Enter` on the edited link displays an error since the target is invalid.

Similarly, if you create a _symbolic link_ instead of a _directory junction_, and follow the same steps above, and set _Symlink_ to `%APPDATA%`, the value is set to `%APPDATA%` instead of the expanded value `C:\Users\rohitab\AppData\Roaming`.

If you enter an environment variable while creating the link, it is expanded. If you create a link using the _Make folder_ dialog and set the _Target_ to an environment variable, it is expanded as well. The issue is only with editing the link. In all cases, auto-completion of environment variables is active.

Also, the keyboard accelerator for _Symlink_ is missing in the _Attributes_ dialog that pops up when you edit the link.

One last thing. In the _Link_ dialog for creating links using `Alt+F6`, what is the _Filter_ used for?

**Comment by alabuzhev** [comment]
Ok, I can't see why not. 6080.

> what is the Filter used for?

Alt+F6 allows to create hard links recursively.

**Comment by rohitab** [comment]
That was quick! The issue is now resolved. I just tested version `3.0.6082.0 x64`.

Thanks for the information about hard links. You might want to consider disabling the _Use filter_ checkbox if the _Link type_ is anything other than _hard link_. This would be consistent with the _Link_ dialog that opens when you press `Alt+F6` on a file.

It might also be good to remove _directory junction_ and _symbolic link (folder)_ from the _Link type_ dropdown when creating links to files, and remove _symbolic link (file)_ when creating links to directories.

**Comment by alabuzhev** [comment]
> It might also be good to remove _directory junction_ and _symbolic link (folder)_ from the _Link type_ dropdown when creating links to files, and remove _symbolic link (file)_ when creating links to directories.

We used to do that decades ago, in 2k/XP times - the dialog tried to be smart and prohibit junctions to files, network paths etc. Then MS introduced symlinks in Vista without such restrictions and to accommodate that we would've needed to complicate the logic even further. It was easier to drop the whole thing and not make assumptions about what is possible and what isn't, what makes sense and what doesn't.

**Comment by rohitab** [comment]
Makes sense. Thanks for taking the time to explain.
