### ISSUE TITLE
Default code page problem

### ISSUE THREAD

**Issue by skipik** [FarGroup/FarManager#588]
### Far Manager version

3.0.6079.0

### OS version

10.0.22621.963

### Other software

Additional info:
1. http://forum.ru-board.com/topic.cgi?forum=5&topic=51024&start=540#10
2. https://foto.sp-shopogoliki.ru/images/2023/01/m31b1nex5fqcp36fp5st.png
3. http://forum.ru-board.com/topic.cgi?forum=5&topic=51024&start=540#11

### Steps to reproduce

1. Set EditorDefaultCodePage to 65001
2. Shift+F4 -> test.txt

### Expected behavior

Code page should be 65001

### Actual behavior

Code page is ANSI

**Comment by alabuzhev** [comment]
6081
