### ISSUE TITLE
Не работает Backspace в командной строке

### ISSUE THREAD

**Issue by Sublihim** [FarGroup/FarManager#59]
Far 3.0 Build 5252

Не работает клавиша Backspace в командной строке.
Если ввести что-либо в командной строке, то уже невозможно ничего удалить. (Если обе панели видимы)
Если же закрыть панели по Ctrl+O, то Backspace просто возвращается на начальную позицию, но ничего не стирает.

**Comment by Sublihim** [comment]
Нет, не макрос. Просто в процессе работы. Если я наберу что-то в командной строке под панелями, то стереть это уже затруднительно

**Comment by shmuz** [comment]
1. Попробуйте без макросов и плагинов. Запустите Фар командой `far /p` и проверьте ещё раз.
2. Попробуйте с другими билдами Фар, например 3.0.5000.

**Comment by Sublihim** [comment]
Все, разобрался. Действительно макрос в LuaMacro
```
Macro {
  description="";
  area="Shell"; key="BS";
  flags="";
  code="Keys(\"Home\")";
}
```
Спасибо! Проблема решена!
