### ISSUE TITLE
Duplicate keyboard accelerators in Sort modes

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#591]
### Far Manager version

3.0.6083.0 x64

### OS version

10.0.22623.1037

### Steps to reproduce

Press `Ctrl+F12` in a Panel to open _Sort modes_

### Expected behavior

Items should have unique keyboard accelerators

### Actual behavior

The following items have duplicate keyboard accelerators:
1. _Change time_ and _Use sort groups_ both use `g`
2.  _Write time_ and _Show directories first_ both use `w`

**Comment by alabuzhev** [comment]
6086

**Comment by rohitab** [comment]
Tested version `3.0.6087.0 x64`. It's fixed. Thank you.
