### ISSUE TITLE
Find file dialog clears search text on keyboard accelerator

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#592]
### Far Manager version

3.0.6083.0 x64

### OS version

10.0.22623.1037

### Steps to reproduce

1. Press `Alt+F7` in a Panel to open the _Find file_ dialog
2. Make sure the _Text_ box contains the last entered search text from history
3. Press `Alt+t` to switch focus to the _Text_ box

### Expected behavior

Focus shifts to the _Text_ box, and previous search text remains

### Actual behavior

Focus shifts to _Text_ box, but the previous search text is removed. If you want to modify the text, you have to type it in again. Note that using the `Tab` key or mouse to switch focus, does not remove the text, which is the correct behavior.

The same thing happens with the _Hex_ control as well. If you had previously searched for hex, and you open the dialog and press `Alt+h`, the hex control is cleared.

Regarding the new layout -- previously, you could type in the file mask, then press `Tab` (or the down arrow) and type in the search text. Now, you have to press `Tab` twice (or the down arrow thrice) to get to the text control. The radio buttons for _Text_ and _Hex_ are probably not used as frequently as the search text box. Would it be possible to change the tab order so that pressing `Tab` from the file mask control, moves focus to the search text control, like before?

**Comment by MKadaner** [comment]
For tab order, see #590. I'll look at the disappearing last search text.

**Comment by alabuzhev** [comment]
@MKadaner I've already looked into disappearing text, no worries.

**Comment by MKadaner** [comment]
@alabuzhev I have disappearing text ready. Looks nice and simple. Will you accept it?

**Comment by alabuzhev** [comment]
@MKadaner Of course, thank you.

**Comment by MKadaner** [comment]
Both issues should be fixed in 6086.

**Comment by rohitab** [comment]
Perfect! I tested version `3.0.6087.0 x64`. Both issues are fixed. Thank you.
