### ISSUE TITLE
List of selected files doesn't work

### ISSUE THREAD

**Issue by bitraid** [FarGroup/FarManager#60]
The "list of selected files" (`!&`) and "list of selected sort file names" (`!&~`) has stopped working after b4ae95e.

Steps to reproduce:
*Select some files
*Press <kbd>Ctrl</kbd>+<kbd>g</kbd>
*Type `echo !&`
*Press <kbd>Enter</kbd>

**Comment by alabuzhev** [comment]
Fixed in 97f5dea27.
