### ISSUE TITLE
Process list plugin randomly switches selection to other processes with the same name

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#603]
### Far Manager version

3.0.6090.0 x64

### OS version

10.0.22623.1095

### Steps to reproduce

1. Open the _Process list_ plugin panel. You can do this by running `plist:`
2. Press `Ctrl+F3` to sort by _Name_
3. Go to any process that has multiple instances running, say `svchost.exe`
4. Press `Ins` key to select the process

### Expected behavior

Process is selected.

### Actual behavior

Process is selected. However, almost immediately, the selection switches to another process with the same name `svchost.exe`, but with a different PID. This keeps happening in a continuous loop. If you don't see this behavior, please try selecting another instance of the process, or try another process with multiple instances.

**Comment by alabuzhev** [comment]
This one is a hairy problem, sort of, due to bad design decisions of the past.
Preserving selection on panel refresh is name-based, but names are not necessarily unique on plugin panels.

6092, to some extent.

**Comment by rohitab** [comment]
I just tested version `3.0.6092.0 x64`. The issue is fixed.

If it happens to fail occasionally, that's fine. Your comment above should help people understand the reason.
