### ISSUE TITLE
Process list plugin does not synchronize sort modes menu with sort order

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#604]
### Far Manager version

3.0.6090.0 x64

### OS version

10.0.22623.1095

### Steps to reproduce

1. Open the _Process list_ plugin panel. You can do this by running `plist:`
2. Press `Ctrl+F12` to open _Sort modes_
3. Select _Name_ and press `Enter` to sort by _Name_
4. Press `Ctrl+F4` to sort by _Extension_
5. Note that the _sort mode letter_ in the upper left-hand corner of the panel is displaying `x`
6. Press `Ctrl+F12` to reopen _Sort modes_

### Expected behavior

_Extension_ should be selected since the panel is sorted by extension, as indicated by the `x` sort mode letter.

### Actual behavior

_Name_ is selected instead of _Extension_.

There are a few other issues related to _Sort modes_:

**Reverse sort**
Make sure that _Allow reverse sort modes_ in _Panel settings_ is checked. Press `Ctrl+F12` to open _Sort modes_, and select an item that is already selected. The sort order should be reversed, i.e. from ascending to descending and vice versa. However, this only happens if the sort order was previously ascending.

**Show selected first**
You can use `Shift+F12` hotkey to enable the _Show selected first_ option in the panel. However, this option is not displayed under _Sort modes_, like in regular panels.

**Multiple Sort mode menus**
If you select _Sort modes_ from the main menu, or press `Ctrl+F12`, a customized version of _Sort modes_ is displayed. However, if you right-click on the sort mode letter, the standard _Sort modes_ menu is displayed instead. These menus are not synchronized either. For example, if you press `Ctrl+F12` and select _PID_, then right-click the sort mode letter, you'll see that _Change time_ is selected. If you now press `Enter` on _Change time_, the _PID_ sort order will be reversed.

**Comment by alabuzhev** [comment]
> Name is selected instead of Extension.
> Reverse sort

206.

> Show selected first

Unfortunately Far does not have an API to toggle "selected first" (or at least I can't find one).
I'm not saying it can't be added in the future, but probably better under a separate issue.

> Multiple Sort mode menus

Far does not provide a way to customize the sort menu so the plugin intercepts Ctrl+F12 and shows its own, but it does not prevent the user from invoking the standard menu in some other ways, e.g. via a right-click on the sort mode letter.
Technically it should be possible to do so, by intercepting mouse input and trying to figure out what exactly has been clicked, but that would be more complex and I'm not sure it's worth the effort.

**Comment by rohitab** [comment]
I just tested _Far_ version `3.0.6092.0 x64` with _Process list_ build `206`. The _Reverse sort_ issue is fixed. However, the issue where _Name is selected instead of Extension_ is still present.

Thanks for the info. I will create a separate issue for _Show selected first_, so it stays logged in an open ticket.

**Comment by alabuzhev** [comment]
> Name is selected instead of Extension is still present

I misread you and thought it's about the cursor position in the menu, which was also wrong.

207.

**Comment by rohitab** [comment]
No worries. I just tested version `3.0.6093.0 x64`. The issue is fixed. Thank you.
