### ISSUE TITLE
Regexp replace: quantifier applied to a group empties its matched text

### ISSUE THREAD

**Issue by HamRusTal** [FarGroup/FarManager#609]
### Far Manager version

3.0.6092.0

### OS version

10.0.19044.2486

### Steps to reproduce

**1.** Start editing an empty (e.g. new) file in a “vanilla” Far:
    `far.exe -ro -p -s "%TEMP%\FarProfile\%RANDOM%" -e "%TEMP%\BrandNewFile"`.
**2.** Type `88`, jump to the the text beginning.
**3.** Replace `(8)+` by `$1` with regular expressions.

### Expected behavior

One replacement should happen and the text should become `8`

### Actual behavior

One replacement happens but the text becomes empty

**Comment by HamRusTal** [comment]
https://regex101.com/ make a valuable note:
> A repeated capturing group will only capture the last iteration.

**Comment by HamRusTal** [comment]
Regression:
b6013 — good
b6018 — bad

So it's most likely b6018 that introduced the bug:
```
drkns 04.09.2022 18:26:41 +0100 - build 6018

1. 0003336: Regex \{(.)?\} finds } in {}.
```

**Comment by alabuzhev** [comment]
@shmuz any suggestions?

**Comment by shmuz** [comment]
@alabuzhev 
> A repeated capturing group will only capture the last iteration.

This is true AFAIK.
As `(8)+` is greedy `88` must be found and should be replaced by the last-iteration capture, i.e. `8`.

If you check this with plugin LF Search on last Far builds you'll see that Oniguruma, PCRE and PCRE2 behave identically (and differently from FAR regexp).

**Comment by shmuz** [comment]
In far2l `88` is replaced by 8

But in far2l this
> `1. 0003336: Regex \{(.)?\} finds } in {}`
works incorrectly. Will have to check it.

**Comment by shmuz** [comment]
@alabuzhev If you (by chance) want to compare with far2l sources then see it in **my fork**, i.e. https://github.com/shmuz/far2l/blob/master/far2l/src/mix/RegExp.cpp

**Comment by alabuzhev** [comment]
@shmuz I can compare it if you are sure that it actually works in your fork after the fix for M3336.

**Comment by shmuz** [comment]
Sorry I probably made much noise.
I've just rechecked it thoroughly. It is the same as on Far3: correct on the old version and incorrect on the current one.

**Comment by shmuz** [comment]
@alabuzhev 
See my commit https://github.com/shmuz/far2l/commit/4b08fff5d9ba2553c108df8c0e510db52e8da882 (only the change in RefExp.cpp is relevant).
I'm not very sure in this "fix" but chose to go that way.

**Comment by alabuzhev** [comment]
@shmuz thanks, 6094.

**Comment by HamRusTal** [comment]
Thank you!
