### ISSUE TITLE
Editor Replace Button Hotkey

### ISSUE THREAD

**Issue by alabuzhev** [FarGroup/FarManager#618]
### Discussed in https://github.com/FarGroup/FarManager/discussions/616

<div type='discussions-op-text'>

<sup>Originally posted by **rohitab** January 27, 2023</sup>
Most dialogs in _Far_ do not have hotkeys for the default button, since you can just press `Enter`. For example, in the _Search_ dialog in Viewer/Editor/Help, the _Search_ button does not have a hotkey. However, in the _Replace_ dialog in the Editor, the _Replace_ button has an `Alt+R` hotkey.

What do you think about removing the hotkey from the _Replace_ button and assigning `Alt+R` to the _Replace with_ edit control instead? It seems natural to me, to use `Alt+S` and `Alt+R` to switch between _Search_ and _Replace_ with boxes. It might inconvenience people that are accustomed to using the `Alt+R`/`Alt+E` hotkeys though.

> [MKadaner](https://github.com/MKadaner): I also noticed this discrepancy. I think this is a good idea. The decision is mostly for the language maintainers, except for there is no dedicated maintainer for English localization.</div>

**Comment by HamRusTal** [comment]
I have R assigned to “Replace with” locally for years, so I'm both hands for this.
Also, I assigned E to “Regular expressions” so that I don't need to use both hands to toggle it (doing it «одной левой»).
```
// For builds after 6095
MSearchReplaceReplaceWith = "&Replace with"
MSearchReplaceRegexp = "R&egular expressions"
MSearchReplaceReplace = "Replace"
```

**Comment by MKadaner** [comment]
Thank you, @alabuzhev. I did not realize that a discussion cannot be assigned. Sorry for all the hassle. It would be way simpler if you just pushed this change.
