### ISSUE TITLE
Cannot modify the environment variable

### ISSUE THREAD

**Issue by nZeus** [FarGroup/FarManager#62]
Hi,

Cannot set the PATH variable.

1. Run Far (Far Manager, version 3.0 (build 5254) x64)
2. Type `SET PATH += c:\xxx\`
3. Type `ECHO %PATH%`
4. The PATH didn't change.

This didn't help:
`F9 -> Options -> System Settings -> [x] Automatic update of environment variables`

**Comment by alabuzhev** [comment]
> +=

Who taught you this?
It doesn't work this way.
