### ISSUE TITLE
Sporadically Crashes on opening text files with viewer (by F3)

### ISSUE THREAD

**Issue by rukeba** [FarGroup/FarManager#623]
### Far Manager version

3.0.6060.0

### OS version

10.0.22000.1455

### Steps to reproduce

Click F3 to open text file with default viewer. File size does not matter, from a few bytes to megabytes.

### Expected behavior

Expecting to see file content in viewer.

### Actual behavior

Red window with title "Oops" and text:
 > Something went wrong.
 > Please send the bug report to the developers:
 > [path to dump]

**Comment by HamRusTal** [comment]
Does it still cash in the nightly build? The “stable” version is quite old…

**Comment by rukeba** [comment]
> Does it still cash in the nightly build? The “stable” version is quite old…

Ok, i will try.

**Comment by rukeba** [comment]
Error still exists in latest nightly build:

```
Exception: 0xE06D7363 - C++ exception (class far_sqlite_exception)
Details:   [history.db] - SQLite error 11: database disk image is malformed while executing "REPLACE INTO viewerposition_history VALUES (NULL,'D:\production\Log\iismanagerservice\iismanagerservice.log',133195507391646780,0,0,0,-1);"
errno:     0x00000000 - No error
LastError: 0x00000012 - There are no more files.
NTSTATUS:  0x80000006 - {No More Files} No more files were found which match the file specification.
Address:   0x0004441C - KERNELBASE.dll!RaiseException+0x6C
Function:  throw_exception
Source:    sqlitedb.cpp(129)
File:      C:\Program Files\Far Manager\Far.exe
Plugin:    
 
Far:       3.0.6098.0 x64 (833c939)
Compiler:  Microsoft Visual C++, version 19.34.31933.0
PE time:   2023-01-29 16:50:31.000
File time: 2023-01-29 14:50:34.000
OS:        Windows NT Workstation 10.0.22000, 0x100 (Windows 10 Pro, version 21H2, OS build 22000.1455)
Kernel:    10.0.22000.1455 (WinBuild.160101.0800)
Host:      C:\Windows\System32\conhost.exe 10.0.22000.1 (WinBuild.160101.0800)
Parent:    C:\Windows\explorer.exe 10.0.22000.184 (WinBuild.160101.0800)
Command:   "C:\Program Files\Far Manager\Far.exe" 
Uptime:    00:00:14
```

**Comment by alabuzhev** [comment]
> [history.db] - SQLite error 11: database disk image is malformed

That says it all. Rename/move your %farlocalprofile%\history.db, it should fix the crash.
Afterwards you can try recovering the histories using sqlite3.exe or third party tools if you have something valuable there, or just remove the file otherwise.

**Comment by rukeba** [comment]
Deleting of history.db fixed the problem.
Thanks.
