### ISSUE TITLE
инсталятор создаёт некорректные ярлыки для запуска программы

### ISSUE THREAD

**Issue by AVBL** [FarGroup/FarManager#633]
### Far Manager version

?

### OS version

Windows 10.0.19045.2604

### Other software

Проблема в следующем. После установки фара я пытаюсь настроить свойства окна (Alt-пробел -> Свойства). Задаю размер шрифта и размеры окна
![image](https://user-images.githubusercontent.com/49921898/220901639-08315efd-6ceb-4fd4-87b4-e1cdf69a9470.png)
После выхода и повторного запуска фара окно оказывается в режиме распахнутого. Если я сворачиваю окно кнопкой на заголовке окна, то ширина оказывается той, что я выбирал, а вот высота оказывается заданной в 50 (так что окно фара занимает всю высоту экрана). Эта беда происходит и с запуском фара через ярлык на столе, и через ярлык в меню Пуск.

Однако, если создать новый ярлык, то эта проблема уходит.

PS: Я не могу заполнить поле "Far Manager version", поскольку, надо полагать, версия показывается в первых строках, а эти строки улетают за край окна (у меня кроме стандартных установлено ещё сколько-то плагинов). Команды с перенаправлением (типа far:about>file или far:about|more) не работают. Но установлена последняя стабильная версия фара.

### Steps to reproduce

*

### Actual behavior

*

**Comment by skipik** [comment]
![123](https://user-images.githubusercontent.com/24621645/220904685-2d958567-c4f8-4749-8b5d-30f2bc70d391.png)
Здесь что у вас выбрано?

**Comment by AVBL** [comment]
Я сохранил один из старых ярлыков, сейчас посмотрел - там "Развёрнутое". Mea culpa, напрочь забыл что опция разворачивания сидит там, а не в свойствах окна. Установка опции "развёрнутое" на новом ярлыке вызывает такое же поведение, как я описал (в том числе игнорирование высоты, заданное в настройках окна), так что это уже не вина фара. В связи с этим, полагаю, топик можно закрыть.
