### ISSUE TITLE
Traditional Chinese characters are overlapped

### ISSUE THREAD

**Issue by lambertlulala** [FarGroup/FarManager#635]
### Far Manager version

3.0.6105.0 x64

### OS version

10.0.22621.1265

### Steps to reproduce

1. Create folders or files with Chinese filenames. For instance, create a directory with name `我要吃水果` and a file with name `測試檔案.txt`.
2. List the folders or files with Far Manager.

### Expected behavior

```
我要吃水果
測試檔案.txt
```

### Actual behavior

Please see the screenshot.
![圖片](https://user-images.githubusercontent.com/76695321/220956305-5200399c-f6f4-4d49-a020-6ff221069c57.png)

**Comment by alabuzhev** [comment]
Options, Interface settings

[x] Use Virtual Terminal for rendering
[x] Fullwidth-aware rendering

Ok, Shift+F9, restart Far.

**Comment by lambertlulala** [comment]
It resolves the problem, thank you!

**Comment by alabuzhev** [comment]
The support is still in development and doesn't cover all the cases, so you might still notice overlaps or truncated strings here and there.
It should slowly improve as we go.

**Comment by lambertlulala** [comment]
Thank you for the continuous and active development! It works perfectly now. :smile:

**Comment by LigH-de** [comment]
Which font and possibly other options are required to actually display Asian characters? I have Consolas and I see only substitutions by a Smilie (probably ASCII 1).

**Comment by johnd0e** [comment]
Try https://github.com/alabuzhev/unicon

**Comment by alabuzhev** [comment]
@johnd0e worth mentioning that it only enables Asian characters in the BMP, which is better than nothing, but could be not enough.
OpenConsole from [the latest available Windows Terminal](https://github.com/microsoft/terminal#installing-windows-terminal-canary) supports everything that unicon does and much more.

**Comment by LigH-de** [comment]
So far I avoid Windows 11, so I'll try unicon as Far plugin just for testing.

**Comment by omglolpower** [comment]
> Options, Interface settings
> 
> [x] Use Virtual Terminal for rendering [x] Fullwidth-aware rendering
> 
> Ok, Shift+F9, restart Far.

Real heroes are not on cinema screen.

**Comment by lambertlulala** [comment]
I've used the [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) font for many years, and it's perfect in Far Manager.
