### ISSUE TITLE
Far manager always open drives on the right pane

### ISSUE THREAD

**Issue by ezxpro** [FarGroup/FarManager#636]
### Far Manager version

3.0.6107.3143

### OS version

Windows 10 Version 10.0.19045.2604

### Steps to reproduce

1. Download Far Manager (zipped or MSI version)
2. Install it (if on MSI version)
3. Launch far manager
4. Click "Change Drive" or press Alt+F2
5. Select new drive
6. It opens on the right pane no matter what

### Expected behavior

It should open the new drive on the active pane?

### Actual behavior

Regardless of which pane is the active one, it always opens the drives I select on the right pane.

**Comment by yegor-mialyk** [comment]
AltF1 - the left panel and AltF2 - the right panel.

**Comment by ezxpro** [comment]
> AltF1 - the left panel and AltF2 - the right panel.

Oh, I see. How about doing it by pointing and clicking?

**Comment by yegor-mialyk** [comment]
You can mouse click on a <sorting letter> (e.g. "n") in the top left corner of each panel to open the Change Drive dialog. Or press and hold Alt and then click on the key bar bottom left of the screen (1Left, 2Right)

**Comment by alabuzhev** [comment]
> It should open the new drive on the active pane?

No, it's always on the right one:

![image](https://user-images.githubusercontent.com/11453922/221356612-704adb02-bced-428f-aac0-60e3c84fb53e.png)
