### ISSUE TITLE
зацикливание на большом .js файле

### ISSUE THREAD

**Issue by AVBL** [FarGroup/FarManager#637]
### Far Manager version

последняя стабильная

### OS version

Windows 10.0.19045.2604

### Steps to reproduce

Среди файлов Steam есть, например, такие файлы:
![image](https://user-images.githubusercontent.com/49921898/221057231-312372ff-ee6f-4824-9e96-6836ff5e50e2.png)
При попытке открыть один из этих файлов на редактирование Far задумывается на долгое время (4-5 минут):
![image](https://user-images.githubusercontent.com/49921898/221057621-6220b577-2500-4366-b86d-431c589b5ec1.png)
при этом очень сильно нагружая процессор:
![image](https://user-images.githubusercontent.com/49921898/221057653-f8ac54d6-5463-4113-90a5-1678ec8a78be.png)
и в результате не открывая файл. Для удобства присоединяю один из этих файлов стима.
[sp.js.zip](https://github.com/FarGroup/FarManager/files/10819427/sp.js.zip)

### Actual behavior

*

**Comment by alabuzhev** [comment]
Please report Colorer issues [here](https://github.com/colorer/FarColorer/issues/new).
