### ISSUE TITLE
динамические изменение размеров окон истории

### ISSUE THREAD

**Issue by AVBL** [FarGroup/FarManager#638]
### Description of the new feature or improvement

В Far есть окошки "Истории просмотра и редактирования" (Alt-F11) и "История папок" (Alt-F12). Содержимое этих окошек можно чистить построчно с помощью с помощью Shift-Del. Раньше при удалении самой длинной строки окно автоматически ужималось, сейчас я обратил внимание, что этого не происходит. Нельзя ли вернуть старое поведение?

**Comment by yegor-mialyk** [comment]
Какую выгоду дает старое поведение?

**Comment by yegor-mialyk** [comment]
Для задающихся вопросом "почему вообще меняли, когда и так хорошо работало?". Вопрос - риторический. Ответов может быть много, вроде унификации или избавления от неявной логики. Но, так же, он (ответ) может и отсутствовать вовсе.

**Comment by AVBL** [comment]
> Вопрос - риторический
Я это предполагал, потому и не задал его. :)

> Какую выгоду
1. Логичность. Размеры всегда соответствуют содержимому, а сейчас при одном и том же содержимом размеры могут быть разными (после чистки и при следующих открытиях).
2. Я периодически чищу истории от мусора и изменение размеров мне сразу показывало, что самый мусор (обычно это всякие "Arclite:") уже убран.

**Comment by AVBL** [comment]
Добавлю ещё один момент. Списки в "Историях" разделены на блоки с указанием даты занесения в историю в начале блока. Раньше, если удалялась последняя запись в блоке, автоматически уходил и разделитель. Сейчас разделители остаются до перезахода в историю. Причём если чистится много записей, может образоваться целый завал таких разделителей.

**Comment by alabuzhev** [comment]
It is intentional to avoid flickering.
