### ISSUE TITLE
Selection not removed in Editor and edit controls on pressing Ctrl+Num6

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#647]
### Far Manager version

3.0.6111.0 x64

### OS version

10.0.22624.1391

### Steps to reproduce

1. Make sure the Editor option _Persistent blocks_ is turned off
2. Open any file in the Editor
3. Select some text and press `Ctrl + Num6` (Ctrl + Right arrow on Numeric Keypad)

### Expected behavior

The selection should be removed.

### Actual behavior

Selection is not removed. This issue is also present in edit controls in dialogs.

The issue appears to be due to a typo in line **2366** of the following code - keys should be `NUMPAD6` instead of `NUMPAD7`.
https://github.com/FarGroup/FarManager/blob/086158463672996daa6b68d5867b43ffdc695dcf/far/edit.cpp#L2355-L2368

**Comment by alabuzhev** [comment]
Thanks, should be numpad6 indeed.
6112.

**Comment by rohitab** [comment]
I just tested version `3.0.6113.0 x64`. The issue is fixed. Thanks.
