### ISSUE TITLE
Pressing Ctrl+Enter in the find all menu of the Editor crashes Far if all entries are filtered out

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#650]
### Far Manager version

3.0.6111.0 x64

### OS version

10.0.22624.1391

### Steps to reproduce

1. Open any file in the Editor
2. Press `F7` to open Search
3. Input any word that is present in the file
4. Press `Alt + A` to show all matching entries
5. Press `Ctrl + Alt + F` or `Right Alt` to start filtering menu items
6. Keep pressing `Z` until all entries are filtered out and the menu is empty
7. Press `Ctrl + Enter`

### Expected behavior

Nothing. Since there are no visible entries, pressing `Ctrl + Enter` should do nothing.

### Actual behavior

Far crashes and shows _Oops_ dialog along with the path to crash logs. This also happens with `Ctrl + Left Mouse Click` in the empty menu.

The issue appears to be with the following code. Since the menu is filtered out and nothing is selected, `SelectedPos` is `-1`, which causes `GetComplexUserDataPtr` to return `nullptr`. The next line of code tries to access `coord.Line` and causes an access violation.
https://github.com/FarGroup/FarManager/blob/5c126bea7af1d9d89c087dda02b45495aa0d222f/far/editor.cpp#L3755-L3765

A similar issue is present when you call `Menu.ItemStatus()` from Lua. The code tries to get the menu item at position `SelectPos`, which is invalid, causing an exception.
https://github.com/FarGroup/FarManager/blob/5c126bea7af1d9d89c087dda02b45495aa0d222f/far/vmenu.cpp#L898-L905

The following code, which is executed when you call `Menu.GetValue()`, properly validates `SelectPos` before using it, and does _not_ cause an exception.
https://github.com/FarGroup/FarManager/blob/5c126bea7af1d9d89c087dda02b45495aa0d222f/far/vmenu.cpp#L872-L883

The following code for `Menu.Value` also checks to ensure that it does not use an invalid value.
https://github.com/FarGroup/FarManager/blob/5c126bea7af1d9d89c087dda02b45495aa0d222f/far/vmenu.cpp#L921-L925

**Comment by alabuzhev** [comment]
Ugh. Fixed these, but other menus somewhere could have the same issue probably.
6113.

**Comment by AVBL** [comment]
> Press Ctrl + Alt + F or Right Alt to start filtering menu items
> Keep pressing Z until all entries are filtered out and the menu is empty

These keys are not mentioned either in the window interface nor in the help (F1). PS: In addition, keys from the numeric part of the keyboard (for example, Ctrl-Num2) are not supported - for some reason it is called Gray +.

**Comment by HamRusTal** [comment]
> These keys are not mentioned either in the window interface nor in the help (F1).

`Ctrl+Alt+F` is mentioned in the “Menu control commands” section (`@MenuCmd`). `Z` is not special there, it's just a character being typed to the menu filter.

**Comment by rohitab** [comment]
I just tested version `3.0.6113.0 x64`. The issue is fixed. Thanks.

@AVBL, both `Ctrl+Alt+F` and `RAlt` are listed in the _Help_ files in the _Menu control commands_ topic, as well as the _Common control commands_ topic. You can search for hotkeys in _Help_. For example, press `F1`, then `F7`, then type in `RAlt` and press `Enter`. You should see both these topics listed.

As @HamRusTal mentioned, the `Z` key is not a hotkey; it was used for this test case to filter out all entries.
