### ISSUE TITLE
Crash on opening two dialogs

### ISSUE THREAD

**Issue by nightroman** [FarGroup/FarManager#66]
Far 3.0.5261, plugin FarNet 5.2.14 + PowerShellFar 5.2.5

The following PowerShell scripts cause crashes.

*z3-.ps1* shows one modal dialog and on its opening shows another modal dialog:

    ps: .\z3-.ps1

```powershell
$dialog1 = $Far.CreateDialog(1, 1, 52, 3)
$text1 = $dialog1.AddText(1, 1, 50, "")
$dialog1.add_Initialized({
    $dialog2 = $Far.CreateDialog(1, 6, 52, 3)
    $text2 = $dialog2.AddText(1, 1, 50, "")
    $dialog2.Show()
})
$dialog1.Show()
```

*z4-.ps1* opens two non modal dialogs:

    ps: .\z3-.ps1

```powershell
$dialog1 = $Far.CreateDialog(1, 1, 52, 3)
$text1 = $dialog1.AddText(1, 1, 50, "")
$dialog1.Open()

$dialog2 = $Far.CreateDialog(1, 6, 52, 3)
$text2 = $dialog2.AddText(1, 1, 50, "")
$dialog2.Open()
```

**Comment by nightroman** [comment]
My bad, the second dialog has a typo in its right bottom (3 -> 8) and should be

```powershell
$dialog2 = $Far.CreateDialog(1, 6, 52, 8)
```

Please close if the crash is "legitimate" in this case.

**Comment by alabuzhev** [comment]
f28513c0ebd54836ce76bd3bfa70694159728954 should fix the crash.

**Comment by nightroman** [comment]
Thank you. Covered by a test in my test suite.
