### ISSUE TITLE
Regex search in Editor, again

### ISSUE THREAD

**Issue by MKadaner** [FarGroup/FarManager#660]
### Far Manager version

3.0.6116.0

### OS version

10.0.22621.1413

### Steps to reproduce

1. `F9` - Options - Editor - Set _Cursor at the end_ to _on_.
2. (It is also useful to set _Select found_ to _on_ to help visualize the problem, though it does not affect the behavior.)
3. Open any file with the internal Editor.
4. `F7` - search forward for `...` regex.
5. Press `Shift+F7` repeatedly.

### Expected behavior

With each `Shift+F7`, the cursor moves forward one character at a time. (If _Select found_ is _on_, the three-character selection moves forward one character at a time.)

### Actual behavior

With each `Shift+F7`, the cursor moves forward _three_ characters at a time skipping two subsequent overlapping matches. (If _Select found_ is _on_, the three-character selection leaps forward by three characters at a time.)

If search for the regex `()` (or any other regex matching empty string), search forward does not progress, i.e., pressing `Shift+F7` does not move the cursor.

Actual behavior in all other cases: search for either of these regexes backwards and search with _Cursor at the end_ set to _off_ in either direction moves cursor one character at a time, as expected.

**Comment by MKadaner** [comment]
This bug is easy to fix, but it would change the existing behavior.

@HamRusTal, what do you think?

**Comment by HamRusTal** [comment]
I agree that the bug report is valid and that the current behavior is erroneous in the described scenario.
Also, can you please fix the typo in the Issue Title (Rege**s** instead of Rege**x**)?

**Comment by MKadaner** [comment]
Fixed the title, Thanks.
I will add the fix to #651.

**Comment by MKadaner** [comment]
Addressed in #651.
