### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by AVBL** [FarGroup/FarManager#665]
### Far Manager version

3.0.6111.0

### OS version

win 10

### Steps to reproduce

Попытался просканировать подкаталоги внутри каталога TEMP.
TEMP=C:\Temp
TMP=C:\Temp
Выделил всё содержимое и нажал F3 стоя на каталоге. Сначала фар вывел диалог с запросом на доступ:
![image](https://user-images.githubusercontent.com/49921898/228115550-8ff7b093-129e-406f-981f-c51c5e5cea05.png)
Ставлю галку на "Больше не спрашивать" и Enter. В результате выскочило сообщение о проблемах фара с предложением хакрыть фар или проигнорировать. Закрыл фар и запустил снова. Повторил процедуру - крах повторился. Третий раз перезапустил фар и попытался определить на чём именно крах произошёл, сканировал по частям, но больше такого не происходило.
[bug_report.txt](https://github.com/FarGroup/FarManager/files/11084794/bug_report.txt)
[bug_report.txt](https://github.com/FarGroup/FarManager/files/11084795/bug_report.txt)

### Actual behavior

*

**Comment by alabuzhev** [comment]
Ugh.
6123 (hopefully).
