### ISSUE TITLE
AlternateFileName returns different values with different Lua APIs

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#670]
### Far Manager version

3.0.6128.0 x64

### OS version

10.0.22624.1537

### Use Provided Script

1. Extract `AlternateFileNameIssue.lua` from the archive [AlternateFileNameIssue.lua.zip](https://github.com/FarGroup/FarManager/files/11136267/AlternateFileNameIssue.lua.zip)
2. Copy `AlternateFileNameIssue.lua` to `%FARPROFILE%\Macros\scripts`
3. Restart Far, or run `macro:load` to reload macros
4. Open any archive in the ArcLite plugin
5. Press `Ctrl+/` to run the provided macro

### Or, Manually Call APIs
1. Call `panel.GetCurrentPanelItem`
2. Call `far.Host.GetFindData`
3. Compare `AlternateFileName` returned in the panel item

### Expected behavior

`AlternateFileName` displays the same value, either `nil` or `FileName`

### Actual behavior

`AlternateFileName` displays different values. In the first case, it displays the `FileName`. In the second case it displays `nil`. Here is the output from the script showing the difference.

### Script Output

```plain
╔════════════ Alternate File name Issue ════════════╗
║                                                   ║
║ Method #1          : panel.GetCurrentPanelItem    ║
║ Filename:          : FarManager-ci-v3.0.6128.3249 ║
║ AlternateFileName  : FarManager-ci-v3.0.6128.3249 ║
║                                                   ║
║                                                   ║
║ Method #2          : far.Host.GetFindData         ║
║ Filename           : FarManager-ci-v3.0.6128.3249 ║
║ AlternateFileName  : nil                          ║
║                                                   ║
╟───────────────────────────────────────────────────╢
║                      { OK }                       ║
╚═══════════════════════════════════════════════════╝
````

### panel.GetCurrentPanelItem

When you call `panel.GetCurrentPanelItem` using Lua, it uses `FCTL_GETCURRENTPANELITEM`, which in turn uses `FileList::FileListToPluginItem2`. Here is the relevant code from this function that stores the `AlternateFileName`. Please see the last line **5687**.

https://github.com/FarGroup/FarManager/blob/34496192a009f034a646791b0614251d1f8252c4/far/filelist.cpp#L5861-L5867

If `AlternateFileName` is not present, the function returns the `FileName` instead, as shown here:

https://github.com/FarGroup/FarManager/blob/086158463672996daa6b68d5867b43ffdc695dcf/far/platform.fs.cpp#L170-L173

### far.Host.GetFindData

This API is handled by the function `far_host_GetFindData`, which obtains data from the plugin and calls `PushPanelItem`. Here is the relevant code from this function. Please see the last line **546**. It stores `AlternateFileName` as-is. If `AlternateFileName` is not set, the field is not stored, i.e. `nil` is returned in Lua. The ArcLite plugin does not have an `AlternateFileName`, so it stores a `nil` value.

https://github.com/FarGroup/FarManager/blob/66a12a3b2282554396e7bfcecf4c94da9cd12e1b/plugins/luamacro/luafar/service.c#L535-L546

### Suggestion

Both the above APIs use `PushPanelItem` to store the panel item. However, since `panel.GetCurrentPanelItem` uses `find_data::AlternateFileName`, it sets `AlternateFileName` to the `FileName` if it is not set. In contrast, `far.Host.GetFindData` just stores the `AlternateFileName` if available, and `nil` if not available.

I think both (all) APIs should return the same value for `AlternateFileName`, preferably `nil` if the value is not set. However, it might break existing macros that people have written. The other option would be to modify `PushPanelItem` so that it returns `FileName` if `AlternateFileName` is not available, similar to `find_data::AlternateFileName`.

Please note that there are other APIs like `panel.GetPanelItem` and `panel.GetSelectedPanelItem` that behave similar to `panel.GetCurrentPanelItem`.

**Comment by johnd0e** [comment]
@shmuz

**Comment by shmuz** [comment]
@johnd0e, as you know I'm spending all my spare time nowadays on far2m, etc. and there's no `AlternateFileName` there.

**Comment by shmuz** [comment]
@rohitab
LuaFAR usually tries to convey to Lua things that it receives from C with no modification if possible.
If it receives `FileName` from Far it just passes it over to Lua. So I don't see a simple solution to this issue,

WRT to breaking someone's existing macros - I think very few people use `AlternateFileName`, the behavior can be changed, But again - LuaFAR should not have knowledge about the values it receives and should not change them.

**Comment by rohitab** [comment]
@shmuz 
How about something like the following patch? This fixes the issue on the _Far_ side, without making changes to LuaFAR. I've tested it, and it appears to be working correctly.

### Patch

```diff
diff --git a/far/filelist.cpp b/far/filelist.cpp
index 4fabb04ee..c52e69cba 100644
--- a/far/filelist.cpp
+++ b/far/filelist.cpp
@@ -5829,7 +5829,7 @@ size_t FileList::FileListToPluginItem2(const FileListItem& fi,FarGetPluginPanelI
 	const auto
 		StaticSize      = sizeof(PluginPanelItem),
 		FilenameSize    = StringSizeInBytes(fi.FileName),
-		AltNameSize     = StringSizeInBytes(fi.AlternateFileName()),
+		AltNameSize     = fi.HasAlternateFileName() ? StringSizeInBytes(fi.AlternateFileName()) : 0,
 		ColumnsSize     = fi.CustomColumns.size() * sizeof(wchar_t*),
 		ColumnsDataSize = std::ranges::fold_left(fi.CustomColumns, 0uz, [&](size_t s, const wchar_t* i) { return s + (i? StringSizeInBytes(i) : 0); }),
 		DescriptionSize = fi.DizText? StringSizeInBytes(fi.DizText) : 0,
@@ -5887,9 +5887,12 @@ size_t FileList::FileListToPluginItem2(const FileListItem& fi,FarGetPluginPanelI
 		return size;
 	gpi->Item->FileName = CopyToBuffer(FilenameOffset, fi.FileName);
 
-	if (not_enough_for(AltNameOffset, AltNameSize))
-		return size;
-	gpi->Item->AlternateFileName = CopyToBuffer(AltNameOffset, fi.AlternateFileName());
+	if (AltNameSize)
+	{
+		if (not_enough_for(AltNameOffset, AltNameSize))
+			return size;
+		gpi->Item->AlternateFileName = CopyToBuffer(AltNameOffset, fi.AlternateFileName());
+	}
 
 	if (ColumnsSize)
 	{
diff --git a/plugins/arclite/farutils.cpp b/plugins/arclite/farutils.cpp
index 7ba3127d4..e6a2e4b91 100644
--- a/plugins/arclite/farutils.cpp
+++ b/plugins/arclite/farutils.cpp
@@ -209,7 +209,8 @@ static PanelItem get_panel_item(HANDLE h_panel, FILE_CONTROL_COMMANDS command, s
   pi.file_size = panel_item->FileSize;
   pi.pack_size = panel_item->AllocationSize;
   pi.file_name = panel_item->FileName;
-  pi.alt_file_name = panel_item->AlternateFileName;
+  if (panel_item->AlternateFileName)
+    pi.alt_file_name = panel_item->AlternateFileName;
   pi.user_data = panel_item->UserData.Data;
   return pi;
 }

```

### Test Script
Please note that there was a bug in the original test script I provided, so here is an updated version for testing these changes: [`AlternateFileNameIssue-v2.lua.zip`](https://github.com/FarGroup/FarManager/files/14070848/AlternateFileNameIssue-v2.lua.zip)

_p.s. sorry for the late reply_

**Comment by shmuz** [comment]
@rohitab 
I think if this patch makes behavior consistent we may apply it.
Let's @alabuzhev decide.

**Comment by alabuzhev** [comment]
Can't see why not.
@rohitab would you like to create a PR?

**Comment by rohitab** [comment]
@shmuz appreciate that. Thank you.
@alabuzhev thank you as well. Sure, I will create a PR.
@johnd0e thank you for bringing this issue back to life!
