### ISSUE TITLE
Unused key bar labels in Help

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#671]
### Far Manager version

3.0.6128.0 x64

### OS version

10.0.22624.1537

### Steps to reproduce

1. Press `F1` to open _Help_
2. Press and hold `Shift`

### Expected behavior

Key bar labels for `3` and `7` (`Shift+F3` and `Shift+F7`) should be empty.

### Actual behavior

Key bar label for `3` shows _Docums_, and `7` shows _Next_.

Unless I'm mistaken, both `Shift+F3` and `Shift+F7` do not appear to do anything in _Help_.

**Comment by alabuzhev** [comment]
Nice catch. Those are the only remnants of some experiments from 2001, removed in 2010. We definitely don't need them.
