### ISSUE TITLE
[Feature Request] Change hosting in CMD to hosting in Powershell

### ISSUE THREAD

**Issue by drweb86** [FarGroup/FarManager#675]
### Description of the new feature or improvement

My vision that cmd prompt which is below far is outdated and Powershell seems like become stable tool for commands. Propose to consider switching to powershell.

PS. this is just an idea. As for me Far suits me as it is entirely.

**Comment by yegor-mialyk** [comment]
@drweb86, you can change this today by editing `System.Executor.Comspec` and `System.Executor.ComspecArguments` settings by setting them to PowerShell in `far:config`.

**Comment by alabuzhev** [comment]
Far is neither "hosted in" nor "hosting" anything.
The command prompt under panels *is* Far.
An external command processor is only involved when Far cannot execute the entered command (e.g. `dir`) directly.
As mentioned above, it is configurable and you can already switch to anything you like.

**Comment by drweb86** [comment]
Thanks guys. did not know that.
