### ISSUE TITLE
ExitFAR event handler not called in Lua on Far exit

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#684]
### Far Manager version

3.0.6141.0 x64

### OS version

10.0.22624.1755

### Steps to reproduce

1. Extract `ExitFAR-Issue.lua` from the attached archive [ExitFAR-Issue.lua.zip](https://github.com/FarGroup/FarManager/files/11468907/ExitFAR-Issue.lua.zip)
2. Copy `ExitFAR-Issue.lua` to `%FARPROFILE%\Macros\scripts`
3. Restart _Far_, or run `macro:load` to reload macros
4. Run `macro:load` again. You should see the message `ExitFAR: unload = true`, and a sleep message followed by a 3 second delay
5. Press `F10` to exit _Far_

### Expected behavior

You should see the message `ExitFAR: unload = false`, followed by a 3 second delay before _Far_ exits.

### Actual behavior

_Far_ exits without displaying the message from the event handler.

### Current Version

This was working fine in version `3.0.6137.0 x64`. The issue appears to be due to the following change made in commit: https://github.com/FarGroup/FarManager/commit/a889bd945a86f50b9ba3943ade979fa2d60fbc89

https://github.com/FarGroup/FarManager/blob/850b342c004ecd97d69e98c0f94a316eae49b38d/far/plugins.cpp#L175-L178

The above change calls `Plugin::Unload` with `bExitFAR` set to `false`, which causes the following code to _not_ call `ExitFAR`.

https://github.com/FarGroup/FarManager/blob/850b342c004ecd97d69e98c0f94a316eae49b38d/far/plclass.cpp#L726-L727
https://github.com/FarGroup/FarManager/blob/850b342c004ecd97d69e98c0f94a316eae49b38d/far/plclass.cpp#L745-L752

### Previous Versions

In previous versions, `bExitFAR`, the parameter to `Luamacro->Unload`, was set to `true` as seen here. In this case, the `ExitFAR` event handler was being called.

https://github.com/FarGroup/FarManager/blob/7d3c296d217ee8a5768fc5f6190aaa7c0830bef1/far/plugins.cpp#L159-L162

### Usage

I use the `ExitFAR` event handler to perform cleanup operations, like deleting temporary files created by macros, when _Far_ exits. With the current build, this feature is broken. The event handler is only called when macros are reloaded, and not when _Far_ exits.

### Source Code of attached `ExitFAR-Issue.lua`

```lua
Event {
    group = "ExitFAR";
    description = "ExitFAR Event Issue";
    action = function(unload)
        mf.printconsole("\nExitFAR: unload = " .. (unload and "true" or "false"))
        mf.printconsole("\nSleeping for 3 seconds before unload/exit...")
        mf.sleep(3000)
    end;
}
```

**Comment by rohitab** [comment]
@w17 notifying you since you pushed commit https://github.com/FarGroup/FarManager/commit/a889bd945a86f50b9ba3943ade979fa2d60fbc89

**Comment by rohitab** [comment]
Just in case anyone is interested in a binary patch to resolve this issue, you can make the following change to `Far.exe` using any hex editor.

##### Patch for Far version [`3.0.6142.0 x64`](https://github.com/FarGroup/FarManager/releases/tag/ci/v3.0.6142.3300)

| File Offset | Original Bytes | Patched Bytes |
|--------|--------|--------|
| `1773ae` | `33 D2` | `B2 01` |

This changes `false` to `true` in the following code, so that the `ExitFAR` is called on exit.

https://github.com/FarGroup/FarManager/blob/59231c2b931a2cb70f25ab75b301a65bcc323ea2/far/plugins.cpp#L177

**Comment by w17** [comment]
@rohitab works as expected (tested on mine macros):
```
Event {
  description = "Save panel directories on Exit";
  group = "ExitFAR";
  action = function(reload_macros)
    --far.Show("ExitFar", reload_macros)
    mf.printconsole("\nExitFAR: unload = " .. (reload_macros and "true" or "false"))
    mf.printconsole("\nSleeping for 3 seconds before unload/exit...")
    mf.sleep(3000)
    if not reload_macros then
      local p = {A=panel.GetPanelDirectory(nil,1),P=panel.GetPanelDirectory(nil,0),L=APanel.Left}
      mf.msave("setup", "ExitFAR", p)
    end
  end
}

Macro {
  description = "Restore panel directories on Start";
  area="Shell"; key="auto"; flags="RunAfterFARStart";
  action=function()
    local p = mf.mload("setup", "ExitFAR")
    if p and p.A then panel.SetPanelDirectory(nil,1,p.A) end
    if p and p.P then panel.SetPanelDirectory(nil,0,p.P) end
    if p and APanel.Left ~= p.L then Keys("CtrlU") end
  end
}
```

**Comment by w17** [comment]
Ought...
Probably I found the reason.
I have one more local uncommited change in manager.cpp.

**Comment by w17** [comment]
No. Without that also works as expected
`Far Manager, version 3.0.6144.0 (Private) x64                                                                           Copyright © 1996-2000 Eugene Roshal, Copyright © 2000-2023 Far Group                                                                                                                                                                                                                                                                                                    ExitFAR: unload = true                                                                                                                                                                                                                          Sleeping for 3 seconds before unload/exit...                                                                                                                                                                                                    D:\Projects\far\far3-svn\far>macro:load`

**Comment by w17** [comment]
Missed change required for real far exit.

**Comment by rohitab** [comment]
Thank you! I just tested version `3.0.6146.0 x64` and it's working now.

The newline issue also got fixed as well, which is great. In previous versions, `mf.printconsole` did not output a newline when called during exit. That's why I had the extra `\n` at the beginning of the messages.
