### ISSUE TITLE
Search in archives option not saved in Find File search

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#685]
### Far Manager version

3.0.6142.0 x64

### OS version

10.0.22624.1755

### Steps to reproduce

1. Press `Alt+F7` to open _Find file_
2. Press `Alt+I` to enable _Search in archives_
3. Press `Enter` to search
4. Press `Esc` to close _Find file_ results
5. Press `Alt+F7` to reopen _Find file_

### Expected behavior

_Search in archives_ option is enabled (checked).

### Actual behavior

_Search in archives_ option is disabled (unchecked).

Please note that this happens regardless of whether the _Containing_ input box has text. The other options like _Case sensitive_ and _Whole words_ are only saved if the _Containing_ input box has text, but _Search in archives_ option is never saved. This was working correctly in version `3.0.6134.0 x64`.

**Comment by MKadaner** [comment]
That's weird. I do not think I touched _Search in archives_, at least not intentionally. Will have a look.

**Comment by rohitab** [comment]
Thanks! By the way, this issue is also present with the _Not containing_ checkbox.

https://github.com/FarGroup/FarManager/blob/59231c2b931a2cb70f25ab75b301a65bcc323ea2/far/findfile.cpp#L191-L192

In previous versions (where it worked), these options were stored in a static variable so they were persisted across multiple searches.

https://github.com/FarGroup/FarManager/blob/d76ab4d5a6b755b22e5239de8a71532af82fb156/far/findfile.cpp#L3034-L3036

**Comment by MKadaner** [comment]
Yeah! I already noticed that. Fixing it as well. Stay tuned.

**Comment by MKadaner** [comment]
Fixed in #686.

**Comment by rohitab** [comment]
Just tested version `3.0.6144.0 x64`. The issue is fixed now. Thank you!
