### ISSUE TITLE
Commands history: empty Folder for commands with host-file plugin prefix run via file association

### ISSUE THREAD

**Issue by HamRusTal** [FarGroup/FarManager#687]
### Far Manager version

3.0.6142.0

### OS version

10.0.19045.2604

### Steps to reproduce

1. Run FAR: `far.exe -s "%TEMP%\FarProfile\2023-05-15" -p"%FARHOME%\Plugins\Arclite"`
2. Create new association:
    ```
    ╔══════════════════════ Edit file associations ══════════════════════╗
    ║ A file mask or several file masks:                                 ║
    ║ *.exe                                                             ↓║
    ║ Description of the association:                                    ║
    ║ Reproduce empty Folder in AltHistory                               ║
    ╟────────────────────────────────────────────────────────────────────╢
    ║ [ ] Execute command (used for Enter):                              ║
    ║                                                                    ║
    ║ [x] Execute command (used for Ctrl+PgDn):                          ║
    ║     arc:"!\!.!"                                                    ║
    ║ [ ] View command (used for F3):                                    ║
    ║                                                                    ║
    ║ [ ] View command (used for Alt+F3):                                ║
    ║                                                                    ║
    ║ [ ] Edit command (used for F4):                                    ║
    ║                                                                    ║
    ║ [ ] Edit command (used for Alt+F4):                                ║
    ║                                                                    ║
    ╟────────────────────────────────────────────────────────────────────╢
    ║                         { OK } [ Cancel ]                          ║
    ╚════════════════════════════════════════════════════════════════════╝
    ```
3. Position file panel cursor to `far.exe` and press `Ctrl+PgDn` — the PE file is entered as an archive.
4. Open Commands history (`Alt+F8`) — the last command is like `arc:"C:\Programs\Far Manager\Far.exe"` and is highlighted.
5. Open the Information dialog for the command (`F3`).

### Expected behavior

The Folder field shows the full path of the directory containing `far.exe`.

### Actual behavior

The Folder field is empty.

**Comment by HamRusTal** [comment]
Original report: [post in the Forum topic on the _AltHistory_ plugin](https://forum.farmanager.com/viewtopic.php?p=174694&sid=c6051c6bbc1c1f21d96c9010e105efba#p174694).

**Comment by alabuzhev** [comment]
1. History is updated after invoking the association.
2. Invoking the association changes the file panel to a plugin panel
3. Arclite claims that its panel directory is empty for whatever reason.
4. We have what we have.

The first point here is questionable: associations can call plugins and plugins can do all sorts of unholy things with histories and directories.
In 6143 history is updated before invoking the association. Maybe it will break something, maybe not.

**Comment by w17** [comment]
> Arclite claims that its panel directory is empty for whatever reason.
Panel Directory for arclite is path in archive (root of archive == "") isn't it?

And as I can see after 6143 this issue is solved ans should be closed.
