### ISSUE TITLE
Change time for read-only or system files cannot be set

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#692]
### Far Manager version

3.0.6147.0 x64

### OS version

10.0.22624.1755

### Steps to reproduce

1. Position the cursor on any file which has _Read only_ or _System_ attribute already set
2. Press `Ctrl+A` to open _Attributes_ dialog
3. Press `Alt+G` to switch to _Change time_ input
4. Type in `01/01/1991`
5. Press `Enter` to save the new attributes
6. Press `Ctrl+A` to reopen  _Attributes_ dialog

### Expected behavior

The file _Change time_ should display the entered value `01/01/1991` for the date.

### Actual behavior

The file _Change time_ displays the time when the attributes were set.

Please note that this issue only occurs with files that have the _Read only_ or _System_ attribute set. If the file does not have these attributes, the _Change time_ is set correctly.

### Additional Information
The issue appears to be in the `ESetFileTime` function, which uses `without_ro` function to manage files with these attributes differently.

https://github.com/FarGroup/FarManager/blob/33131a632eb1c5c182e8ee0427a60c1c13c7870d/far/fileattr.cpp#L147-L158

The function `without_ro` removes `FILE_ATTRIBUTE_READONLY` and `FILE_ATTRIBUTE_SYSTEM` from the file and restores them after the specified `Action`. However, when the file attributes are restored, the _Change time_ gets reset to the current time.

https://github.com/FarGroup/FarManager/blob/33131a632eb1c5c182e8ee0427a60c1c13c7870d/far/fileattr.cpp#L59-L81

### Possible Fix
The `ESetFileTime` function opens the file using `GENERIC_WRITE`, which is why it needs to remove the attributes of the file and restore them after the operation. If it used `FILE_WRITE_ATTRIBUTES` instead, additional operations would not be required, and the _Change time_ would be set correctly.

I tested these changes (see patch below). The issue appears to be resolved.

### Last access time Issue
A related issue is that the _Last access time_ of the file is reset when you change any other time, regardless of the file attributes. For example, if you change just the _Last write time_ of the file, the _Last access time_ will also be changed. This is due to the file being opened with `GENERIC_WRITE` access. Using `FILE_WRITE_ATTRIBUTES` resolves this issue as well.

### Patch
```patch
--- a\FarManager-ci-v3.0.6147.3322\far\fileattr.cpp	2023-05-19 16:06:28.000000000 +1000
+++ b\FarManager-ci-v3.0.6147.3322\far\fileattr.cpp	2023-05-20 13:12:50.000000000 +1000
@@ -143,21 +143,21 @@
 {
 	if (!LastWriteTime && !CreationTime && !LastAccessTime && !ChangeTime)
 		return;
 
 	const auto Implementation = [&]
 	{
-		const os::fs::file File(Name, GENERIC_WRITE, os::fs::file_share_all, nullptr, OPEN_EXISTING, FILE_FLAG_OPEN_REPARSE_POINT);
+		const os::fs::file File(Name, FILE_WRITE_ATTRIBUTES, os::fs::file_share_all, nullptr, OPEN_EXISTING, FILE_FLAG_OPEN_REPARSE_POINT);
 		if (!File)
 			return false;
 
 		return File.SetTime(CreationTime, LastAccessTime, LastWriteTime, ChangeTime);
 	};
 
 	retryable_ui_operation(
-		without_ro(Name, CurrentAttributes, Implementation),
+		Implementation,
 		Name, lng::MSetAttrTimeCannotFor, SkipErrors);
 }
 
 static bool set_file_sparse(string_view const Name, bool const State)
 {
 	const os::fs::file File(Name, FILE_WRITE_DATA, os::fs::file_share_all, nullptr, OPEN_EXISTING);
```

**Comment by alabuzhev** [comment]
Thanks a lot for the detailed report and the fix!
Added to 6149.

**Comment by rohitab** [comment]
Of course, and thank you for the quick turnaround. I'm happy to help, especially if it saves you time.

I just tested version `3.0.6149.0 x64`. The issue is resolved.
