### ISSUE TITLE
Change time cannot be set simultaneously with other file attributes

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#693]
### Far Manager version

3.0.6147.0 x64

### OS version

10.0.22624.1755

### Steps to reproduce

1. Position the cursor on any file
2. Press `Ctrl+A` to open _Attributes_ dialog
3. Press `Alt+A` to toggle the _Archive_ attribute
4. Press `Alt+G` to switch to _Change time_ input
5. Type in `01/01/1991`
6. Press `Enter` to save the new attributes
7. Press `Ctrl+A` to reopen  _Attributes_ dialog

### Expected behavior

The file _Change time_ should display the entered value `01/01/1991` for the date.

### Actual behavior

The file _Change time_ displays the time when the attributes were set. Note that the _Archive_ attribute is toggled correctly. If you modify only the _Change time_ (and any other file time), the value is set correctly.

### Additional Information
The issue appears to be in the `process_single_file` function, which sets the file time _before_ setting other attributes like _Archive_. As a result, if other attributes and the time are changed  simultaneously, the _Change time_ gets reset.

Here is the relevant code from `process_single_file` function. As you can see here, `ESetFileTime` (Line **648**) is called before `ESetFileAttributes` (Line **673**).

https://github.com/FarGroup/FarManager/blob/33131a632eb1c5c182e8ee0427a60c1c13c7870d/far/setattr.cpp#L648-L674

### Possible Fix
I modified the code in `process_single_file` so that `ESetFileTime` is called at the end, after setting all other attributes. This appears to have resolved the issue.

**Comment by alabuzhev** [comment]
Thanks a lot for the detailed report and the fix!
Added to 6149.

**Comment by rohitab** [comment]
Of course, and thank you for the quick turnaround. I'm happy to help, especially if it saves you time.

I just tested version `3.0.6149.0 x64`. The issue is resolved.
