### ISSUE TITLE
File creation time lost after saving read-only file on secondary disk

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#694]
### Far Manager version

3.0.6147.0 x64

### OS version

10.0.22624.1755

### Steps to reproduce

1. Switch panel to a secondary disk -- this can be another partition, a USB key, or a mounted virtual disk image -- anything other than `C:`
2. Position cursor on any file which has _Read only_ attribute set, preferably a `.txt` file
3. Press `Ctrl+A` to open _Attributes_ dialog
4. Note the value for _Creation time_
5. Press `Esc` to close the _Attributes_ dialog
6. Press `F4` to edit the file
7. Press `Shift+F10` to save the file and quit the _Editor_
8. Press `Enter` when prompted by the _Editor_ to overwrite a read-only file
9. Press `Ctrl+A` to reopen  _Attributes_ dialog

### Expected behavior

The file _Creation time_ should show the original value from `Step 4` above.

### Actual behavior

The file _Creation time_ displays the time when the file was saved, i.e., the original _Creation time_ is lost.

Please note that this issue only occurs with files that have the _Read only_ attribute set, and it only occurs on secondary drives (at least for me). If you save a read-only file on the primary drive `C:`, the file _Creation time_ is _not_ lost. Also, if you set `Editor.SaveSafely` to `false` using `far:config`, this issue does not occur.

### Additional Information
The issue appears to be with the [ReplaceFile](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-replacefilew) Windows API. The following comment in the source points to a similar issue regarding DAC, when using a temporary file, i.e., when `Editor.SaveSafely` is `true`, the default setting in _Far_.

https://github.com/FarGroup/FarManager/blob/33131a632eb1c5c182e8ee0427a60c1c13c7870d/far/file_io.cpp#L89-L92

### ReplaceFile API

I checked the `ReplaceFile` API from a separate test application, and it behaves differently on primary and secondary disks, at least on my system. On the primary disk, the creation time of `lpReplacedFileName` is used. On secondary drives, the creation time of `lpReplacementFileName` is used.

### Possible Fix
I copied the _Creation time_ from the original file `FileName` to the temporary file `OutFile`, before the `ReplaceFile` API is called via `os::fs::replace_file`. This seems to have fixed the issue. Please see the patch below for the changes.

### Patch

```patch
--- a\FarManager-ci-v3.0.6147.3322\far\file_io.cpp	2023-05-19 16:06:28.000000000 +1000
+++ b\FarManager-ci-v3.0.6147.3322\far\file_io.cpp	2023-05-20 16:56:44.000000000 +1000
@@ -127,12 +127,21 @@
 		Stream.exceptions(Stream.badbit | Stream.failbit);
 
 		Handler(Stream);
 
 		Stream.flush();
 		OutFile.SetEnd();
+
+		if (UseTemporaryFile)
+		{
+			os::chrono::time_point CreationTime;
+			if (os::fs::GetFileTimeSimple(FileName, &CreationTime, nullptr, nullptr, nullptr))
+			{
+				OutFile.SetTime(&CreationTime, nullptr, nullptr, nullptr);
+			}
+		}
 	}
 
 	if (UseTemporaryFile)
 	{
 		if (!os::fs::replace_file(FileName, OutFileName, CreateBackup? FileName + L".bak"sv : L""sv, REPLACEFILE_IGNORE_MERGE_ERRORS | REPLACEFILE_IGNORE_ACL_ERRORS))
 			throw MAKE_FAR_EXCEPTION(L"Can't replace the file"sv);
```

**Comment by alabuzhev** [comment]
Thanks a lot for the detailed report and the fix!
Added to 6149.

**Comment by rohitab** [comment]
Of course, and thank you for the quick turnaround. I'm happy to help, especially if it saves you time.

I just tested version `3.0.6149.0 x64`. The issue is resolved.
