### ISSUE TITLE
Archive file creation time lost after deleting files

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#695]
### Far Manager version

3.0.6150.0 x64

### OS version

10.0.22624.1755

### Steps to reproduce

1. Position the cursor on any updatable archive, say `.zip`
2. Press `Ctrl+A` to open _Attributes_ dialog
3. Note the value for _Creation time_
4. Press `Esc` to close the Attributes dialog
5. Press `Ctrl+PgDn` to enter archive using ArcLite plugin
6. Select any file, then press `F8` to delete the file, then press `Enter` when prompted to confirm deletion
7. Press `Ctrl+PgUp` to exit the archive
8. Press `Ctrl+A` to reopen _Attributes_ dialog

### Expected behavior

The file _Creation time_ should show the original value from `Step 3` above.

### Actual behavior

The file _Creation time_ displays the time when the archive was saved, i.e., the original _Creation time_ is lost.

Please note that this issue only occurs when deleting files from the archive. If you add files to the archive, the file _Creation time_ is _not_ lost.

### Additional Information
When you update an archive, by adding files to it, the creation time is _not_ lost, since the `Archive::update` function copies the original creation time, as seen in line `1173` here.

https://github.com/FarGroup/FarManager/blob/66dd48e54fd86f28abf8aa7d51a8aed7002f5ed9/plugins/arclite/update.cpp#L1171-L1176

The `set_ctime` function is defined in the `SimpleUpdateStream` class.

https://github.com/FarGroup/FarManager/blob/66dd48e54fd86f28abf8aa7d51a8aed7002f5ed9/plugins/arclite/update.cpp#L193-L196

### Possible Fix
I copied the above code from `Archive::update` in [`plugins/arclite/update.cpp`](https://github.com/FarGroup/FarManager/blob/66dd48e54fd86f28abf8aa7d51a8aed7002f5ed9/plugins/arclite/update.cpp#L1171-L1173) to `Archive::delete_files` in [`plugins/arclite/delete.cpp`](https://github.com/FarGroup/FarManager/blob/66dd48e54fd86f28abf8aa7d51a8aed7002f5ed9/plugins/arclite/delete.cpp#L198) and added the `set_ctime` function to the `ArchiveFileDeleterStream` class. I tested the changes and the issue appears to be resolved now. Please see the patch below for the changes.

### Patch
```patch
--- a\FarManager-ci-v3.0.6150.3328\plugins\arclite\delete.cpp	Mon May 22 05:48:11 2023
+++ b\FarManager-ci-v3.0.6150.3328\plugins\arclite\delete.cpp	Mon May 22 17:55:10 2023
@@ -96,6 +96,11 @@ public:
     return S_OK;
     COM_ERROR_HANDLER_END
   }
+
+  bool set_ctime(const FILETIME& ctime) noexcept {
+    FILETIME dummy{0, 0};
+    return set_time_nt(ctime, dummy, dummy);
+  }
 };
 
 class ArchiveFileDeleter: public IArchiveUpdateCallback, public ComBase {
@@ -190,11 +195,16 @@ void Archive::delete_files(const std::ve
 
     const auto progress = std::make_shared<ArchiveFileDeleterProgress>();
     ComObject<IArchiveUpdateCallback> deleter(new ArchiveFileDeleter(new_indices, progress));
-    ComObject<IOutStream> update_stream(new ArchiveFileDeleterStream(temp_arc_name, progress));
+    auto archive_file_deleter_stream = new ArchiveFileDeleterStream(temp_arc_name, progress);
+    ComObject<IOutStream> update_stream(archive_file_deleter_stream);
 
     COM_ERROR_CHECK(copy_prologue(update_stream));
 
     COM_ERROR_CHECK(out_arc->UpdateItems(update_stream, static_cast<UInt32>(new_indices.size()), deleter));
+
+    WIN32_FILE_ATTRIBUTE_DATA fa;
+    if (File::attributes_ex(arc_path, &fa))
+      archive_file_deleter_stream->set_ctime(fa.ftCreationTime);
     close();
     update_stream.Release();
     File::move_file(temp_arc_name, arc_path, MOVEFILE_REPLACE_EXISTING);

```

**Comment by alabuzhev** [comment]
Thank you, added to 336.

**Comment by rohitab** [comment]
Just tried out version `3.0.6151.0 x64`. The issue is fixed.  Thank you!
