### ISSUE TITLE
Don't call ProcessConsoleInput on special macro keys

### ISSUE THREAD

**Issue by shmuz** [FarGroup/FarManager#696]
### Far Manager version

latest

### OS version

win 10

### Steps to reproduce

With the event below being loaded the macro tests fail.
```lua
Event {
  group="consoleinput";
  action=function(rec) return rec end;
}
```

### Actual behavior

See steps to reproduce.

**Comment by shmuz** [comment]
```diff
diff --git a/far/keyboard.cpp b/far/keyboard.cpp
index 001fa3a62..dd95972a2 100644
--- a/far/keyboard.cpp
+++ b/far/keyboard.cpp
@@ -1105,7 +1105,7 @@ DWORD GetInputRecord(INPUT_RECORD *rec, bool ExcludeMacro, bool ProcessMouse)
 
 	DWORD Key = GetInputRecordImpl(rec, ExcludeMacro, ProcessMouse);
 
-	if (Key)
+	if (Key && (Key!=KEY_OP_PLAINTEXT) && (Key!=KEY_OP_SELWORD) && (Key!=KEY_OP_XLAT))
 	{
 		if (Global->CtrlObject)
 		{
```

**Comment by shmuz** [comment]
@alabuzhev 
Is there something wrong with the suggested patch?

**Comment by alabuzhev** [comment]
@shmuz no, why? Looks good as far as I can tell.
Except maybe exclude the whole KEY_OP_* range between `KEY_OP_BASE` and `KEY_OP_ENDBASE` just in case?

**Comment by shmuz** [comment]
Yes, excluding the whole range is even better.

**Comment by alabuzhev** [comment]
6154
