### ISSUE TITLE
Help/Viewer/Editor Search/Replace “Search for” text field's completion menu disappears upon Up/Down arrows

### ISSUE THREAD

**Issue by HamRusTal** [FarGroup/FarManager#697]
### Far Manager version

3.0.6151.0

### OS version

10.0.19045.2604

### Steps to reproduce

1. Start Far: `far.exe -s "%TEMP%\FarProfile\2023-05-26" -p`
2. Open e.g. its `changelog` for editing.
3. Start a couple of replacements to populate the history (no need to actually replace anything): `aa` to `aa`, `ab` to `ab`.
4. Open the Replace dialog.
5. Observe the following behavior: type `a` into the `Replace with` field — the completion drop-down menu opens, press Up/Down — the menu stays, its current item follows the arrows pressed.
6. Now type `a` into the `Search for` field, then press the Up/Down arrows.

### Expected behavior

The completion drop-down menu stays, its current item follows the arrows pressed — just like in the `Replace with` field.

### Actual behavior

The completion drop-down menu disappears but the dialog behaves as if the menu is still shown: the Up/Down arrows change the current field text, `Esc` does not close the dialog.

**Comment by MKadaner** [comment]
Ough! Apparently, I broke it in 6144 (gh-686). Will look during the weekend. Thank you for reporting.

**Comment by MKadaner** [comment]
Fixed in 6156 (#394)
