### ISSUE TITLE
Unmodified files are overwritten in plugins if code page is changed

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#700]
### Far Manager version

3.0.6158.0 x64

### OS version

10.0.22631.1830

### Steps to reproduce

1. Open any archive
2. Select a file in the archive and press `F4` to edit it using the built-in Editor
3. Press `Shift+F8` to open _Code pages_
4. Press `0` to change the code page to _UTF-16 (Big endian)_
5. If you get a warning about the file containing characters that cannot be read, press `Enter` to accept
6. Press `Shift+F8` to reopen _Code pages_
7. Press `2` to change the code page to _UTF-16 (Little endian)_
8. If you get a warning about the file containing characters that cannot be read, press `Enter` to accept
9. Press `Esc` to close the Editor

### Expected behavior

You are returned to the archive panel with the file.

### Actual behavior

The ArcLite plugin displays the _Add files to archive_ dialog. Note that you were _not_ prompted to save the file in the Editor, since it was not modified.

This issue is not limited to the ArcLite plugin. It happens with all plugins. For example, if you use the NetBox plugin to connect to a server over SFTP, the file will be automatically uploaded/overwritten, without any prompts.

### Additional Information
When a file from a plugin is opened for editing, and then closed, _Far_ checks to see if the file has changed, and if so, uploads the file to the plugin. Here is the relevant code containing the check in line `1969`.

https://github.com/FarGroup/FarManager/blob/5fc85a848ae5ea55dd381143576f427a750773fe/far/filelist.cpp#L1964-L1971

The `UploadFile` flag is set based on the value returned by `FileEditor::IsFileChanged`, which is defined as follows.

https://github.com/FarGroup/FarManager/blob/5fc85a848ae5ea55dd381143576f427a750773fe/far/fileedit.hpp#L112

`FileEditor::IsFileChanged` returns the value of `Editor::IsChanged`, which is defined as follows.

https://github.com/FarGroup/FarManager/blob/5fc85a848ae5ea55dd381143576f427a750773fe/far/editor.cpp#L4741-L4744

If either the flags `FEDITOR_MODIFIED` or `FEDITOR_WASCHANGED` are set, the file is considered to have changed. This sets the `UploadFile` flag, which results in calling `PluginManager::PutFiles` to upload the file to the plugin.

### Code Page Change
When the code page is changed, `FileEditor::ReloadFile` function is called, as seen here in line `1443` (scroll to end).

https://github.com/FarGroup/FarManager/blob/5fc85a848ae5ea55dd381143576f427a750773fe/far/fileedit.cpp#L1429-L1443

This function sets the flag `Editor::FEDITOR_WASCHANGED`, as seen here.

https://github.com/FarGroup/FarManager/blob/5fc85a848ae5ea55dd381143576f427a750773fe/far/fileedit.cpp#L1772-L1778

### Editor::FEDITOR_WASCHANGED
I believe the issue is due to the `Editor::FEDITOR_WASCHANGED` flag being set when the code page is changed. Normally, this flag is set after a new/modified file is saved, as seen here.

https://github.com/FarGroup/FarManager/blob/5fc85a848ae5ea55dd381143576f427a750773fe/far/fileedit.cpp#L2078-L2079

### Possible Fix
I modified `FileEditor::ReloadFile` so that `Editor::FEDITOR_WASCHANGED` is no longer set on a code page change. This appears to have resolved the issue. See the patch below for changes.

### Save As with new Code page Issue
While looking at this issue, I came across another related one. While editing a file inside an archive, if you press `Shift+F2` to use the _Save file as_ feature, and change the _Code page_, the file is not updated in the archive. However, if you modify the  _Change line breaks to_ setting in the same dialog, the file is updated in the archive. The code to handle this is as follows.

https://github.com/FarGroup/FarManager/blob/5fc85a848ae5ea55dd381143576f427a750773fe/far/fileedit.cpp#L1951-L1955

 This issue is also present with all other plugins, like NetBox. The patch below resolves this issue as well. However, there is still one remaining issue, viz., if you modify only the _Add signature (BOM)_ setting, the file is not updated. I couldn't find a place where the previous value was stored, but it can easily be added in.

### Patch
```patch
--- a/FarManager-ci-v3.0.6158.3356/far/fileedit.cpp
+++ b/FarManager-ci-v3.0.6158.3356/far/fileedit.cpp
@@ -1771,7 +1771,6 @@ bool FileEditor::ReloadFile(uintptr_t codepage)
 	{
 		if (LoadFile(strFullFileName, user_break, ErrorState))
 		{
-			m_editor->m_Flags.Set(Editor::FEDITOR_WASCHANGED);
 			m_editor->m_Flags.Clear(Editor::FEDITOR_MODIFIED);
 			Show();
 			return true;
@@ -1954,6 +1953,11 @@ int FileEditor::SaveFile(const string_view Name, int Ask, bool bSaveAs, error_st
 		m_editor->GlobalEOL = Eol;
 	}
 
+	if (Codepage != m_codepage)
+	{
+		m_editor->m_Flags.Set(Editor::FEDITOR_WASCHANGED);
+	}
+
 	if (!os::fs::exists(Name))
 		m_Flags.Set(FFILEEDIT_NEW);
 

```

**Comment by rohitab** [comment]
@alabuzhev Since you just modified the code related to this, would you mind looking at this issue as well, assuming you have the time? My description is really long, but the fix is small.

**Comment by alabuzhev** [comment]
@rohitab, of course - I somehow completely overlooked this issue.

> I couldn't find a place where the previous value was stored

TBH, all the shenanigans with this flag don't make much sense to me.
As you mentioned, IsFileChanged is only used to determine whether to upload the file back to the plugin or not.
And there is a much simpler way to tell with confidence that the file was changed: it was changed if the user successfully saved it at least once.

6185.

**Comment by rohitab** [comment]
No worries and thank you for looking into this.

Unfortunately, this is causing issues with the _Save file as_ feature. In fact, the issues started with commit https://github.com/FarGroup/FarManager/commit/450dbad51c9ec6c34de2478c2a9d7fe336fd4588

### Current Directory Issue

Prior to https://github.com/FarGroup/FarManager/commit/450dbad51c9ec6c34de2478c2a9d7fe336fd4588, if you edited a file in an archive, and pressed `Shift+F2` to save the file, Far would overwrite the temporary file. Then, when you closed the Editor, the file would be updated in the archive. After the changes in commit https://github.com/FarGroup/FarManager/commit/450dbad51c9ec6c34de2478c2a9d7fe336fd4588, when you press `Shift+F2` to save the file, it is saved in the current directory, instead of the temporary directory. Due to this, the file never gets updated in the archive. I believe this is caused by the following changes:

https://github.com/FarGroup/FarManager/blob/450dbad51c9ec6c34de2478c2a9d7fe336fd4588/far/filelist.cpp#L1956-L1961

The Editor is created with the current directory set to the temporary directory, which causes the following code to set `strFileName` to just the filename, without the path.

https://github.com/FarGroup/FarManager/blob/450dbad51c9ec6c34de2478c2a9d7fe336fd4588/far/fileedit.cpp#L2183-L2184

When you press `Shift+F2`, you'll see that the _Save file as_ dialog only shows the filename, not the full path in the temporary directory, like it did in earlier versions. When you save the file, it gets saved in the current directory. When you close the Editor, Far will prompt you to add it to the archive. However, the file that gets added is the old version from the temporary directory, not the one that you saved.

Just to test it out, I removed the following line and built version `6183` and it worked as expected.

https://github.com/FarGroup/FarManager/blob/450dbad51c9ec6c34de2478c2a9d7fe336fd4588/far/filelist.cpp#L1959

Of course, showing just the filename without the full path to the temporary directory is much better, if it can work.

### Filename/Path Issue

Now, regarding commit https://github.com/FarGroup/FarManager/commit/ddc4a5153f3e53139837e8d11be74202a0b6e8d7. The changes that you made fixed the issue that I reported. However, this commit is also causing issues with the _Save file as_ feature. If you edit a file in an archive, then press `Shift+F2` to save the file, it is saved to the current directory, instead of the temporary directory, just like the commit described above. However, even after reverting the change as I did above, the issue remains. I believe this is due to the following change which uses the filename without the path.

https://github.com/FarGroup/FarManager/blob/ddc4a5153f3e53139837e8d11be74202a0b6e8d7/far/fileedit.cpp#L2075-L2083

For testing, I reverted this change to use the full path. However, now there is another issue.

### FFILEEDIT_WAS_SAVED Flag
If you press `Shift+F2` to save an unmodified file, and change just the code page or line breaks, the flag `FFILEEDIT_WAS_SAVED` is not set due to the following condition:

https://github.com/FarGroup/FarManager/blob/ddc4a5153f3e53139837e8d11be74202a0b6e8d7/far/fileedit.cpp#L1888-L1904

Since the file was neither modified, nor is it a new file, the flag `FFILEEDIT_WAS_SAVED` is never set on Line `1903`, which causes [`FileEditor::WasFileSaved`](https://github.com/FarGroup/FarManager/blob/ddc4a5153f3e53139837e8d11be74202a0b6e8d7/far/fileedit.hpp#L113) to return `false` which in turn sets [`UploadFile`](https://github.com/FarGroup/FarManager/blob/ddc4a5153f3e53139837e8d11be74202a0b6e8d7/far/filelist.cpp#L1964) to `false`, so the file is never updated in the archive.

**Comment by alabuzhev** [comment]
Thank you for checking and for the analysis. 6186.

**Comment by rohitab** [comment]
Thank again. All the issues I reported are fixed, but I just found another issue. Sorry, didn't realize it would get so complicated!

### Automatic Code Page Detection Fails
Due to the changes in commit https://github.com/FarGroup/FarManager/commit/450dbad51c9ec6c34de2478c2a9d7fe336fd4588, automatic code page detection is no longer working for files opened in plugins, or for files that are in a different directory than the current directory.

The issue appears to be due to the following code, which tries to open the file using its filename `strFileName` instead of the full filename with path `strFullFileName`. Since the file is located in a different directory than the current, the file cannot be opened, causing code page detection to fail.

https://github.com/FarGroup/FarManager/blob/6527c888661f347cbc7c5d8977f93ac7f4af1bba/far/fileedit.cpp#L1244-L1248

I changed Line **1246** as shown here and the issue got resolved.

```diff
-  const os::fs::file EditFile(strFileName, FILE_READ_DATA, os::fs::file_share_read, nullptr, OPEN_EXISTING);
+  const os::fs::file EditFile(strFullFileName, FILE_READ_DATA, os::fs::file_share_read, nullptr, OPEN_EXISTING);
```

**Comment by alabuzhev** [comment]
Thank you, applied.

**Comment by rohitab** [comment]
All good. I just tested version `3.0.6187.0 x64`. Thanks.
