### ISSUE TITLE
On systems with Privilege Manager of BeyondTrust an additional black console window with Far Manager icon might be opened

### ISSUE THREAD

**Issue by rosti-il** [FarGroup/FarManager#701]
### Far Manager version

3.0.6116.0 x64

### OS version

10.0.22621.1702
This is Windows 11 22H2. The same issue was on Windows 10 before it was upgraded into Windows 11. Windows 11 was then also reinstalled by our IT department from scratch (from their image with all their junk preinstalled).

### Other software

![image](https://github.com/FarGroup/FarManager/assets/45571812/9967c491-da8e-44ff-8934-2fd1c6b2ec34)
This is my work computer with such a corporate junk IT installs to "protect" it. I can't uninstall or reconfigure it. My corporate user isn't local administrator. That Privilege Manager of BeyondTrust is a kind of workaround our IT found to the problem they created by themselves.

### Steps to reproduce

1. Make sure you're not a local administrator
2. Make sure a Privilege Manager of BeyondTrust is installed
3. Try to do any operation that needs administrator privilege and accept administrator's privilege leveraging like in this screenshot: 
![image](https://github.com/FarGroup/FarManager/assets/45571812/6d77ae16-1543-48ee-9ca0-812c1c0ffaa7)
In this example I'm trying to create a `1` directory within `C:\Program Files\Git\` one.

### Expected behavior

No additional window is openned

### Actual behavior

An additional black console window with Far Manager icon is opened
![image](https://github.com/FarGroup/FarManager/assets/45571812/95a431b7-b581-437d-a5c7-ec29d5270076)

That additional window is where the work is actually done. If I need to do something that takes time (for example deleting a lot of files) and close that additional window before the work is done, then the work is not completed.

**Comment by alabuzhev** [comment]
We spawn the elevated process here:
https://github.com/FarGroup/FarManager/blob/5fc85a848ae5ea55dd381143576f427a750773fe/far/elevation.cpp#L430-L441

As you can see, we do not pass SW_* to ShellExecuteEx, which is equivalent to passing SW_HIDE, making the window invisible.

Presumably that "Privilege Manager" thing intercepts ShellExecuteEx and meddles with its parameters for some unholy reasons.
We can't do much about it, except maybe something like

```DIFF
diff --git a/far/elevation.cpp b/far/elevation.cpp
index 5f4b29497..9763b6a5e 100644
--- a/far/elevation.cpp
+++ b/far/elevation.cpp
@@ -55,6 +55,7 @@ THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #include "exception.hpp"
 #include "exception_handler.hpp"
 #include "log.hpp"
+#include "console.hpp"
 
 // Platform:
 #include "platform.hpp"
@@ -1041,6 +1042,7 @@ class elevated:noncopyable
 public:
 	int Run(string_view const Uuid, DWORD PID, bool UsePrivileges)
 	{
+		ShowWindow(console.GetWindow(), SW_HIDE);
 		os::set_error_mode(SEM_FAILCRITICALERRORS | SEM_NOOPENFILEERRORBOX);
 
 		std::array const Privileges

```
to try to hide it *again* after the creation.
However, that corporate junk isn't available for free, so I cannot check that assumption.

**Comment by rosti-il** [comment]
I'm not familiar with the Win32 API but according to a comment by Eryk Sun in [this](https://stackoverflow.com/questions/54927156/how-to-hide-shellexecuteex-console-window-but-not-application-window) article you should call `CreateProcessW` with the flag `CREATE_NO_WINDOW` instead of `ShellExecuteEx`. Calling `ShowWindow(console.GetWindow(), SW_HIDE)` could hide the window but it will flash it anyway, so using the `CreateProcessW` way should be better.

> However, that corporate junk isn't available for free, so I cannot check that assumption.

I can try to test it with a nightly build. Just tell me which nightly build to try.

**Comment by yegor-mialyk** [comment]
@rosti-il, give this one a try to see whether it behaves any differently:
[Far6161-gh701.zip](https://github.com/FarGroup/FarManager/files/11699558/Far6161-gh701.zip)

**Comment by alabuzhev** [comment]
> according to a comment by Eryk Sun in [this](https://stackoverflow.com/questions/54927156/how-to-hide-shellexecuteex-console-window-but-not-application-window) article you should call `CreateProcessW` with the flag `CREATE_NO_WINDOW` instead of `ShellExecuteEx`

Thanks for the suggestion, but we usually do things the way we do them for a reason. In this particular case the reason is "CreateProcessW does not support elevation".

**Comment by rosti-il** [comment]
> give this one a try to see whether it behaves any differently:
> [Far6161-gh701.zip](https://github.com/FarGroup/FarManager/files/11699558/Far6161-gh701.zip)

Unfortunately it behaves the same way - the additional console window with Far icon is still opened.

> Thanks for the suggestion, but we usually do things the way we do them for a reason. In this particular case the reason is "CreateProcessW does not support elevation".

OK, but there is a `CreateProcessAsUserW`.
Also I've found this interesting article https://www.codeproject.com/Articles/19165/Vista-UAC-The-Definitive-Guide about an alternative to the `ShellExecuteEx` for running an elevated process.

Another option could be running another executable (instead of `Far.exe`) that is not a console application and so it will never try to open any console or window at all.

**Comment by alabuzhev** [comment]
Of course.
It's not like going to great lengths in an open source project to workaround bugs of a noname corpoware is impossible in principle, but the probability of such event is pretty low.

If you find a simple workaround, not involving reimplementing existing facilities from scratch, reverse-engineering Windows, using external libraries, introducing new executables etc., please let us know.

**Comment by rosti-il** [comment]
@alabuzhev isn't the `CreateProcessAsUserW` with the `CREATE_NO_WINDOW` flag - that simple workaround?

**Comment by alabuzhev** [comment]
> isn't the `CreateProcessAsUserW` with the `CREATE_NO_WINDOW` flag - that simple workaround?


> the process that calls the CreateProcessAsUser function must have the SE_INCREASE_QUOTA_NAME privilege
> To get a primary token that represents the specified user, call the LogonUser function

No.
