### ISSUE TITLE
Trackpad scrolling issue in build 6159

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#702]
### Far Manager version

3.0.6159.0 x64

### OS version

10.0.22631.1830]

### Steps to reproduce

Open a text file in the Editor, and use the trackpad to scroll vertically (drag two fingers up/down).

### Expected behavior

Editor scrolls the file immediately, without requiring a lot of movement, similar to previous versions.

### Actual behavior

Editor does not scroll the file, unless the scrolling (two finger drag) is done rapidly. Slow movement does not scroll at all. In previous versions, minimal movement causes the file to scroll.

Please note that this issue is not limited to the Editor. It also occurs in the Viewer, Help and File Panels. The same issue is also present with horizontal scrolling.

I tried changing the value for `System.MsWheelDeltaEdit`. The value works as expected, but the issue with scrolling persists. I also tried the other vertical/horizontal configuration values for Editor, Viewer and Help.

### Additional Information
The changes made in commit https://github.com/FarGroup/FarManager/commit/ca7c33dce4bc57e188184fb5fce70c790f20bc2c are causing the issue, at least on my system. I traced the issue to the following function:

https://github.com/FarGroup/FarManager/blob/ca7c33dce4bc57e188184fb5fce70c790f20bc2c/far/manager.cpp#L117-L123

When trying to scroll normally, this function returns `0`, which results in no scrolling. When scrolling rapidly, this function returns a non-zero value, which results in scrolling. The absolute value in `HIWORD` of `dwButtonState` is less than `WHEEL_DELTA`, which causes the final return value to be `0`.

### Test Code
Just for testing, I modified `Manager::Key::NumberOfWheelEvents` function so that the return value is always greater than or equal to `1`, and never `0`. Here is the exact change.

```patch
--- a/FarManager-ci-v3.0.6158.3356/far/manager.cpp
+++ a/FarManager-ci-v3.0.6158.3356/far/manager.cpp
@@ -119,7 +119,7 @@ size_t Manager::Key::NumberOfWheelEvents() const
 	if (!m_EventFilled || m_Event.EventType != MOUSE_EVENT || !(m_Event.Event.MouseEvent.dwEventFlags & MOUSE_WHEELED | MOUSE_HWHEELED))
 		return 1;
 
-	return std::abs(static_cast<short>(extract_integer<WORD, 1>(m_Event.Event.MouseEvent.dwButtonState)) / WHEEL_DELTA);
+	return std::max(1, std::abs(static_cast<short>(extract_integer<WORD, 1>(m_Event.Event.MouseEvent.dwButtonState)) / WHEEL_DELTA));
 }
 
 static bool CASHook(const Manager::Key& key)
```

This patch fixes the issue for me. Scrolling is working like before; well actually, it is a little bit better than before.

I'm not sure if this is the correct way to fix this issue, but I thought I'd post it here since it's working for me.

**Comment by alabuzhev** [comment]
Supposedly the proper way to do it is

> add the incoming delta values until WHEEL_DELTA is reached

but that would require way more changes in mouse processing.

**Comment by rohitab** [comment]
I was looking at the documentation for [`MOUSE_EVENT_RECORD`](https://learn.microsoft.com/en-us/windows/console/mouse-event-record-str), but could not find any mention of calculating the distance moved. I had a look at the [`WM_MOUSEWHEEL`](https://learn.microsoft.com/en-gb/windows/win32/inputdev/wm-mousewheel) documentation too, but I guess I wasn't paying attention, because I completely missed the part about adding the incoming delta values. Appreciate the info.

I just tested version `3.0.6160.0 x64`. All is good now. Thanks for the quick turnaround.

**Comment by alabuzhev** [comment]
> Scrolling is working like before; well actually, it is a little bit better than before.

I configured gestures on my touchpad, which I normally don't use, and wow - it is horribly, horribly oversensitive.
Which is not surprising, if we react to every tiny change as if it is the whole `WHEEL_DELTA`.

In 6161 onwards wheel ticks are accumulated as recommended, it should be more manageable now.
If you're used to oversensitivity and want it back, increasing System.Ms[H]WheelDelta* should help.

**Comment by rohitab** [comment]
I liked the fast scrolling, although that's a matter of personal preference and also depends on the hardware. The way you've implemented it now is the correct way, and the scrolling matches what I see in other applications.

Maybe some day though you can add a configuration to increase/decrease mouse scrolling sensitivity by using a different `WHEEL_DELTA`. Changing `System.Ms[H]WheelDelta*` doesn't have the same effect, since these values control the amount of scrolling, whereas `WHEEL_DELTA` controls the sensitivity, i.e. how much movement is required to scroll.  As an example, in build `6060`, I had these values set to `1` and could scroll one line at a time, using minimal finger motion, very similar feel to how smooth scrolling works in Chrome.

### Scrolling Direction Change

I think when the direction of scrolling is changed, the previous ticks (from the opposite direction) should be discarded. The difference might not be very noticeable, but I can see it. Something like this should fix this issue:

```patch
--- a/FarManager-ci-v3.0.6161.3359/far/keyboard.cpp
+++ b/FarManager-ci-v3.0.6161.3359/far/keyboard.cpp
@@ -828,7 +828,7 @@ static bool ProcessMouseEvent(MOUSE_EVENT_RECORD& MouseEvent, bool ExcludeMacro,
 		// You can also choose your scroll granularity and accumulate deltas until it is reached.
 		static int StoredTicks = 0;
 		const auto Ticks = static_cast<short>(extract_integer<WORD, 1>(MouseEvent.dwButtonState));
-		StoredTicks += Ticks;
+		StoredTicks = (StoredTicks ^ Ticks) < 0 ? Ticks : StoredTicks + Ticks;
 
 		if (std::abs(StoredTicks) < WHEEL_DELTA)
 		{

```

### Window Detection
I noticed another issue, which is not new. When you scroll rapidly, say in the Editor, and then you press `Esc` to quit out, the File Panel continues the scrolling, from what was left over in the Editor. Is there a way to detect that the window has changed, and stop sending keys? In the code below, `repeat` will send the keys until finished, regardless of whether the window has changed.

https://github.com/FarGroup/FarManager/blob/1af76c353f3075ab1df33f0d1dabc513886e4cde/far/editor.cpp#L1691-L1696

### Previous Patch
Now that you added the following code...

https://github.com/FarGroup/FarManager/blob/1af76c353f3075ab1df33f0d1dabc513886e4cde/far/keyboard.cpp#L833-L837

...maybe `std::max` is no longer required here?

https://github.com/FarGroup/FarManager/blob/1af76c353f3075ab1df33f0d1dabc513886e4cde/far/manager.cpp#L122

**Comment by alabuzhev** [comment]
> configuration to increase/decrease mouse scrolling sensitivity by using a different `WHEEL_DELTA`

Ok. "Delta" is already taken, so it will be System.MsWheelThreshold.

> I think when the direction of scrolling is changed, the previous ticks (from the opposite direction) should be discarded

Yes, if we were scrolling up, then fully stopped or maybe switched to something different, then started scrolling down, "unwinding" the previous stash doesn't make sense.

There are probably subtle cases where discarding could be undesirable, e.g. when the user fiddles with the input, either consciously or unconsciously:

![image](https://github.com/FarGroup/FarManager/assets/11453922/21523b16-b576-4587-a88e-3190824ea36e)

While playing with the touchpad, I noticed that sometimes ticks alternate between 1 and -1 simply when I change the touch angle. However, this is probably way less common than normal direction change and can be ignored.

> When you scroll rapidly, say in the Editor, and then you press `Esc` to quit out, the File Panel continues the scrolling, from what was left over in the Editor

Are you sure this is about what was left over in the Editor and not just regular input events from the device? I tried multiple times, but couldn't stop immediately after switching windows.

> maybe `std::max` is no longer required here?

Yes, should not be needed, thank you.

**Comment by rohitab** [comment]
> Ok. "Delta" is already taken, so it will be System.MsWheelThreshold.

Excellent. I've configured `System.MsWheelThreshold` to `20`, with all other delta values to `1`, and scrolling is just perfect for me.

> There are probably subtle cases where discarding could be undesirable, e.g. when the user fiddles with the input, either consciously or unconsciously:

Well explained, especially with the image. You're correct, although I doubt anyone is going to complain, or even notice these cases.

> Are you sure this is about what was left over in the Editor and not just regular input events from the device? I tried multiple times, but couldn't stop immediately after switching windows.

I added some logs and tried again. You're right; the issue is not with _Far_; it's just the way my hardware/driver works. If I rapidly flick two fingers, completely remove them from the touchpad, then use the keyboard to switch applications, scrolling continues in the new application.

All issues in this ticket have been resolved. Thank you.
