### ISSUE TITLE
Multiple log files created and console logs empty in sync mode

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#704]
### Far Manager version

3.0.6162.0 x64

### OS version

10.0.22631.1835

### Steps to reproduce

Use the following to configure logging and run _Far_:

```batch
mkdir %TEMP%\FarLogs

set far.log.level=info
set far.log.sink=file;console
set far.log.sink.file.mode=sync
set far.log.sink.console.mode=sync
set far.log.sink.file.path=%TEMP%\FarLogs

Far.exe
```

### Expected behavior

- Far creates `1` log file in `%TEMP%\FarLogs`
- Pressing `Ctrl+Shift+L` shows the console log

### Actual behavior

- Far creates `2` log files in `%TEMP%\FarLogs` - one is empty, the other contains the expected logs
- Pressing `Ctrl+Shift+L` shows a blank screen

If you also set the environment variable `far.log.sink.composite.mode` to `sync`, then `4` log files are created, `3` of them empty.

The default mode of `async` works as expected, creating a single log file, and the console log is visible when pressing `Ctrl+Shift+L`

The issue appears to be with the following code, which causes the `sink_type` (file, console etc.) to be created twice.

https://github.com/FarGroup/FarManager/blob/f32598d08341a78a799acd1e48058cd0eda89b1e/far/log.cpp#L676-L679

### Patch
The following patch fixes the issue, but it could be wrong.

```patch
--- a/FarManager-ci-v3.0.6162.3360/far/log.cpp
+++ b/FarManager-ci-v3.0.6162.3360/far/log.cpp
@@ -674,7 +674,7 @@ namespace
 	};
 
 	template<typename sink_type>
-	class sync final: public sink_boilerplate<sink_type>, private synchronized_impl<sink_type>
+	class sync final: public synchronized_impl<sink_boilerplate<sink_type>>
 	{
 	public:
 		static constexpr auto mode = sink_mode::sync;

```

**Comment by alabuzhev** [comment]
Hmm, I probably overcomplicated the class hierarchy there a bit...

Thank you, the fix looks correct. 6163.

**Comment by rohitab** [comment]
Thanks. I wasn't sure about the fix. Templates give me a headache!

I just tested `3.0.6163.0 x64`. All good.
