### ISSUE TITLE
Амперсанд в !?<title>?<init>!

### ISSUE THREAD

**Issue by 2underscores-vic** [FarGroup/FarManager#71]
При использовании оператора `!?<title>?<init>!` в меню, в заголовке выводится метка пункта меню с амперсандом, который используется для назначения горячей клавиши:

![image](https://user-images.githubusercontent.com/14104863/46279186-19d27780-c571-11e8-8b3a-8c677798b5cb.png)

Сам пункт меню выглядит так:

![image](https://user-images.githubusercontent.com/14104863/46279478-dc221e80-c571-11e8-82fb-1ce33792a315.png)

**Comment by alabuzhev** [comment]
It's not the worst part - the menu was turning real `&` characters in file names into hotkeys.
Both issues should be fixed in 58082cf60d156f9ed966c1e27a5a0d80d9923963 (build 5278).
