### ISSUE TITLE
New Editor option `Add signature (BOM) by default`

### ISSUE THREAD

**Issue by MKadaner** [FarGroup/FarManager#712]
### Description of the new feature or improvement

Some time ago I switched `Default code page` Editor option from `OEM` (or was it `ANSI`?) to `UTF-8`. It works great, as expected. No more silly dialogs `The character "ы" (U+044B) is not supported by the selected code page`.

However, another issue popped up. By default, the Editor adds BOM to new files if they are saved in a Unicode code page. Most of the time, I create pure ASCII-7 files, and many of them are intended to be consumed by something which does not understand BOM. Most notable are CMD scripts. I've lost count of times when a newly minted CMD file is broken like this:

```
C:\TEMP>∩╗┐echo Hello world!
'∩╗┐echo' is not recognized as an internal or external command,
operable program or batch file.
```

Of course, it's easy to fix with `Shift+F2` and unchecking `Add signature (BOM)` checkbox, but why? Can we have one more Editor option next to `Default code page`?

### Proposed technical implementation details (optional)

I can do this.

**Comment by alabuzhev** [comment]
hlf:Editor.AddUnicodeBOM

**Comment by MKadaner** [comment]
Thank you. Silly me, especially as I already have this option set to `false` on one of my machines.

**Comment by alabuzhev** [comment]
Thinking about it, the existing option is probably suboptimal: it affects all BOMs, while in reality you likely only want to disable it for UTF-8, but not for UTF-16 LE/BE. Doing it separately could be better. On the other hand, UTF-16 formats are probably too rare these days to care about them.

**Comment by MKadaner** [comment]
I think treating all of them the same should be fine. I cannot remember when I've last seen a UTF-16LE file in the wild (not crafted for some kind of testing), and I am pretty sure I've never seen UTF-16BE. Both UTF-16 encodings should be easily detectable, so the modern trend of no-BOM should work all ways.
