### ISSUE TITLE
MacOS m1 support

### ISSUE THREAD

**Issue by gonchik** [FarGroup/FarManager#717]
###  MacOS m1 m2 support
Hello, 

do you have a plan of supporting m1 and m2 MacOS builds? 

I like that application as was taught to use when I was in University :) 
Fortunately, I am still using that on my windows machine. 

Cheers,
GT

**Comment by HamRusTal** [comment]
FAR Manager does not support any macOS, regardless of hardware architecture.
You might wish to look at *NIX ports like `far2l`/`far2m` (Google them).

**Comment by gonchik** [comment]
@HamRusTal  thanks.
