### ISSUE TITLE
Wrong buttons in warning message when creating a new file from a plugin panel

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#726]
### Far Manager version

3.0.6182.0 x64

### OS version

10.0.22631.2265

### Steps to reproduce

1. Open a plugin panel, e.g., by running `arc:%FARHOME%\Plugins\FarColorer\base\common.zip`
2. Press `Shift+F4` to create a new file using Editor.
3. Press `Del` to empty out the filename in the _Open/create file_ field.
4. Press `Enter` to create the file.

### Expected behavior

Far displays a warning message dialog with 2 buttons: _Yes_ and _No_, since the user is being asked a question.

### Actual behavior

Far displays a warning message dialog with 1 button: _Cancel_.

```plain
   ╔══════════════════ Warning ═══════════════════╗
   ║ The name of the file to edit cannot be empty ║
   ║                  Continue?                   ║
   ╟──────────────────────────────────────────────╢
   ║                  { Cancel }                  ║
   ╚══════════════════════════════════════════════╝
```

If you press `Esc`, the operation will be cancelled. However, if you press the _Cancel_ button, Far will reopen the _Open/create file_ dialog.

### Additional Information
The warning message is displayed by the following code:

https://github.com/FarGroup/FarManager/blob/f6da06da4336cdce3edc0633400cb4d7b5094cff/far/filelist.cpp#L1849-L1860

I think line **1857** should be:

```diff
- { lng::MCancel }, 
+ { lng::MHYes, lng::MHNo },
```

**Comment by alabuzhev** [comment]
@rohitab this is a quite old (17 years, oh my!) issue and the current warning is intentional.
[Initial discussion](https://forum.farmanager.com/viewtopic.php?t=1677)
[Initial report](https://bugs.farmanager.com/view.php?id=231)

Briefly, opening nameless files on plugin panels led to mysterious issues due to some quirks in the code.
In 3045936bb4aed8380f12987cae73ebffd9ea1a29 this message was added as a basic temporary workaround to prevent the users from doing so.
The intention was to fix the code in the future and then remove the whole quoted block, but apparently it never happened.

**Comment by alabuzhev** [comment]
Since it popped up, we might as well fix it. 6183.

**Comment by rohitab** [comment]
@alabuzhev I didn't realize this was such an old issue! Thank you for fixing it.

### Save as Issue

There still appears to be one remaining issue. If you use `F10` or `Esc` to quit the editor, it automatically saves the file, instead of showing the _Save file as_ dialog, like it did in previous versions. Here are the steps to reproduce it:

1. Go to any folder in a regular file panel.
2. Press `Shift+F4` to create a new file using Editor.
3. Press `Del` to empty out the filename in the _Open/create file_ field.
4. Press `Enter` to create the file.
5. Type in some text, say `testing`.
6. Press `F10` to quit the Editor.
7. When prompted with _File has been modified. Save?_ message, press `Enter` to confirm.

The file will be saved in the current directory, with the template based name, e.g., `New_File_2023-09-06_13.40.58.889.txt`. In previous versions, Far showed the _Save file as_ dialog instead of automatically saving the file, which is the correct behavior in my opinion.

If you use a plugin panel in Step 1, Far will save the file in a temporary folder and send it to the plugin, without prompting for a file name.

If you press `F2` in Step 6 above, Far will show the _Save file as_ dialog, as expected.

I found a workaround by adding a `?` to the template, which prevents the file from being saved, and shows the _Save file as_ dialog when you press `F10` to quit the Editor.

### Template:
I see you have added the following _"no funny stuff"_ check to ensure that the generated name is different from the template. Is this really required? I wanted to use just `?` as the template, or even `New?`, but the following check prevents me from doing so.

https://github.com/FarGroup/FarManager/blob/450dbad51c9ec6c34de2478c2a9d7fe336fd4588/far/fileedit.cpp#L2211-L2216

Just to test it out, I removed the above check to allow any template to be used. I'm now able to use `?` as the template without any issues. I tested using file panels and NetBox, ArcLite, ProcList, Registry and TmpPanel plugins. All of them work correctly even without the above check.

**Comment by alabuzhev** [comment]
> I found a workaround by adding a `?` to the template

And this is exactly why it "worked" before.
This whole saving logic is a disaster, I'll see if I can improve it.

> ensure that the generated name is different from the template

The purpose of `NewName != Template` it to ensure that the template produces unique names.
If the name is not unique, subsequent attempts to create a new file without specifying a name would detect that such a file is already being edited and show a confirmation dialog (Current / New Instance / Reload). I don't think that such a confirmation is appropriate here - we are clearly trying to create a new file.

Now that you mentioned it, I realize that `NewName != Template` is not quite enough: the user can, say, keep {year} there and the check will pass, but nevertheless the names won't be unique. Perhaps it would be better to keep things simple and let user do whatever they want here.

**Comment by rohitab** [comment]
> And this is exactly why it "worked" before.

Yes, I looked at the old code and saw that invalid filename characters were causing the file creation operation to fail, resulting in the Editor showing the _Save file as_ dialog. That's how I found out what character(s) to use in the template.

> This whole saving logic is a disaster, I'll see if I can improve it.

That would be great!

> If the name is not unique, subsequent attempts to create a new file without specifying a name would detect that such a file is already being edited and show a confirmation dialog (Current / New Instance / Reload).

Ah, I didn't notice this case. I just tested this with an older version of Far, and even with the original `?New File?` name, this dialog was still being displayed. All this time using Far, and I never once came across this case.

> I don't think that such a confirmation is appropriate here - we are clearly trying to create a new file.

I agree.

>  Perhaps it would be better to keep things simple and let user do whatever they want here.

Maybe once you improve the logic, this case will no longer be relevant? If the Editor knows that the user is creating a new nameless file, while another nameless file is open, it doesn't need to display this dialog.

**Comment by alabuzhev** [comment]
> That would be great!

6184, but beware of bugs.

> Maybe once you improve the logic, this case will no longer be relevant?

Not yet, but we can come up with something. I've removed the check for now.

**Comment by rohitab** [comment]
Perfect!

I just tested version `3.0.6184.0 x64` and everything appears to be working correctly. I tried an empty string and a `?` for the template, and both work correctly. I also tried with a couple of different plugins and code pages.
