### ISSUE TITLE
Different Internal Editor "expand tabs" settings for different file extensions

### ISSUE THREAD

**Issue by guban** [FarGroup/FarManager#737]
### Description of the new feature or improvement

It would be nice to expand tabs to spaces for .py files (Python source code), but keep tabs for all other file extensions.
Presently, Far allows only one global setting that applies to all files.

**Comment by johnd0e** [comment]
This and all similar tasks are usually solved with help of some plugin or script, e.g.:
- https://plugring.farmanager.com/plugin.php?pid=364&l=en
- https://github.com/trexinc/evil-programmers/blob/master/LuaEditorSettingsCore/Macros/modules/editorsettings/python.moon

it also possible to implement with rather simple macro.

**Comment by guban** [comment]
The simple macro works for me. Thank you very much, @johnd0e!
