### ISSUE TITLE
Problem with relative paths in arguments if running from directory with full path longer than MAX_PATH chars

### ISSUE THREAD

**Issue by M0sc** [FarGroup/FarManager#74]
If command or application is running from current directory with full path longer than MAX_PATH chars using command line with arguments with relative paths then these relative paths couldn't be properly converted to full Win32 paths (using \\\\?\\ prefix) since current directory is not set as expected. This issue occured because of using ShellExcecuteExW API.
https://github.com/FarGroup/FarManager/blob/94d0bb66d59707fb0e7f5440ee06d85e9eded35f/far/execute.cpp#L1002
This API doesn't support paths longer than MAX_PATH in lpDirectory member of _SHELLEXECUTEINFOW structure. The code in _SetWorkingDir method of CShellExecute class in shell32.dll performs the following (Windows 7 SP1 reversing using WinDbg):

1) copy path from lpDirectory to internal class member calling StringCchCopyW API with cchDest == MAX_PATH (first error for path longer than MAX_PATH);
2) check if path exists calling PathIsDirectoryW API from shwapi.dll (second error for path longer than MAX_PATH since pszPath parameter of this API must be a pointer to a null-terminated string of maximum length MAX_PATH);
3) if path not exists then call the PathGetDriveNumberW API from shwapi.dll and if it returns value >=0 set internal class member equal to root directory using call of PathStripToRootW API from shwapi.dll.

This code completely damaged working directory passed from FAR and then internal class member mentioned is used as lpCurrentDirectory parameter in call of CreateProcessW API from kernel32.dll. Thus current directory of child proccess (CurrentDirectory member of _RTL_USER_PROCESS_PARAMETERS structure pointed by ProcessParameters member of PEB structure) is set to wrong path.

Steps to reproduce:
1) create directory with path longer than MAX_PATH chars if it is not exists;
2) set it as current directory in active panel;
3) execute the following from command line: "robocopy . . /quit";
4) look at  path of "Source" and "Dest" in output.

Note for developers of applications which assumed to properly handle paths longer than MAX_PATH: do not use shell APIs that are limited to MAX_PATH (many if not even all of those which are using paths in parameters).

**Comment by alabuzhev** [comment]
Thanks for the report, but I don't think we can fix this - as you've already mentioned, Windows can't set the actual path, and setting anything else will not be what the user expected.

One possible workaround is to use a short path ("c:\blabla~1") if the full path is longer than MAX_PATH.
However, it would only delay the inevitable.
