### ISSUE TITLE
Shortname filename Panel

### ISSUE THREAD

**Issue by TorakikiSan** [FarGroup/FarManager#742]
### Far Manager version

3.0.6194.0

### OS version

10.0.19045.3570

### Other software

No other softwares

### Steps to reproduce

Simply, start the program

### Expected behavior

Nomal file panel with long name

### Actual behavior

Normal file panel with short name (like "PROGRA~2" instead of "Program Files"). See the attached image

Thanks

![SharedScreenshot](https://github.com/FarGroup/FarManager/assets/37299746/96faaae7-d69c-4fe2-bfda-e41fc4d2fe94)

**Comment by alabuzhev** [comment]
You probably pressed <kbd>Ctrl</kbd>+<kbd>N</kbd> accidentally. Press it again.

**Comment by TorakikiSan** [comment]
You are right!
It's fine now, thanks

**Comment by TorakikiSan** [comment]
You are right!
It's fine now, thanks
