### ISSUE TITLE
Reverse search missing/not working anymore

### ISSUE THREAD

**Issue by AndreyRa** [FarGroup/FarManager#743]
### Far Manager version

3.0.6161.0

### OS version

10.0.17763.316]

### Steps to reproduce

Open text file
F7
Alt-v for revese search
Shif-F7 for repeat last search - work on forward direction, not reverse.

### Expected behavior

Previous versions (3.0.6000.0 and earlier) had a reverse search option that worked repeatedly using Shift-F7 combination.
This version does not has this function.
Now I cannot search the log files backwards.

### Actual behavior

Repeated search works only in the forward direction.

**Comment by yegor-mialyk** [comment]
A newer version no longer features the `[x] Reverse search` option. Instead, it now offers `[ Find previous ]` and `{ Find next }` actions. The shortcut `Shift+F7` continues to facilitate forward search, while `Alt+F7` enables backward search.

**Comment by AndreyRa** [comment]
Oh, thanks for the quick response.
Sorry for the inconvenience, I missed this change.

**Comment by MKadaner** [comment]
Mentioning #646 for completeness.
