### ISSUE TITLE
Far switch `-set` ignored when used together with panel path arguments

### ISSUE THREAD

**Issue by nightroman** [FarGroup/FarManager#746]
### Far Manager version

Far Manager, version 3.0.6208.0 x64

### OS version

Microsoft Windows [Version 10.0.19045.3570]

### Steps to reproduce

The switch `-set` is respected in this command

```
far -set:Panel.Left.Visible=false
```

The switch `-set` is ignored in this command (one or two panel paths are specified)

```
far . -set:Panel.Left.Visible=false
```

### Expected behavior

`-set` should work with or without panel paths in the command line

### Actual behavior

`-set` works only without panel paths in the command line

**Comment by nightroman** [comment]
And this still does not work as I expect:
```
far -set:Panel.Left.Visible=false .
```

**Comment by alabuzhev** [comment]
> And the topic is not clear about this detail

Yes, it probably should say something like
```DIFF
- It is possible to specify at most two paths (to folders, files or archives) or two commands with plugin prefix in the command line.
+ It is possible to specify at most two paths (to folders, files or archives) or two commands with plugin prefix after the switches in the command line.
```

Better wordings, alternative suggestions, and PRs are welcome.

**Comment by alabuzhev** [comment]
> And this still does not work as I expect:
> 
> ```
> far -set:Panel.Left.Visible=false .
> ```

I guess your active panel is left in the config.

**Comment by nightroman** [comment]
> > And this still does not work as I expect:
> > ```
> > far -set:Panel.Left.Visible=false .
> > ```
> 
> I guess your active panel is left in the config.

Not sure I understand.

This works, both panels are hidden:
```
far -set:Panel.Left.Visible=false -set:Panel.Right.Visible=false
```

This does not, both panels are visible:
```
far -set:Panel.Left.Visible=false -set:Panel.Right.Visible=false . .
```

**Comment by nightroman** [comment]
Also, this works, Far starts with active panel at C:\tmp and without plugins:
```
far C:\tmp -p
```

So that switches, at least some, may be specified after panel paths (and to be honest, this is rather expected behavior).

**Comment by alabuzhev** [comment]
> Also, this works

Yes, I've double checked and it's actually supported, you can mix them as you like, sorry for the confusion.

> Not sure I understand.

Specifying active or passive panel path makes that panel visible.
`far . -set:Panel.Left.Visible=false` = *"please make left panel invisible and show `.` on the active panel (which makes that panel visible)"*.
If the active is left it will make it visible again.
You can check that -set works by hiding the right panel instead.

**Comment by nightroman** [comment]
Right... it's getting clearer but not quite better.
How do I start Far with two specified paths and hidden panels?

The use case is https://github.com/FarGroup/FarManager/discussions/740 In VSCode terminal window I'd like to use Far as command line on steroids. I need the current path and no panels shown. How to achieve this?

**Comment by alabuzhev** [comment]
> How do I start Far with two specified paths and hidden panels?

`far -set:Panel.Left.Visible=false -set:Panel.Right.Visible=false -set:Panel.Left.Folder=dir1 -set:Panel.Right.Folder=dir2`

**Comment by nightroman** [comment]
@alabuzhev Great, thank you!

**Comment by yegor-mialyk** [comment]
BTW, @nightroman shared the command line below:

`Far.exe -set:Panel.Left.Folder=. -set:Panel.Right.Folder=.`

Although it's functional, the initial display shows an unattractive directory title `.` in the panel and a command prompt labeled `.>`. Refer to the example given. This aesthetic issue might be something we want to consider addressing within Far Manager.

```
╔═════════════════════╦══════════ . ════════╦══════════════════════╗
║n       Name         ║        Name         ║         Name         ║
║..                   ║                     ║                      ║
...
...
╚════════════ 4,851,858,542 (12/0) ═══ 153,708,863,488 ════════════╝
.>
```

**Comment by alabuzhev** [comment]
lol

Doing this via -set is somewhat hacky after all: Panel.*.Folder are not exposed to the user normally and far doesn't expect funny unprocessed paths there.

**Comment by nightroman** [comment]
@alabuzhev How to achieve this: start Far with both panels hidden and invoke a plugin command?
Naïve approach 
```
far -set:Panel.Left.Visible=false -set:Panel.Right.Visible=false lua:=42
```
is not quite right, one panel is shown and then the plugin command is invoked.

**Comment by nightroman** [comment]
> Specifying active or passive panel path makes that panel visible.

I start to think that this Far behaviour is questionable, Far is too creative in doing what was not really asked.

**Comment by yegor-mialyk** [comment]
I think Far just treats `lua:=42` as a "path", turns on a panel and run a lua expression. Same as
`far -set:Panel.Right.Visible=false -set:Panel.Left.Visible=false f:\ c:\`
will show both panels.

**Comment by nightroman** [comment]
> I think Far just treats lua:=42 as a "plugin path"

Yes... Like I said, Far is too creative in doing what was not asked... This is not always "useful".

**Comment by nightroman** [comment]
All in all, the question "How to start Far with both panels hidden and invoke a plugin command without showing a panel?" describes a practically useful case. And the answer is probably "there is no easy way of doing this".

**Comment by alabuzhev** [comment]
Creativeness is here:
https://github.com/FarGroup/FarManager/blob/adb8db1f6804ff04438ba2226d0b0f53d3b0ade3/far/main.cpp#L234

It was introduced here 20+ years ago:
https://github.com/FarGroup/FarManager/commit/9e2f8aa0b8f379e03a4e2036e7a33f61f2d85acc#diff-bc3a65d3cea6b0b39e533489cb794d36d81c61e7c8a31983e731ba351656f0b1R609

The description is quite mouthful, but doesn't really answer "why".

Doing this:

```DIFF
diff --git a/far/main.cpp b/far/main.cpp
index 321832f6c..0776de5b9 100644
--- a/far/main.cpp
+++ b/far/main.cpp
@@ -231,7 +231,6 @@ static int MainProcess(
 
 				auto& CurrentPanelOptions = (Global->Opt->LeftFocus == active)? Global->Opt->LeftPanel : Global->Opt->RightPanel;
 				CurrentPanelOptions.m_Type = static_cast<int>(panel_type::FILE_PANEL);  // сменим моду панели
-				CurrentPanelOptions.Visible = true;     // и включим ее
 				CurrentPanelOptions.Folder = strPath;
 			};
 
```
seemingly fixes the issue and doesn't break anything else, but I haven't checked thoroughly.
Try it yourself, if everything is ok, I wouldn't mind removing that line (a PR is welcome).

**Comment by nightroman** [comment]
Thank you for the kind invitation but Far development is too much for me.

I'll figure out some hard way, e.g. a workaround feature in PowerShellFar. My case requirements also include controlling which panel / path is active exactly. Far switches deal with left and right panel which may not be active kind of "randomly". It's all too complicated.

**Comment by alabuzhev** [comment]
@yegor-mialyk any news?

**Comment by yegor-mialyk** [comment]
I tried several different combinations, and everything works well. However, I would suggest a small UX improvement: set the focus on the panel that is currently visible, in case you run the command below and your left panel previously had focus:

```
Far.exe -set:Panel.Left.Visible=false .
```

Something like the following, but I’m not sure if it is the right place for it, maybe it should be done after the `SetupPanel()` calls:

```diff
diff --git a/far/main.cpp b/far/main.cpp
index 48d7c9847..c9a4a5efe 100644
--- a/far/main.cpp
+++ b/far/main.cpp
@@ -228,8 +228,16 @@ static int MainProcess(
 
 				auto& CurrentPanelOptions = (Global->Opt->LeftFocus == active)? Global->Opt->LeftPanel : Global->Opt->RightPanel;
 				CurrentPanelOptions.m_Type = static_cast<int>(panel_type::FILE_PANEL);  // сменим моду панели
-				CurrentPanelOptions.Visible = true;     // и включим ее
 				CurrentPanelOptions.Folder = strPath;
+
+				if (Global->Opt->LeftPanel.Visible && !Global->Opt->RightPanel.Visible)
+				{
+					Global->Opt->LeftFocus = true; // focus left if only left is visible
+				}
+				else if (!Global->Opt->LeftPanel.Visible && Global->Opt->RightPanel.Visible)
+				{
+					Global->Opt->LeftFocus = false; // focus right if only right is visible
+				}
 			};
 
 			if (!apanel.empty())
```

**Comment by alabuzhev** [comment]
> > Specifying active or passive panel path makes that panel visible.
> 
> I start to think that this Far behaviour is questionable, Far is too creative in doing what was not really asked.

6525.

**Comment by nightroman** [comment]
Thank you! One issue less, very good progress.

Q: This PowerShell command (needs FarNet.PowerShellFar module) is not working as expected:

```powershell
	far @(
		'-ro'
		'-set:Panel.Left.Folder=\ROM'         # not full path panel title
		'-set:Panel.Right.Folder=\ROM\FarDev' # not full path panel title
		'-set:Panel.Left.Visible=false'
		'-set:Panel.Right.Visible=false'
		'-set:Panel.LeftFocus=true'
		'ps:$Far.Panel.CurrentDirectory'
		'ps:$Far.Panel2.CurrentDirectory'
	)
```

It starts Far with panels hidden (OK) but `ps:` commands both print `C:\Bin\Far\x64` (not OK) and if we make panels visible then they are both `C:\Bin\Far\x64`.

What's wrong and how to make it right?
(I expect one command prints `C:\ROM` and another `C:\ROM\FarDev` and panel paths are set to these paths).

**Comment by yegor-mialyk** [comment]
I think either
```
far -set:Panel.Left.Folder=C:\ROM -set:Panel.Right.Folder=C:\ROM\FarDev -set:Panel.Left.Visible=false -set:Panel.Right.Visible=false
```
or
```
far -set:Panel.Left.Visible=false -set:Panel.Right.Visible=false C:\ROM C:\ROM\Dev
```

**Comment by nightroman** [comment]
Ah. Maybe I was not clear enough. I want all the parameters, not some of them. I.e. all `-set` parameters and two `ps:` parameters. I.e. I want to setup the panels and then execute plugin commands with that panels set. It's rather a natural use case to me.

Commands like `ps:$Far.Panel.CurrentDirectory` above are just examples and also to show the problem. In reality I'd use more practical commands instead. And usually one command, of course, not two. But two commands are also possible in some cases.

**Comment by alabuzhev** [comment]
> `'-set:Panel.Left.Folder=\ROM'         # not full path panel title`

Probably https://github.com/FarGroup/FarManager/issues/746#issuecomment-1802638716

**Comment by nightroman** [comment]
Yes. I made that comments as the reminder "to whom it may concern", sorry for that :)
