### ISSUE TITLE
Build 6209 crashes on start with the profile from build 5629

### ISSUE THREAD

**Issue by shmuz** [FarGroup/FarManager#747]
### Far Manager version

3.0.6209.0 x86

### OS version

Microsoft Windows [Version 10.0.22621.2428]

### Steps to reproduce

1. Run fresh Far b6209 with profile from b5629 (`Far.exe -p`)
2. Observe immediate crash.
3. Same behavior with /export from b5629 and then /import to b6209.

### Actual behavior

Crash.

**Comment by shmuz** [comment]
[bug_report.txt](https://github.com/FarGroup/FarManager/files/13326517/bug_report.txt)
[README.txt](https://github.com/FarGroup/FarManager/files/13326518/README.txt)

**Comment by alabuzhev** [comment]
Seeing the problematic config would help.
At least everything under `<setting key="Panel.SortLayers" ...`.
(removing those items might help as well)

**Comment by shmuz** [comment]
```
        <setting key="Panel.SortLayers" name="0" type="text" value=""/>
        <setting key="Panel.SortLayers" name="1" type="text" value="1"/>
        <setting key="Panel.SortLayers" name="10" type="text" value="2 1"/>
        <setting key="Panel.SortLayers" name="11" type="text" value="2 1"/>
        <setting key="Panel.SortLayers" name="12" type="text" value="2 1"/>
        <setting key="Panel.SortLayers" name="13" type="text" value="3 1"/>
        <setting key="Panel.SortLayers" name="14" type="text" value="2 1"/>
        <setting key="Panel.SortLayers" name="2" type="text" value="14 1"/>
        <setting key="Panel.SortLayers" name="3" type="text" value="2 1"/>
        <setting key="Panel.SortLayers" name="4" type="text" value="2 1"/>
        <setting key="Panel.SortLayers" name="5" type="text" value="2 1"/>
        <setting key="Panel.SortLayers" name="6" type="text" value="2 1"/>
        <setting key="Panel.SortLayers" name="7" type="text" value="2 1"/>
        <setting key="Panel.SortLayers" name="8" type="text" value="2 1"/>
        <setting key="Panel.SortLayers" name="9" type="text" value="2 1"/>
```

**Comment by alabuzhev** [comment]
5629 doesn't have the code that could produce these records, they are from one of the newer builds, likely 5631.

But anyway, 6210.

**Comment by shmuz** [comment]
> 5629 doesn't have the code that could produce these records

It may be so. I started to use 5629 as my work horse (and put its profiles aside) a few (may be 10-20) builds later, therefore its profiles could be affected by those builds.
And thanks for the fix, I'm going to look at 6210 tomorrow.

**Comment by shmuz** [comment]
6210 does not crash.
