### ISSUE TITLE
Crash with MsiUpdate 1.4.0.5 with new version

### ISSUE THREAD

**Issue by BestiaPL** [FarGroup/FarManager#755]
### Far Manager version

3.0.6221.3573

### OS version

10.0.19041.3324

### Steps to reproduce

After update Far from version 3.0.6216 and run I've got crach error in plugin MsiUpdate
This plugin is really old (from year 2017) and has no update.

Crash report:
[Far_20231201_074228706_6612.zip](https://github.com/FarGroup/FarManager/files/13522413/Far_20231201_074228706_6612.zip)

### Actual behavior

Crash when running Far.

**Comment by alabuzhev** [comment]
![Deja vu](https://github.com/FarGroup/FarManager/assets/11453922/7ad4d5e8-bc43-47bb-b092-5caadaf0a5ee)

Looks like a duplicate of #313

**Comment by w17** [comment]
Really looks :)
@BestiaPL, I didn't update and upload this plugin anymore.
If you lost latest version (1.4.6) I can rebuild it for you...
But really I think that Renewal is better choice.
It can now update .MSI installed Far too...

**Comment by BestiaPL** [comment]
OK :)
So, I've deleted plugin.

Issue closed.
