### ISSUE TITLE
Обнаружил что пропал детектор IO_REPARSE_TAG_DEDUP

### ISSUE THREAD

**Issue by check4game** [FarGroup/FarManager#758]
Доброе время суток, 

https://github.com/FarGroup/FarManager/blob/81c9c659889c65e404ddf8d79514a175b5ea0789/far/setattr.cpp#L861-L867

хотел бы прояснить, зачем убрали этот код? 

в текущей версии для таких файлов в диалоге атрибутов в качестве имени отображаются "(data not available)", 
хотя ранее отображалось DEDUP...

**Comment by alabuzhev** [comment]
The intention was to show [all known tags](https://github.com/FarGroup/FarManager/blob/e5ebcd772c8bfc58db24c6f8e6547e3700c9fd74/far/flink.cpp#L704-L851) there, not only dedup. Looks like the rest of the change got lost along the way.

6222.
