### ISSUE TITLE
Wrong color of selected files and directories

### ISSUE THREAD

**Issue by kn-nikolaev** [FarGroup/FarManager#761]
### Far Manager version

3.0.6208.3532

### OS version

10.0.19045.3803

### Steps to reproduce

Select any file or directory.
Far shows selected items as "black on background color".
![6208](https://github.com/FarGroup/FarManager/assets/154007985/6dd4faa0-5cb5-47a7-b5f7-3c9a61abb01b)

Before this version Far showed selected items as "yellow on background color".
![6207](https://github.com/FarGroup/FarManager/assets/154007985/c5f51184-71d0-4798-a724-ff1527acb46b)

I can activate "Options"-"Files highlighting and sort groups"-"group"-"3. Selected file name"-"Background" to workaround. Previous versions didn't require this action.

### Expected behavior

"Yellow on background color" for selected items.

### Actual behavior

"Black on background color" for selected items.

**Comment by yegor-mialyk** [comment]
@kn-nikolaev, please take a look at the recent issue: https://github.com/FarGroup/FarManager/issues/759

**Comment by kn-nikolaev** [comment]
This is quite unexpected. Thank yoy!
