### ISSUE TITLE
"Find All" list is truncated from the top on a short screen.

### ISSUE THREAD

**Issue by MKadaner** [FarGroup/FarManager#769]
### Far Manager version

3.0.6240.0

### OS version

10.0.22621.2861

### Steps to reproduce

1. Resize Far console windows to 15 lines tall.
2. Edit a file with a certain text fragment repeats multiple times.
3. Search for this repeated pattern and press `All` button.
4. Observe the "Find All" is shifted way up the screen and truncated at the top.

### Actual behavior

![image](https://github.com/FarGroup/FarManager/assets/35671029/ee65f298-6638-40a8-bcb4-3438b98999a1)

![image](https://github.com/FarGroup/FarManager/assets/35671029/2572cf4d-afa8-45be-857a-db3fd58ee2ca)

![image](https://github.com/FarGroup/FarManager/assets/35671029/78c19911-aaa2-4063-a639-b46e78e93c9b)

**Comment by MKadaner** [comment]
The issue actually goes back at least as far as 3.0.6000.0. I did not dig deeper into the history.

**Comment by alabuzhev** [comment]
https://github.com/FarGroup/FarManager/blob/98c87eedeae30934a745680fd7666eee8a37997d/far/editor.cpp#L3750

Well, 14 - 20 will be outside the screen indeed. At least we don't crash.

As far as I remember, [the idea](https://github.com/FarGroup/FarManager/commit/f67fd2471c5a323f877ebc938853c676d12eb4c8#diff-23da63b3a468b0aacf55ea8ab4991fda026cfee63a88ec33df80f7e70ac16727R3786-R3787) was to move the list down to not obscure the editor and see some context.

**Comment by alabuzhev** [comment]
6241

**Comment by MKadaner** [comment]
Thank you!
