### ISSUE TITLE
3.0.5300: Поломался Save file position в просмотровщике (F3)

### ISSUE THREAD

**Issue by vmech** [FarGroup/FarManager#77]
Независимо от положения переключателя Options / Viewer settings / Save file position позиции в просмотренных файлах сохраняются на всё время сессии FAR'а.
**Viewer.SaveViewerPos** так же не оказывает влияния на поведение.

Такое поведение вызывает установленный (_не сброшенный **принудительно вручную**_) Options / Viewer settings / Save bookmarks (он же **Viewer.SaveViewerShortPos**).

**ЗЫ.** Я предлагаю оставлять эти флаги сброшенными в чистой дефолтной конфигурации. Дабы не писать «лишнего» на диск пользователя. И для редактора в том числе. Кому нужно, тот сам всё установит, сохранит, и экспортирует «на будущее».

**Comment by w17** [comment]
5309

**Comment by w17** [comment]
Сбрасывать все  опции - это точно не для большинства пользователей.
К тому же задача 'не писать ничего' проще и надежнее достигается запуском **far -ro**.
