### ISSUE TITLE
Some dialogs are not centered after resizing

### ISSUE THREAD

**Issue by yulian5** [FarGroup/FarManager#773]
### Far Manager version

3.0.6249.0

### OS version

Windows 10, 11

### Steps to reproduce

With any open static dialog (except copy/move/delete progress dialogs) try to resize Far3 window. Progress dialogs (copy/move/delete) are constantly updated and stay in the center.

### Expected behavior

Dialog which is originally in the center should be in center after resizing.

### Actual behavior

Dialog is displayed in wrong position based on action (increased or reduced size). In some cases dialog will be placed outside of visible area.

![Far3_Dialog1_Resized](https://github.com/FarGroup/FarManager/assets/13651587/a665b726-6ff7-4c6d-bf0c-78d82aa29164)

<img width="842" alt="Far3_Dialog2" src="https://github.com/FarGroup/FarManager/assets/13651587/9abee3b2-f56e-4479-9861-4285501332a9">

**Comment by alabuzhev** [comment]
> dialogs are not centered after resizing

This is intentional.

> Progress dialogs (copy/move/delete) are constantly updated and stay in the center

They stay in the center because they are fake dialogs and the user cannot reposition them manually.

> In some cases dialog will be placed outside of visible area.

Partially, but never entirely.

**Comment by yulian5** [comment]
> Partially, but never entirely.

@alabuzhev, can you see what dialog on the screen?

<img width="723" alt="Far3 copy4" src="https://github.com/FarGroup/FarManager/assets/13651587/cdd9ecf9-5f34-45ed-ac1e-e6a2fec2a6b9">

**Comment by yulian5** [comment]
@alabuzhev 

> >dialogs are not centered after resizing

> This is intentional.

May I ask what is the intention? Especially to have only a half of dialog visible? Or only a border?

**Comment by alabuzhev** [comment]
> can you see what dialog on the screen?

The one that was visible before the resize obviously.

> May I ask what is the intention? Especially to have only a half of dialog visible? Or only a border?

Not all dialogs are centered. In some cases the arrangement is important (e.g. options - colors).

However, dialogs that were *initially* centered (and not moved manually later) should probably remain centered in this case.

**Comment by johnd0e** [comment]
> However, dialogs that were initially centered (and not moved manually later) should probably remain centered in this case.

Good point

**Comment by HamRusTal** [comment]
> > Progress dialogs (copy/move/delete) are constantly updated and stay in the center
> 
> They stay in the center because they are fake dialogs and the user cannot reposition them manually.

Technically, Copy/Move (not sure about Delete) progress dialogs are real and can e.g. be [resized/moved by a scripted event](https://forum.farmanager.com/viewtopic.php?p=176983#p176983). It's only some peculiarity of input event handling that these dialogs don't accept user-initiated repositioning.

**Comment by alabuzhev** [comment]
> dialogs that were initially centered (and not moved manually later) should probably remain centered in this case.

Build 6251.
Since the vast majority of dialogs are initially centered, this may as well resolve this issue.

**Comment by yulian5** [comment]
It looks like fixed except "Quit" dialog which probably doesn't make any sense to resize anyway.

**Comment by alabuzhev** [comment]
> except "Quit" dialog

Good catch, thanks.
6257.

**Comment by yulian5** [comment]
@alabuzhev Thanks for quick fixes!

> Good catch, thanks.

Much appreciated! (pressed wrong button during debugging)
