### ISSUE TITLE
Copy Dialog enhancement: Save user choice for existing files

### ISSUE THREAD

**Issue by yulian5** [FarGroup/FarManager#775]
### Description of the new feature or improvement

I'd like to offer for your judgment a few Copy Dialog enhancements. This is the second one.

In my style of work I rather creates new files than modify the existing ones. So every time I copy something I need to change option for existing files from "Ask" to "Skip" either in Copy dialog or in Warning about existing file dialog. As I do it hundreds times a day it's quite annoying. And I'm sure other users have their own preferences (like overwrite or Only newer files). 

And another thing, actions with similar pattern are repeated usually, and the user can change the option any time.

It's actually a little inconsistent: the option "Preserve timestamps" is saved without even asking and the option about "Already existing files:" is not saved but doesn't even have that possibility in the dialog.

<img width="572" alt="240113 Far2 Copy Dialog2" src="https://github.com/FarGroup/FarManager/assets/13651587/34dfc071-7a75-4b70-988d-5dd8072a3e9a">

If in option "Already existing files:" user selects non-default choice (anything except "Ask") suggestion is:

1. save the user choice
2. highlight it with different color, so next time it will be obvious that the action is not the default one

**Comment by yegor-mialyk** [comment]
Why not to use a simple macro? I personally have one for "Overwrite" mode (CtrlAltF5).

**Comment by yulian5** [comment]
@yegor-mialyk 
That is just prove the point: using macro is a workaround and using it for that simple task means that copy dialog is not very well organized. Just think about it: we have dialog with number of options and using the personal macro means that those options do not fit your task or so (awkwardly) designed that it force you to use macro instead of direct controls.

And anyway in that case why do we need dialogs at all? Just have API with commands and options and assigning macros to them will do any possible task without any dialogs at all.

I'm trying to improve this dialog as a starting point. Far UI is dated like 25-30 years ago and may be improved significantly making it more powerful and faster. Muscle memory used to press dozen buttons multiple times for a simple task is better to reroute for something more useful and avoid hand spasm and save a little time for some other fun.

Most even very advanced users do not create macros for such kind of tasks. It looks more natural just to press dozen buttons in the dialog. And even if you create macros for some task, all other dialogs still need your time.

Let say you spend 2 hours a day using Far. Increasing Far performance only 10% give you 12 min of free time a day, or about 3 days in an year. It means that you don't need to spend 3 whole days every year just pressing buttons and selecting controls. If you use Far more that 2 hours a day then make you estimate.

**Comment by MKadaner** [comment]
If cutting off the time necessary to select the right option in a combobox gives you overall 10% performance improvement, your use case is a bit too narrow, and a macro is probably the right answer.

**Comment by yulian5** [comment]
@MKadaner, as I mentioned in another post using macros in standard copy dialog means that dialog itself need improvements, what was my point in the first place. Unfortunately I cannot actively participate in the development now so I'm just posting some issues hoping that somebody will fix them if they feel that way. Otherwise I can work on those issues later by myself.

**Comment by yulian5** [comment]
@yegor-mialyk 

> Why not to use a simple macro? I personally have one for "Overwrite" mode (CtrlAltF5).

You're guys are super supportive! For almost all issues I received a possible workaround or suggestion.

But I'm a little confused about that. Is it so difficult to change something? Or doesn't make any sense as everybody got used to use it as is. Like it's OSS and be happy to use it as is. 

It looks like you're not very satisfied with Copy dialog options in some way. And you're making a lot of development by yourself. But in this case (and probably some others) you didn't rise a red flag for possible improvements. May I ask out of curiosity why?

**Comment by yegor-mialyk** [comment]
First of all, thousands of users rely on muscle memory when copying or moving files in Far Manager. I personally use `F5 Enter` all the time and don't pay attention to what is selected in the dialog. For me, "keeping" selected options between Copy sessions would represent a significant change (so it's an absolute **NO** from me on that one).

Second, regarding UI improvements, you suggest replacing a dropdown with radio buttons. While it's often beneficial to save a click or a keypress, I'm not convinced of the advantages in this particular instance. I believe that 100% of users in 99% of their day-to-day tasks do not adjust this setting. Your workflow may be quite distinct from that of others, which is perfectly okay. However, I still think that if you really chnage the 'Already existing files' option multiple times a day, a key macro would be more beneficial for you, even if radio buttons were to replace a dropdown tomorrow.

Third, altering the UI is likely to make hundreds of users unhappy because some will have macros that become broken, while others have developed muscle memory for selecting those options, and so on.

**Comment by yulian5** [comment]
@yegor-mialyk, thank you for your opinion.

> I personally ... don't pay attention to what is selected in the dialog.

That is bad. I bet most users still need dialogs with options.

> I believe that 100% of users in 99% of their day-to-day tasks do not adjust this setting.

Then what, let remove redundant settings?

Probably, at all times there have been people who actively resist any change, relying on muscle memory and developed habits, but I’m glad that our ancestors were not like that, otherwise we would still be in the Stone Age.

I'm even afraid now to offer more radical changes to Far UI. Did you notice for example, that Far has 2 config menus? Archaic confusing F9 and unfinished far:config? I bet you'll say we need both.

**Comment by lowtrucks** [comment]
lol. why not just ban this annoying idiot?

**Comment by yulian5** [comment]
@lowtrucks 

Anton, I like Far 3 and trying to make it better.
Is a personal insult your best argument in discussion?

**Comment by yulian5** [comment]
@alabuzhev

I'll stop posting anything from now on. This behavior by Anton @lowtrucks is unacceptable.

**Comment by lowtrucks** [comment]
> I'll stop posting anything from now on.

thank you!

**Comment by yegor-mialyk** [comment]
> Then what, let remove redundant settings?

Did I suggest to remove those settings? Did I call them redundant? They are still there for you and me.

> that Far has 2 config menus? Archaic confusing F9 and unfinished far:config

Create a separate ticket or discussion as this is not related to the Copy dialog, and will share my opinion there. As I understand you do not like both.

**Comment by alabuzhev** [comment]
> lol. why not just ban this annoying idiot?

Please behave or I'll follow your suggestion.

**Comment by yulian5** [comment]
@yegor-mialyk 

Thank you for your valuable input. It's always nice and often productive to discuss with reasonable intelligent people.

**Comment by yulian5** [comment]
This suggested feature doesn't have enough community support.

**Comment by HamRusTal** [comment]
@yulian5 Shouldn't this Issue be closed as Not Planned rather than Completed?

**Comment by yulian5** [comment]
@HamRusTal You're absolutely right.
