### ISSUE TITLE
Enable selection of compression methods for Zip archives

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#781]
### Description of the new feature or improvement

If you create a new Zip archive, or if you add new files to an existing Zip archive, the _Method_ dropdown is disabled. All files in the Zip archive are added using the `Deflate` method. However, it is possible to change the method using _Advanced parameters_. In contrast, if you create a 7-Zip archive, the _Method_ dropdown is enabled, and allows you to choose from built-in or external methods.

I believe it would be useful to enable the _Method_ dropdown for Zip archives as well. This would allow the user to select the method in the _Create archive_ and _Add files to archive_ dialogs.

### Proposed technical implementation details (optional)

The core implementation is already present in the code. What is needed is to make changes to the user interface. I made some modifications to the code, as shown in the patch below. With these changes, you can now select the _Method_ while creating or adding files to Zip archives.

This patch also enables the `Deflate` and `Deflate64` (Enhanced Deflate) compression methods for 7-Zip archives.

Most of the changes are straightforward. The only other change I made was to automatically switch the _Method_ when using _Select archiver_ to switch between `7z` and `zip`. This was done to avoid changing the current functionality. So, for example, if you select the `zip` archiver, the `Deflate` method is automatically selected. If you select the `7z` archiver, the `LZMA` method is automatically selected. However, if you manually change the method, say to `PPMD`, it will remain as such, and not change when switching archivers.

### Binaries for Testing
I've compiled the 64-bit version of ArcLite with this patch. The binaries are attached below. I've also included support for the `ZSTD` format. Please note that the `ZSTD` format is an external _Format_ plugin, and is in no way integrated with code. I'm only including it here so you can try compressing Zip archives using `ZSTD` for testing.

All these archives can be opened in ArcLite. The Zip archives compressed with `Deflate`, `Deflate64`, and `PPMD` can also be opened in Windows Explorer. Archives compressed with `ZSTD` can be also be opened in WinZip, without any additional plugins.

To install, extract the attached [`far-arclite-zip-zstd-x64.zip`](https://github.com/FarGroup/FarManager/files/14070708/far-arclite-zip-zstd-x64.zip) and replace all the files in `%FARHOME%\Plugins\arclite`. I would suggest testing with the latest version of Far Manager, version `3.0.6260.0 x64`.

### Minor Bug in Existing Code
While changing the code, I came across a minor issue. The following should use a logical operator `&&` instead of a bitwise operator `&`. I've fixed this in the patch as well.

https://github.com/FarGroup/FarManager/blob/8484c300b8413d65950ceece686e2f34b4a597ea/plugins/arclite/ui.cpp#L856

### Attached Files

 * [`arclite-zip-methods.patch`](https://github.com/FarGroup/FarManager/files/14070706/arclite-zip-methods.patch)
 * [`far-arclite-zip-zstd-x64.zip`](https://github.com/FarGroup/FarManager/files/14070708/far-arclite-zip-zstd-x64.zip)

### Patch
This patch has been tested with Far Manager, version `3.0.6260.0 x64`, which is the most recent version.

```diff
diff --git a/plugins/arclite/archive.cpp b/plugins/arclite/archive.cpp
index 79c234dd9..5096de312 100644
--- a/plugins/arclite/archive.cpp
+++ b/plugins/arclite/archive.cpp
@@ -12,6 +12,8 @@ const wchar_t* c_method_copy   = L"Copy";
 const wchar_t* c_method_lzma   = L"LZMA";
 const wchar_t* c_method_lzma2  = L"LZMA2";
 const wchar_t* c_method_ppmd   = L"PPMD";
+const wchar_t* c_method_deflate = L"Deflate";
+const wchar_t* c_method_deflate64 = L"Deflate64";
 
 #define DEFINE_ARC_ID(name, v) \
 static constexpr unsigned char c_guid_##name[] = "\x69\x0F\x17\x23\xC1\x40\x8A\x27\x10\x00\x00\x01\x10" v "\x00\x00"; \
diff --git a/plugins/arclite/archive.hpp b/plugins/arclite/archive.hpp
index 2be2bf153..e5f5f528c 100644
--- a/plugins/arclite/archive.hpp
+++ b/plugins/arclite/archive.hpp
@@ -31,6 +31,8 @@ extern const wchar_t* c_method_copy;   // pseudo method
 extern const wchar_t* c_method_lzma;   // standard 7z methods
 extern const wchar_t* c_method_lzma2;  //
 extern const wchar_t* c_method_ppmd;   //
+extern const wchar_t* c_method_deflate;
+extern const wchar_t* c_method_deflate64;
 
 extern const UInt64 c_min_volume_size;
 
diff --git a/plugins/arclite/arclite_bel.lng b/plugins/arclite/arclite_bel.lng
index 77fcb2cf6..29eb8535c 100644
--- a/plugins/arclite/arclite_bel.lng
+++ b/plugins/arclite/arclite_bel.lng
@@ -83,6 +83,8 @@
 "LZMA"
 "LZMA2"
 "PPMD"
+"Deflate"
+"Deflate64"
 
 // Delete files
 "Вы жадаеце выдаліць абраныя файлы?"
diff --git a/plugins/arclite/arclite_eng.lng b/plugins/arclite/arclite_eng.lng
index 9676ed338..1a5e612e1 100644
--- a/plugins/arclite/arclite_eng.lng
+++ b/plugins/arclite/arclite_eng.lng
@@ -83,6 +83,8 @@
 "LZMA"
 "LZMA2"
 "PPMD"
+"Deflate"
+"Deflate64"
 
 // Delete files
 "Do you want to delete selected files?"
diff --git a/plugins/arclite/arclite_ita.lng b/plugins/arclite/arclite_ita.lng
index afb6ad577..d193062e6 100644
--- a/plugins/arclite/arclite_ita.lng
+++ b/plugins/arclite/arclite_ita.lng
@@ -83,6 +83,8 @@
 "LZMA"
 "LZMA2"
 "PPMD"
+"Deflate"
+"Deflate64"
 
 // Delete files
 "Vuoi Eliminare I Files Selezionati?"
diff --git a/plugins/arclite/arclite_pol.lng b/plugins/arclite/arclite_pol.lng
index f4c02eff6..d9222bd3c 100644
--- a/plugins/arclite/arclite_pol.lng
+++ b/plugins/arclite/arclite_pol.lng
@@ -83,6 +83,8 @@
 "LZMA"
 "LZMA2"
 "PPMD"
+"Deflate"
+"Deflate64"
 
 // Delete files
 "Chcesz usunąć zaznaczone pliki?"
diff --git a/plugins/arclite/arclite_rus.lng b/plugins/arclite/arclite_rus.lng
index 91a0f75f5..f556e4c4f 100644
--- a/plugins/arclite/arclite_rus.lng
+++ b/plugins/arclite/arclite_rus.lng
@@ -83,6 +83,8 @@
 "LZMA"
 "LZMA2"
 "PPMD"
+"Deflate"
+"Deflate64"
 
 // Delete files
 "Вы хотите удалить выбранные файлы?"
diff --git a/plugins/arclite/arclite_spa.lng b/plugins/arclite/arclite_spa.lng
index 2e0e1a84a..dacc89ff7 100644
--- a/plugins/arclite/arclite_spa.lng
+++ b/plugins/arclite/arclite_spa.lng
@@ -83,6 +83,8 @@
 "LZMA"
 "LZMA2"
 "PPMD"
+"Deflate"
+"Deflate64"
 
 // Delete files
 "Quiere borrar los archivos seleccionados?"
diff --git a/plugins/arclite/attr.cpp b/plugins/arclite/attr.cpp
index 047ee7a97..1cd24bf65 100644
--- a/plugins/arclite/attr.cpp
+++ b/plugins/arclite/attr.cpp
@@ -466,7 +466,7 @@ void Archive::load_update_props() {
   if (in_arc->GetArchiveProperty(kpidMethod, prop.ref()) == S_OK && prop.is_str()) {
     std::list<std::wstring> m_list = split(prop.get_str(), L' ');
 
-    static const wchar_t *known_methods[] = { c_method_lzma, c_method_lzma2, c_method_ppmd };
+    static const wchar_t *known_methods[] = { c_method_lzma, c_method_lzma2, c_method_ppmd, c_method_deflate, c_method_deflate64 };
 
     for (const auto& m_str: m_list) {
       if (_wcsicmp(m_str.c_str(), c_method_copy) == 0) {
diff --git a/plugins/arclite/cmdline.cpp b/plugins/arclite/cmdline.cpp
index 1927e1456..becb10ceb 100644
--- a/plugins/arclite/cmdline.cpp
+++ b/plugins/arclite/cmdline.cpp
@@ -198,10 +198,10 @@ OpenCommand parse_open_command(const CommandArgs& ca) {
 // arc:u [-l:<level>] [-m:<method>] [-s[:(y|n)]] [-p:<password>] [-eh[:(y|n)]]
 //   [-mf[:(y|n)]] [-ie[:(y|n)]] [-o[:(o|s)]] [-adv:<advanced>] <archive> (<file1> <file2> ... | @<filelist>)
 //   <level> = 0|1|3|5|7|9
-//   <method> = lzma|lzma2|ppmd
+//   <method> = lzma|lzma2|ppmd|deflate|deflate64
 
 static const unsigned c_levels[] = { 0, 1, 3, 5, 7, 9 };
-static const wchar_t* c_methods[] = { L"lzma", L"lzma2", L"ppmd" };
+static const wchar_t* c_methods[] = { L"lzma", L"lzma2", L"ppmd", L"deflate", L"deflate64" };
 
 UpdateCommand parse_update_command(const CommandArgs& ca) {
   bool create = ca.cmd == cmdCreate;
diff --git a/plugins/arclite/msg.hpp b/plugins/arclite/msg.hpp
index 1f1dc0cce..1d20f5070 100644
--- a/plugins/arclite/msg.hpp
+++ b/plugins/arclite/msg.hpp
@@ -73,6 +73,8 @@
 	MSG_COMPRESSION_METHOD_LZMA,
 	MSG_COMPRESSION_METHOD_LZMA2,
 	MSG_COMPRESSION_METHOD_PPMD,
+	MSG_COMPRESSION_METHOD_DEFLATE,
+	MSG_COMPRESSION_METHOD_DEFLATE64,
 	MSG_DELETE_DLG_CONFIRM,
 	MSG_CREATE_DIR_DLG_NAME,
 	MSG_TEST_OK,
diff --git a/plugins/arclite/ui.cpp b/plugins/arclite/ui.cpp
index f29e0b298..24fc99bde 100644
--- a/plugins/arclite/ui.cpp
+++ b/plugins/arclite/ui.cpp
@@ -670,6 +670,8 @@ const CompressionMethod c_methods[] = {
   { MSG_COMPRESSION_METHOD_LZMA, c_method_lzma },
   { MSG_COMPRESSION_METHOD_LZMA2, c_method_lzma2 },
   { MSG_COMPRESSION_METHOD_PPMD, c_method_ppmd },
+  { MSG_COMPRESSION_METHOD_DEFLATE, c_method_deflate },
+  { MSG_COMPRESSION_METHOD_DEFLATE64, c_method_deflate64 },
 };
 
 static bool is_SWFu(const std::wstring& fname)
@@ -853,7 +855,7 @@ private:
     update_level_list();
     bool is_compressed = get_list_pos(level_ctrl_id) != 0;
     for (int i = method_ctrl_id - 1; i <= method_ctrl_id; i++) {
-      enable(i, is_7z & is_compressed);
+      enable(i, (is_7z || is_zip) && is_compressed);
     }
     enable(solid_ctrl_id, is_7z && is_compressed);
     enable(encrypt_ctrl_id, is_7z || is_zip);
@@ -937,7 +939,7 @@ private:
     bool is_compressed = options.level != 0;
 
     if (is_compressed) {
-      if (is_7z) {
+      if (is_7z || is_zip) {
         options.method.clear();
         unsigned method_sel = get_list_pos(method_ctrl_id);
         const auto& codecs = ArcAPI::codecs();
@@ -1111,8 +1113,18 @@ private:
     }
     else if (new_arc && msg == DN_BTNCLICK && !main_formats.empty() && param1 >= main_formats_ctrl_id && param1 < main_formats_ctrl_id + static_cast<int>(main_formats.size())) {
       if (param2) {
+        ArcType prev_arc_type = arc_type;
         arc_type = main_formats[param1 - main_formats_ctrl_id];
         arc_levels('g');
+        if (arc_type != prev_arc_type) {
+          unsigned method_sel = get_list_pos(method_ctrl_id);
+          if (method_sel == 3 && arc_type == c_7z) {
+            set_list_pos(method_ctrl_id, 0); // Deflate -> LZMA
+          }
+          else if (method_sel == 0 && arc_type == c_zip) {
+            set_list_pos(method_ctrl_id, 3); // LZMA -> Deflate
+          }
+        }
         set_control_state();
       }
     }
diff --git a/plugins/arclite/update.cpp b/plugins/arclite/update.cpp
index c36627c4c..22c360274 100644
--- a/plugins/arclite/update.cpp
+++ b/plugins/arclite/update.cpp
@@ -811,7 +811,7 @@ void Archive::set_properties(IOutArchive* out_arc, const UpdateOptions& options)
     static const ExternalCodec defopts { L"", 1,9,0, 1,3,5,7,9, false };
 
     std::wstring method;
-    if (options.arc_type == c_7z)
+    if (options.arc_type == c_7z || options.arc_type == c_zip)
       method = options.method;
     else if (ArcAPI::formats().count(options.arc_type))
       method = ArcAPI::formats().at(options.arc_type).name;
@@ -947,6 +947,13 @@ void Archive::set_properties(IOutArchive* out_arc, const UpdateOptions& options)
         }
       }
     }
+    else if (options.arc_type == c_zip) {
+      if (!ignore_method) {
+        names.push_back(L"0"); values.push_back(method);
+        ++n_01;
+      }
+      names.push_back(L"x"); values.push_back(level);
+    }
     else if (options.arc_type != c_bzip2 || level != 0) {
       names.push_back(L"x"); values.push_back(level);
     }

```

**Comment by alabuzhev** [comment]
@rohitab looks good, would you like to create a PR?

**Comment by rohitab** [comment]
@alabuzhev sure, will do.

**Comment by atolismesh** [comment]
After this patch, ArcLite began to give an error  "ArcLite Not implemented (0x80004001) update. cpp : 1141" when attempting to create a ZIP archive. It appears that impossible combinations of compression methods were selected automatically or based on saved settings.

<img width="248" alt="image" src="https://github.com/FarGroup/FarManager/assets/130924690/6be6c750-b1e9-4b02-862b-cb0477dc0e44">

**Comment by HamRusTal** [comment]
> an error "ArcLite Not implemented (0x80004001) update. cpp : 1141" when attempting to create a ZIP archive.

What compression level and compression method did you choose in the initial “Create archive” dialog? Do you get the error if you choose the Deflate or LZMA method there?

**Comment by atolismesh** [comment]
Ultra+LZMA2 
I didn't choose anything, everything is by default. 
This is my initial screen right after pressing Shift+F1^
<img width="510" alt="image" src="https://github.com/FarGroup/FarManager/assets/130924690/4d482d6e-7132-41b0-bf1b-2dc32c843371">
This is my screen  after switching to zip:
<img width="511" alt="image" src="https://github.com/FarGroup/FarManager/assets/130924690/0f778abd-9353-4696-ade9-6493afdf6747">

**Comment by HamRusTal** [comment]
> I didn't choose anything, everything is by default.

For me, the “defaults” are different: “Compression level” is Normal, “Method” is LZMA. Clearly, you used the “Save settings” button in the past with your choices.
Yet I agree that ideally these choices should be saved per archiver, especially given that some combinations are not supported.

**Comment by atolismesh** [comment]
I think error is in this code:
```
         arc_levels('g');
+        if (arc_type != prev_arc_type) {
+          unsigned method_sel = get_list_pos(method_ctrl_id);
+          if (method_sel == 3 && arc_type == c_7z) {
+            set_list_pos(method_ctrl_id, 0); // Deflate -> LZMA
+          }
+          else if (method_sel == 0 && arc_type == c_zip) {
+            set_list_pos(method_ctrl_id, 3); // LZMA -> Deflate
+          }
+        }
```
 else if (method_sel == 0 || method_sel == 1 || method_sel == 2 && arc_type == c_zip) 
etc

**Comment by rohitab** [comment]
@atolismesh, please refer to the following from the _**Proposed technical implementation details**_ section above.

> The only other change I made was to automatically switch the _Method_ when using _Select archiver_ to switch between `7z` and `zip`. This was done to avoid changing the current functionality. So, for example, if you select the `zip` archiver, the `Deflate` method is automatically selected. If you select the `7z` archiver, the `LZMA` method is automatically selected. <ins>**However, if you manually change the method, say to `PPMD`, it will remain as such, and not change when switching archivers**.</ins>

As @HamRusTal mentioned, you most likely changed the default method from `LZMA` to `LZMA2`. As stated above, if you manually change the method, it will remain as such when switching archivers.

**Comment by 4ndrej** [comment]
Allowing to use "impossible combinations of compression methods" is bad practice and should be avoided. The "create archive dialog" should be aware of supported archiver/method combinations.

**Comment by yegor-mialyk** [comment]
@4ndrej, there was a time when ZIP used to be just an archive format with predefined compression methods (like store, deflate, etc.). Nowadays, ZIP is more like a container where people store files using various compression methods (you can find many ZIP archives with LZMA, ZSTD, etc., in the wild). So why not support those and manipulate them, especially being a "File and Archive Manager" in the first place?

**Comment by 4ndrej** [comment]
> @4ndrej, there was a time when ZIP used to be just an archive format with predefined compression methods (like store, deflate, etc.). Nowadays, ZIP is more like a container where people store files using various compression methods (you can find many ZIP archives with LZMA, ZSTD, etc., in the wild). So why not support those and manipulate them, especially being a "File and Archive Manager" in the first place?

Maybe zip allows LZMA2, but ArcLite does not like this combination giving an error "ArcLite Not implemented (0x80004001) update. cpp : 1141" when attempting to create a ZIP archive using LZMA2 compression method.

**Comment by rohitab** [comment]
> The "create archive dialog" should be aware of supported archiver/method combinations.

@4ndrej Note that additional archivers and methods can be dynamically added using codec and format plugins, so it might not always be possible to know which methods and combinations are supported beforehand. I have 12 methods and 25 archivers, and some of them give error messages. For example, if you try to add multiple files using the ZSTD archiver, you'll get the error message _"The parameter is incorrect. (0x80070057)"_ because this feature is not supported by ZSTD.

However, we should be able to prevent selection of unsupported archive methods for ZIP, especially since many people have run into issues.

Section `4.4.5` of the [.ZIP File Format Specification](https://pkwaredownloads.blob.core.windows.net/pkware-general/Documentation/APPNOTE-6.3.10.TXT) lists out the supported compression methods. Section `4.1.3` states that "_When compression is used, one of the documented compression algorithms MUST be used_". So, any method other than the ones from Section `4.4.5` should not be available for selection by the user.

@yegor-mialyk Are you aware of any Zip archives that use methods other than those listed in this spec? LZMA and ZSTD are both listed in the spec, LZMA2 is not, and I'm curious if you have seen a Zip that uses this method.

**Comment by yegor-mialyk** [comment]
Thank you, @rohitab, for the documentation link. It looks like the spec covers even more methods than I saw before, so sticking with the spec is fine for me.
