### ISSUE TITLE
Stack corruption in Process list plugin

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#782]
### Far Manager version

3.0.6260.0 x64

### OS version

10.0.22635.3130

### Steps to reproduce

1. Build Far in _Debug_ mode.
2. Run Far in the Visual Studio debugger (preferred) or directly.
3. Press `F11` to open _Plugin commands_, then select _Process list_.
4. Select a process and press `F3` to view details.

### Expected behavior

Far opens the built-in Viewer with details about the selected process.

### Actual behavior

Microsoft Visual C++ Runtime Library shows a _Debug Error_ window, with the following message:

**Run-Time Check Failure # 2 - Stack around the variable 'iob' was corrupted.**

The window opens and closes very quickly, and the Viewer does open up with details of the selected process. If you run Far within a debugger, Visual Studio throws an Exception with the same message.

If you don't see the message the first time, select another process and press `F3`.

### Issue
The issue appears to be due to the following code which does not allocate enough memory for the `iob` variable, causing the stack check to fail. Note that in _Release_ mode, this doesn't cause an issue, since the data is not accessed, and the combined storage for `iob` and `info` is sufficient.

https://github.com/FarGroup/FarManager/blob/8484c300b8413d65950ceece686e2f34b4a597ea/plugins/proclist/handles.cpp#L102-L109

### Patch
The following patch fixes the issue.

```diff
diff --git a/plugins/proclist/handles.cpp b/plugins/proclist/handles.cpp
index 1eaea3e1e..c12136bfe 100644
--- a/plugins/proclist/handles.cpp
+++ b/plugins/proclist/handles.cpp
@@ -101,10 +101,10 @@ static std::wstring GetFileName(HANDLE Handle)
 		{
 			static DWORD WINAPI GetFileNameThread(PVOID Param)
 			{
-				DWORD iob[2];
-				BYTE info[256];
+				IO_STATUS_BLOCK iob;
+				FILE_BASIC_INFO info;
 				const auto FileBasicInformation = 4;
-				pNtQueryInformationFile(Param, iob, info, sizeof(info), FileBasicInformation);
+				pNtQueryInformationFile(Param, &iob, &info, sizeof(info), FileBasicInformation);
 				return 0;
 			}
 		};

```

**Comment by alabuzhev** [comment]
Thanks
