### ISSUE TITLE
Crash when opening a plugin via an association from a plugin panel

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#783]
### Far Manager version

3.0.6260.0 x64

### OS version

10.0.22635.3130

### Steps to reproduce

1. Extract `assoc.farconfig` from the attached archive [`assoc.farconfig.zip`](https://github.com/FarGroup/FarManager/files/14071346/assoc.farconfig.zip).
2. Import `assoc.farconfig` using the command `far.exe -import assoc.farconfig`.
3. Download the attached [`Outer.zip`](https://github.com/FarGroup/FarManager/files/14071349/Outer.zip) file, which is essentially a Zip archive containing another Zip archive.
4. Select `Outer.zip` in Far, press `Ctrl+PgDn`, then select `Zip Open` from the _Select associations_ menu.
5. Select `Inner.zip`, press `Ctrl+PgDn`, then select `Zip Echo`.
6. You will see the temporary filename in the Editor. Press `Esc` to close the Editor.
7. On `Inner.zip`, press `Ctrl+PgDn` again, then select `Zip Open (Recursive)`
8. You will see the file `Sample.txt` in the archive.
9. Press `Ctrl+PgUp` to close the `Inner.zip` archive and return to the `Outer.zip` archive.
10. On `Inner.zip`, press `Ctrl+PgDn`, then select `Zip Open`.

### Expected behavior

The `Inner.zip` archive is opened and the file `Sample.txt` is visible.

### Actual behavior

Far crashes with an _Oops_ dialog.

Note that this issue is not limited to ArcLite or Zip archives. If you open a SSH connection using NetBox, and press `Ctrl+PgDn` on any Zip archive, and select `Zip Open`, it will cause a crash as well.

The crash is in the following code. The function `GetPluginHandle()` returns a `nullptr`, and dereferencing it results in a crash.

https://github.com/FarGroup/FarManager/blob/8484c300b8413d65950ceece686e2f34b4a597ea/far/filelist.cpp#L2719

Adding a check for `nullptr` fixes the crash, but the temporary file is not deleted.

Note that the `Zip Open` command is defined as `arc:!\!.!`, while the `Zip Recursive` command is defined as `arc:-r !\!.!`. The former crashes, while the latter works. The `-r` argument opens the ArcLite panel in recursive mode (`OPIF_RECURSIVEPANEL`) as seen in the following code:

https://github.com/FarGroup/FarManager/blob/8484c300b8413d65950ceece686e2f34b4a597ea/plugins/arclite/cmdline.cpp#L174-L176

**Comment by rohitab** [comment]
I just tried older versions. The changes between the following two versions appear to be causing the crash.

- [`v3.0.6226.3598 (Good)`](https://github.com/FarGroup/FarManager/releases/tag/ci%2Fv3.0.6226.3598)
- [`v3.0.6227.3600 (Crash)`](https://github.com/FarGroup/FarManager/releases/tag/ci%2Fv3.0.6227.3600)

Here are the commits between these versions:

- https://github.com/FarGroup/FarManager/commit/dd4ce37a090851365dbb13a753bd280d073ce13b
- https://github.com/FarGroup/FarManager/commit/f43b0945030eca0c7f9ce43e8a1a56892275083a
- https://github.com/FarGroup/FarManager/commit/371c8ea00f1e587881860d8f5626060c6c7ddb57
- https://github.com/FarGroup/FarManager/commit/afbd23b4903d112d11758b0db126b8352a3bc7eb
- https://github.com/FarGroup/FarManager/commit/c9e09b5b6bf2708d4ab3934770242adc0ba1b647

**Comment by alabuzhev** [comment]
Should be (hopefully) fixed in 6261.

**Comment by rohitab** [comment]
The crash is resolved, and the file is deleted as well. However, the issue now is that the file is deleted too soon, i.e., it is deleted while the archive is still open. This means that you can no longer modify the archive.

After `Step 10` above, you will see `Sample.txt` from `Inner.zip`, as expected. However, as this point, the temporary file `Inner.zip` in the `%TEMP%` directory has been deleted. You can verify this by running the command `lua:=mf.fexist(APanel.HostFile)` which will show a dialog with the result  `false`.

If you now try to add a file to the archive (copy a file from the Passive panel), you will see an error dialog stating: **The system cannot find the path specified. (0x80070003)**.

Note that if you use `Zip Open (Recursive)`, the file is not deleted until after the archive is closed, and you can add files to the archive. Running `lua:=mf.fexist(APanel.HostFile)` will show the result `true`.

**Comment by alabuzhev** [comment]
I see. Please try with this patch:

```DIFF
--- a/far/filelist.cpp
+++ b/far/filelist.cpp
@@ -2724,13 +2724,18 @@ void FileList::ProcessEnter(bool EnableExec,bool SeparateWindow,bool EnableAssoc
 				if (const auto PluginHandle = GetPluginHandle())
 				{
 					PluginHandle->delayed_delete(FileNameToDelete);
+					return;
 				}
-				else
+
+				// gh-783: in some cases the panel could be gone before we get here
+				if (const auto PluginHandle = Parent()->ActivePanel()->GetPluginHandle())
 				{
-					// gh-783: in some cases the panel could be gone before we get here
-					delayed_deleter Deleter(true);
-					Deleter.add(FileNameToDelete);
+					PluginHandle->delayed_delete(FileNameToDelete);
+					return;
 				}
+
+				delayed_deleter Deleter(true);
+				Deleter.add(FileNameToDelete);
 			}
 		};
 
```

**Comment by rohitab** [comment]
Unfortunately, this one still has issues. The host file is valid and you can now add files to the archive. However, as soon as you exit the archive, the file is deleted before the archive has a chance to [update](https://github.com/FarGroup/FarManager/blob/master/far/filelist.cpp#L3013-L3014). Far displays the message:  **Cannot read folder contents**. This is displayed by the following code:

https://github.com/FarGroup/FarManager/blob/31d27e377b899cba58c3253754cadbc1cc82196d/far/filelist.cpp#L7086-L7094

**Comment by alabuzhev** [comment]
I'm not sure that this is even supposed to work.
When you do `arc:\!.!` on a plugin panel, far extracts the file and gives it to the plugin.
The plugin creates a new panel that replaces the existing one, so there's nothing to update when we go up.
Are you sure this part worked before f43b0945030eca0c7f9ce43e8a1a56892275083a?

**Comment by rohitab** [comment]
You're right. It's not supposed to work because the original panel is closed. Apologies for the trouble, my mistake.

As for [`f43b094`](https://github.com/FarGroup/FarManager/commit/f43b0945030eca0c7f9ce43e8a1a56892275083a), the file is deleted, so you can't even add it to the archive.

I don't think even the last patch is required since there is no point keeping the file around. In fact, I tried with an archive on a SSH server (via NetBox), and the current behavior works better compared to the one with the above patch.

All is good. The last change you commited https://github.com/FarGroup/FarManager/commit/31d27e377b899cba58c3253754cadbc1cc82196d resolves this issue. Thank you.
