### ISSUE TITLE
Enable autocompletion in edit controls after initialization

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#786]
### Description of the new feature or improvement

Autocompletion in dialog edit controls works for History, File system and Environment. However, this initialization must be done when the control is initially created. If the control has already been created, setting flags like `DIF_EDITPATH` and `DIF_HISTORY` using `DM_SETDLGITEM` message do not work.

Even though History can be enabled after initialization, using `DM_SETHISTORY` message, the Autocompletion feature for History does not work.

I believe this feature would be useful, since it would allow enabling (or disabling) of History and Autocompletion features for dialogs created by plugins or by Far itself.

### Proposed technical implementation details (optional)

Code to implement this feature is already present, however, it is currently called in the [DlgEdit::DlgEdit](https://github.com/FarGroup/FarManager/blob/bd2ec802fc91be8e3ce5c608dec5d9cde0ac262c/far/dlgedit.cpp#L56-L105) constructor. I made some modifications to the code as shown in the patch below. It's not the ideal patch, but with these changes, both History and Autocompletion can be enabled _after_ the dialog has been created. These features can also be enabled from Lua `DialogEvent` handlers in response to `DN_INITDIALOG` messages, or enabled at any time using `DM_SETDLGITEM` message. Both these features are demonstrated in the attached script.

### Patch
This patch has been tested with Far Manager, version `3.0.6262.0 x64`, which is the most recent version. The patch is also attached as [`Autocompletion.patch`](https://github.com/FarGroup/FarManager/files/14093275/Autocompletion.patch)

```diff
diff --git a/far/dialog.cpp b/far/dialog.cpp
index bc854e41f..f35d51da8 100644
--- a/far/dialog.cpp
+++ b/far/dialog.cpp
@@ -637,7 +637,7 @@ std::any* Dialog::GetListItemComplexUserData(size_t ListId, size_t ItemId) const
   TODO: Необходимо применить ProcessRadioButton для исправления
         кривых рук некоторых плагинописателей (а надо?)
 */
-void Dialog::InitDialogObjects(size_t ID)
+void Dialog::InitDialogObjects(size_t ID, bool ReInit)
 {
 	size_t InitItemCount;
 	bool AllElements = false;
@@ -802,6 +802,10 @@ void Dialog::InitDialogObjects(size_t ID)
 					Item.ListPtr->SetVDialogItemID(I);
 				}
 			}
+			else if (ReInit)
+			{
+				static_cast<DlgEdit*>(Item.ObjPtr)->Init();
+			}
 
 			const auto DialogEdit = static_cast<DlgEdit*>(Item.ObjPtr);
 			// Mantis#58 - символ-маска с кодом 0х0А - пропадает
@@ -5770,7 +5774,7 @@ intptr_t Dialog::SendMessage(intptr_t Msg,intptr_t Param1,void* Param2)
 				CurItem.ListPtr->ChangeFlags(VMENU_DISABLED, (CurItem.Flags&DIF_DISABLE)!=0);
 
 			// еще разок, т.к. данные могли быть изменены
-			InitDialogObjects(Param1);
+			InitDialogObjects(Param1, true);
 			ShowConsoleTitle();
 			if (DialogMode.Check(DMODE_SHOW))
 			{
diff --git a/far/dialog.hpp b/far/dialog.hpp
index d627df075..877aef19c 100644
--- a/far/dialog.hpp
+++ b/far/dialog.hpp
@@ -252,7 +252,7 @@ public:
 	};
 
 protected:
-	void InitDialogObjects(size_t ID = static_cast<size_t>(-1));
+	void InitDialogObjects(size_t ID = static_cast<size_t>(-1), bool ReInit = false);
 
 private:
 	friend class History;
diff --git a/far/dlgedit.cpp b/far/dlgedit.cpp
index b7329d7d8..bfe168a72 100644
--- a/far/dlgedit.cpp
+++ b/far/dlgedit.cpp
@@ -57,6 +57,11 @@ DlgEdit::DlgEdit(window_ptr Owner,size_t Index,DLGEDITTYPE Type):
 	SimpleScreenObject(std::move(Owner)),
 	m_Index(Index),
 	Type(Type)
+{
+	Init();
+}
+
+void DlgEdit::Init()
 {
 	switch (Type)
 	{
@@ -71,7 +76,7 @@ DlgEdit::DlgEdit(window_ptr Owner,size_t Index,DLGEDITTYPE Type):
 
 			FarList* iList = nullptr;
 			DWORD iFlags=0;
-			const auto& CurItem = GetDialog()->Items[Index];
+			const auto& CurItem = GetDialog()->Items[m_Index];
 			if(Global->Opt->Dialogs.AutoComplete && CurItem.Flags&(DIF_HISTORY|DIF_EDITPATH|DIF_EDITPATHEXEC) && !(CurItem.Flags&DIF_DROPDOWNLIST) && !(CurItem.Flags&DIF_NOAUTOCOMPLETE))
 			{
 				iFlags=EditControl::EC_ENABLEAUTOCOMPLETE;
diff --git a/far/dlgedit.hpp b/far/dlgedit.hpp
index c5fb62b7c..bf50eb408 100644
--- a/far/dlgedit.hpp
+++ b/far/dlgedit.hpp
@@ -79,6 +79,8 @@ public:
 	DlgEdit(window_ptr Owner,size_t Index,DLGEDITTYPE Type);
 	~DlgEdit() override;
 
+	void Init();
+
 	bool ProcessKey(const Manager::Key& Key) override;
 	bool ProcessMouse(const MOUSE_EVENT_RECORD *MouseEvent) override;
 

```

### Binaries for Testing
I have compiled the 64-bit version of Far with this patch. To use this version:

- Download `x64` Far version [`v3.0.6262.3675`](https://github.com/FarGroup/FarManager/releases/tag/ci%2Fv3.0.6262.3675)
- Or, use [`Far.x64.3.0.6262.3675.bd2ec802fc91be8e3ce5c608dec5d9cde0ac262c.7z`](https://github.com/FarGroup/FarManager/releases/download/ci%2Fv3.0.6262.3675/Far.x64.3.0.6262.3675.bd2ec802fc91be8e3ce5c608dec5d9cde0ac262c.7z)
- Install Far as you normally would.
- Extract `Far.exe` from the attached [`Far.exe.zip`](https://github.com/FarGroup/FarManager/files/14093190/Far.exe.zip) and replace the one in the above installed version.

### Lua Script for Testing
I created a Lua script for testing, and to demonstrate this feature. Please note that this script will only work if the patch has been applied. You can also use the binary from [`Far.exe.zip`](https://github.com/FarGroup/FarManager/files/14093190/Far.exe.zip) that has already been compiled with this patch. Here are the required steps for testing:

**Install Script**

1. Extract `Dialog.Autocompletion.lua` from the attached archive [`Dialog.Autocompletion.lua.zip`](https://github.com/FarGroup/FarManager/files/14093185/Dialog.Autocompletion.lua.zip).
2. Copy `Dialog.Autocompletion.lua` to `%FARPROFILE%\Macros\scripts`
3. Restart Far or run `macro:load` to reload macros.

**Test Method 1**

1. From a file panel, press `Ctrl+/`. This will open the _Edit file associations_ dialog and enable History and Autocompletion for the _Description of the association_ edit control.
2. Press `Ctrl+Down` and you should see History from the File Copy/Rename dialog.
3. If you start typing, say a path, Autocompletion should work.
5. You can press `Ctrl+/` to toggle the features at any time.

**Test Method 2**

1. Press `F9`, then select File associations, then press the `Ins` key. This will open the _Edit file associations_ dialog.
2. Note that neither History nor Autocompletion are enabled for the _Description of the association_ edit control.
3. If you type a path, Autocompletion will _not_ work.
6. Press `Ctrl+/` to enable both these features.
7. Note that the dropdown arrow is displayed next to the _Description of the association_ edit control.
8. Press `Ctrl+Down` and you should see History from the File Copy/Rename dialog.
9. If you start typing, say a path, Autocompletion should work.
10. You can press `Ctrl+/` to toggle the features at any time.

### Lua Script Source Code
```lua
-- Autocompletion Test
-- Rohitab Batra <rohitab@rohitab.com>
--
-- There are two ways of using this test:
--
--  1. Press "Ctrl+/" in a panel to open the "Edit file associations" dialog, and automatically
--     enable History and Autocompletion features.
--
--  2. Manually open the dialog using "F9 > File associations", then press the "Ins" key.
--     Note that both History and Autocompletion are disabled for the "Description of the association" box.
--     Press "Ctrl+/" to enable these features.
--
--  You can press "Ctrl+/" at any time to toggle History and Autocompletion.
--
-- NOTES:
--   * You need to apply the patch for these features to work.
--   * Autocompletion will use entries from the Copy/Rename dialogs, since most
--     people will have some entries already populated in these.
--     Autocompletion of paths is also enabled.


-- Dialog Ids
local FILE_ASSOC_MODIFY_ID = win.Uuid(far.Guids.FileAssocModifyId)

-- Initialization
local F = far.Flags

-- Property Indexes
local IDX_HISTORY = 7
local IDX_FLAGS = 9
local IDX_MAXLENGTH = 11

-- Item Indexes
local IDX_DESCRIPTION = 5

-- Global variables
local Globals = {
    enableEvent = false,
}


function ToggleFeatures(dialog)
    -- This works to enable History, but Autocompletion still doesn't work.
    --dialog:send(F.DM_SETHISTORY, IDX_DESCRIPTION, "Copy")

    -- Get the "Description of the association" edit box.
    local item = dialog:send(F.DM_GETDLGITEM, IDX_DESCRIPTION)
    local flags = bor(F.DIF_EDITPATH, F.DIF_HISTORY)

    -- If History is not enabled, enable it, otherwise disable it.
    if band(item[IDX_FLAGS], F.DIF_HISTORY) == 0 then
        -- This doesn't work at all, unless you apply the patch I provided.
        item[IDX_HISTORY] = "Copy"
        item[IDX_FLAGS] = bor(item[IDX_FLAGS], flags)

        -- Some features, like setting maximum input length, already work.
        --item[IDX_MAXLENGTH] = 5
    else
        item[IDX_FLAGS] = band(item[IDX_FLAGS], bnot(flags))
    end

    -- Update the dialog edit box with new information.
    dialog:send(F.DM_SETDLGITEM, IDX_DESCRIPTION, item)
end


Macro {
    area = "Shell";
    key = "Ctrl/";
    description = "Autocomplete Test: Open the Edit file associations dialog";
    action = function()
        Globals.enableEvent = true
        Keys("F9", APanel.Left and "2*Right" or "2*Left", "10*Down Enter Ins Tab")
        Globals.enableEvent = false
    end;
}


Macro {
    area = "Dialog";
    key = "Ctrl/";
    description = "Autocomplete Test: Toggle History and Autocompletion features";
    condition = function()
        return Dlg.Id == far.Guids.FileAssocModifyId
    end;
    action = function()
        ToggleFeatures(far.AdvControl(F.ACTL_GETWINDOWINFO).Id)
    end;
}


Event {
    group = "DialogEvent";
    description = "Autocomplete Test: Enable History and Autocompletion features automatically";
    condition = function(Event, FarDialogEvent)
        return Globals.enableEvent and Event == F.DE_DLGPROCINIT and FarDialogEvent.Msg == F.DN_INITDIALOG
    end;
    action = function(Event, FarDialogEvent)
        local dialog = FarDialogEvent.hDlg
        local info = dialog:send(F.DM_GETDIALOGINFO)
        if info and info.Id == FILE_ASSOC_MODIFY_ID then
            ToggleFeatures(dialog)
        end
    end;
}
```

### Attached Files

- [`Autocompletion.patch`](https://github.com/FarGroup/FarManager/files/14093275/Autocompletion.patch)
- [`Dialog.Autocompletion.lua.zip`](https://github.com/FarGroup/FarManager/files/14093185/Dialog.Autocompletion.lua.zip)
- [`Far.exe.zip`](https://github.com/FarGroup/FarManager/files/14093190/Far.exe.zip)

**Comment by alabuzhev** [comment]
Good catch, thank you.
I can't see why not, although indeed, maybe it could be done differently or better.
Hard to say, the whole thing is rather messy.

A PR would be welcome anyway.

**Comment by rohitab** [comment]
Thanks! I will create a PR.

**Comment by nightroman** [comment]
Cool, thank you @rohitab and @alabuzhev, engaging in FarNet, so far looks good.

**Comment by nightroman** [comment]
@rohitab @alabuzhev 
Maybe off-topic, but equally this may be related to the change. Please let me know if a separate issue is needed.

Steps:
- in a panel, navigate to any file, open the attributes dialog `CtrlA`
- click the edit box `Owner:`, delete all test (`BUILTIN\Administrators` in my case)
- now set `DIF_EDITPATH` for this edit box (by Lua macro?), I do this in PowerShellFar as F11 / PowerShellFar / Invoke commands + `$far.Dialog.Focused.IsPath = $true` + Enter

This really works, paths are completed after that.
But the original text `BUILTIN\Administrators` is restored unexpectedly for some reason. Bug, feature? Can you repro using a macro or FarNet.PowerShellFar?

**Comment by nightroman** [comment]
The same story is with changing history (I do this in PSF by `$far.Dialog.Focused.History = 'NewFolder'` but this is not yet released, you cannot reproduce in PSF yet). The original deleted text `BUILTIN\Administrators` appears after changing the history. But the history works as expected in this edit box, good.

**Comment by rohitab** [comment]
@nightroman I cannot reproduce your issue with version `3.0.6266.0 x64`. I created a macro for testing. Can you please try this on your end and let me know if you are still facing the same issues?

1. Extract `Dialog.FeatureTest.lua` from the attached archive [`Dialog.FeatureTest.lua.zip`](https://github.com/FarGroup/FarManager/files/14149045/Dialog.FeatureTest.lua.zip)
2. Copy `Dialog.FeatureTest.lua` to `%FARPROFILE%\Macros\scripts`
3. Restart Far or run `macro:load` to reload macros.
4. Open any dialog, and set focus to an edit control.
5. Use any of the following hotkeys for setting or changing features.

### Hotkeys

- `Ctrl+P`: Enable path completion.
- `Ctrl+H`: Set or change History to _NewFolder_.
- `Ctrl+M`: Set maximum text length to 10.

### Issues

The only issue I have seen is when you use `Ctrl+M` to set the maximum text length. In this case, the previous text is restored. However, this issue is present in older versions of Far as well. In fact, I was planning to create a separate ticket for this later on.

### Additional Notes
In the macro, `USE_DM_SET_HISTORY` is currently set to `false`. In this case, the macro uses `DM_SETDLGITEM` to enable History. If you set `USE_DM_SET_HISTORY` to `true`, the macro will use `DM_SETHISTORY` instead. Both of these are working fine for me.

### Lua Macro Source Code

This macro is also attached as [`Dialog.FeatureTest.lua.zip`](https://github.com/FarGroup/FarManager/files/14149045/Dialog.FeatureTest.lua.zip)

```lua
-- Dialog Feature Test Macro for GitHub Ticket #786
-- Rohitab Batra <rohitab@rohitab.com>
--
-- Set focus to an edit control in a dialog, then press any of the following keys:
--  * Ctrl+P - Enable path completion
--  * Ctrl+H - Set or change History to 'NewFolder'
--  * Ctrl+M - Set maximum text length to 10


-- Initialization
local F = far.Flags

-- Property Indexes
local IDX_TYPE = 1
local IDX_HISTORY = 7
local IDX_FLAGS = 9

-- Configuration
local USE_DM_SET_HISTORY = false


Macro {
    area = "Dialog";
    key = "CtrlP";
    description = "TEST: Enable path completion for current item";
    action = function()
        local dialog = far.AdvControl(F.ACTL_GETWINDOWINFO).Id

        local item = dialog:send(F.DM_GETDLGITEM, Dlg.CurPos)
        if not item or item[IDX_TYPE] ~= F.DI_EDIT then
            return far.Show("Please set focus to an edit box, then try again.")
        end

        if item then
            item[IDX_FLAGS] = bor(item[IDX_FLAGS], F.DIF_EDITPATH)
            dialog:send(F.DM_SETDLGITEM, Dlg.CurPos, item)
        end

        far.AdvControl(F.ACTL_REDRAWALL)
    end
}


Macro {
    area = "Dialog";
    key = "CtrlH";
    description = "TEST: Set History for current item to 'NewFolder'";
    action = function()
        local dialog = far.AdvControl(F.ACTL_GETWINDOWINFO).Id

        local item = dialog:send(F.DM_GETDLGITEM, Dlg.CurPos)
        if not item or item[IDX_TYPE] ~= F.DI_EDIT then
            return far.Show("Please set focus to an edit box, then try again.")
        end

        if USE_DM_SET_HISTORY then
            -- Method 1
            dialog:send(F.DM_SETHISTORY, Dlg.CurPos, "NewFolder")
        else
            -- Method 2
            item[IDX_HISTORY] = "NewFolder"
            item[IDX_FLAGS] = bor(item[IDX_FLAGS], F.DIF_HISTORY)
            dialog:send(F.DM_SETDLGITEM, Dlg.CurPos, item)
        end

        far.AdvControl(F.ACTL_REDRAWALL)
    end
}


Macro {
    area = "Dialog";
    key = "CtrlM";
    description = "TEST: Set maximum length of current item to 10";
    action = function()
        local dialog = far.AdvControl(F.ACTL_GETWINDOWINFO).Id

        local item = dialog:send(F.DM_GETDLGITEM, Dlg.CurPos)
        if not item or item[IDX_TYPE] ~= F.DI_EDIT then
            return far.Show("Please set focus to an edit box, then try again.")
        end

        dialog:send(F.DM_SETMAXTEXTLENGTH, Dlg.CurPos, 10)

        far.AdvControl(F.ACTL_REDRAWALL)
    end
}
```

### Attached Files

- [`Dialog.FeatureTest.lua.zip`](https://github.com/FarGroup/FarManager/files/14149045/Dialog.FeatureTest.lua.zip)

**Comment by nightroman** [comment]
@rohitab Thank you for taking a look.

With Far 3.0.6266.0 x64 and your macros I cannot reproduce issues `CtrlP`, `CtrlH` and can reproduce `CtrlM`.

I still can reproduce path and history issues using my plugin. Maybe macro vs plugin matters (apparently).
I will play and test a little bit more and open an issue about my specific use case (or a forum discussion).

**Comment by nightroman** [comment]
@rohitab
Perhaps the difference is:
I use `DM_GETDLGITEMSHORT` and `DM_SETDLGITEMSHORT` (and it works funny).
You use `DM_GETDLGITEM` and `DM_SETDLGITEM` (and it works fine).

**Comment by nightroman** [comment]
I have created my separate issue https://github.com/FarGroup/FarManager/issues/790
