### ISSUE TITLE
DI_EDIT changes text after DM_SETDLGITEMSHORT

### ISSUE THREAD

**Issue by nightroman** [FarGroup/FarManager#790]
### Far Manager version

3.0.6266

### OS version

10.0.22631.3007

### Other software

To reproduce, the plugin `FarNet` is needed and its module `FarNet.PowerShellFar`, the latest versions recommended,
see <https://github.com/nightroman/FarNet#readme> for how to install.

Perhaps, the steps are doable using Lua but I cannot provide such code, I do not really master Lua in Far.

### Steps to reproduce

(1) In a panel, navigate to any file, open the attributes dialog `CtrlA`.

(2) Click the edit box `Owner:`, delete all test (`BUILTIN\Administrators` in my case).

(3) Open the PowerShellFar command box: `F11` / `PowerShellFar` / `Invoke commands`

(4) Type/paste `$far.Dialog.Focused.IsPath = $true` and press `Enter`.

As a result, the original text `BUILTIN\Administrators` is unexpectedly restored.

### What plugin does

The plugin changes `DI_EDIT` flags like `DIF_EDITPATH` using `DM_GETDLGITEMSHORT` for getting original data and then `DM_SETDLGITEMSHORT` for setting changed. Per Far enc., `DM_SETDLGITEMSHORT` should not affect text.

Here is the used code:
https://github.com/nightroman/FarNet/blob/275581a8402e8ed43cda2963bf5e1cdd8242e952/FarNet/FarNetMan/DialogControls.cpp#L99-L114

```cpp
void FarControl::SetFlag(int flag, bool value)
{
    if (_dialog->_hDlg != INVALID_HANDLE_VALUE)
    {
        FarDialogItem di;
        Info.SendDlgMessage(_dialog->_hDlg, DM_GETDLGITEMSHORT, Id, &di);
        if (value == ((di.Flags & flag) != 0))
            return;
        SET_FLAG(di.Flags, flag, value);
        Info.SendDlgMessage(_dialog->_hDlg, DM_SETDLGITEMSHORT, Id, &di);
    }
    else
    {
        SET_FLAG(_flags, flag, value);
    }
}
```

### Expected behavior

`DM_SETDLGITEMSHORT` should not change text.

### Actual behavior

`DM_SETDLGITEMSHORT` changes text.

**Comment by rohitab** [comment]
@nightroman Thank you for reporting the issue and providing the instructions to test.

I am able to reproduce this issue. However, this appears to be unrelated to #786. I tested an older Far version `3.0.6250.0 x64`, and the issue is present there as well. Did this work for you before, and if so, in which version? If not, then this issue is most likely related to a similar issue with `DM_SETMAXTEXTLENGTH` that I mentioned in https://github.com/FarGroup/FarManager/issues/786#issuecomment-1925018534 (the `Ctrl+M` test).

**Comment by nightroman** [comment]
I cannot tell if it's related to #786 or another mentioned. #786 simply triggered my new development and testing in this area, so that I've found this issue. It probably existed before. Changing edit controls properties after opening dialogs was not actively used/tested yet.

**Comment by rohitab** [comment]
No worries, I found the issue. I've created PR #791. If it gets approved it should fix the issue. Meanwhile, if you want you can use the following precompiled binary for testing.

- Install `x64` Far version [`v3.0.6267.3691`](https://github.com/FarGroup/FarManager/releases/tag/ci%2Fv3.0.6267.3691)
- Extract `Far.exe` from [`Far.exe.zip`](https://github.com/FarGroup/FarManager/files/14155645/Far.exe.zip) and overwrite the one in the above installed directory.

I have also updated the test macro. You can extract it from [`Dialog.FeatureTest.lua.zip`](https://github.com/FarGroup/FarManager/files/14155647/Dialog.FeatureTest.lua.zip). I've added another hotkey `Ctrl+T`, which will reproduce your test above.

### Attached Files

- [`Far.exe.zip`](https://github.com/FarGroup/FarManager/files/14155645/Far.exe.zip)
- [`Dialog.FeatureTest.lua.zip`](https://github.com/FarGroup/FarManager/files/14155647/Dialog.FeatureTest.lua.zip)

**Comment by nightroman** [comment]
@rohitab Thank you!
I have tried the precompiled binary, the issue is fixed. I'll keep using this binary, if I notice something, I'll get back.

FWIW, all my tests pass, I have some rather extensive set - https://github.com/nightroman/FarNet/tree/main/Test
That does not mean of course that everything is covered.
When the fix is in (hopefully), I'll cover it by tests, too.

**Comment by rohitab** [comment]
@nightroman That's great to hear. I appreciate you testing and reporting back promptly. Far version [`v3.0.6268.3694`](https://github.com/FarGroup/FarManager/releases/tag/ci%2Fv3.0.6268.3694) is available now and includes this change.

[FarNet](https://github.com/nightroman/FarNet) looks interesting. Now that I already have it installed, I'm going to play around with it.

**Comment by nightroman** [comment]
@rohitab FarNet is interesting indeed, especially if you use .NET or PowerShell.

Here is the promised test :)
https://github.com/nightroman/FarNet/blob/main/Test/Dialog/x-2024-02-04-IEdit-set-IsPath.fas.ps1
