### ISSUE TITLE
FindFile Trap 

### ISSUE THREAD

**Issue by Zeroes1** [FarGroup/FarManager#795]
### Far Manager version

3.0.6270

### OS version

10.0.19045.3930

### Other software

nope

### Steps to reproduce

drkns 2024-02-10 14:45:04+00:00 - build 6270

предположительно изменения:
2. Improve encoding diagnostics.

приводят к падению

Alt+f7
ищем внутри файлов
`"C:\=PROJECT_FAR2=\Encyclopedia\LUAFAR_MANUAL\"` (тут распакованный CHM на файлы)
например слово panel
Всегда падаем одинаково

[Far_20240211_220243846_4944.zip](https://github.com/FarGroup/FarManager/files/14234559/Far_20240211_220243846_4944.zip)

### Expected behavior

build 6269 all ok

### Actual behavior

100% Trap

**Comment by alabuzhev** [comment]
6272
