### ISSUE TITLE
Pressing the folder shortcut key multiple times should toggle selected folder if there are multiple folders bound to the same key.

### ISSUE THREAD

**Issue by imsh** [FarGroup/FarManager#796]
### Description of the new feature or improvement

Imagine a folder shortcut with multiple folder locations bound to the same shortcut:
Pressing "RCtrl-3" opens a dialog with "c:\movies" "d:\movies" "x:\movies" folders.

If I want to choose the third option, then my keyboard presses will be "rctrl-3", then "down", "down", then "Enter"
This is quite a tedious combination for a shortcut, partly because it involves quite a lot of hand movement due to usage of "down" button.
What I want is that pressing "RCtrl-3" each subsequent time will result in the same action as pressing "down" key in the dialog. In my example, the same combination will become "RCtrl-3" three times and then "enter". It will require less hand movement so it will be easier to use and easier to get the "muscle memory" of this combination.

A bonus wish:  If I press "rctrl-3" which gets the selection dialog opened, I should still be able to press "rctrl-4" to have another folder selection dialog opened or to jump directly to the folder saved in rctrl-4 if it is the only one.

**Comment by HamRusTal** [comment]
> A bonus wish: If I press "rctrl-3" which gets the selection dialog opened, I should still be able to press "rctrl-4" to have another folder selection dialog opened or to jump directly to the folder saved in rctrl-4 if it is the only one.

I use the following macro script for this:
```lua
Macro {
  description = "Change drive or use another Folder Shortcut from the target selection menu";
  area = 'Menu Disks'; key = '/RCtrl[0-9]|LAltF[12]/';
  condition = function()
    return Menu.Id == far.Guids.FolderShortcutsMoreId or Menu.Id == far.Guids.ChangeDiskMenuId
  end;
  action = function() Keys'Esc AKey' end
}
```

Likely you can write a script of your own that will implement the main desired behavior — you'll need to override the `RCtrl0`—`RCtrl9` keys at least in the `Shell` area and memorize the key pressed between invocations (e.g. in a local variable outside of the `Macro` definition), then send key presses to FAR depending on the area and whether the saved key is the same as the one at hand.

**Comment by alabuzhev** [comment]
> It will require less hand movement

Amen to that, 6273.

> If I press "rctrl-3" which gets the selection dialog opened, I should still be able to press "rctrl-4" to have another folder selection dialog opened

6273 as well.

> or to jump directly to the folder saved in rctrl-4 if it is the only one

I played with it a little and a direct jump seems to be not so good in this context.
E.g. when you don't really remember whether you need RCtrl+4 or RCtrl+5 or RCtrl+6 and press all of them sequentially to have a look and the first one pressed was not the one but now it jumped somewhere randomly, ugh.
RCtrl+\<N> pressed in a list now always opens a list, even if it's empty or has just one item.

**Comment by imsh** [comment]
I've tried 6273 and everything worked like a charm! I'm also super impressed with the speed of the change, I've never seen such things happening on github before 😂
