### ISSUE TITLE
Ignore leading spaces in command line

### ISSUE THREAD

**Issue by o-sdn-o** [FarGroup/FarManager#798]
### Description of the new feature or improvement

To implement [the idea of integrating a file manager with a command line shell](https://www.linux.org.ru/forum/talks/17517526) the `cd` command is required to change the current directory. We (https://github.com/directvt/vtm) have to prefix the `cd` command with a space to prevent shells from saving it to history. Unfortunately, Far Manager does not accept `cd` commands prefixed with spaces.

https://github.com/FarGroup/FarManager/assets/11535558/7070f3ce-9603-48ca-b237-dbfe188ea7ae

Without the prefix space everything works fine, but a lot of `cd` commands falls to the shell history when syncing, for example, with bash.

Related to https://forum.farmanager.com/viewtopic.php?t=13176

### Proposed technical implementation details (optional)

The simplest solution would be to ignore all spaces or add the `"<space>CD"` command as a special case to the `"CD"` and `"CHDIR"` command set when parsing.

**Comment by alabuzhev** [comment]
Do any other shells support this convention already?

**Comment by o-sdn-o** [comment]
behavior of space-prefixed commands in:
- pwsh: https://github.com/PowerShell/PowerShell/issues/10403#issuecomment-523833700
  ```pwsh
  Set-PSReadLineOption -AddToHistoryHandler {
        param($line)
        $line -notmatch '^\s+|AsPlainText'
  }
  ```
- bash with `HISTCONTROL=ignorespace` in ~/.bashrc (it is default in WSL)
- zsh with `setopt HIST_IGNORE_SPACE` in  ~/.zshrc
- cmd.exe in vtm environment for runtime command history

**Comment by yegor-mialyk** [comment]
I have an impression that it should be possible to create a macro that will turn off history if it detects leading spaces in a command

**Comment by o-sdn-o** [comment]
The main issue is that the space-prefixed `cd` command is not executed at all by Far Manager.

**Comment by o-sdn-o** [comment]
For context, the approach is as follows: the shell (no matter which one), when outputting its prompt, also prints an OSC9;9 notification with the current directory. The hosting desktop (e.g. vtm desktop environment) catches these notifications and sends them to all subscribed windows that execute the `<space>cd <cur_dir>\n` command. The `cd` command is cross-platform compatible.

**Comment by o-sdn-o** [comment]
> Do any other shells support this convention already?

If you mean a feature that synchronizes the directories of several console windows using cd command injection, then probably no one except vtm.

**Comment by alabuzhev** [comment]
I mean suppressing history with leading spaces.

Just ignoring them would be fine: cmd does that, so we ought to do that too for consistency anyway.

**Comment by o-sdn-o** [comment]
> Just ignoring them would be fine: cmd does that

cmd ignore space-prefixed in vtm environment only. In Windows Terminal or in classic console prompt all commands including space-prefixed falls to the runtime cmd history.
