### ISSUE TITLE
Issue with left mouse click outside of autocomplete history list

### ISSUE THREAD

**Issue by ssvine** [FarGroup/FarManager#799]
### Far Manager version

3.0.6273.0

### OS version

10.0.19045.4046

### Steps to reproduce

Если начать вводить текст в контрол `DI_EDIT` c установленным флагом `DIF_HISTORY` так, чтобы открылся список автокомплита, то при клике левой кнопкой мыши в любом месте вне самого списка (хоть на диалоге, хоть вне его) получим автоматический ввод текущего содержимого контрола с закрытием диалога.

(Для примера можно открыть диалог создания каталога)

### Actual behavior

Когда я выбираю нужный элемент в списке с помощью клавиатуры и нажимаю `Enter`, я понимаю свой выбор.

Когда клик мышью, которая не стоит на каком-либо элементе списка, автоматически транслируется в `Enter` - это не то, что я ожидаю. По логике вещей, это должно работать как нажатие на `Esc`. 

Предлагаю сделать ограничение на трансляцию клика в `Enter` - смотреть, находится ли мышь на каком-нибудь элементе списка.

**Comment by alabuzhev** [comment]
6275
