### ISSUE TITLE
Backspace does not open user menu of parent folder

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#800]
### Far Manager version

3.0.6274.0 x64

### OS version

10.0.22635.3140

### Steps to reproduce

1. Extract the attached archive [`UserMenu-Test.zip`](https://github.com/FarGroup/FarManager/files/14317590/UserMenu-Test.zip) to `%TEMP%`
2. Enter the directory `%TEMP%\1\2\3`
3. Press `F2` to open the user menu
4. You should see a single entry with the name `Level 3`
5. Press the backspace key `BS`

### Expected behavior

The local user menu from the parent folder should open, showing a single entry `Level 2`

### Actual behavior

The main user menu is opened.

### Additional Information
This issue was introduced in c58b405. Here is the relevant part of the commit:

```diff
--- a/far/usermenu.cpp
+++ b/far/usermenu.cpp
@@ -349,27 +349,35 @@ void UserMenu::SaveMenu(string_view const MenuFileName) const
 void UserMenu::ProcessUserMenu(bool ChooseMenuType, string_view const MenuFileName)
 {
 	// Путь к текущему каталогу с файлом LocalMenuFileName
-	auto strMenuFilePath = Global->CtrlObject->Cp()->ActivePanel()->GetCurDir();
-	// по умолчанию меню - это FarMenu.ini
-	m_MenuMode = menu_mode::local;
+	string strMenuFilePath;
```

The original code initialized `strMenuFilePath`. The current version only initializes this value if `ChooseMenuType` is `true`. When `F2` is pressed, the code calls [`user_menu(false)`](https://github.com/FarGroup/FarManager/blob/7c51250ba05e603bf3125a3857ef416c1fd34448/far/cmdline.cpp#L336-L340) which in turn [initializes](https://github.com/FarGroup/FarManager/blob/7c51250ba05e603bf3125a3857ef416c1fd34448/far/usermenu.cpp#L1139-L1142) `UserMenu` with `ChooseMenuType` as `false`. As a result, [`this`](https://github.com/FarGroup/FarManager/blob/7c51250ba05e603bf3125a3857ef416c1fd34448/far/usermenu.cpp#L358-L385) code is not executed and `strMenuFilePath` is not initialized.

Finally, since `strMenuFilePath` is empty, the function `CutToParent` returns `false` causing the menu to switch to the global user menu, as seen here:

https://github.com/FarGroup/FarManager/blob/7c51250ba05e603bf3125a3857ef416c1fd34448/far/usermenu.cpp#L464-L475

### Possible Fix
The following patch fixes this issue:

```diff
diff --git a/far/usermenu.cpp b/far/usermenu.cpp
index c19283755..e05a0ca18 100644
--- a/far/usermenu.cpp
+++ b/far/usermenu.cpp
@@ -383,6 +383,10 @@ void UserMenu::ProcessUserMenu(bool ChooseMenuType, string_view const MenuFileNa
 			std::unreachable();
 		}
 	}
+	else
+	{
+		strMenuFilePath = Global->CtrlObject->Cp()->ActivePanel()->GetCurDir();
+	}
 
 	// основной цикл обработки
 	bool FirstRun=true;

```

### Remaining Issue
There may be another issue, the behavior of which is modified with the above patch. If you run the following command, you will see `Level 3`. However, when you press `BS`, it will _not_ go to the parent menu, but the title of the menu will change from **_Local menu_** to **_Main menu (Global)_**.

`lua:mf.usermenu(2, win.GetEnv("TEMP")..[[\1\2\3\FarMenu.ini]])`

I'm not sure if this is the expected behavior. After the above patch, you need to press `BS` a number of times (equal to the depth of the folder) before it reaches the main menu, and causes the title to change.

**Comment by alabuzhev** [comment]
Both should be fixed in 6275.

**Comment by rohitab** [comment]
Thank you. Both these issues are resolved.

I did notice another minor issue when you use `Shift+F2` to switch menus, after opening a menu using `mf.usermenu`. In the test case above:

- If you press `Shift+F2` on `Level 3`, the menu doesn't change, but the title rotates from **_Local menu_** to **_Main menu (Global)_** to **_Main menu (User)_** and back. Older versions had the same behavior.
- If you press `BS`, then `Shift+F2` on `Level 2`, the menu switches to **_Main menu (User)_**, and remains there regardless of how many times you press `Shift+F2` again.

I'm closing this ticket since the issues I reported have been resolved. I just thought I'd mention the above for completeness.

**Comment by alabuzhev** [comment]
Thanks for checking.

> another minor issue

That one is essentially the same. Should be fixed in 6277.

**Comment by rohitab** [comment]
All good now. Thank you.
