### ISSUE TITLE
Colors from deleted lines are reused causing spurious colors in the editor

### ISSUE THREAD

**Issue by rohitab** [FarGroup/FarManager#801]
### Far Manager version

3.0.6277.0 x64

### OS version

10.0.22635.3209

### Steps to reproduce

1. Run the command `copy "%FARHOME%\Addons\Macros\Editor.ColorWord.moon" "%FARPROFILE%\Macros\scripts"` to install the addon script that allows you to color words in the editor.
2. Run `macro:load` to reload macros, or restart Far.
3. Run `edit:%FARHOME%\Documentation\eng\Bug.Report.txt` to open the editor with the provided file.
4. Go to `Line 10` and `Col 19` so that the cursor is on the `the` word.
5. Press `F5` to color the words.
6. All the `the` words should now have a light blue background.
7. Press `Home` to go to the beginning of `Line 10`.
8. Hold `Shift` and press the `Down` arrow `8` times to select the complete paragraph.
9. Press `Ctrl+X` to cut the paragraph.
10. Press `Ctrl+V` to paste the paragraph.
11. Press `Ctrl+Z` to undo the change.
12. Press `F5` to turn off the coloring of all words.
14. Press `Ctrl+V` to paste the paragraph again.

### Expected behavior

The paragraph is pasted and none of the words are colored with a light blue background.

### Actual behavior

The paragraph is pasted, but some words are randomly colored in light blue as seen on the screenshot.

**NOTE**: If you don't see this issue, press `Ctrl+Z` and `Ctrl+Shift+Z` combination a few times. If you still don't see the issue, close the editor and repeat from `Step 3` above. The issue might take a couple of attempts to reproduce.

![color-issue](https://github.com/FarGroup/FarManager/assets/800999/6639f599-273c-4961-9537-d2c1f5400342)

### Additional Information
Colors are added to the editor using [`ECTL_ADDCOLOR`](https://github.com/FarGroup/FarManager/blob/155a050fa43590f51fda030afed954a7d30dea53/far/editor.cpp#L5599-L5622), which calls [`Editor::AddColor`](https://github.com/FarGroup/FarManager/blob/155a050fa43590f51fda030afed954a7d30dea53/far/editor.cpp#L6766-L6769) to store information about the item and its color in `m_ColorList`.

https://github.com/FarGroup/FarManager/blob/155a050fa43590f51fda030afed954a7d30dea53/far/editor.cpp#L6766-L6769

Colors are deleted using [`ECTL_DELCOLOR`](https://github.com/FarGroup/FarManager/blob/155a050fa43590f51fda030afed954a7d30dea53/far/editor.cpp#L5649-L5665), which calls [`Editor::DeleteColor`](https://github.com/FarGroup/FarManager/blob/155a050fa43590f51fda030afed954a7d30dea53/far/editor.cpp#L5659-L5662) to remove entries from `m_ColorList`.

https://github.com/FarGroup/FarManager/blob/155a050fa43590f51fda030afed954a7d30dea53/far/editor.cpp#L6771-L6777

Auto-delete colors, specified by `ECF_AUTODELETE`, which are used by `Editor.ColorWord.moon`, are deleted in response to `EE_REDRAW`.

https://github.com/FarGroup/FarManager/blob/155a050fa43590f51fda030afed954a7d30dea53/far/editor.cpp#L6912-L6920

### Issue

When a line or block is deleted from the editor, the [`Editor::DeleteString`](https://github.com/FarGroup/FarManager/blob/155a050fa43590f51fda030afed954a7d30dea53/far/editor.cpp#L2843-L2944) function is called. However, this function does _not_ call [`Editor::DeleteColor`](https://github.com/FarGroup/FarManager/blob/155a050fa43590f51fda030afed954a7d30dea53/far/editor.cpp#L6771-L6782) to remove entries from `m_ColorList`. As a result, older entries from deleted lines are never removed, and can get reused when new lines are added, causing random coloring.

### Patch
The following patch fixes this issue. I've tested it with `Editor.ColorWord.moon`, as well as my own Lua script, which is how I found this issue in the first place. It appears to be working correctly.

```diff
diff --git a/far/editor.cpp b/far/editor.cpp
index 1f4c5aa89..d1db089ce 100644
--- a/far/editor.cpp
+++ b/far/editor.cpp
@@ -2935,6 +2935,7 @@ Editor::numbered_iterator Editor::DeleteString(numbered_iterator DelPtr, bool De
 	}
 
 	m_AutoDeletedColors.erase(std::to_address(DelPtr));
+	DeleteColor(DelPtr, [](const ColorItem& Item) { return true; });
 
 	const auto Result = numbered_iterator(Lines.erase(DelPtr), DelPtr.Number());
 

```

**Comment by alabuzhev** [comment]
Thanks for the fix and, as always, for the excellent bug report.

Applied to 6278.

**Comment by rohitab** [comment]
I appreciate that. Thank you.

Just tested version `3.0.6278.0 x64`. This issue is resolved.
