### ISSUE TITLE
filenames with Chinese UTF-8 chars spoils alignment in panel view

### ISSUE THREAD

**Issue by tbali0524** [FarGroup/FarManager#817]
### Far Manager version

3.0.6226

### OS version

10.0.22631.3296

### Steps to reproduce

It seems if the folder contains any file with some 4-byte UTF-8 characters in it, then the subsequent lines are not properly aligned.
See example screenshot.
![ss_far_bug1](https://github.com/FarGroup/FarManager/assets/51286559/6891289a-bf59-4bdc-8292-64d0a080cdd0)

### Expected behavior

Filenames are properly displayed in the panbel view

### Actual behavior

Subsequent lines are not properly aligned.

**Comment by HamRusTal** [comment]
Try `[x] Fullwidth-aware rendering` in `Interface settings` (from the Options menu).

**Comment by tbali0524** [comment]
Thanks, this solved it. I close this issue.
