### ISSUE TITLE
After exiting the drawio application, the Far panel view is distorted, needs manual reset

### ISSUE THREAD

**Issue by tbali0524** [FarGroup/FarManager#818]
### Far Manager version

3.0.6226.0

### OS version

10.0.22631.3296

### Steps to reproduce

Open any .drawio document by hiting Enter in the Far file panel. (With drawio desktop application installed)
Drawio app correctly opens but after closing it, it prints some message back to the FAR window and it confuses the Far panel view. Screenshot:
![ss_far_bug2](https://github.com/FarGroup/FarManager/assets/51286559/545a3bf1-761f-4c7a-a1eb-3e7c695958ba)
Resetting the view (e.g. Maximize icon + Restore down icon of the Terminal) solves the problem.

### Expected behavior

After exiting the drawio app, Far should be used as before

### Actual behavior

The panel view is distorted and needs manual resetting of the terminal window.

**Comment by bitraid** [comment]
See #495.
