### ISSUE TITLE
Can create CON and NUL files but cannot rename to that names

### ISSUE THREAD

**Issue by ssvine** [FarGroup/FarManager#819]
### Far Manager version

3.0.6299.0

### OS version

10.0.19045.4170

### Steps to reproduce

1. Create files `con`, `nul` and check they are successfully created
2. Rename that files to some unrelated names
3. Try to rename them back

### Expected behavior

Renaming to `con` or `nul` is successful

### Actual behavior

Cannot rename files to `con` or `nul`.
Interestingly, everything is ok with other reserved names like `prn`, `aux`, `com1`, etc.

**Comment by alabuzhev** [comment]
This behavior is intentional and even described in Help (F6 F1).
Renaming to ./con or ./nul should work.

**Comment by ssvine** [comment]
Ah, I see. Thanks for the answer.
