### ISSUE TITLE
Версия для iOS

### ISSUE THREAD

**Issue by ahryshchanka** [FarGroup/FarManager#82]
Доброго дня. спасибо за программу, очень нравится.

Можно ли сделать билд для iOS операционной системы. В сети есть описание как упаковать программу для iOS, тогда возникает вопрос -- зачем заморачивать пользователя со всеми этими активностями, если можно попробовать сделать такую версию как часть процесса билда программы?

**Comment by trexinc** [comment]
Где можно почитать о таких чудесах технологии?

**Comment by ahryshchanka** [comment]
@trexinc   http://heximal.ru/blog/vsyachina/zapuskaem-far-manager-pod-mac-os-x/

**Comment by trexinc** [comment]
А OS X и wine. Да фар можно конечно запускать под Wine на любых операционых системах где есть Wine но устновить и настроить вайн это, ИМХО, дело пользователя. Я считаю что в этих операционых системах лучше использовать нативные интсрументы.

**Comment by shciubrcom** [comment]
Правильно я понимаю, что нативной версии для мака не планируется?

**Comment by alabuzhev** [comment]
Closed as a duplicate of #3
