### ISSUE TITLE
Crash related to NetBox

### ISSUE THREAD

**Issue by shmuz** [FarGroup/FarManager#824]
### Far Manager version

3.0.6299

### OS version

10.0.22631.3296

### Steps to reproduce

Run `lua:@test.lua` where test lua contains the following:
```lua
local farhome = win.GetEnv("FARHOME")
local dll = farhome.."\\Plugins\\NetBox\\NetBox.dll"

local hnd = far.ForcedLoadPlugin("PLT_PATH", dll)
far.UnloadPlugin(hnd)
far.LoadPlugin("PLT_PATH", dll)

editor.Editor(farhome.."\\FarEng.lng")
```

### Expected behavior

Opening the editor with FarEng.lng

### Actual behavior

Crash.
[bug_report.txt](https://github.com/FarGroup/FarManager/files/14908077/bug_report.txt)
[far.mdmp.zip](https://github.com/FarGroup/FarManager/files/14908089/far.mdmp.zip)

**Comment by alabuzhev** [comment]
@michaellukashov fyi

**Comment by ssvine** [comment]
`Far` has a problem here because it never calls `FreeLibrary`. So any plugin that undergoes `far.ForcedLoadPlugin / far.UnloadPlugin` won't be unloaded from the address space of the process (`DllMain` of the plugin will get exactly one `DLL_PROCESS_ATTACH` at the first load and one `DLL_PROCESS_DETACH` at the `Far` termination).

This results in global / static local variables not being cleared on reload. So it's worth fixing this on `Far`'s side.

**Comment by alabuzhev** [comment]
> it never calls `FreeLibrary`

![image](https://github.com/FarGroup/FarManager/assets/11453922/5d07aad2-add9-4ff0-8503-b7644dfd6f89)

**Comment by alabuzhev** [comment]
[NetBox/libs/openssl-3/crypto/init.c](https://github.com/michaellukashov/Far-NetBox/blob/9c9de8aecd0994233bc6a69cd918ade6420ab4a3/libs/openssl-3/crypto/init.c#L140-L142):

```C
        ret = GetModuleHandleEx(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS
                                | GET_MODULE_HANDLE_EX_FLAG_PIN,
                                (void *)&base_inited, &handle);
```

![image](https://github.com/FarGroup/FarManager/assets/11453922/f0ac3533-2b93-4d4f-9f55-bcc58262454e)

I hope it is obvious what is going on.

If you want `FreeLibrary` to work, you need to tell OpenSSL to [stop pinning the whole thing](https://github.com/openssl/openssl/blob/master/INSTALL.md#no-pinshared) by defining `OPENSSL_NO_PINSHARED`.

**Comment by ssvine** [comment]
> it never calls FreeLibrary

I made that quick assumption just by observing `DllMain` calls and an obvious case that `LoadLibrary` / `FreeLibrary` should work normal. That was wrong. So, it's time to look at Far's sources more thoroughly ;)

@alabuzhev thanks for you time.

**Comment by alabuzhev** [comment]
3.0.6304 comes with a fixed NetBox.
