### ISSUE TITLE
Чекбокс для обратного поиска в файле

### ISSUE THREAD

**Issue by avilovv** [FarGroup/FarManager#828]
### Description of the new feature or improvement

В новом диалоговом окне поиска в файле нет чекбокса "обратный поиск". Вместо него добавлена кнопка "Искать предыдущий", что неудобно, если эту операцию приходится выполнять часто. Просьба вернуть чекбокс "обратный поиск", как было до версии 3.0.6060 включительно.

**Comment by yegor-mialyk** [comment]
`AltF7`?

**Comment by avilovv** [comment]
> `AltF7`?

Alt-F7 повторяет поиск той же строки. Бывает, что нужно искать разные строки обратным поиском. В новом интерфейсе для этого приходится нажимать на специальную кнопку, это неудобно.

**Comment by HamRusTal** [comment]
> искать разные строки обратным поиском

Непонятно, что это означает. Приведите, пожалуйста пример.

> приходится нажимать на специальную кнопку, это неудобно

Если речь о кнопке «Искать предыдущий», то лично мне как раз наоборот стало удобнее — я из диалога в одно действие (нажатие кнопки) запускаю нужный мне поиск, а не в два, как раньше (выставить галку, нажать кнопку).

**Comment by avilovv** [comment]
> Непонятно, что это означает. Приведите, пожалуйста пример.
Пример: в логе с конца поискать одну строку, потом другую строку, потом третью. Для этого надо каждый раз нажимать кнопку "искать предыдущий" мышкой. Раньше можно было просто запускать поиск enter-ом после ввода очередной строки.

> Если речь о кнопке «Искать предыдущий», то лично мне как раз наоборот стало удобнее — я из диалога в одно действие (нажатие кнопки) запускаю нужный мне поиск, а не в два, как раньше (выставить галку, нажать кнопку).
А мне стало неудобно. Если быть последовательным, зачем вообще чекбоксы. Почему бы не сделать кнопки "искать как regex", "искать с учетом регистра" и т.д. (сарказм)

**Comment by HamRusTal** [comment]
> надо каждый раз нажимать кнопку "искать предыдущий" мышкой

Совершенно незачем нажимать её мышкой — используйте горячую клавишу.

**Comment by avilovv** [comment]
> Совершенно незачем нажимать её мышкой — используйте горячую клавишу.

В русском интерфейсе в качестве горячей клавиши подсвечивается русская буква "п". Ввел строку для поиска, ушел с нее TAB-ом (иначе горячая клавиша не сработает), переключился на русский, нажал "п", переключился обратно на английский. 5 нажатий вместо одного нажатия enter.

**Comment by johnd0e** [comment]
@avilovv 
Горячие клавиши надо использовать иначе: Alt-п
Уходить никуда не надо.
Переключать раскладку не надо.

**Comment by avilovv** [comment]
> @avilovv Горячие клавиши надо использовать иначе: Alt+п Уходить никуда не надо. Переключать раскладку не надо.

Все равно 2 нажатия вместо одного нажатия enter. Собственно я проблему для себя решил - откатился на 3.0.6060. Очень жаль, что far ломает привычный и удобный функционал по совершенно невнятным причинам.

**Comment by MKadaner** [comment]
> ...по совершенно невнятным причинам

Обсуждение причин было здесь: #600.

**Comment by avilovv** [comment]
> Обсуждение причин было здесь: #600.

Определенно следовало оставить чекбокс для тех, кому он нужен. Кому удобнее пользоваться горячими клавишами - пусть будут и горячие клавиши.

**Comment by alabuzhev** [comment]
https://xkcd.com/1172/
