### ISSUE TITLE
ZIP created with ArcLite faled to decompress (by 3rd party)

### ISSUE THREAD

**Issue by d4rkmen** [FarGroup/FarManager#832]
### Far Manager version

3.0.6300

### OS version

10.0.19045.4291

### Steps to reproduce

After update from 3.0.6161 to the latest 3.0.6300 faced problem: Magisk modules zipped (or changed) with Far (ArcLite) become not readable by Magisk (Unzip error)
Not sure what exactly has been changed, but rolling back to 3.0.6161 fix the problem
Same time the archive looks fine and passes testing well

### Actual behavior

Failed to unzip by Magisk

**Comment by alabuzhev** [comment]
#781 enabled non-standard compression methods for zip format.
When creating or modifying zip archives, make sure to select "Deflate" method:

![image](https://github.com/FarGroup/FarManager/assets/11453922/5ee8f0a2-a8bc-48cf-bcba-e593cd7c6cee)

It should happen automatically in theory, but apparently it didn't.
Maybe it has something to do with your saved settings, if any.

**Comment by d4rkmen** [comment]
It was set to LZMA. Thanks
