### ISSUE TITLE
Internal editor, new insert feature

### ISSUE THREAD

**Issue by lelicopter** [FarGroup/FarManager#833]
### Description of the new feature or improvement

After Alt+Shift+Arrow special selection was created, add a shortcut to add a different text afret or before selection.

### Proposed technical implementation details (optional)

its useful for large text convertions.
for example, have a list:
```
1,3,5
2,4,6
```
we can select column one (value 1,2) and insert "(" before.
and select column five (values 5,6) and insert ")," after.
as result we have:
```
(1,3,5),
(2,4,6),

```
this is mostly complete for add this result to source code ( like Python style):
a = {`...result from copy/paste from editor...`}

**Comment by HamRusTal** [comment]
What you ask is implemented as a script already: [SciTE-like.lua](https://forum.farmanager.com/viewtopic.php?p=126100#p126100) (use an online translator if/when needed).

**Comment by lelicopter** [comment]
> What you ask is implemented as a script already: [SciTE-like.lua](https://forum.farmanager.com/viewtopic.php?p=126100#p126100) (use an online translator if/when needed).

Thanx for advice! Спасибо за подсказку.

**Comment by lelicopter** [comment]
Thanx for advice! Спасибо за подсказку.
