### ISSUE TITLE
Сдвиг строк редактора при использовании креста

### ISSUE THREAD

**Issue by ctapmex** [FarGroup/FarManager#841]
### Far Manager version

3.0.6333.0

### OS version

10.0.22631.3447

### Other software

Терминал Windows
Версия: 1.19.11213.0

### Steps to reproduce

Открываем любой файл на редактирование. Включаем показ Креста, именно полного креста. Переходим в верхний левый угол, стрелками влево, вправо, вниз . и наблюдаем как пропадает верхняя строка, происходят проблемы с отображением.

### Actual behavior

на видео показано, что происходит
https://github.com/FarGroup/FarManager/assets/1277115/7db26dff-061d-40e4-b729-43c9fe7b65c5

**Comment by ctapmex** [comment]
на win10 + терминал 1.17.11461.0 такой проблемы нет

**Comment by ctapmex** [comment]
а вот начиная с 1.19 и до самой последней  1.21 проблемы появляются.

**Comment by johnd0e** [comment]
1.19.240430003
Не вижу проблемы у себя.

**Comment by yegor-mialyk** [comment]
1.21.1272.0 не пропадает.

> [x] Use Virtual Terminal for rendering
> [x] Fullwidth-aware rendering

**Comment by ctapmex** [comment]
для решения достаточно
[x] Use Virtual Terminal for rendering

**Comment by alabuzhev** [comment]
[microsoft/terminal/issues/new](https://github.com/microsoft/terminal/issues/new?assignees=&labels=Issue-Bug%2CNeeds-Triage&projects=&template=Bug_Report.yml)

**Comment by johnd0e** [comment]
> для решения достаточно

У меня действительно эта опция была активирована, но выключил, и всё равно не воспроизводится

**Comment by ctapmex** [comment]
так может "Use Virtual Terminal for rendering" включать о умолчанию на системах выше 10 ?

**Comment by yegor-mialyk** [comment]
Говорят, что ConEmu из-за этой настройки "втыкает" (очень медленно перерисовывает). Но, я лично, его не использую, поэтому мне ок :)
