### ISSUE TITLE
Commit "Properly align color structures" breaks C++/CLI compilation of plugin.hpp

### ISSUE THREAD

**Issue by nightroman** [FarGroup/FarManager#844]
### Far Manager version

Far 3.0.6333

### OS version

Windows 11

### Other software

VS 2022

### Steps to reproduce

With this [commit](https://github.com/FarGroup/FarManager/commit/e75420a55f1873e3d7dee88a1be96b935e4229a7) I cannot compile plugin.hpp in C++/CLI project (FarNet plugin).

If there is a proper way of dealing with this new `plugin.hpp` or a workaround, I'll use it.
But for the moment I cannot compile starting with Far 3.0.6333

### Expected behavior

I can compile / use plugin.hpp in C++/CLI projects.

### Actual behavior

I cannot compile / use plugin.hpp in C++/CLI projects.
The error is like "you cannot use aligned in managed code"

**Comment by alabuzhev** [comment]
@nightroman I've added `!defined(__cplusplus_cli)`, hopefully it helps.

**Comment by nightroman** [comment]
Yes, it compiles, thank you very much!
