### ISSUE TITLE
Некорректная реакция на F11

### ISSUE THREAD

**Issue by a-ivanitskiy** [FarGroup/FarManager#848]
### Far Manager version

3.0.6300.0 x64

### OS version

10.0.22631.3593

### Steps to reproduce

Открыть Far manager, нажать F11

### Expected behavior

Открывается меню плагинов (Plugin command)

### Actual behavior

Окно Far разворачивается на весь экран

**Comment by karbazol** [comment]
Это потому, что вы запускаете Far в Windows Terminal. Два пути это поправить - либо запускать Far от имени админстратора, либо убрать из настроек Windows Terminal обработку нажатия F11.
