### ISSUE TITLE
Crashing on every executable file or copying any file

### ISSUE THREAD

**Issue by seg-on** [FarGroup/FarManager#85]
After last update to 3.0.5354 x64 (I tried nightly 3.0.5355 x64 too) when I run some executable file or copy file Far is crashing down.

![image](https://user-images.githubusercontent.com/19683952/51597486-a8da1580-1efb-11e9-9d88-5b6b4aae14ec.png)

**Comment by alabuzhev** [comment]
As the exception text says, one of your configuration dbs is broken, presumably history.
Run `explorer %FARLOCALPROFILE%`, close all instances of Far and delete history.db in that folder (make a backup copy first).

**Comment by seg-on** [comment]
Thanks very much, now looks good :)

**Comment by johnd0e** [comment]
@djonik1562 
https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database
