### ISSUE TITLE
Windows 10 32-bit crash

### ISSUE THREAD

**Issue by Montura** [FarGroup/FarManager#854]
### Far Manager version

3.0.6344.3912

### OS version

10.0.19045.2006

### Other software

Git for Windows v2.45.2 
ImpEx plugin v0.8.15

### Steps to reproduce

Actually, it's hard to explain what's going on...
1. I used the latest standalone Far version.
2. Added ImpEx plugin 
3. Two days ago everything was OK.
4. Typed in Far console in git repo: `git difftool`
5. Looked at changes, typed in Far console `:q` (like vim)
6. As I remember, I've done it twice - for left and right diff view 
7. Then the right Far panel with dir list has become empty: only the header **Name** and that's it
8. I closed Far and reopened it.
9. Got a crash with **far.mddmp**

P.S. 
1. I removed installed Far 
2. Download again the latest version
3. Opened it first time and got a crash again

### Expected behavior

Work without crash

### Actual behavior

Crash after opening
[crahs_log_and_dump_far_20240708_084616951_6832.zip](https://github.com/user-attachments/files/16125165/crahs_log_and_dump_far_20240708_084616951_6832.zip)

![image](https://github.com/FarGroup/FarManager/assets/4503006/f06db934-9825-4168-b29e-bbba0186d76b)

**Comment by alabuzhev** [comment]
Please share your generalconfig.db.
Renaming / removing that file could also help with the startup crash.

**Comment by Montura** [comment]
@alabuzhev, sorry for a stupid question, but I don't know where to find `generalconfig.db`.

**Comment by alabuzhev** [comment]
C:\Users\montura\AppData\Roaming\Far Manager\Profile

**Comment by Montura** [comment]
Thanks a lot!
[generalconfig.zip](https://github.com/user-attachments/files/16134588/generalconfig.zip)

**Comment by alabuzhev** [comment]
Fixed in 6345.
