### ISSUE TITLE
Network plug-in bug

### ISSUE THREAD

**Issue by Galaxy-Wizard** [FarGroup/FarManager#859]
### Far Manager version

3.0.6300.0 x64

### OS version

10.0.19042.2965

### Steps to reproduce

![image](https://github.com/user-attachments/assets/fe2ebe68-1687-4acb-a8db-286591608d6d)
Увайсці ў сетку, націснуць Alternative ды Enter, каб увайсці ў поўнаэкранны рэжым, - убачыце памылку ў модулі агляду сеткі.

### Expected behavior

Full screen mode should work correctly all the times.

### Actual behavior

Picture is not redrawn correctly after entering full screen mode.

**Comment by Galaxy-Wizard** [comment]
The application was in modal state while trying to enter the router into its smb server.

**Comment by alabuzhev** [comment]
It should work as expected in the latest available version.

**Comment by Galaxy-Wizard** [comment]
Это не ошибка конкретного плагина.
Это ошибка в проектировании системы плагинов: вы создали систему плагинов такой уязвимой, как будто сейчас 1995 года и Билл Гайтс на выставке показывает свою Windows 95 и она улетает в синий экран смерти.
Честно скажу: такого проектировщика плагинов - немыслемого оболдуя - я бы не подпускал к компьютеру, пока он не отработает и не сдаст мне экзамен с младшего разработчика на ведущего разработчика. Он бы у меня дворником работал, а не программистом.
### **_Это ошибка проектирования интерфейса взаимодействия между программой и её надстройками._**

**Comment by HamRusTal** [comment]
> Это не ошибка конкретного плагина.
> Это ошибка в проектировании системы плагинов

Раз вы так хорошо всё знаете и понимаете и вас настолько огорчает нынешнее положение дел, за чем же дело стало?! Предложите продуманный детальный поэтапный план, следуя которому вы лично готовы исправить ситуацию, сохраняя работоспособность тех ценных старых плагинов, развитием которых уже никто не занимается. Вон, я гляжу, первый шаг месяц назад уже сделали, Фар себе форкнули. Что же вдруг остановились-то для пустых жалоб?
