### ISSUE TITLE
Разделить рабочие нити от нитей графического интерфейса

### ISSUE THREAD

**Issue by Galaxy-Wizard** [FarGroup/FarManager#860]
### Description of the new feature or improvement

Разделить рабочие нити от нитей графического интерфейса.

### Proposed technical implementation details (optional)

MFC in static library for platforms ARM, ARM32, x86-32, x86-64: use AfxCreateThread for each worker action while Main Thread uses events loop, and GUI Thread running separately from Main Thread and Worked Threads.

**Comment by yegor-mialyk** [comment]
Are you sure this ticket is applicable to Far Manager? Far Manager does not have any GUI and its code does not utilize MFC.

**Comment by Galaxy-Wizard** [comment]
100 пудов. Любое консольное приложение может иметь GUI Thread. Что по вашему делает функция wmain, чтобы вызвать WinMain. Я предлагаю только статическое связывание и разделение потоков, рабочих от потоков графического интерфейса. На счёт MFC не настаиваю. Ваша программа строится для Linux?

**Comment by Galaxy-Wizard** [comment]
Посмотрите баг про компонент для работы с сетеью.

**Comment by Galaxy-Wizard** [comment]
Я имею в виду под _GUI_ _поток рисования в консольном режиме_ работы видеоплаты в окне программы.

**Comment by yegor-mialyk** [comment]
I see no reason to continue this conversation trying to explain anything, we speak different languages literally and figuratively. It won't go anywhere.

**Comment by Galaxy-Wizard** [comment]
Тогда иди дальше выращивать укроп в своём огороде. Коноплю только не выращивай, а то ОМОН приедет и повяжет.

**Comment by alabuzhev** [comment]
We have no plans to implement this sort of thing in the foreseeable future.

**Comment by Galaxy-Wizard** [comment]
Это показывает вашу безграмотность и разгильдяйство.
Удачно сидеть в своей луже.
