### ISSUE TITLE
Strange characters in console after cd

### ISSUE THREAD

**Issue by skipik** [FarGroup/FarManager#866]
### Far Manager version

3.0.6360.0

### OS version

10.0.22631.4037

### Steps to reproduce

Open far [in conhost, not wt]
Try to cd - down - some of your entries from history - enter [try to jump to some of your folders from history]

### Expected behavior

There won't be any weird characters in console

### Actual behavior

Sometimes there are some weird characters after some entries (on the next line): https://ibb.co/cbMVr10
It started to happen since b6348.
Additional info: https://forum.ru-board.com/topic.cgi?forum=5&topic=51024&start=2020#3

**Comment by johnd0e** [comment]
@skipik 

`[x] Use Virtual Terminal for rendering`?

**Comment by skipik** [comment]
@johnd0e looks like it fixes the problem, yeah. So it's up to @alabuzhev if that should be labeled as a bug or not.

**Comment by alabuzhev** [comment]
6361
