### ISSUE TITLE
Viewer problems

### ISSUE THREAD

**Issue by skipik** [FarGroup/FarManager#867]
### Far Manager version

3.0.6361.0

### OS version

10.0.22631.4037

### Steps to reproduce

Run far manager in conhost
[x] Use Virtual Terminal for rendering
F3/F4 on the attached file
Press Page Down for a bit
[History3264.txt](https://github.com/user-attachments/files/16679596/History3264.txt)

### Expected behavior

No ui problems

### Actual behavior

Some viewer ui problems uncluding the key bar

**Comment by johnd0e** [comment]
Unable to reproduce

**Comment by skipik** [comment]
@johnd0e for me it's 100% repro even on a clean profile

**Comment by yegor-mialyk** [comment]
- is it under Conhost?
- what is the Font used?

**Comment by skipik** [comment]
@yegor-mialyk conhost, yes, it's in the steps of my report. Consolas 16 or 20.

**Comment by alabuzhev** [comment]
The attached file uses `・` ([U+30FB](https://www.compart.com/en/unicode/U+30FB) Katakana Middle Dot) for bullet points in lists (only the author knows why).

Unlike some less exotic options, e.g. `·` ([U+00B7](https://www.compart.com/en/unicode/U+00B7) Middle Dot) or `•` ([U+2022](https://www.compart.com/en/unicode/U+2022) Bullet), and like the other Katakana characters, U+30FB is [fullwidth](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms), i.e. it occupies two screen cells.

You need to turn on `[x] Fullwidth-aware rendering` to draw such characters properly-ish (to some extent, it is still an ongoing project).

**Comment by skipik** [comment]
@alabuzhev you're right. [x] Fullwidth-aware rendering fixes it. Thanks a lot!
