### ISSUE TITLE
FAR sets nanosecond filetime incorrectly

### ISSUE THREAD

**Issue by Markus74a** [FarGroup/FarManager#878]
### Far Manager version

3.0.6383

### OS version

10.0.22631.4391

### Steps to reproduce

In the current version (3.0.6383), FAR incorrectly sets file times.

**Steps to reproduce**
- Select any file, `Ctrl-A` edit its attributes and set the file time to `11:11:11,1111111`
- View the attributes again. All four file times now have the timestamp `11:11:11,1110111`

I found out by trial and error that the bug was introduced between these two builds:
- Far.x64.**3.0.6378.3994**.a3c51b15ba70db0eeeb26096e2ee6b04c4afbfa2.7z
- Far.x64.**3.0.6379.3995**.de699bfc40644027c49079148e02404cff13d5d2.7z

With 3.0.6378 everything works fine, starting with 3.0.6379 the 4th digit of the nanoseconds is always set to `0`.

This bug does not happen when using the Windows build-in file copy routine, but whenever FAR actively sets the time, for example, using the "Change File Attributes" function.

I noticed this when the "Advanced Compare" plugin suddenly reported most of the files in two identical directories as different. The only files identified as "same" where the ones where the original file time already had a `0` as the 4th nanosecond digit.

### Actual behavior

Whenever FAR writes a file time (write, change, modify or access time) in the format **`AB:CD:EF,GHIJKLM`** (e.g. `01:23:45,1234567`), FAR will store the times as **`AB:CD:EF,GHI0KLM`** (e.g. `01:23:45,1230567`), always setting the **`J`** part of the timestamp to zero.

**Comment by alabuzhev** [comment]
Nice catch, thank you. Fixed in 6384.
