### ISSUE TITLE
ArcLite crash during an archive update

### ISSUE THREAD

**Issue by skipik** [FarGroup/FarManager#886]
### Far Manager version

3.0.6394.0

### OS version

Windows NT Workstation 6.1.7601 Service Pack 1

### Other software

There is a dump file and bug-report inside of the test copy as well.
Original bug report and some additional info [ru lang] - > [One](https://forum.ru-board.com/topic.cgi?forum=5&topic=51024&start=2240#21), [Two](https://forum.ru-board.com/topic.cgi?forum=5&topic=51024&start=2260#7)
P.S. no matter what OS is using. I have the same crash on Microsoft Windows [Version 10.0.22631.4460].

### Steps to reproduce

1. Download the [test copy](https://www.upload.ee/files/17436732/x64_test.7z.html).
2. Run Far.exe
3. Open test.zip on one of the panels [enter or ctrl+pgdwn]
4. Try to copy 20241126_092828.png (or any other file) inside of test.zip [procedure of an archive update]
5. Wait and see

### Expected behavior

No crashes

### Actual behavior

ArcLite crashes with a dump file
[bug_report.txt](https://github.com/user-attachments/files/17934995/bug_report.txt)
[far.mdmp.zip](https://github.com/user-attachments/files/17935008/far.mdmp.zip)

**Comment by w17** [comment]
Зачем было 53 мегабайтеый архив аттачить?
Достаточно отдельного пустого test.zip из него.

**Comment by skipik** [comment]
Fixed. Thanks!
