### ISSUE TITLE
Files verification after copying them/moving to another storage

### ISSUE THREAD

**Issue by birdie-github** [FarGroup/FarManager#9]
It would be great if Far had an option for either binary comparing or checksumming copied files against their sources.

For the copied files filesystem caching obviously must be disabled because otherwise you'll be comparing dirty caches against the source (if there's enough RAM to accommodate the source files), and you'll always receive a perfect match.

**Comment by alabuzhev** [comment]
There are many plugins available for both binary and checksum comparison, consider usig them.

We have no plans to include such feature by default as it's too specific (same as retries, skipping bad sectors etc. when reading from a damaged storage).
