### ISSUE TITLE
DI_FIXEDIT Mask value corruption

### ISSUE THREAD

**Issue by dpelevin** [FarGroup/FarManager#91]
FarManager in ~20% of cases corrupts DI_FIXEDIT Mask value. It can be reproduced with a Release builds only. 

Steps to reproduce:
1. Far Manager, version 3.0 (build 5354) x64
2. Install '[fixedit-mask-corruption](https://github.com/dpelevin/farmanager-fixedit-mask-corruption/releases/download/v0.1.0/fixedit_mask_corruption_x64-0.1.0.zip)' plugin, which creates dialog with 2 checkboxes and a fixedit field at execution. 
3. Execute plugin from plugin menu several times: F11 -> 'DI_FIXEDIT mask corruption'
Usually problem is reproduced couple of times in ten executions.

In a normal case you should see the following dialog:
![farmanager_fixedit_mask_corruption_00](https://user-images.githubusercontent.com/1065021/53843460-85eb5880-3fb3-11e9-96d3-92dc930c28aa.png)
in the case problem take place, mask is replaced with one of checkbox labels:
![farmanager_fixedit_mask_corruption_01](https://user-images.githubusercontent.com/1065021/53843508-b29f7000-3fb3-11e9-8d2f-7d30aa1bea15.png)

To confirm that this is not a problem at plugin side, I've attached to a Far process with a Visual Studio and checked dialog items array plagin passes to Far. As you can see at the screenshot below, at first breakpoint at [apiDialogInit](https://github.com/FarGroup/FarManager/blob/v3.0.5354.738/far/plugapi.cpp#L988) method Item[3].Mask have valid '+9(999)-999-99-99' value, but [at second breakpoint](https://github.com/FarGroup/FarManager/blob/v3.0.5354.738/far/dialog.cpp#L4209) the value of (this->Items[3]).strMask is corrupted and equals to 'checkbox2'. So corruption took place while DialogItem to DialogItemEx conversion.

Btw. I wasn't able to set a second breakpoint with pdb file available at farmanager.com for the release v3.0.5354. Visual Studio told that sources at corresponding git tag [v3.0.5354.738](https://github.com/FarGroup/FarManager/tree/v3.0.5354.738) are different. So I've finished a debbuging with a release build I've build myself with VS 2017 15.8.6.

![farmanager_fixedit_mask_corruption](https://user-images.githubusercontent.com/1065021/53843144-8e8f5f00-3fb2-11e9-9d5a-a84cd70700fd.png)

**Comment by alabuzhev** [comment]
I also have a screenshot:

![image](https://user-images.githubusercontent.com/11453922/53846647-af04ec80-3fa5-11e9-828f-43261ca05361.png)

1 - this is the DialogInit entry point. The previous frame in the call stack is your plugin.
2 - you've already sent us rubbish in all dialog items.

And, unsurprisingly:

![image](https://user-images.githubusercontent.com/11453922/53846690-d22f9c00-3fa5-11e9-8a40-056884b99bd9.png)

Summary: rubbish in, rubbish out.

**Comment by dpelevin** [comment]
So I was really lucky to catch the problem only with mask of fixedit 😂 Thanks for the hint - have to debug a little more.

**Comment by dpelevin** [comment]
@alabuzhev, you know, it really looks strange.

I belive that you are right and a problem is at the plugin side. But no matter what I am doing 'Watch' view always shows valid string values for a dialog items passed by the plugin. Usually I have no issues with catching invalid data passed by a plugin while debuging.

Do you have any ideas what I could miss and why we are observing different results while debugging?
Thanks in advance.

**Comment by dpelevin** [comment]
Even in Rust you can screw up everything with a dangling pointer passed to a C API, if you didn't notice object ownership transfer and following implicit object clenup, happend just before you passed the pointer 🤦‍♂️🤦‍♂️🤦‍♂️

Since now I am not evern wondering that I saw valid values at the debugger and experience the issue at the same time 😂

@alabuzhev, sorry for bothering you.
