### ISSUE TITLE
3.0.5354 падает при любой файловой операции, скрин прилагается

### ISSUE THREAD

**Issue by sharp-dev** [FarGroup/FarManager#93]
скрин - https://i.imgur.com/7Fhdg3Y.png
ОС - Win 10 x64 1809 лицензия
падают 3.0.5354 и x64 и x86
3.0.5300 работает стабильно, а так же лет несколько (более 5 точно) до этого не наблюдал проблем с "дневными" сборками 3.*
**updated так как крешится sqlite, привожу особенности настройки Far.exe.ini (которая много лет уже и используется):
since sqlite is crashing, I’ll quote Far.exe.ini settings (which has been used for many years):**
> UserProfileDir=%FARHOME%\.profile
UserLocalProfileDir=%FARHOME%\.user

**Comment by alabuzhev** [comment]
Have you tried to read the message? In particular, the second line.

**Comment by sharp-dev** [comment]
Yes. but DB configurations are not destroyed. Moreover, they are binary identical at the time of launching Far 3.0.5354, see the screenshots (sorry for the electronic transfer)
1 - https://i.imgur.com/UNbvU2W.png
2 - https://i.imgur.com/pq4KXyb.png

**Comment by alabuzhev** [comment]
> DB configurations are not destroyed

Yet they are, and it's not about Far.exe.ini nor your profile location.
v5300 "works" only because it doesn't check *any* SQLite return codes (surprise!), so instead of saving some of your settings it simply drops them on the floor.

**Make a backup copy of your profile dirs** and remove *.db files one by one until 5354 can start, then put any undamaged files back.

**Comment by sharp-dev** [comment]
very grateful! after kament above, has already begun checking in this direction. fortunately, this is just LocalProfile / history.db and it seems a year or two or two ago, there was a failure with the system date, then I just cleaned up the history, not only did the 5300 miss the error))

**Comment by alabuzhev** [comment]
After 32f5d4ca24ce8a4183829979d4958ae56a7dd215 such exception messages will include the database name to make hunting it down easier.

**Comment by sharp-dev** [comment]
it's a good idea ))
